.section .late_rodata
nonmatching jtbl_800419C8

dlabel jtbl_800419C8
    /* 425C8 800419C8 8002C0A8 */ .word .L8002C0A8
    /* 425CC 800419CC 8002C638 */ .word .L8002C638
    /* 425D0 800419D0 8002C3EC */ .word .L8002C3EC
    /* 425D4 800419D4 8002C638 */ .word .L8002C638
    /* 425D8 800419D8 8002C638 */ .word .L8002C638
    /* 425DC 800419DC 8002C170 */ .word .L8002C170
    /* 425E0 800419E0 8002C1B4 */ .word .L8002C1B4
    /* 425E4 800419E4 8002C408 */ .word .L8002C408
    /* 425E8 800419E8 8002C638 */ .word .L8002C638
    /* 425EC 800419EC 8002C150 */ .word .L8002C150
    /* 425F0 800419F0 8002C538 */ .word .L8002C538
    /* 425F4 800419F4 8002C598 */ .word .L8002C598
    /* 425F8 800419F8 8002C5B4 */ .word .L8002C5B4
    /* 425FC 800419FC 8002C5D8 */ .word .L8002C5D8
    /* 42600 80041A00 8002C628 */ .word .L8002C628
    /* 42604 80041A04 8002C41C */ .word .L8002C41C
    /* 42608 80041A08 8002C440 */ .word .L8002C440
    /* 4260C 80041A0C 8002C4A8 */ .word .L8002C4A8
    /* 42610 80041A10 8002C638 */ .word .L8002C638
    /* 42614 80041A14 8002C638 */ .word .L8002C638
    /* 42618 80041A18 8002C638 */ .word .L8002C638
    /* 4261C 80041A1C 8002C638 */ .word .L8002C638
    /* 42620 80041A20 8002C210 */ .word .L8002C210
    /* 42624 80041A24 8002C318 */ .word .L8002C318
enddlabel jtbl_800419C8
.size jtbl_800419C8, . - jtbl_800419C8

nonmatching D_80041A28

dlabel D_80041A28
    /* 42628 80041A28 48F42400 */ .float 500000
    /* 4262C 80041A2C 00000000 */ .float 0
enddlabel D_80041A28
.size D_80041A28, . - D_80041A28


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8002C044, 0x648

glabel func_8002C044
    /* 2CC44 8002C044 27BDFF30 */  addiu      $sp, $sp, -0xD0
    /* 2CC48 8002C048 AFB50034 */  sw         $s5, 0x34($sp)
    /* 2CC4C 8002C04C AFB20028 */  sw         $s2, 0x28($sp)
    /* 2CC50 8002C050 248E0040 */  addiu      $t6, $a0, 0x40
    /* 2CC54 8002C054 00809025 */  or         $s2, $a0, $zero
    /* 2CC58 8002C058 AFBF0044 */  sw         $ra, 0x44($sp)
    /* 2CC5C 8002C05C AFBE0040 */  sw         $fp, 0x40($sp)
    /* 2CC60 8002C060 AFB7003C */  sw         $s7, 0x3C($sp)
    /* 2CC64 8002C064 AFB60038 */  sw         $s6, 0x38($sp)
    /* 2CC68 8002C068 AFB40030 */  sw         $s4, 0x30($sp)
    /* 2CC6C 8002C06C AFB3002C */  sw         $s3, 0x2C($sp)
    /* 2CC70 8002C070 AFB10024 */  sw         $s1, 0x24($sp)
    /* 2CC74 8002C074 AFB00020 */  sw         $s0, 0x20($sp)
    /* 2CC78 8002C078 F7B40018 */  sdc1       $f20, 0x18($sp)
    /* 2CC7C 8002C07C AFAE0050 */  sw         $t6, 0x50($sp)
    /* 2CC80 8002C080 24950050 */  addiu      $s5, $a0, 0x50
  .L8002C084:
    /* 2CC84 8002C084 964F0040 */  lhu        $t7, 0x40($s2)
    /* 2CC88 8002C088 2DE10018 */  sltiu      $at, $t7, 0x18
    /* 2CC8C 8002C08C 1020016A */  beqz       $at, .L8002C638
    /* 2CC90 8002C090 000F7880 */   sll       $t7, $t7, 2
    /* 2CC94 8002C094 3C018004 */  lui        $at, %hi(jtbl_800419C8)
    /* 2CC98 8002C098 002F0821 */  addu       $at, $at, $t7
    /* 2CC9C 8002C09C 8C2F19C8 */  lw         $t7, %lo(jtbl_800419C8)($at)
    /* 2CCA0 8002C0A0 01E00008 */  jr         $t7
    /* 2CCA4 8002C0A4 00000000 */   nop
  .L8002C0A8:
    /* 2CCA8 8002C0A8 8E440018 */  lw         $a0, 0x18($s2)
    /* 2CCAC 8002C0AC 50800163 */  beql       $a0, $zero, .L8002C63C
    /* 2CCB0 8002C0B0 02A02025 */   or        $a0, $s5, $zero
    /* 2CCB4 8002C0B4 0C00B292 */  jal        alSeqNextEvent
    /* 2CCB8 8002C0B8 27A50088 */   addiu     $a1, $sp, 0x88
    /* 2CCBC 8002C0BC 87A20088 */  lh         $v0, 0x88($sp)
    /* 2CCC0 8002C0C0 24010001 */  addiu      $at, $zero, 0x1
    /* 2CCC4 8002C0C4 27A40088 */  addiu      $a0, $sp, 0x88
    /* 2CCC8 8002C0C8 10410008 */  beq        $v0, $at, .L8002C0EC
    /* 2CCCC 8002C0CC 24010003 */   addiu     $at, $zero, 0x3
    /* 2CCD0 8002C0D0 1041000F */  beq        $v0, $at, .L8002C110
    /* 2CCD4 8002C0D4 02402825 */   or        $a1, $s2, $zero
    /* 2CCD8 8002C0D8 24010004 */  addiu      $at, $zero, 0x4
    /* 2CCDC 8002C0DC 10410012 */  beq        $v0, $at, .L8002C128
    /* 2CCE0 8002C0E0 24180002 */   addiu     $t8, $zero, 0x2
    /* 2CCE4 8002C0E4 10000155 */  b          .L8002C63C
    /* 2CCE8 8002C0E8 02A02025 */   or        $a0, $s5, $zero
  .L8002C0EC:
    /* 2CCEC 8002C0EC AFB200D0 */  sw         $s2, 0xD0($sp)
    /* 2CCF0 8002C0F0 0C00AE04 */  jal        func_8002B810
    /* 2CCF4 8002C0F4 AFB5004C */   sw        $s5, 0x4C($sp)
    /* 2CCF8 8002C0F8 8FB200D0 */  lw         $s2, 0xD0($sp)
    /* 2CCFC 8002C0FC 8FB5004C */  lw         $s5, 0x4C($sp)
    /* 2CD00 8002C100 0C00ABD8 */  jal        func_8002AF60
    /* 2CD04 8002C104 02402025 */   or        $a0, $s2, $zero
    /* 2CD08 8002C108 1000014C */  b          .L8002C63C
    /* 2CD0C 8002C10C 02A02025 */   or        $a0, $s5, $zero
  .L8002C110:
    /* 2CD10 8002C110 0C00AD49 */  jal        func_8002B524
    /* 2CD14 8002C114 27A40088 */   addiu     $a0, $sp, 0x88
    /* 2CD18 8002C118 0C00ABD8 */  jal        func_8002AF60
    /* 2CD1C 8002C11C 02402025 */   or        $a0, $s2, $zero
    /* 2CD20 8002C120 10000146 */  b          .L8002C63C
    /* 2CD24 8002C124 02A02025 */   or        $a0, $s5, $zero
  .L8002C128:
    /* 2CD28 8002C128 AE580034 */  sw         $t8, 0x34($s2)
    /* 2CD2C 8002C12C 24190010 */  addiu      $t9, $zero, 0x10
    /* 2CD30 8002C130 3C067FFF */  lui        $a2, (0x7FFFFFFF >> 16)
    /* 2CD34 8002C134 A7B90088 */  sh         $t9, 0x88($sp)
    /* 2CD38 8002C138 34C6FFFF */  ori        $a2, $a2, (0x7FFFFFFF & 0xFFFF)
    /* 2CD3C 8002C13C 02A02025 */  or         $a0, $s5, $zero
    /* 2CD40 8002C140 0C009818 */  jal        n_alEvtqPostEvent
    /* 2CD44 8002C144 27A50088 */   addiu     $a1, $sp, 0x88
    /* 2CD48 8002C148 1000013C */  b          .L8002C63C
    /* 2CD4C 8002C14C 02A02025 */   or        $a0, $s5, $zero
  .L8002C150:
    /* 2CD50 8002C150 240E0009 */  addiu      $t6, $zero, 0x9
    /* 2CD54 8002C154 A7AE00BC */  sh         $t6, 0xBC($sp)
    /* 2CD58 8002C158 8E460064 */  lw         $a2, 0x64($s2)
    /* 2CD5C 8002C15C 02A02025 */  or         $a0, $s5, $zero
    /* 2CD60 8002C160 0C009818 */  jal        n_alEvtqPostEvent
    /* 2CD64 8002C164 27A500BC */   addiu     $a1, $sp, 0xBC
    /* 2CD68 8002C168 10000134 */  b          .L8002C63C
    /* 2CD6C 8002C16C 02A02025 */   or        $a0, $s5, $zero
  .L8002C170:
    /* 2CD70 8002C170 8E500044 */  lw         $s0, 0x44($s2)
    /* 2CD74 8002C174 0C00AA9C */  jal        n_alSynStopVoice
    /* 2CD78 8002C178 02002025 */   or        $a0, $s0, $zero
    /* 2CD7C 8002C17C 0C00B46C */  jal        func_8002D1B0
    /* 2CD80 8002C180 02002025 */   or        $a0, $s0, $zero
    /* 2CD84 8002C184 8E110010 */  lw         $s1, 0x10($s0)
    /* 2CD88 8002C188 02402025 */  or         $a0, $s2, $zero
    /* 2CD8C 8002C18C 922F0037 */  lbu        $t7, 0x37($s1)
    /* 2CD90 8002C190 51E00004 */  beql       $t7, $zero, .L8002C1A4
    /* 2CD94 8002C194 02402025 */   or        $a0, $s2, $zero
    /* 2CD98 8002C198 0C00B1A3 */  jal        func_8002C68C
    /* 2CD9C 8002C19C 02202825 */   or        $a1, $s1, $zero
    /* 2CDA0 8002C1A0 02402025 */  or         $a0, $s2, $zero
  .L8002C1A4:
    /* 2CDA4 8002C1A4 0C00AD2D */  jal        func_8002B4B4
    /* 2CDA8 8002C1A8 02002825 */   or        $a1, $s0, $zero
    /* 2CDAC 8002C1AC 10000123 */  b          .L8002C63C
    /* 2CDB0 8002C1B0 02A02025 */   or        $a0, $s5, $zero
  .L8002C1B4:
    /* 2CDB4 8002C1B4 8E500044 */  lw         $s0, 0x44($s2)
    /* 2CDB8 8002C1B8 24190001 */  addiu      $t9, $zero, 0x1
    /* 2CDBC 8002C1BC 8E110010 */  lw         $s1, 0x10($s0)
    /* 2CDC0 8002C1C0 92380034 */  lbu        $t8, 0x34($s1)
    /* 2CDC4 8002C1C4 57000003 */  bnel       $t8, $zero, .L8002C1D4
    /* 2CDC8 8002C1C8 924E004C */   lbu       $t6, 0x4C($s2)
    /* 2CDCC 8002C1CC A2390034 */  sb         $t9, 0x34($s1)
    /* 2CDD0 8002C1D0 924E004C */  lbu        $t6, 0x4C($s2)
  .L8002C1D4:
    /* 2CDD4 8002C1D4 8E530048 */  lw         $s3, 0x48($s2)
    /* 2CDD8 8002C1D8 02202025 */  or         $a0, $s1, $zero
    /* 2CDDC 8002C1DC A22E0030 */  sb         $t6, 0x30($s1)
    /* 2CDE0 8002C1E0 8E4F001C */  lw         $t7, 0x1C($s2)
    /* 2CDE4 8002C1E4 02402825 */  or         $a1, $s2, $zero
    /* 2CDE8 8002C1E8 01F3C021 */  addu       $t8, $t7, $s3
    /* 2CDEC 8002C1EC 0C00AC8E */  jal        func_8002B238
    /* 2CDF0 8002C1F0 AE380024 */   sw        $t8, 0x24($s1)
    /* 2CDF4 8002C1F4 00022C00 */  sll        $a1, $v0, 16
    /* 2CDF8 8002C1F8 00052C03 */  sra        $a1, $a1, 16
    /* 2CDFC 8002C1FC 02002025 */  or         $a0, $s0, $zero
    /* 2CE00 8002C200 0C00B494 */  jal        n_alSynSetVol
    /* 2CE04 8002C204 02603025 */   or        $a2, $s3, $zero
    /* 2CE08 8002C208 1000010C */  b          .L8002C63C
    /* 2CE0C 8002C20C 02A02025 */   or        $a0, $s5, $zero
  .L8002C210:
    /* 2CE10 8002C210 8E590080 */  lw         $t9, 0x80($s2)
    /* 2CE14 8002C214 8E540048 */  lw         $s4, 0x48($s2)
    /* 2CE18 8002C218 8E510044 */  lw         $s1, 0x44($s2)
    /* 2CE1C 8002C21C 27A500A8 */  addiu      $a1, $sp, 0xA8
    /* 2CE20 8002C220 0320F809 */  jalr       $t9
    /* 2CE24 8002C224 02802025 */   or        $a0, $s4, $zero
    /* 2CE28 8002C228 444EF800 */  cfc1       $t6, $31
    /* 2CE2C 8002C22C 240F0001 */  addiu      $t7, $zero, 0x1
    /* 2CE30 8002C230 44CFF800 */  ctc1       $t7, $31
    /* 2CE34 8002C234 C7A400A8 */  lwc1       $f4, 0xA8($sp)
    /* 2CE38 8002C238 00409825 */  or         $s3, $v0, $zero
    /* 2CE3C 8002C23C 3C014F00 */  lui        $at, (0x4F000000 >> 16)
    /* 2CE40 8002C240 460021A4 */  cvt.w.s    $f6, $f4
    /* 2CE44 8002C244 02202025 */  or         $a0, $s1, $zero
    /* 2CE48 8002C248 02402825 */  or         $a1, $s2, $zero
    /* 2CE4C 8002C24C 444FF800 */  cfc1       $t7, $31
    /* 2CE50 8002C250 00000000 */  nop
    /* 2CE54 8002C254 31EF0078 */  andi       $t7, $t7, 0x78
    /* 2CE58 8002C258 51E00013 */  beql       $t7, $zero, .L8002C2A8
    /* 2CE5C 8002C25C 440F3000 */   mfc1      $t7, $f6
    /* 2CE60 8002C260 44813000 */  mtc1       $at, $f6
    /* 2CE64 8002C264 240F0001 */  addiu      $t7, $zero, 0x1
    /* 2CE68 8002C268 46062181 */  sub.s      $f6, $f4, $f6
    /* 2CE6C 8002C26C 44CFF800 */  ctc1       $t7, $31
    /* 2CE70 8002C270 00000000 */  nop
    /* 2CE74 8002C274 460031A4 */  cvt.w.s    $f6, $f6
    /* 2CE78 8002C278 444FF800 */  cfc1       $t7, $31
    /* 2CE7C 8002C27C 00000000 */  nop
    /* 2CE80 8002C280 31EF0078 */  andi       $t7, $t7, 0x78
    /* 2CE84 8002C284 15E00005 */  bnez       $t7, .L8002C29C
    /* 2CE88 8002C288 00000000 */   nop
    /* 2CE8C 8002C28C 440F3000 */  mfc1       $t7, $f6
    /* 2CE90 8002C290 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 2CE94 8002C294 10000007 */  b          .L8002C2B4
    /* 2CE98 8002C298 01E17825 */   or        $t7, $t7, $at
  .L8002C29C:
    /* 2CE9C 8002C29C 10000005 */  b          .L8002C2B4
    /* 2CEA0 8002C2A0 240FFFFF */   addiu     $t7, $zero, -0x1
    /* 2CEA4 8002C2A4 440F3000 */  mfc1       $t7, $f6
  .L8002C2A8:
    /* 2CEA8 8002C2A8 00000000 */  nop
    /* 2CEAC 8002C2AC 05E0FFFB */  bltz       $t7, .L8002C29C
    /* 2CEB0 8002C2B0 00000000 */   nop
  .L8002C2B4:
    /* 2CEB4 8002C2B4 44CEF800 */  ctc1       $t6, $31
    /* 2CEB8 8002C2B8 0C00AC8E */  jal        func_8002B238
    /* 2CEBC 8002C2BC A22F0036 */   sb        $t7, 0x36($s1)
    /* 2CEC0 8002C2C0 8E43001C */  lw         $v1, 0x1C($s2)
    /* 2CEC4 8002C2C4 8E380024 */  lw         $t8, 0x24($s1)
    /* 2CEC8 8002C2C8 00022C00 */  sll        $a1, $v0, 16
    /* 2CECC 8002C2CC 00052C03 */  sra        $a1, $a1, 16
    /* 2CED0 8002C2D0 03032023 */  subu       $a0, $t8, $v1
    /* 2CED4 8002C2D4 04800003 */  bltz       $a0, .L8002C2E4
    /* 2CED8 8002C2D8 240203E8 */   addiu     $v0, $zero, 0x3E8
    /* 2CEDC 8002C2DC 10000001 */  b          .L8002C2E4
    /* 2CEE0 8002C2E0 00801025 */   or        $v0, $a0, $zero
  .L8002C2E4:
    /* 2CEE4 8002C2E4 26240004 */  addiu      $a0, $s1, 0x4
    /* 2CEE8 8002C2E8 0C00B494 */  jal        n_alSynSetVol
    /* 2CEEC 8002C2EC 00403025 */   or        $a2, $v0, $zero
    /* 2CEF0 8002C2F0 24190016 */  addiu      $t9, $zero, 0x16
    /* 2CEF4 8002C2F4 A7B900BC */  sh         $t9, 0xBC($sp)
    /* 2CEF8 8002C2F8 AFB100C0 */  sw         $s1, 0xC0($sp)
    /* 2CEFC 8002C2FC AFB400C4 */  sw         $s4, 0xC4($sp)
    /* 2CF00 8002C300 02A02025 */  or         $a0, $s5, $zero
    /* 2CF04 8002C304 27A500BC */  addiu      $a1, $sp, 0xBC
    /* 2CF08 8002C308 0C009818 */  jal        n_alEvtqPostEvent
    /* 2CF0C 8002C30C 02603025 */   or        $a2, $s3, $zero
    /* 2CF10 8002C310 100000CA */  b          .L8002C63C
    /* 2CF14 8002C314 02A02025 */   or        $a0, $s5, $zero
  .L8002C318:
    /* 2CF18 8002C318 8E590080 */  lw         $t9, 0x80($s2)
    /* 2CF1C 8002C31C 8E540048 */  lw         $s4, 0x48($s2)
    /* 2CF20 8002C320 8E510044 */  lw         $s1, 0x44($s2)
    /* 2CF24 8002C324 9250004C */  lbu        $s0, 0x4C($s2)
    /* 2CF28 8002C328 27A500A8 */  addiu      $a1, $sp, 0xA8
    /* 2CF2C 8002C32C 0320F809 */  jalr       $t9
    /* 2CF30 8002C330 02802025 */   or        $a0, $s4, $zero
    /* 2CF34 8002C334 C7A800A8 */  lwc1       $f8, 0xA8($sp)
    /* 2CF38 8002C338 00107880 */  sll        $t7, $s0, 2
    /* 2CF3C 8002C33C 01F07823 */  subu       $t7, $t7, $s0
    /* 2CF40 8002C340 E628002C */  swc1       $f8, 0x2C($s1)
    /* 2CF44 8002C344 8E4E0068 */  lw         $t6, 0x68($s2)
    /* 2CF48 8002C348 C634002C */  lwc1       $f20, 0x2C($s1)
    /* 2CF4C 8002C34C 000F78C0 */  sll        $t7, $t7, 3
    /* 2CF50 8002C350 01CF1821 */  addu       $v1, $t6, $t7
    /* 2CF54 8002C354 90780010 */  lbu        $t8, 0x10($v1)
    /* 2CF58 8002C358 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 2CF5C 8002C35C 44810000 */  mtc1       $at, $f0
    /* 2CF60 8002C360 44989000 */  mtc1       $t8, $f18
    /* 2CF64 8002C364 00409825 */  or         $s3, $v0, $zero
    /* 2CF68 8002C368 4600A101 */  sub.s      $f4, $f20, $f0
    /* 2CF6C 8002C36C 26240004 */  addiu      $a0, $s1, 0x4
    /* 2CF70 8002C370 07010005 */  bgez       $t8, .L8002C388
    /* 2CF74 8002C374 46809220 */   cvt.s.w   $f8, $f18
    /* 2CF78 8002C378 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 2CF7C 8002C37C 44815000 */  mtc1       $at, $f10
    /* 2CF80 8002C380 00000000 */  nop
    /* 2CF84 8002C384 460A4200 */  add.s      $f8, $f8, $f10
  .L8002C388:
    /* 2CF88 8002C388 46082182 */  mul.s      $f6, $f4, $f8
    /* 2CF8C 8002C38C 3C0142FE */  lui        $at, (0x42FE0000 >> 16)
    /* 2CF90 8002C390 44815000 */  mtc1       $at, $f10
    /* 2CF94 8002C394 00000000 */  nop
    /* 2CF98 8002C398 460A3103 */  div.s      $f4, $f6, $f10
    /* 2CF9C 8002C39C C6260028 */  lwc1       $f6, 0x28($s1)
    /* 2CFA0 8002C3A0 46002200 */  add.s      $f8, $f4, $f0
    /* 2CFA4 8002C3A4 C464000C */  lwc1       $f4, 0xC($v1)
    /* 2CFA8 8002C3A8 46083282 */  mul.s      $f10, $f6, $f8
    /* 2CFAC 8002C3AC 00000000 */  nop
    /* 2CFB0 8002C3B0 460A2182 */  mul.s      $f6, $f4, $f10
    /* 2CFB4 8002C3B4 44053000 */  mfc1       $a1, $f6
    /* 2CFB8 8002C3B8 0C00B368 */  jal        n_alSynSetPitch
    /* 2CFBC 8002C3BC 00000000 */   nop
    /* 2CFC0 8002C3C0 24190017 */  addiu      $t9, $zero, 0x17
    /* 2CFC4 8002C3C4 A7B900BC */  sh         $t9, 0xBC($sp)
    /* 2CFC8 8002C3C8 AFB100C0 */  sw         $s1, 0xC0($sp)
    /* 2CFCC 8002C3CC AFB400C4 */  sw         $s4, 0xC4($sp)
    /* 2CFD0 8002C3D0 A3B000C8 */  sb         $s0, 0xC8($sp)
    /* 2CFD4 8002C3D4 02A02025 */  or         $a0, $s5, $zero
    /* 2CFD8 8002C3D8 27A500BC */  addiu      $a1, $sp, 0xBC
    /* 2CFDC 8002C3DC 0C009818 */  jal        n_alEvtqPostEvent
    /* 2CFE0 8002C3E0 02603025 */   or        $a2, $s3, $zero
    /* 2CFE4 8002C3E4 10000095 */  b          .L8002C63C
    /* 2CFE8 8002C3E8 02A02025 */   or        $a0, $s5, $zero
  .L8002C3EC:
    /* 2CFEC 8002C3EC 8FA40050 */  lw         $a0, 0x50($sp)
    /* 2CFF0 8002C3F0 AFB200D0 */  sw         $s2, 0xD0($sp)
    /* 2CFF4 8002C3F4 0C00AE04 */  jal        func_8002B810
    /* 2CFF8 8002C3F8 AFB5004C */   sw        $s5, 0x4C($sp)
    /* 2CFFC 8002C3FC 8FB200D0 */  lw         $s2, 0xD0($sp)
    /* 2D000 8002C400 1000008D */  b          .L8002C638
    /* 2D004 8002C404 8FB5004C */   lw        $s5, 0x4C($sp)
  .L8002C408:
    /* 2D008 8002C408 02402825 */  or         $a1, $s2, $zero
    /* 2D00C 8002C40C 0C00AD49 */  jal        func_8002B524
    /* 2D010 8002C410 8FA40050 */   lw        $a0, 0x50($sp)
    /* 2D014 8002C414 10000089 */  b          .L8002C63C
    /* 2D018 8002C418 02A02025 */   or        $a0, $s5, $zero
  .L8002C41C:
    /* 2D01C 8002C41C 8E4E0034 */  lw         $t6, 0x34($s2)
    /* 2D020 8002C420 24010001 */  addiu      $at, $zero, 0x1
    /* 2D024 8002C424 240F0001 */  addiu      $t7, $zero, 0x1
    /* 2D028 8002C428 11C10083 */  beq        $t6, $at, .L8002C638
    /* 2D02C 8002C42C 02402025 */   or        $a0, $s2, $zero
    /* 2D030 8002C430 0C00ABD8 */  jal        func_8002AF60
    /* 2D034 8002C434 AE4F0034 */   sw        $t7, 0x34($s2)
    /* 2D038 8002C438 10000080 */  b          .L8002C63C
    /* 2D03C 8002C43C 02A02025 */   or        $a0, $s5, $zero
  .L8002C440:
    /* 2D040 8002C440 8E580034 */  lw         $t8, 0x34($s2)
    /* 2D044 8002C444 24010002 */  addiu      $at, $zero, 0x2
    /* 2D048 8002C448 5701007C */  bnel       $t8, $at, .L8002C63C
    /* 2D04C 8002C44C 02A02025 */   or        $a0, $s5, $zero
    /* 2D050 8002C450 8E51006C */  lw         $s1, 0x6C($s2)
    /* 2D054 8002C454 12200011 */  beqz       $s1, .L8002C49C
    /* 2D058 8002C458 26300004 */   addiu     $s0, $s1, 0x4
  .L8002C45C:
    /* 2D05C 8002C45C 0C00AA9C */  jal        n_alSynStopVoice
    /* 2D060 8002C460 02002025 */   or        $a0, $s0, $zero
    /* 2D064 8002C464 0C00B46C */  jal        func_8002D1B0
    /* 2D068 8002C468 02002025 */   or        $a0, $s0, $zero
    /* 2D06C 8002C46C 92390037 */  lbu        $t9, 0x37($s1)
    /* 2D070 8002C470 02402025 */  or         $a0, $s2, $zero
    /* 2D074 8002C474 53200004 */  beql       $t9, $zero, .L8002C488
    /* 2D078 8002C478 02402025 */   or        $a0, $s2, $zero
    /* 2D07C 8002C47C 0C00B1A3 */  jal        func_8002C68C
    /* 2D080 8002C480 02202825 */   or        $a1, $s1, $zero
    /* 2D084 8002C484 02402025 */  or         $a0, $s2, $zero
  .L8002C488:
    /* 2D088 8002C488 0C00AD2D */  jal        func_8002B4B4
    /* 2D08C 8002C48C 02002825 */   or        $a1, $s0, $zero
    /* 2D090 8002C490 8E51006C */  lw         $s1, 0x6C($s2)
    /* 2D094 8002C494 5620FFF1 */  bnel       $s1, $zero, .L8002C45C
    /* 2D098 8002C498 26300004 */   addiu     $s0, $s1, 0x4
  .L8002C49C:
    /* 2D09C 8002C49C AE40001C */  sw         $zero, 0x1C($s2)
    /* 2D0A0 8002C4A0 10000065 */  b          .L8002C638
    /* 2D0A4 8002C4A4 AE400034 */   sw        $zero, 0x34($s2)
  .L8002C4A8:
    /* 2D0A8 8002C4A8 8E4E0034 */  lw         $t6, 0x34($s2)
    /* 2D0AC 8002C4AC 24010001 */  addiu      $at, $zero, 0x1
    /* 2D0B0 8002C4B0 02A02025 */  or         $a0, $s5, $zero
    /* 2D0B4 8002C4B4 55C10061 */  bnel       $t6, $at, .L8002C63C
    /* 2D0B8 8002C4B8 02A02025 */   or        $a0, $s5, $zero
    /* 2D0BC 8002C4BC 0C0097E9 */  jal        func_80025FA4
    /* 2D0C0 8002C4C0 00002825 */   or        $a1, $zero, $zero
    /* 2D0C4 8002C4C4 02A02025 */  or         $a0, $s5, $zero
    /* 2D0C8 8002C4C8 0C0097E9 */  jal        func_80025FA4
    /* 2D0CC 8002C4CC 24050002 */   addiu     $a1, $zero, 0x2
    /* 2D0D0 8002C4D0 8E51006C */  lw         $s1, 0x6C($s2)
    /* 2D0D4 8002C4D4 1220000D */  beqz       $s1, .L8002C50C
    /* 2D0D8 8002C4D8 26300004 */   addiu     $s0, $s1, 0x4
  .L8002C4DC:
    /* 2D0DC 8002C4DC 02002825 */  or         $a1, $s0, $zero
    /* 2D0E0 8002C4E0 02402025 */  or         $a0, $s2, $zero
    /* 2D0E4 8002C4E4 0C00AD03 */  jal        func_8002B40C
    /* 2D0E8 8002C4E8 3406C350 */   ori       $a2, $zero, 0xC350
    /* 2D0EC 8002C4EC 10400004 */  beqz       $v0, .L8002C500
    /* 2D0F0 8002C4F0 02402025 */   or        $a0, $s2, $zero
    /* 2D0F4 8002C4F4 02002825 */  or         $a1, $s0, $zero
    /* 2D0F8 8002C4F8 0C00ACBA */  jal        func_8002B2E8
    /* 2D0FC 8002C4FC 3406C350 */   ori       $a2, $zero, 0xC350
  .L8002C500:
    /* 2D100 8002C500 8E310000 */  lw         $s1, 0x0($s1)
    /* 2D104 8002C504 5620FFF5 */  bnel       $s1, $zero, .L8002C4DC
    /* 2D108 8002C508 26300004 */   addiu     $s0, $s1, 0x4
  .L8002C50C:
    /* 2D10C 8002C50C 240F0002 */  addiu      $t7, $zero, 0x2
    /* 2D110 8002C510 AE4F0034 */  sw         $t7, 0x34($s2)
    /* 2D114 8002C514 24180010 */  addiu      $t8, $zero, 0x10
    /* 2D118 8002C518 3C067FFF */  lui        $a2, (0x7FFFFFFF >> 16)
    /* 2D11C 8002C51C A7B800BC */  sh         $t8, 0xBC($sp)
    /* 2D120 8002C520 34C6FFFF */  ori        $a2, $a2, (0x7FFFFFFF & 0xFFFF)
    /* 2D124 8002C524 02A02025 */  or         $a0, $s5, $zero
    /* 2D128 8002C528 0C009818 */  jal        n_alEvtqPostEvent
    /* 2D12C 8002C52C 27A500BC */   addiu     $a1, $sp, 0xBC
    /* 2D130 8002C530 10000042 */  b          .L8002C63C
    /* 2D134 8002C534 02A02025 */   or        $a0, $s5, $zero
  .L8002C538:
    /* 2D138 8002C538 8E51006C */  lw         $s1, 0x6C($s2)
    /* 2D13C 8002C53C 86590044 */  lh         $t9, 0x44($s2)
    /* 2D140 8002C540 1220003D */  beqz       $s1, .L8002C638
    /* 2D144 8002C544 A659003A */   sh        $t9, 0x3A($s2)
    /* 2D148 8002C548 02202025 */  or         $a0, $s1, $zero
  .L8002C54C:
    /* 2D14C 8002C54C 0C00AC8E */  jal        func_8002B238
    /* 2D150 8002C550 02402825 */   or        $a1, $s2, $zero
    /* 2D154 8002C554 8E43001C */  lw         $v1, 0x1C($s2)
    /* 2D158 8002C558 8E2E0024 */  lw         $t6, 0x24($s1)
    /* 2D15C 8002C55C 00022C00 */  sll        $a1, $v0, 16
    /* 2D160 8002C560 00052C03 */  sra        $a1, $a1, 16
    /* 2D164 8002C564 01C32023 */  subu       $a0, $t6, $v1
    /* 2D168 8002C568 04800003 */  bltz       $a0, .L8002C578
    /* 2D16C 8002C56C 240203E8 */   addiu     $v0, $zero, 0x3E8
    /* 2D170 8002C570 10000001 */  b          .L8002C578
    /* 2D174 8002C574 00801025 */   or        $v0, $a0, $zero
  .L8002C578:
    /* 2D178 8002C578 26240004 */  addiu      $a0, $s1, 0x4
    /* 2D17C 8002C57C 0C00B494 */  jal        n_alSynSetVol
    /* 2D180 8002C580 00403025 */   or        $a2, $v0, $zero
    /* 2D184 8002C584 8E310000 */  lw         $s1, 0x0($s1)
    /* 2D188 8002C588 5620FFF0 */  bnel       $s1, $zero, .L8002C54C
    /* 2D18C 8002C58C 02202025 */   or        $a0, $s1, $zero
    /* 2D190 8002C590 1000002A */  b          .L8002C63C
    /* 2D194 8002C594 02A02025 */   or        $a0, $s5, $zero
  .L8002C598:
    /* 2D198 8002C598 8E4F0044 */  lw         $t7, 0x44($s2)
    /* 2D19C 8002C59C 8E580048 */  lw         $t8, 0x48($s2)
    /* 2D1A0 8002C5A0 8E59004C */  lw         $t9, 0x4C($s2)
    /* 2D1A4 8002C5A4 AE4F0088 */  sw         $t7, 0x88($s2)
    /* 2D1A8 8002C5A8 AE58008C */  sw         $t8, 0x8C($s2)
    /* 2D1AC 8002C5AC 10000022 */  b          .L8002C638
    /* 2D1B0 8002C5B0 AE590090 */   sw        $t9, 0x90($s2)
  .L8002C5B4:
    /* 2D1B4 8002C5B4 92500044 */  lbu        $s0, 0x44($s2)
    /* 2D1B8 8002C5B8 8E4F0068 */  lw         $t7, 0x68($s2)
    /* 2D1BC 8002C5BC 924E0045 */  lbu        $t6, 0x45($s2)
    /* 2D1C0 8002C5C0 0010C080 */  sll        $t8, $s0, 2
    /* 2D1C4 8002C5C4 0310C023 */  subu       $t8, $t8, $s0
    /* 2D1C8 8002C5C8 0018C0C0 */  sll        $t8, $t8, 3
    /* 2D1CC 8002C5CC 01F8C821 */  addu       $t9, $t7, $t8
    /* 2D1D0 8002C5D0 10000019 */  b          .L8002C638
    /* 2D1D4 8002C5D4 A32E0008 */   sb        $t6, 0x8($t9)
  .L8002C5D8:
    /* 2D1D8 8002C5D8 8E450044 */  lw         $a1, 0x44($s2)
    /* 2D1DC 8002C5DC 241901E8 */  addiu      $t9, $zero, 0x1E8
    /* 2D1E0 8002C5E0 3C018004 */  lui        $at, %hi(D_80041A28)
    /* 2D1E4 8002C5E4 10A00008 */  beqz       $a1, .L8002C608
    /* 2D1E8 8002C5E8 AE450018 */   sw        $a1, 0x18($s2)
    /* 2D1EC 8002C5EC C4281A28 */  lwc1       $f8, %lo(D_80041A28)($at)
    /* 2D1F0 8002C5F0 C4A40014 */  lwc1       $f4, 0x14($a1)
    /* 2D1F4 8002C5F4 46044282 */  mul.s      $f10, $f8, $f4
    /* 2D1F8 8002C5F8 4600518D */  trunc.w.s  $f6, $f10
    /* 2D1FC 8002C5FC 440E3000 */  mfc1       $t6, $f6
    /* 2D200 8002C600 10000002 */  b          .L8002C60C
    /* 2D204 8002C604 AE4E002C */   sw        $t6, 0x2C($s2)
  .L8002C608:
    /* 2D208 8002C608 AE59002C */  sw         $t9, 0x2C($s2)
  .L8002C60C:
    /* 2D20C 8002C60C 8E450020 */  lw         $a1, 0x20($s2)
    /* 2D210 8002C610 50A0000A */  beql       $a1, $zero, .L8002C63C
    /* 2D214 8002C614 02A02025 */   or        $a0, $s5, $zero
    /* 2D218 8002C618 0C00AC56 */  jal        func_8002B158
    /* 2D21C 8002C61C 02402025 */   or        $a0, $s2, $zero
    /* 2D220 8002C620 10000006 */  b          .L8002C63C
    /* 2D224 8002C624 02A02025 */   or        $a0, $s5, $zero
  .L8002C628:
    /* 2D228 8002C628 8E450044 */  lw         $a1, 0x44($s2)
    /* 2D22C 8002C62C 02402025 */  or         $a0, $s2, $zero
    /* 2D230 8002C630 0C00AC56 */  jal        func_8002B158
    /* 2D234 8002C634 AE450020 */   sw        $a1, 0x20($s2)
  .L8002C638:
    /* 2D238 8002C638 02A02025 */  or         $a0, $s5, $zero
  .L8002C63C:
    /* 2D23C 8002C63C 0C00986C */  jal        func_800261B0
    /* 2D240 8002C640 8FA50050 */   lw        $a1, 0x50($sp)
    /* 2D244 8002C644 1040FE8F */  beqz       $v0, .L8002C084
    /* 2D248 8002C648 AE420030 */   sw        $v0, 0x30($s2)
    /* 2D24C 8002C64C 8E4F001C */  lw         $t7, 0x1C($s2)
    /* 2D250 8002C650 01E2C021 */  addu       $t8, $t7, $v0
    /* 2D254 8002C654 AE58001C */  sw         $t8, 0x1C($s2)
    /* 2D258 8002C658 8FBF0044 */  lw         $ra, 0x44($sp)
    /* 2D25C 8002C65C 8FBE0040 */  lw         $fp, 0x40($sp)
    /* 2D260 8002C660 8FB7003C */  lw         $s7, 0x3C($sp)
    /* 2D264 8002C664 8FB60038 */  lw         $s6, 0x38($sp)
    /* 2D268 8002C668 8FB50034 */  lw         $s5, 0x34($sp)
    /* 2D26C 8002C66C 8FB40030 */  lw         $s4, 0x30($sp)
    /* 2D270 8002C670 8FB3002C */  lw         $s3, 0x2C($sp)
    /* 2D274 8002C674 8FB20028 */  lw         $s2, 0x28($sp)
    /* 2D278 8002C678 8FB10024 */  lw         $s1, 0x24($sp)
    /* 2D27C 8002C67C 8FB00020 */  lw         $s0, 0x20($sp)
    /* 2D280 8002C680 D7B40018 */  ldc1       $f20, 0x18($sp)
    /* 2D284 8002C684 03E00008 */  jr         $ra
    /* 2D288 8002C688 27BD00D0 */   addiu     $sp, $sp, 0xD0
endlabel func_8002C044
.size func_8002C044, . - func_8002C044
