.include "macro.inc"

.section .rodata, "a"

/* Generated by spimdisasm 1.42.4 */

.align 2
nonmatching D_800D5E00

dlabel D_800D5E00
    /* 7E050 800D5E00 */ .asciz "M11PLAIN01"
    /* 4D3131504C41494E30310000 */
.align 2
enddlabel D_800D5E00
.size D_800D5E00, . - D_800D5E00

.align 2
nonmatching D_800D5E0C

dlabel D_800D5E0C
    /* 7E05C 800D5E0C */ .asciz "M11PLAINRG"
    /* 4D3131504C41494E52470000 */
.align 2
enddlabel D_800D5E0C
.size D_800D5E0C, . - D_800D5E0C

.align 2
nonmatching D_800D5E18

dlabel D_800D5E18
    /* 7E068 800D5E18 */ .asciz "M11PLAIN03"
    /* 4D3131504C41494E30330000 */
.align 2
enddlabel D_800D5E18
.size D_800D5E18, . - D_800D5E18

.align 2
nonmatching D_800D5E24

dlabel D_800D5E24
    /* 7E074 800D5E24 */ .asciz "M11PLAIN02"
    /* 4D3131504C41494E30320000 */
.align 2
enddlabel D_800D5E24
.size D_800D5E24, . - D_800D5E24

.align 2
nonmatching D_800D5E30

dlabel D_800D5E30
    /* 7E080 800D5E30 */ .asciz "G11"
    /* 47313100 */
.align 2
enddlabel D_800D5E30
.size D_800D5E30, . - D_800D5E30

.align 2
nonmatching D_800D5E34

dlabel D_800D5E34
    /* 7E084 800D5E34 */ .asciz "M12WOODS01"
    /* 4D3132574F4F445330310000 */
.align 2
enddlabel D_800D5E34
.size D_800D5E34, . - D_800D5E34

.align 2
nonmatching D_800D5E40

dlabel D_800D5E40
    /* 7E090 800D5E40 */ .asciz "M12WOODS02"
    /* 4D3132574F4F445330320000 */
.align 2
enddlabel D_800D5E40
.size D_800D5E40, . - D_800D5E40

.align 2
nonmatching D_800D5E4C

dlabel D_800D5E4C
    /* 7E09C 800D5E4C */ .asciz "M12WOODS03"
    /* 4D3132574F4F445330330000 */
.align 2
enddlabel D_800D5E4C
.size D_800D5E4C, . - D_800D5E4C

.align 2
nonmatching D_800D5E58

dlabel D_800D5E58
    /* 7E0A8 800D5E58 */ .asciz "M12WOODS04"
    /* 4D3132574F4F445330340000 */
.align 2
enddlabel D_800D5E58
.size D_800D5E58, . - D_800D5E58

.align 2
nonmatching D_800D5E64

dlabel D_800D5E64
    /* 7E0B4 800D5E64 */ .asciz "M12WOODSRG"
    /* 4D3132574F4F445352470000 */
.align 2
enddlabel D_800D5E64
.size D_800D5E64, . - D_800D5E64

.align 2
nonmatching D_800D5E70

dlabel D_800D5E70
    /* 7E0C0 800D5E70 */ .asciz "MBADO01"
    /* 4D4241444F303100 */
.align 2
enddlabel D_800D5E70
.size D_800D5E70, . - D_800D5E70

.align 2
nonmatching D_800D5E78

dlabel D_800D5E78
    /* 7E0C8 800D5E78 */ .asciz "G12"
    /* 47313200 */
.align 2
enddlabel D_800D5E78
.size D_800D5E78, . - D_800D5E78

.align 2
nonmatching D_800D5E7C

dlabel D_800D5E7C
    /* 7E0CC 800D5E7C */ .asciz "M13CASTLE01"
    /* 4D3133434153544C45303100 */
.align 2
enddlabel D_800D5E7C
.size D_800D5E7C, . - D_800D5E7C

.align 2
nonmatching D_800D5E88

dlabel D_800D5E88
    /* 7E0D8 800D5E88 */ .asciz "M13CASTLE02"
    /* 4D3133434153544C45303200 */
.align 2
enddlabel D_800D5E88
.size D_800D5E88, . - D_800D5E88

.align 2
nonmatching D_800D5E94

dlabel D_800D5E94
    /* 7E0E4 800D5E94 */ .asciz "M13CASTLE03"
    /* 4D3133434153544C45303300 */
.align 2
enddlabel D_800D5E94
.size D_800D5E94, . - D_800D5E94

.align 2
nonmatching D_800D5EA0

dlabel D_800D5EA0
    /* 7E0F0 800D5EA0 */ .asciz "M13CASTLE04"
    /* 4D3133434153544C45303400 */
.align 2
enddlabel D_800D5EA0
.size D_800D5EA0, . - D_800D5EA0

.align 2
nonmatching D_800D5EAC

dlabel D_800D5EAC
    /* 7E0FC 800D5EAC */ .asciz "M13CASTLE05"
    /* 4D3133434153544C45303500 */
.align 2
enddlabel D_800D5EAC
.size D_800D5EAC, . - D_800D5EAC

.align 2
nonmatching D_800D5EB8

dlabel D_800D5EB8
    /* 7E108 800D5EB8 */ .asciz "M13CASTLE06"
    /* 4D3133434153544C45303600 */
.align 2
enddlabel D_800D5EB8
.size D_800D5EB8, . - D_800D5EB8

.align 2
nonmatching D_800D5EC4

dlabel D_800D5EC4
    /* 7E114 800D5EC4 */ .asciz "M13CASTLEADO"
    /* 4D3133434153544C4541444F00000000 */
.align 2
enddlabel D_800D5EC4
.size D_800D5EC4, . - D_800D5EC4

.align 2
nonmatching D_800D5ED4

dlabel D_800D5ED4
    /* 7E124 800D5ED4 */ .asciz "M13CASTLE07"
    /* 4D3133434153544C45303700 */
.align 2
enddlabel D_800D5ED4
.size D_800D5ED4, . - D_800D5ED4

.align 2
nonmatching D_800D5EE0

dlabel D_800D5EE0
    /* 7E130 800D5EE0 */ .asciz "MBDEDEDE01"
    /* 4D4244454445444530310000 */
.align 2
enddlabel D_800D5EE0
.size D_800D5EE0, . - D_800D5EE0

.align 2
nonmatching D_800D5EEC

dlabel D_800D5EEC
    /* 7E13C 800D5EEC */ .asciz "G13"
    /* 47313300 */
.align 2
enddlabel D_800D5EEC
.size D_800D5EEC, . - D_800D5EEC

.align 2
nonmatching D_800D5EF0

dlabel D_800D5EF0
    /* 7E140 800D5EF0 */ .asciz "M1WHISPY"
    /* 4D3157484953505900000000 */
.align 2
enddlabel D_800D5EF0
.size D_800D5EF0, . - D_800D5EF0

.align 2
nonmatching D_800D5EFC

dlabel D_800D5EFC
    /* 7E14C 800D5EFC */ .asciz "M21DESERT01"
    /* 4D3231444553455254303100 */
.align 2
enddlabel D_800D5EFC
.size D_800D5EFC, . - D_800D5EFC

.align 2
nonmatching D_800D5F08

dlabel D_800D5F08
    /* 7E158 800D5F08 */ .asciz "M21DESERT02"
    /* 4D3231444553455254303200 */
.align 2
enddlabel D_800D5F08
.size D_800D5F08, . - D_800D5F08

.align 2
nonmatching D_800D5F14

dlabel D_800D5F14
    /* 7E164 800D5F14 */ .asciz "M21DESERTRG"
    /* 4D3231444553455254524700 */
.align 2
enddlabel D_800D5F14
.size D_800D5F14, . - D_800D5F14

.align 2
nonmatching D_800D5F20

dlabel D_800D5F20
    /* 7E170 800D5F20 */ .asciz "M21DESERT03"
    /* 4D3231444553455254303300 */
.align 2
enddlabel D_800D5F20
.size D_800D5F20, . - D_800D5F20

.align 2
nonmatching D_800D5F2C

dlabel D_800D5F2C
    /* 7E17C 800D5F2C */ .asciz "M21DESERT04"
    /* 4D3231444553455254303400 */
.align 2
enddlabel D_800D5F2C
.size D_800D5F2C, . - D_800D5F2C

.align 2
nonmatching D_800D5F38

dlabel D_800D5F38
    /* 7E188 800D5F38 */ .asciz "G21"
    /* 47323100 */
.align 2
enddlabel D_800D5F38
.size D_800D5F38, . - D_800D5F38

.align 2
nonmatching D_800D5F3C

dlabel D_800D5F3C
    /* 7E18C 800D5F3C */ .asciz "M22RUINS01"
    /* 4D32325255494E5330310000 */
.align 2
enddlabel D_800D5F3C
.size D_800D5F3C, . - D_800D5F3C

.align 2
nonmatching D_800D5F48

dlabel D_800D5F48
    /* 7E198 800D5F48 */ .asciz "M22RUINS05"
    /* 4D32325255494E5330350000 */
.align 2
enddlabel D_800D5F48
.size D_800D5F48, . - D_800D5F48

.align 2
nonmatching D_800D5F54

dlabel D_800D5F54
    /* 7E1A4 800D5F54 */ .asciz "M22RUINS02"
    /* 4D32325255494E5330320000 */
.align 2
enddlabel D_800D5F54
.size D_800D5F54, . - D_800D5F54

.align 2
nonmatching D_800D5F60

dlabel D_800D5F60
    /* 7E1B0 800D5F60 */ .asciz "M22RUINS03"
    /* 4D32325255494E5330330000 */
.align 2
enddlabel D_800D5F60
.size D_800D5F60, . - D_800D5F60

.align 2
nonmatching D_800D5F6C

dlabel D_800D5F6C
    /* 7E1BC 800D5F6C */ .asciz "M22RUINS04"
    /* 4D32325255494E5330340000 */
.align 2
enddlabel D_800D5F6C
.size D_800D5F6C, . - D_800D5F6C

.align 2
nonmatching D_800D5F78

dlabel D_800D5F78
    /* 7E1C8 800D5F78 */ .asciz "M22RUINSDEDEDE"
    /* 4D32325255494E534445444544450000 */
.align 2
enddlabel D_800D5F78
.size D_800D5F78, . - D_800D5F78

.align 2
nonmatching D_800D5F88

dlabel D_800D5F88
    /* 7E1D8 800D5F88 */ .asciz "G22"
    /* 47323200 */
.align 2
enddlabel D_800D5F88
.size D_800D5F88, . - D_800D5F88

.align 2
nonmatching D_800D5F8C

dlabel D_800D5F8C
    /* 7E1DC 800D5F8C */ .asciz "M23SAND01"
    /* 4D323353414E443031000000 */
.align 2
enddlabel D_800D5F8C
.size D_800D5F8C, . - D_800D5F8C

.align 2
nonmatching D_800D5F98

dlabel D_800D5F98
    /* 7E1E8 800D5F98 */ .asciz "M23SAND02"
    /* 4D323353414E443032000000 */
.align 2
enddlabel D_800D5F98
.size D_800D5F98, . - D_800D5F98

.align 2
nonmatching D_800D5FA4

dlabel D_800D5FA4
    /* 7E1F4 800D5FA4 */ .asciz "M23SANDRG"
    /* 4D323353414E445247000000 */
.align 2
enddlabel D_800D5FA4
.size D_800D5FA4, . - D_800D5FA4

.align 2
nonmatching D_800D5FB0

dlabel D_800D5FB0
    /* 7E200 800D5FB0 */ .asciz "M23SAND03"
    /* 4D323353414E443033000000 */
.align 2
enddlabel D_800D5FB0
.size D_800D5FB0, . - D_800D5FB0

.align 2
nonmatching D_800D5FBC

dlabel D_800D5FBC
    /* 7E20C 800D5FBC */ .asciz "M23SAND04"
    /* 4D323353414E443034000000 */
.align 2
enddlabel D_800D5FBC
.size D_800D5FBC, . - D_800D5FBC

.align 2
nonmatching D_800D5FC8

dlabel D_800D5FC8
    /* 7E218 800D5FC8 */ .asciz "M23SAND06"
    /* 4D323353414E443036000000 */
.align 2
enddlabel D_800D5FC8
.size D_800D5FC8, . - D_800D5FC8

.align 2
nonmatching D_800D5FD4

dlabel D_800D5FD4
    /* 7E224 800D5FD4 */ .asciz "M23SAND07"
    /* 4D323353414E443037000000 */
.align 2
enddlabel D_800D5FD4
.size D_800D5FD4, . - D_800D5FD4

.align 2
nonmatching D_800D5FE0

dlabel D_800D5FE0
    /* 7E230 800D5FE0 */ .asciz "M23SAND05"
    /* 4D323353414E443035000000 */
.align 2
enddlabel D_800D5FE0
.size D_800D5FE0, . - D_800D5FE0

.align 2
nonmatching D_800D5FEC

dlabel D_800D5FEC
    /* 7E23C 800D5FEC */ .asciz "G23"
    /* 47323300 */
.align 2
enddlabel D_800D5FEC
.size D_800D5FEC, . - D_800D5FEC

.align 2
nonmatching D_800D5FF0

dlabel D_800D5FF0
    /* 7E240 800D5FF0 */ .asciz "M24PYRAMID01"
    /* 4D3234505952414D4944303100000000 */
.align 2
enddlabel D_800D5FF0
.size D_800D5FF0, . - D_800D5FF0

.align 2
nonmatching D_800D6000

dlabel D_800D6000
    /* 7E250 800D6000 */ .asciz "M24PYRAMID02"
    /* 4D3234505952414D4944303200000000 */
.align 2
enddlabel D_800D6000
.size D_800D6000, . - D_800D6000

.align 2
nonmatching D_800D6010

dlabel D_800D6010
    /* 7E260 800D6010 */ .asciz "M24PYRAMID03"
    /* 4D3234505952414D4944303300000000 */
.align 2
enddlabel D_800D6010
.size D_800D6010, . - D_800D6010

.align 2
nonmatching D_800D6020

dlabel D_800D6020
    /* 7E270 800D6020 */ .asciz "M24PYRAMIDADO1"
    /* 4D3234505952414D494441444F310000 */
.align 2
enddlabel D_800D6020
.size D_800D6020, . - D_800D6020

.align 2
nonmatching D_800D6030

dlabel D_800D6030
    /* 7E280 800D6030 */ .asciz "M24PYRAMIDADO2"
    /* 4D3234505952414D494441444F320000 */
.align 2
enddlabel D_800D6030
.size D_800D6030, . - D_800D6030

.align 2
nonmatching D_800D6040

dlabel D_800D6040
    /* 7E290 800D6040 */ .asciz "M24PYRAMID04"
    /* 4D3234505952414D4944303400000000 */
.align 2
enddlabel D_800D6040
.size D_800D6040, . - D_800D6040

.align 2
nonmatching D_800D6050

dlabel D_800D6050
    /* 7E2A0 800D6050 */ .asciz "M24PYRAMIDRG"
    /* 4D3234505952414D4944524700000000 */
.align 2
enddlabel D_800D6050
.size D_800D6050, . - D_800D6050

.align 2
nonmatching D_800D6060

dlabel D_800D6060
    /* 7E2B0 800D6060 */ .asciz "M24PYRAMID05"
    /* 4D3234505952414D4944303500000000 */
.align 2
enddlabel D_800D6060
.size D_800D6060, . - D_800D6060

.align 2
nonmatching D_800D6070

dlabel D_800D6070
    /* 7E2C0 800D6070 */ .asciz "G24"
    /* 47323400 */
.align 2
enddlabel D_800D6070
.size D_800D6070, . - D_800D6070

.align 2
nonmatching D_800D6074

dlabel D_800D6074
    /* 7E2C4 800D6074 */ .asciz "M2PIX"
    /* 4D32504958000000 */
.align 2
enddlabel D_800D6074
.size D_800D6074, . - D_800D6074

.align 2
nonmatching D_800D607C

dlabel D_800D607C
    /* 7E2CC 800D607C */ .asciz "M31SEASIDE01"
    /* 4D333153454153494445303100000000 */
.align 2
enddlabel D_800D607C
.size D_800D607C, . - D_800D607C

.align 2
nonmatching D_800D608C

dlabel D_800D608C
    /* 7E2DC 800D608C */ .asciz "M31SEASIDE02"
    /* 4D333153454153494445303200000000 */
.align 2
enddlabel D_800D608C
.size D_800D608C, . - D_800D608C

.align 2
nonmatching D_800D609C

dlabel D_800D609C
    /* 7E2EC 800D609C */ .asciz "M31SEASIDE03"
    /* 4D333153454153494445303300000000 */
.align 2
enddlabel D_800D609C
.size D_800D609C, . - D_800D609C

.align 2
nonmatching D_800D60AC

dlabel D_800D60AC
    /* 7E2FC 800D60AC */ .asciz "M31SEASIDE06"
    /* 4D333153454153494445303600000000 */
.align 2
enddlabel D_800D60AC
.size D_800D60AC, . - D_800D60AC

.align 2
nonmatching D_800D60BC

dlabel D_800D60BC
    /* 7E30C 800D60BC */ .asciz "M31SEASIDERG"
    /* 4D333153454153494445524700000000 */
.align 2
enddlabel D_800D60BC
.size D_800D60BC, . - D_800D60BC

.align 2
nonmatching D_800D60CC

dlabel D_800D60CC
    /* 7E31C 800D60CC */ .asciz "M31SEASIDE05"
    /* 4D333153454153494445303500000000 */
.align 2
enddlabel D_800D60CC
.size D_800D60CC, . - D_800D60CC

.align 2
nonmatching D_800D60DC

dlabel D_800D60DC
    /* 7E32C 800D60DC */ .asciz "G31"
    /* 47333100 */
.align 2
enddlabel D_800D60DC
.size D_800D60DC, . - D_800D60DC

.align 2
nonmatching D_800D60E0

dlabel D_800D60E0
    /* 7E330 800D60E0 */ .asciz "M32RIVER01"
    /* 4D3332524956455230310000 */
.align 2
enddlabel D_800D60E0
.size D_800D60E0, . - D_800D60E0

.align 2
nonmatching D_800D60EC

dlabel D_800D60EC
    /* 7E33C 800D60EC */ .asciz "M32RIVER03"
    /* 4D3332524956455230330000 */
.align 2
enddlabel D_800D60EC
.size D_800D60EC, . - D_800D60EC

.align 2
nonmatching D_800D60F8

dlabel D_800D60F8
    /* 7E348 800D60F8 */ .asciz "M32RIVERRG"
    /* 4D3332524956455252470000 */
.align 2
enddlabel D_800D60F8
.size D_800D60F8, . - D_800D60F8

.align 2
nonmatching D_800D6104

dlabel D_800D6104
    /* 7E354 800D6104 */ .asciz "M32RIVERDEE"
    /* 4D3332524956455244454500 */
.align 2
enddlabel D_800D6104
.size D_800D6104, . - D_800D6104

.align 2
nonmatching D_800D6110

dlabel D_800D6110
    /* 7E360 800D6110 */ .asciz "M32RIVER05"
    /* 4D3332524956455230350000 */
.align 2
enddlabel D_800D6110
.size D_800D6110, . - D_800D6110

.align 2
nonmatching D_800D611C

dlabel D_800D611C
    /* 7E36C 800D611C */ .asciz "M32RIVER04"
    /* 4D3332524956455230340000 */
.align 2
enddlabel D_800D611C
.size D_800D611C, . - D_800D611C

.align 2
nonmatching D_800D6128

dlabel D_800D6128
    /* 7E378 800D6128 */ .asciz "G32"
    /* 47333200 */
.align 2
enddlabel D_800D6128
.size D_800D6128, . - D_800D6128

.align 2
nonmatching D_800D612C

dlabel D_800D612C
    /* 7E37C 800D612C */ .asciz "M33COAST06"
    /* 4D3333434F41535430360000 */
.align 2
enddlabel D_800D612C
.size D_800D612C, . - D_800D612C

.align 2
nonmatching D_800D6138

dlabel D_800D6138
    /* 7E388 800D6138 */ .asciz "M33COAST01"
    /* 4D3333434F41535430310000 */
.align 2
enddlabel D_800D6138
.size D_800D6138, . - D_800D6138

.align 2
nonmatching D_800D6144

dlabel D_800D6144
    /* 7E394 800D6144 */ .asciz "M33COAST03"
    /* 4D3333434F41535430330000 */
.align 2
enddlabel D_800D6144
.size D_800D6144, . - D_800D6144

.align 2
nonmatching D_800D6150

dlabel D_800D6150
    /* 7E3A0 800D6150 */ .asciz "M33COAST02"
    /* 4D3333434F41535430320000 */
.align 2
enddlabel D_800D6150
.size D_800D6150, . - D_800D6150

.align 2
nonmatching D_800D615C

dlabel D_800D615C
    /* 7E3AC 800D615C */ .asciz "M33COAST04"
    /* 4D3333434F41535430340000 */
.align 2
enddlabel D_800D615C
.size D_800D615C, . - D_800D615C

.align 2
nonmatching D_800D6168

dlabel D_800D6168
    /* 7E3B8 800D6168 */ .asciz "M33COASTRG"
    /* 4D3333434F41535452470000 */
.align 2
enddlabel D_800D6168
.size D_800D6168, . - D_800D6168

.align 2
nonmatching D_800D6174

dlabel D_800D6174
    /* 7E3C4 800D6174 */ .asciz "M33COAST05"
    /* 4D3333434F41535430350000 */
.align 2
enddlabel D_800D6174
.size D_800D6174, . - D_800D6174

.align 2
nonmatching D_800D6180

dlabel D_800D6180
    /* 7E3D0 800D6180 */ .asciz "G33"
    /* 47333300 */
.align 2
enddlabel D_800D6180
.size D_800D6180, . - D_800D6180

.align 2
nonmatching D_800D6184

dlabel D_800D6184
    /* 7E3D4 800D6184 */ .asciz "M34SUBMARINE01"
    /* 4D33345355424D4152494E4530310000 */
.align 2
enddlabel D_800D6184
.size D_800D6184, . - D_800D6184

.align 2
nonmatching D_800D6194

dlabel D_800D6194
    /* 7E3E4 800D6194 */ .asciz "M34SUBMARINE02"
    /* 4D33345355424D4152494E4530320000 */
.align 2
enddlabel D_800D6194
.size D_800D6194, . - D_800D6194

.align 2
nonmatching D_800D61A4

dlabel D_800D61A4
    /* 7E3F4 800D61A4 */ .asciz "M34SUBMARINE03"
    /* 4D33345355424D4152494E4530330000 */
.align 2
enddlabel D_800D61A4
.size D_800D61A4, . - D_800D61A4

.align 2
nonmatching D_800D61B4

dlabel D_800D61B4
    /* 7E404 800D61B4 */ .asciz "M34SUBMARINE05"
    /* 4D33345355424D4152494E4530350000 */
.align 2
enddlabel D_800D61B4
.size D_800D61B4, . - D_800D61B4

.align 2
nonmatching D_800D61C4

dlabel D_800D61C4
    /* 7E414 800D61C4 */ .asciz "M34SUBMARINERG"
    /* 4D33345355424D4152494E4552470000 */
.align 2
enddlabel D_800D61C4
.size D_800D61C4, . - D_800D61C4

.align 2
nonmatching D_800D61D4

dlabel D_800D61D4
    /* 7E424 800D61D4 */ .asciz "M34SUBMARINE04"
    /* 4D33345355424D4152494E4530340000 */
.align 2
enddlabel D_800D61D4
.size D_800D61D4, . - D_800D61D4

.align 2
nonmatching D_800D61E4

dlabel D_800D61E4
    /* 7E434 800D61E4 */ .asciz "G34"
    /* 47333400 */
.align 2
enddlabel D_800D61E4
.size D_800D61E4, . - D_800D61E4

.align 2
nonmatching D_800D61E8

dlabel D_800D61E8
    /* 7E438 800D61E8 */ .asciz "M3ACRO"
    /* 4D334143524F0000 */
.align 2
enddlabel D_800D61E8
.size D_800D61E8, . - D_800D61E8

.align 2
nonmatching D_800D61F0

dlabel D_800D61F0
    /* 7E440 800D61F0 */ .asciz "M41JUNGLE01"
    /* 4D34314A554E474C45303100 */
.align 2
enddlabel D_800D61F0
.size D_800D61F0, . - D_800D61F0

.align 2
nonmatching D_800D61FC

dlabel D_800D61FC
    /* 7E44C 800D61FC */ .asciz "M41JUNGLE03"
    /* 4D34314A554E474C45303300 */
.align 2
enddlabel D_800D61FC
.size D_800D61FC, . - D_800D61FC

.align 2
nonmatching D_800D6208

dlabel D_800D6208
    /* 7E458 800D6208 */ .asciz "M41JUNGLE06"
    /* 4D34314A554E474C45303600 */
.align 2
enddlabel D_800D6208
.size D_800D6208, . - D_800D6208

.align 2
nonmatching D_800D6214

dlabel D_800D6214
    /* 7E464 800D6214 */ .asciz "M41JUNGLERG"
    /* 4D34314A554E474C45524700 */
.align 2
enddlabel D_800D6214
.size D_800D6214, . - D_800D6214

.align 2
nonmatching D_800D6220

dlabel D_800D6220
    /* 7E470 800D6220 */ .asciz "M41JUNGLE05"
    /* 4D34314A554E474C45303500 */
.align 2
enddlabel D_800D6220
.size D_800D6220, . - D_800D6220

.align 2
nonmatching D_800D622C

dlabel D_800D622C
    /* 7E47C 800D622C */ .asciz "M41JUNGLE02"
    /* 4D34314A554E474C45303200 */
.align 2
enddlabel D_800D622C
.size D_800D622C, . - D_800D622C

.align 2
nonmatching D_800D6238

dlabel D_800D6238
    /* 7E488 800D6238 */ .asciz "G41"
    /* 47343100 */
.align 2
enddlabel D_800D6238
.size D_800D6238, . - D_800D6238

.align 2
nonmatching D_800D623C

dlabel D_800D623C
    /* 7E48C 800D623C */ .asciz "M42CAVERN01"
    /* 4D343243415645524E303100 */
.align 2
enddlabel D_800D623C
.size D_800D623C, . - D_800D623C

.align 2
nonmatching D_800D6248

dlabel D_800D6248
    /* 7E498 800D6248 */ .asciz "M42CAVERNDEE"
    /* 4D343243415645524E44454500000000 */
.align 2
enddlabel D_800D6248
.size D_800D6248, . - D_800D6248

.align 2
nonmatching D_800D6258

dlabel D_800D6258
    /* 7E4A8 800D6258 */ .asciz "M42CAVERN06"
    /* 4D343243415645524E303600 */
.align 2
enddlabel D_800D6258
.size D_800D6258, . - D_800D6258

.align 2
nonmatching D_800D6264

dlabel D_800D6264
    /* 7E4B4 800D6264 */ .asciz "M42CAVERN03"
    /* 4D343243415645524E303300 */
.align 2
enddlabel D_800D6264
.size D_800D6264, . - D_800D6264

.align 2
nonmatching D_800D6270

dlabel D_800D6270
    /* 7E4C0 800D6270 */ .asciz "M42CAVERN05"
    /* 4D343243415645524E303500 */
.align 2
enddlabel D_800D6270
.size D_800D6270, . - D_800D6270

.align 2
nonmatching D_800D627C

dlabel D_800D627C
    /* 7E4CC 800D627C */ .asciz "M42CAVERNRG"
    /* 4D343243415645524E524700 */
.align 2
enddlabel D_800D627C
.size D_800D627C, . - D_800D627C

.align 2
nonmatching D_800D6288

dlabel D_800D6288
    /* 7E4D8 800D6288 */ .asciz "M42CAVERN04"
    /* 4D343243415645524E303400 */
.align 2
enddlabel D_800D6288
.size D_800D6288, . - D_800D6288

.align 2
nonmatching D_800D6294

dlabel D_800D6294
    /* 7E4E4 800D6294 */ .asciz "G42"
    /* 47343200 */
.align 2
enddlabel D_800D6294
.size D_800D6294, . - D_800D6294

.align 2
nonmatching D_800D6298

dlabel D_800D6298
    /* 7E4E8 800D6298 */ .asciz "M43ROCK01"
    /* 4D3433524F434B3031000000 */
.align 2
enddlabel D_800D6298
.size D_800D6298, . - D_800D6298

.align 2
nonmatching D_800D62A4

dlabel D_800D62A4
    /* 7E4F4 800D62A4 */ .asciz "M43ROCK02"
    /* 4D3433524F434B3032000000 */
.align 2
enddlabel D_800D62A4
.size D_800D62A4, . - D_800D62A4

.align 2
nonmatching D_800D62B0

dlabel D_800D62B0
    /* 7E500 800D62B0 */ .asciz "M43ROCKADO1"
    /* 4D3433524F434B41444F3100 */
.align 2
enddlabel D_800D62B0
.size D_800D62B0, . - D_800D62B0

.align 2
nonmatching D_800D62BC

dlabel D_800D62BC
    /* 7E50C 800D62BC */ .asciz "M43ROCKADO2"
    /* 4D3433524F434B41444F3200 */
.align 2
enddlabel D_800D62BC
.size D_800D62BC, . - D_800D62BC

.align 2
nonmatching D_800D62C8

dlabel D_800D62C8
    /* 7E518 800D62C8 */ .asciz "M43ROCK03"
    /* 4D3433524F434B3033000000 */
.align 2
enddlabel D_800D62C8
.size D_800D62C8, . - D_800D62C8

.align 2
nonmatching D_800D62D4

dlabel D_800D62D4
    /* 7E524 800D62D4 */ .asciz "G43"
    /* 47343300 */
.align 2
enddlabel D_800D62D4
.size D_800D62D4, . - D_800D62D4

.align 2
nonmatching D_800D62D8

dlabel D_800D62D8
    /* 7E528 800D62D8 */ .asciz "M44LAVA01"
    /* 4D34344C4156413031000000 */
.align 2
enddlabel D_800D62D8
.size D_800D62D8, . - D_800D62D8

.align 2
nonmatching D_800D62E4

dlabel D_800D62E4
    /* 7E534 800D62E4 */ .asciz "M44LAVA02"
    /* 4D34344C4156413032000000 */
.align 2
enddlabel D_800D62E4
.size D_800D62E4, . - D_800D62E4

.align 2
nonmatching D_800D62F0

dlabel D_800D62F0
    /* 7E540 800D62F0 */ .asciz "M44LAVADEDE"
    /* 4D34344C4156414445444500 */
.align 2
enddlabel D_800D62F0
.size D_800D62F0, . - D_800D62F0

.align 2
nonmatching D_800D62FC

dlabel D_800D62FC
    /* 7E54C 800D62FC */ .asciz "M44LAVA03"
    /* 4D34344C4156413033000000 */
.align 2
enddlabel D_800D62FC
.size D_800D62FC, . - D_800D62FC

.align 2
nonmatching D_800D6308

dlabel D_800D6308
    /* 7E558 800D6308 */ .asciz "M44LAVA04"
    /* 4D34344C4156413034000000 */
.align 2
enddlabel D_800D6308
.size D_800D6308, . - D_800D6308

.align 2
nonmatching D_800D6314

dlabel D_800D6314
    /* 7E564 800D6314 */ .asciz "M44LAVA06"
    /* 4D34344C4156413036000000 */
.align 2
enddlabel D_800D6314
.size D_800D6314, . - D_800D6314

.align 2
nonmatching D_800D6320

dlabel D_800D6320
    /* 7E570 800D6320 */ .asciz "M44LAVA05"
    /* 4D34344C4156413035000000 */
.align 2
enddlabel D_800D6320
.size D_800D6320, . - D_800D6320

.align 2
nonmatching D_800D632C

dlabel D_800D632C
    /* 7E57C 800D632C */ .asciz "G44"
    /* 47343400 */
.align 2
enddlabel D_800D632C
.size D_800D632C, . - D_800D632C

.align 2
nonmatching D_800D6330

dlabel D_800D6330
    /* 7E580 800D6330 */ .asciz "M4MOLTEN"
    /* 4D344D4F4C54454E00000000 */
.align 2
enddlabel D_800D6330
.size D_800D6330, . - D_800D6330

.align 2
nonmatching D_800D633C

dlabel D_800D633C
    /* 7E58C 800D633C */ .asciz "M51SNOW01"
    /* 4D3531534E4F573031000000 */
.align 2
enddlabel D_800D633C
.size D_800D633C, . - D_800D633C

.align 2
nonmatching D_800D6348

dlabel D_800D6348
    /* 7E598 800D6348 */ .asciz "M51SNOW02"
    /* 4D3531534E4F573032000000 */
.align 2
enddlabel D_800D6348
.size D_800D6348, . - D_800D6348

.align 2
nonmatching D_800D6354

dlabel D_800D6354
    /* 7E5A4 800D6354 */ .asciz "M51SNOWDEE"
    /* 4D3531534E4F574445450000 */
.align 2
enddlabel D_800D6354
.size D_800D6354, . - D_800D6354

.align 2
nonmatching D_800D6360

dlabel D_800D6360
    /* 7E5B0 800D6360 */ .asciz "M51SNOWRG01"
    /* 4D3531534E4F575247303100 */
.align 2
enddlabel D_800D6360
.size D_800D6360, . - D_800D6360

.align 2
nonmatching D_800D636C

dlabel D_800D636C
    /* 7E5BC 800D636C */ .asciz "M51SNOW05"
    /* 4D3531534E4F573035000000 */
.align 2
enddlabel D_800D636C
.size D_800D636C, . - D_800D636C

.align 2
nonmatching D_800D6378

dlabel D_800D6378
    /* 7E5C8 800D6378 */ .asciz "M51SNOW04"
    /* 4D3531534E4F573034000000 */
.align 2
enddlabel D_800D6378
.size D_800D6378, . - D_800D6378

.align 2
nonmatching D_800D6384

dlabel D_800D6384
    /* 7E5D4 800D6384 */ .asciz "G51"
    /* 47353100 */
.align 2
enddlabel D_800D6384
.size D_800D6384, . - D_800D6384

.align 2
nonmatching D_800D6388

dlabel D_800D6388
    /* 7E5D8 800D6388 */ .asciz "M52CLOUD01"
    /* 4D3532434C4F554430310000 */
.align 2
enddlabel D_800D6388
.size D_800D6388, . - D_800D6388

.align 2
nonmatching D_800D6394

dlabel D_800D6394
    /* 7E5E4 800D6394 */ .asciz "M52CLOUD03"
    /* 4D3532434C4F554430330000 */
.align 2
enddlabel D_800D6394
.size D_800D6394, . - D_800D6394

.align 2
nonmatching D_800D63A0

dlabel D_800D63A0
    /* 7E5F0 800D63A0 */ .asciz "M52CLOUD02"
    /* 4D3532434C4F554430320000 */
.align 2
enddlabel D_800D63A0
.size D_800D63A0, . - D_800D63A0

.align 2
nonmatching D_800D63AC

dlabel D_800D63AC
    /* 7E5FC 800D63AC */ .asciz "M52CLOUD06"
    /* 4D3532434C4F554430360000 */
.align 2
enddlabel D_800D63AC
.size D_800D63AC, . - D_800D63AC

.align 2
nonmatching D_800D63B8

dlabel D_800D63B8
    /* 7E608 800D63B8 */ .asciz "M52CLOUD05"
    /* 4D3532434C4F554430350000 */
.align 2
enddlabel D_800D63B8
.size D_800D63B8, . - D_800D63B8

.align 2
nonmatching D_800D63C4

dlabel D_800D63C4
    /* 7E614 800D63C4 */ .asciz "M52CLOUDRG"
    /* 4D3532434C4F554452470000 */
.align 2
enddlabel D_800D63C4
.size D_800D63C4, . - D_800D63C4

.align 2
nonmatching D_800D63D0

dlabel D_800D63D0
    /* 7E620 800D63D0 */ .asciz "G52"
    /* 47353200 */
.align 2
enddlabel D_800D63D0
.size D_800D63D0, . - D_800D63D0

.align 2
nonmatching D_800D63D4

dlabel D_800D63D4
    /* 7E624 800D63D4 */ .asciz "M53BUILDING01"
    /* 4D35334255494C44494E473031000000 */
.align 2
enddlabel D_800D63D4
.size D_800D63D4, . - D_800D63D4

.align 2
nonmatching D_800D63E4

dlabel D_800D63E4
    /* 7E634 800D63E4 */ .asciz "M53BUILDING02"
    /* 4D35334255494C44494E473032000000 */
.align 2
enddlabel D_800D63E4
.size D_800D63E4, . - D_800D63E4

.align 2
nonmatching D_800D63F4

dlabel D_800D63F4
    /* 7E644 800D63F4 */ .asciz "M53BUILDING05"
    /* 4D35334255494C44494E473035000000 */
.align 2
enddlabel D_800D63F4
.size D_800D63F4, . - D_800D63F4

.align 2
nonmatching D_800D6404

dlabel D_800D6404
    /* 7E654 800D6404 */ .asciz "M53BUILDINGRG"
    /* 4D35334255494C44494E475247000000 */
.align 2
enddlabel D_800D6404
.size D_800D6404, . - D_800D6404

.align 2
nonmatching D_800D6414

dlabel D_800D6414
    /* 7E664 800D6414 */ .asciz "M53BUILDINGADO1"
    /* 4D35334255494C44494E4741444F3100 */
.align 2
enddlabel D_800D6414
.size D_800D6414, . - D_800D6414

.align 2
nonmatching D_800D6424

dlabel D_800D6424
    /* 7E674 800D6424 */ .asciz "M53BUILDINGADO2"
    /* 4D35334255494C44494E4741444F3200 */
.align 2
enddlabel D_800D6424
.size D_800D6424, . - D_800D6424

.align 2
nonmatching D_800D6434

dlabel D_800D6434
    /* 7E684 800D6434 */ .asciz "M53BUILDING03"
    /* 4D35334255494C44494E473033000000 */
.align 2
enddlabel D_800D6434
.size D_800D6434, . - D_800D6434

.align 2
nonmatching D_800D6444

dlabel D_800D6444
    /* 7E694 800D6444 */ .asciz "M53BUILDING04"
    /* 4D35334255494C44494E473034000000 */
.align 2
enddlabel D_800D6444
.size D_800D6444, . - D_800D6444

.align 2
nonmatching D_800D6454

dlabel D_800D6454
    /* 7E6A4 800D6454 */ .asciz "G53"
    /* 47353300 */
.align 2
enddlabel D_800D6454
.size D_800D6454, . - D_800D6454

.align 2
nonmatching D_800D6458

dlabel D_800D6458
    /* 7E6A8 800D6458 */ .asciz "M54FACTORY01"
    /* 4D3534464143544F5259303100000000 */
.align 2
enddlabel D_800D6458
.size D_800D6458, . - D_800D6458

.align 2
nonmatching D_800D6468

dlabel D_800D6468
    /* 7E6B8 800D6468 */ .asciz "M54FACTORY02"
    /* 4D3534464143544F5259303200000000 */
.align 2
enddlabel D_800D6468
.size D_800D6468, . - D_800D6468

.align 2
nonmatching D_800D6478

dlabel D_800D6478
    /* 7E6C8 800D6478 */ .asciz "M54FACTORYDEDE"
    /* 4D3534464143544F5259444544450000 */
.align 2
enddlabel D_800D6478
.size D_800D6478, . - D_800D6478

.align 2
nonmatching D_800D6488

dlabel D_800D6488
    /* 7E6D8 800D6488 */ .asciz "M54FACTORY05"
    /* 4D3534464143544F5259303500000000 */
.align 2
enddlabel D_800D6488
.size D_800D6488, . - D_800D6488

.align 2
nonmatching D_800D6498

dlabel D_800D6498
    /* 7E6E8 800D6498 */ .asciz "M54FACTORYRG"
    /* 4D3534464143544F5259524700000000 */
.align 2
enddlabel D_800D6498
.size D_800D6498, . - D_800D6498

.align 2
nonmatching D_800D64A8

dlabel D_800D64A8
    /* 7E6F8 800D64A8 */ .asciz "M54FACTORY07"
    /* 4D3534464143544F5259303700000000 */
.align 2
enddlabel D_800D64A8
.size D_800D64A8, . - D_800D64A8

.align 2
nonmatching D_800D64B8

dlabel D_800D64B8
    /* 7E708 800D64B8 */ .asciz "M54FACTORY06"
    /* 4D3534464143544F5259303600000000 */
.align 2
enddlabel D_800D64B8
.size D_800D64B8, . - D_800D64B8

.align 2
nonmatching D_800D64C8

dlabel D_800D64C8
    /* 7E718 800D64C8 */ .asciz "G54"
    /* 47353400 */
.align 2
enddlabel D_800D64C8
.size D_800D64C8, . - D_800D64C8

.align 2
nonmatching D_800D64CC

dlabel D_800D64CC
    /* 7E71C 800D64CC */ .asciz "M5HR"
    /* 4D35485200000000 */
.align 2
enddlabel D_800D64CC
.size D_800D64CC, . - D_800D64CC

.align 2
nonmatching D_800D64D4

dlabel D_800D64D4
    /* 7E724 800D64D4 */ .asciz "M61RPLAIN02"
    /* 4D363152504C41494E303200 */
.align 2
enddlabel D_800D64D4
.size D_800D64D4, . - D_800D64D4

.align 2
nonmatching D_800D64E0

dlabel D_800D64E0
    /* 7E730 800D64E0 */ .asciz "M61RPLAINRG"
    /* 4D363152504C41494E524700 */
.align 2
enddlabel D_800D64E0
.size D_800D64E0, . - D_800D64E0

.align 2
nonmatching D_800D64EC

dlabel D_800D64EC
    /* 7E73C 800D64EC */ .asciz "M61RPLAIN03"
    /* 4D363152504C41494E303300 */
.align 2
enddlabel D_800D64EC
.size D_800D64EC, . - D_800D64EC

.align 2
nonmatching D_800D64F8

dlabel D_800D64F8
    /* 7E748 800D64F8 */ .asciz "G61"
    /* 47363100 */
.align 2
enddlabel D_800D64F8
.size D_800D64F8, . - D_800D64F8

.align 2
nonmatching D_800D64FC

dlabel D_800D64FC
    /* 7E74C 800D64FC */ .asciz "M62RCASTLE01"
    /* 4D363252434153544C45303100000000 */
.align 2
enddlabel D_800D64FC
.size D_800D64FC, . - D_800D64FC

.align 2
nonmatching D_800D650C

dlabel D_800D650C
    /* 7E75C 800D650C */ .asciz "M62RCASTLE02"
    /* 4D363252434153544C45303200000000 */
.align 2
enddlabel D_800D650C
.size D_800D650C, . - D_800D650C

.align 2
nonmatching D_800D651C

dlabel D_800D651C
    /* 7E76C 800D651C */ .asciz "M62RCASTLEDE"
    /* 4D363252434153544C45444500000000 */
.align 2
enddlabel D_800D651C
.size D_800D651C, . - D_800D651C

.align 2
nonmatching D_800D652C

dlabel D_800D652C
    /* 7E77C 800D652C */ .asciz "M62RCASTLE03"
    /* 4D363252434153544C45303300000000 */
.align 2
enddlabel D_800D652C
.size D_800D652C, . - D_800D652C

.align 2
nonmatching D_800D653C

dlabel D_800D653C
    /* 7E78C 800D653C */ .asciz "M62RCASTLEADO"
    /* 4D363252434153544C4541444F000000 */
.align 2
enddlabel D_800D653C
.size D_800D653C, . - D_800D653C

.align 2
nonmatching D_800D654C

dlabel D_800D654C
    /* 7E79C 800D654C */ .asciz "M62RCASTLE04"
    /* 4D363252434153544C45303400000000 */
.align 2
enddlabel D_800D654C
.size D_800D654C, . - D_800D654C

.align 2
nonmatching D_800D655C

dlabel D_800D655C
    /* 7E7AC 800D655C */ .asciz "G62"
    /* 47363200 */
.align 2
enddlabel D_800D655C
.size D_800D655C, . - D_800D655C

.align 2
nonmatching D_800D6560

dlabel D_800D6560
    /* 7E7B0 800D6560 */ .asciz "M63RCASTLERG01"
    /* 4D363352434153544C45524730310000 */
.align 2
enddlabel D_800D6560
.size D_800D6560, . - D_800D6560

.align 2
nonmatching D_800D6570

dlabel D_800D6570
    /* 7E7C0 800D6570 */ .asciz "M63RCASTLERG02"
    /* 4D363352434153544C45524730320000 */
.align 2
enddlabel D_800D6570
.size D_800D6570, . - D_800D6570

.align 2
nonmatching D_800D6580

dlabel D_800D6580
    /* 7E7D0 800D6580 */ .asciz "M63RCASTLE05"
    /* 4D363352434153544C45303500000000 */
.align 2
enddlabel D_800D6580
.size D_800D6580, . - D_800D6580

.align 2
nonmatching D_800D6590

dlabel D_800D6590
    /* 7E7E0 800D6590 */ .asciz "M63RCASTLERG03"
    /* 4D363352434153544C45524730330000 */
.align 2
enddlabel D_800D6590
.size D_800D6590, . - D_800D6590

.align 2
nonmatching D_800D65A0

dlabel D_800D65A0
    /* 7E7F0 800D65A0 */ .asciz "M63RCASTLE06"
    /* 4D363352434153544C45303600000000 */
.align 2
enddlabel D_800D65A0
.size D_800D65A0, . - D_800D65A0

.align 2
nonmatching D_800D65B0

dlabel D_800D65B0
    /* 7E800 800D65B0 */ .asciz "M63RCASTLERG04"
    /* 4D363352434153544C45524730340000 */
.align 2
enddlabel D_800D65B0
.size D_800D65B0, . - D_800D65B0

.align 2
nonmatching D_800D65C0

dlabel D_800D65C0
    /* 7E810 800D65C0 */ .asciz "M63RCASTLE07"
    /* 4D363352434153544C45303700000000 */
.align 2
enddlabel D_800D65C0
.size D_800D65C0, . - D_800D65C0

.align 2
nonmatching D_800D65D0

dlabel D_800D65D0
    /* 7E820 800D65D0 */ .asciz "M63RCASTLERG05"
    /* 4D363352434153544C45524730350000 */
.align 2
enddlabel D_800D65D0
.size D_800D65D0, . - D_800D65D0

.align 2
nonmatching D_800D65E0

dlabel D_800D65E0
    /* 7E830 800D65E0 */ .asciz "M63RCASTLE08"
    /* 4D363352434153544C45303800000000 */
.align 2
enddlabel D_800D65E0
.size D_800D65E0, . - D_800D65E0

.align 2
nonmatching D_800D65F0

dlabel D_800D65F0
    /* 7E840 800D65F0 */ .asciz "M63RCASTLERG06"
    /* 4D363352434153544C45524730360000 */
.align 2
enddlabel D_800D65F0
.size D_800D65F0, . - D_800D65F0

.align 2
nonmatching D_800D6600

dlabel D_800D6600
    /* 7E850 800D6600 */ .asciz "M63RCASTLE09"
    /* 4D363352434153544C45303900000000 */
.align 2
enddlabel D_800D6600
.size D_800D6600, . - D_800D6600

.align 2
nonmatching D_800D6610

dlabel D_800D6610
    /* 7E860 800D6610 */ .asciz "G63"
    /* 47363300 */
.align 2
enddlabel D_800D6610
.size D_800D6610, . - D_800D6610

.align 2
nonmatching D_800D6614

dlabel D_800D6614
    /* 7E864 800D6614 */ .asciz "M6MIRACLE"
    /* 4D364D495241434C45000000 */
.align 2
enddlabel D_800D6614
.size D_800D6614, . - D_800D6614

.align 2
nonmatching D_800D6620

dlabel D_800D6620
    /* 7E870 800D6620 */ .asciz "M71WADO"
    /* 4D37315741444F00 */
.align 2
enddlabel D_800D6620
.size D_800D6620, . - D_800D6620

.align 2
nonmatching D_800D6628

dlabel D_800D6628
    /* 7E878 800D6628 */ .asciz "M71DEDE"
    /* 4D37314445444500 */
.align 2
enddlabel D_800D6628
.size D_800D6628, . - D_800D6628

.align 2
nonmatching D_800D6630

dlabel D_800D6630
    /* 7E880 800D6630 */ .asciz "M7LAST"
    /* 4D374C4153540000 */
.align 2
enddlabel D_800D6630
.size D_800D6630, . - D_800D6630

.align 2
nonmatching D_800D6638

dlabel D_800D6638
    /* 7E888 800D6638 */ .asciz "ABE200"
    /* 4142453230300000 */
.align 2
enddlabel D_800D6638
.size D_800D6638, . - D_800D6638

.align 2
nonmatching D_800D6640

dlabel D_800D6640
    /* 7E890 800D6640 */ .asciz "ABE100"
    /* 4142453130300000 */
.align 2
enddlabel D_800D6640
.size D_800D6640, . - D_800D6640

.align 2
nonmatching D_800D6648

dlabel D_800D6648
    /* 7E898 800D6648 */ .asciz "EXERCISE01"
    /* 455845524349534530310000 */
.align 2
enddlabel D_800D6648
.size D_800D6648, . - D_800D6648

.align 2
nonmatching D_800D6654

dlabel D_800D6654
    /* 7E8A4 800D6654 */ .asciz "ENETEST1"
    /* 454E45544553543100000000 */
.align 2
enddlabel D_800D6654
.size D_800D6654, . - D_800D6654

.align 2
nonmatching D_800D6660

dlabel D_800D6660
    /* 7E8B0 800D6660 */ .asciz "ENETEST2"
    /* 454E45544553543200000000 */
.align 2
enddlabel D_800D6660
.size D_800D6660, . - D_800D6660

.align 2
nonmatching D_800D666C

dlabel D_800D666C
    /* 7E8BC 800D666C */ .asciz "ITEM01"
    /* 4954454D30310000 */
.align 2
enddlabel D_800D666C
.size D_800D666C, . - D_800D666C

.align 2
nonmatching D_800D6674

dlabel D_800D6674
    /* 7E8C4 800D6674 */ .asciz "BREAKTEST1"
    /* 425245414B54455354310000 */
.align 2
enddlabel D_800D6674
.size D_800D6674, . - D_800D6674
