.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching CartRomHandle2, 0x78

dlabel CartRomHandle2
    /* 80098E00 */ .space 0x78

nonmatching LeoDiskHandle80098E78, 0x78

dlabel LeoDiskHandle80098E78
    /* 80098E78 */ .space 0x78
