.section .late_rodata
nonmatching D_80128700

dlabel D_80128700
    /* B1170 80128700 C61C3C00 */ .float -9999
    /* B1174 80128704 00000000 */ .float 0
    /* B1178 80128708 00000000 */ .float 0
    /* B117C 8012870C 00000000 */ .float 0
enddlabel D_80128700
.size D_80128700, . - D_80128700


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800F6830, 0x280

glabel func_800F6830
    /* 7F2A0 800F6830 3C088005 */  lui        $t0, %hi(gPlayerControllers)
    /* 7F2A4 800F6834 25088F20 */  addiu      $t0, $t0, %lo(gPlayerControllers)
    /* 7F2A8 800F6838 950E0000 */  lhu        $t6, 0x0($t0)
    /* 7F2AC 800F683C 3C01800D */  lui        $at, %hi(D_800D6F3C + 0x4)
    /* 7F2B0 800F6840 3C19800D */  lui        $t9, %hi(D_800D7B68)
    /* 7F2B4 800F6844 A42E6F40 */  sh         $t6, %lo(D_800D6F3C + 0x4)($at)
    /* 7F2B8 800F6848 950F0002 */  lhu        $t7, 0x2($t0)
    /* 7F2BC 800F684C 3C01800D */  lui        $at, %hi(D_800D6F3C + 0x6)
    /* 7F2C0 800F6850 8F397B68 */  lw         $t9, %lo(D_800D7B68)($t9)
    /* 7F2C4 800F6854 A42F6F42 */  sh         $t7, %lo(D_800D6F3C + 0x6)($at)
    /* 7F2C8 800F6858 95180004 */  lhu        $t8, 0x4($t0)
    /* 7F2CC 800F685C 27BDFF80 */  addiu      $sp, $sp, -0x80
    /* 7F2D0 800F6860 3C01800D */  lui        $at, %hi(D_800D6F3C + 0x8)
    /* 7F2D4 800F6864 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 7F2D8 800F6868 13200028 */  beqz       $t9, .L800F690C
    /* 7F2DC 800F686C A4386F44 */   sh        $t8, %lo(D_800D6F3C + 0x8)($at)
    /* 7F2E0 800F6870 3C09800D */  lui        $t1, %hi(D_800D799C)
    /* 7F2E4 800F6874 8D29799C */  lw         $t1, %lo(D_800D799C)($t1)
    /* 7F2E8 800F6878 27A40040 */  addiu      $a0, $sp, 0x40
    /* 7F2EC 800F687C 8D22003C */  lw         $v0, 0x3C($t1)
    /* 7F2F0 800F6880 C4440048 */  lwc1       $f4, 0x48($v0)
    /* 7F2F4 800F6884 8C45003C */  lw         $a1, 0x3C($v0)
    /* 7F2F8 800F6888 8C460040 */  lw         $a2, 0x40($v0)
    /* 7F2FC 800F688C 8C470044 */  lw         $a3, 0x44($v0)
    /* 7F300 800F6890 E7A40010 */  swc1       $f4, 0x10($sp)
    /* 7F304 800F6894 C446004C */  lwc1       $f6, 0x4C($v0)
    /* 7F308 800F6898 E7A60014 */  swc1       $f6, 0x14($sp)
    /* 7F30C 800F689C C4480050 */  lwc1       $f8, 0x50($v0)
    /* 7F310 800F68A0 E7A80018 */  swc1       $f8, 0x18($sp)
    /* 7F314 800F68A4 C44A0054 */  lwc1       $f10, 0x54($v0)
    /* 7F318 800F68A8 E7AA001C */  swc1       $f10, 0x1C($sp)
    /* 7F31C 800F68AC C4500058 */  lwc1       $f16, 0x58($v0)
    /* 7F320 800F68B0 E7B00020 */  swc1       $f16, 0x20($sp)
    /* 7F324 800F68B4 C452005C */  lwc1       $f18, 0x5C($v0)
    /* 7F328 800F68B8 AFA2003C */  sw         $v0, 0x3C($sp)
    /* 7F32C 800F68BC 0C0067AC */  jal        guLookAtF
    /* 7F330 800F68C0 E7B20024 */   swc1      $f18, 0x24($sp)
    /* 7F334 800F68C4 8FA2003C */  lw         $v0, 0x3C($sp)
    /* 7F338 800F68C8 3C04800D */  lui        $a0, %hi(D_800D6ED0)
    /* 7F33C 800F68CC 24846ED0 */  addiu      $a0, $a0, %lo(D_800D6ED0)
    /* 7F340 800F68D0 C4440028 */  lwc1       $f4, 0x28($v0)
    /* 7F344 800F68D4 8C460020 */  lw         $a2, 0x20($v0)
    /* 7F348 800F68D8 8C470024 */  lw         $a3, 0x24($v0)
    /* 7F34C 800F68DC E7A40010 */  swc1       $f4, 0x10($sp)
    /* 7F350 800F68E0 C446002C */  lwc1       $f6, 0x2C($v0)
    /* 7F354 800F68E4 27A5003A */  addiu      $a1, $sp, 0x3A
    /* 7F358 800F68E8 E7A60014 */  swc1       $f6, 0x14($sp)
    /* 7F35C 800F68EC C4480030 */  lwc1       $f8, 0x30($v0)
    /* 7F360 800F68F0 0C006C02 */  jal        HS64_PerspectiveF
    /* 7F364 800F68F4 E7A80018 */   swc1      $f8, 0x18($sp)
    /* 7F368 800F68F8 3C05800D */  lui        $a1, %hi(D_800D6ED0)
    /* 7F36C 800F68FC 24A56ED0 */  addiu      $a1, $a1, %lo(D_800D6ED0)
    /* 7F370 800F6900 00A03025 */  or         $a2, $a1, $zero
    /* 7F374 800F6904 0C00D034 */  jal        guMtxCatF
    /* 7F378 800F6908 27A40040 */   addiu     $a0, $sp, 0x40
  .L800F690C:
    /* 7F37C 800F690C 3C0B8013 */  lui        $t3, %hi(D_801290D8)
    /* 7F380 800F6910 8D6B90D8 */  lw         $t3, %lo(D_801290D8)($t3)
    /* 7F384 800F6914 3C0E800D */  lui        $t6, %hi(D_800D478C)
    /* 7F388 800F6918 25CE478C */  addiu      $t6, $t6, %lo(D_800D478C)
    /* 7F38C 800F691C 956C000A */  lhu        $t4, 0xA($t3)
    /* 7F390 800F6920 3C0A800D */  lui        $t2, %hi(D_800D6B18 + 0x8)
    /* 7F394 800F6924 8D4A6B20 */  lw         $t2, %lo(D_800D6B18 + 0x8)($t2)
    /* 7F398 800F6928 000C6880 */  sll        $t5, $t4, 2
    /* 7F39C 800F692C 01AC6823 */  subu       $t5, $t5, $t4
    /* 7F3A0 800F6930 000D6880 */  sll        $t5, $t5, 2
    /* 7F3A4 800F6934 01AE1821 */  addu       $v1, $t5, $t6
    /* 7F3A8 800F6938 906F0002 */  lbu        $t7, 0x2($v1)
    /* 7F3AC 800F693C 90790000 */  lbu        $t9, 0x0($v1)
    /* 7F3B0 800F6940 906B0001 */  lbu        $t3, 0x1($v1)
    /* 7F3B4 800F6944 8D42003C */  lw         $v0, 0x3C($t2)
    /* 7F3B8 800F6948 000FC200 */  sll        $t8, $t7, 8
    /* 7F3BC 800F694C 00194E00 */  sll        $t1, $t9, 24
    /* 7F3C0 800F6950 03095025 */  or         $t2, $t8, $t1
    /* 7F3C4 800F6954 000B6400 */  sll        $t4, $t3, 16
    /* 7F3C8 800F6958 014C6825 */  or         $t5, $t2, $t4
    /* 7F3CC 800F695C 3C04800C */  lui        $a0, %hi(D_800BE4EC)
    /* 7F3D0 800F6960 35AE00FF */  ori        $t6, $t5, 0xFF
    /* 7F3D4 800F6964 2484E4EC */  addiu      $a0, $a0, %lo(D_800BE4EC)
    /* 7F3D8 800F6968 AC4E0084 */  sw         $t6, 0x84($v0)
    /* 7F3DC 800F696C 8C8F0000 */  lw         $t7, 0x0($a0)
    /* 7F3E0 800F6970 25F90001 */  addiu      $t9, $t7, 0x1
    /* 7F3E4 800F6974 0C02EFD8 */  jal        func_800BBF60
    /* 7F3E8 800F6978 AC990000 */   sw        $t9, 0x0($a0)
    /* 7F3EC 800F697C 3C03800C */  lui        $v1, %hi(D_800BE544)
    /* 7F3F0 800F6980 2463E544 */  addiu      $v1, $v1, %lo(D_800BE544)
    /* 7F3F4 800F6984 8C620000 */  lw         $v0, 0x0($v1)
    /* 7F3F8 800F6988 3C18800C */  lui        $t8, %hi(D_800BE4F8)
    /* 7F3FC 800F698C 04420031 */  bltzl      $v0, .L800F6A54
    /* 7F400 800F6990 44822000 */   mtc1      $v0, $f4
    /* 7F404 800F6994 8F18E4F8 */  lw         $t8, %lo(D_800BE4F8)($t8)
    /* 7F408 800F6998 24010001 */  addiu      $at, $zero, 0x1
    /* 7F40C 800F699C 1701002C */  bne        $t8, $at, .L800F6A50
    /* 7F410 800F69A0 3C01800D */   lui       $at, %hi(gKirbyHp)
    /* 7F414 800F69A4 C4306E50 */  lwc1       $f16, %lo(gKirbyHp)($at)
    /* 7F418 800F69A8 44805000 */  mtc1       $zero, $f10
    /* 7F41C 800F69AC 00000000 */  nop
    /* 7F420 800F69B0 46105032 */  c.eq.s     $f10, $f16
    /* 7F424 800F69B4 00000000 */  nop
    /* 7F428 800F69B8 45030026 */  bc1tl      .L800F6A54
    /* 7F42C 800F69BC 44822000 */   mtc1      $v0, $f4
    /* 7F430 800F69C0 0C03E158 */  jal        func_800F8560
    /* 7F434 800F69C4 00000000 */   nop
    /* 7F438 800F69C8 3C03800C */  lui        $v1, %hi(D_800BE544)
    /* 7F43C 800F69CC 24010003 */  addiu      $at, $zero, 0x3
    /* 7F440 800F69D0 1041002D */  beq        $v0, $at, .L800F6A88
    /* 7F444 800F69D4 2463E544 */   addiu     $v1, $v1, %lo(D_800BE544)
    /* 7F448 800F69D8 8C620000 */  lw         $v0, 0x0($v1)
    /* 7F44C 800F69DC 3C098005 */  lui        $t1, %hi(gPlayerControllers + 0x2)
    /* 7F450 800F69E0 14400015 */  bnez       $v0, .L800F6A38
    /* 7F454 800F69E4 304D8000 */   andi      $t5, $v0, 0x8000
    /* 7F458 800F69E8 95298F22 */  lhu        $t1, %lo(gPlayerControllers + 0x2)($t1)
    /* 7F45C 800F69EC 312B1000 */  andi       $t3, $t1, 0x1000
    /* 7F460 800F69F0 11600025 */  beqz       $t3, .L800F6A88
    /* 7F464 800F69F4 00000000 */   nop
    /* 7F468 800F69F8 0C02ECFC */  jal        func_800BB3F0
    /* 7F46C 800F69FC 00000000 */   nop
    /* 7F470 800F6A00 0C029A67 */  jal        utilPauseAllGObjs
    /* 7F474 800F6A04 00000000 */   nop
    /* 7F478 800F6A08 24040027 */  addiu      $a0, $zero, 0x27
    /* 7F47C 800F6A0C 2405004A */  addiu      $a1, $zero, 0x4A
    /* 7F480 800F6A10 0C02BA99 */  jal        func_800AEA64
    /* 7F484 800F6A14 24060070 */   addiu     $a2, $zero, 0x70
    /* 7F488 800F6A18 3C03800C */  lui        $v1, %hi(D_800BE544)
    /* 7F48C 800F6A1C 2463E544 */  addiu      $v1, $v1, %lo(D_800BE544)
    /* 7F490 800F6A20 00026080 */  sll        $t4, $v0, 2
    /* 7F494 800F6A24 3C01800F */  lui        $at, %hi(D_800EC2E0)
    /* 7F498 800F6A28 AC620000 */  sw         $v0, 0x0($v1)
    /* 7F49C 800F6A2C 002C0821 */  addu       $at, $at, $t4
    /* 7F4A0 800F6A30 10000015 */  b          .L800F6A88
    /* 7F4A4 800F6A34 AC20C2E0 */   sw        $zero, %lo(D_800EC2E0)($at)
  .L800F6A38:
    /* 7F4A8 800F6A38 11A00013 */  beqz       $t5, .L800F6A88
    /* 7F4AC 800F6A3C 00000000 */   nop
    /* 7F4B0 800F6A40 0C029A86 */  jal        utilResumeAllGObjs
    /* 7F4B4 800F6A44 AC600000 */   sw        $zero, 0x0($v1)
    /* 7F4B8 800F6A48 1000000F */  b          .L800F6A88
    /* 7F4BC 800F6A4C 00000000 */   nop
  .L800F6A50:
    /* 7F4C0 800F6A50 44822000 */  mtc1       $v0, $f4
  .L800F6A54:
    /* 7F4C4 800F6A54 3C018013 */  lui        $at, %hi(D_80128700)
    /* 7F4C8 800F6A58 C4328700 */  lwc1       $f18, %lo(D_80128700)($at)
    /* 7F4CC 800F6A5C 468021A0 */  cvt.s.w    $f6, $f4
    /* 7F4D0 800F6A60 240ED8F1 */  addiu      $t6, $zero, -0x270F
    /* 7F4D4 800F6A64 46069032 */  c.eq.s     $f18, $f6
    /* 7F4D8 800F6A68 00000000 */  nop
    /* 7F4DC 800F6A6C 45000003 */  bc1f       .L800F6A7C
    /* 7F4E0 800F6A70 00000000 */   nop
    /* 7F4E4 800F6A74 10000004 */  b          .L800F6A88
    /* 7F4E8 800F6A78 AC6E0000 */   sw        $t6, 0x0($v1)
  .L800F6A7C:
    /* 7F4EC 800F6A7C 04410002 */  bgez       $v0, .L800F6A88
    /* 7F4F0 800F6A80 244F0001 */   addiu     $t7, $v0, 0x1
    /* 7F4F4 800F6A84 AC6F0000 */  sw         $t7, 0x0($v1)
  .L800F6A88:
    /* 7F4F8 800F6A88 0C03D868 */  jal        func_800F61A0
    /* 7F4FC 800F6A8C 00000000 */   nop
    /* 7F500 800F6A90 0C002B62 */  jal        omUpdateAll
    /* 7F504 800F6A94 00000000 */   nop
    /* 7F508 800F6A98 0C03D8A7 */  jal        func_800F629C
    /* 7F50C 800F6A9C 00000000 */   nop
    /* 7F510 800F6AA0 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 7F514 800F6AA4 27BD0080 */  addiu      $sp, $sp, 0x80
    /* 7F518 800F6AA8 03E00008 */  jr         $ra
    /* 7F51C 800F6AAC 00000000 */   nop
endlabel func_800F6830
.size func_800F6830, . - func_800F6830
