.section .late_rodata
nonmatching D_800D5C64

dlabel D_800D5C64
    /* 7DEB4 800D5C64 3FC90FDB */ .float 1.570796371
enddlabel D_800D5C64
.size D_800D5C64, . - D_800D5C64

nonmatching D_800D5C68

dlabel D_800D5C68
    /* 7DEB8 800D5C68 BFC90FDB */ .float -1.570796371
    /* 7DEBC 800D5C6C 00000000 */ .float 0
enddlabel D_800D5C68
.size D_800D5C68, . - D_800D5C68


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800A6820, 0x17C

glabel func_800A6820
    /* 4EA70 800A6820 27BDFF88 */  addiu      $sp, $sp, -0x78
    /* 4EA74 800A6824 F7B60018 */  sdc1       $f22, 0x18($sp)
    /* 4EA78 800A6828 F7B40010 */  sdc1       $f20, 0x10($sp)
    /* 4EA7C 800A682C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 4EA80 800A6830 AFB30030 */  sw         $s3, 0x30($sp)
    /* 4EA84 800A6834 AFB2002C */  sw         $s2, 0x2C($sp)
    /* 4EA88 800A6838 AFB10028 */  sw         $s1, 0x28($sp)
    /* 4EA8C 800A683C AFB00024 */  sw         $s0, 0x24($sp)
    /* 4EA90 800A6840 4481B000 */  mtc1       $at, $f22
    /* 4EA94 800A6844 4480A000 */  mtc1       $zero, $f20
    /* 4EA98 800A6848 00A09825 */  or         $s3, $a1, $zero
    /* 4EA9C 800A684C AFBF0034 */  sw         $ra, 0x34($sp)
    /* 4EAA0 800A6850 00808025 */  or         $s0, $a0, $zero
    /* 4EAA4 800A6854 27B10048 */  addiu      $s1, $sp, 0x48
    /* 4EAA8 800A6858 27B2006C */  addiu      $s2, $sp, 0x6C
  .L800A685C:
    /* 4EAAC 800A685C C6020000 */  lwc1       $f2, 0x0($s0)
    /* 4EAB0 800A6860 C60E0004 */  lwc1       $f14, 0x4($s0)
    /* 4EAB4 800A6864 C6000008 */  lwc1       $f0, 0x8($s0)
    /* 4EAB8 800A6868 46021102 */  mul.s      $f4, $f2, $f2
    /* 4EABC 800A686C 00000000 */  nop
    /* 4EAC0 800A6870 460E7182 */  mul.s      $f6, $f14, $f14
    /* 4EAC4 800A6874 46062200 */  add.s      $f8, $f4, $f6
    /* 4EAC8 800A6878 46000282 */  mul.s      $f10, $f0, $f0
    /* 4EACC 800A687C 0C00CAC8 */  jal        sqrtf
    /* 4EAD0 800A6880 46085300 */   add.s     $f12, $f10, $f8
    /* 4EAD4 800A6884 46140032 */  c.eq.s     $f0, $f20
    /* 4EAD8 800A6888 46000086 */  mov.s      $f2, $f0
    /* 4EADC 800A688C 45030003 */  bc1tl      .L800A689C
    /* 4EAE0 800A6890 C6100000 */   lwc1      $f16, 0x0($s0)
    /* 4EAE4 800A6894 4600B083 */  div.s      $f2, $f22, $f0
    /* 4EAE8 800A6898 C6100000 */  lwc1       $f16, 0x0($s0)
  .L800A689C:
    /* 4EAEC 800A689C 2631000C */  addiu      $s1, $s1, 0xC
    /* 4EAF0 800A68A0 2610000C */  addiu      $s0, $s0, 0xC
    /* 4EAF4 800A68A4 46028482 */  mul.s      $f18, $f16, $f2
    /* 4EAF8 800A68A8 E632FFF4 */  swc1       $f18, -0xC($s1)
    /* 4EAFC 800A68AC C604FFF8 */  lwc1       $f4, -0x8($s0)
    /* 4EB00 800A68B0 46022182 */  mul.s      $f6, $f4, $f2
    /* 4EB04 800A68B4 E626FFF8 */  swc1       $f6, -0x8($s1)
    /* 4EB08 800A68B8 C60AFFFC */  lwc1       $f10, -0x4($s0)
    /* 4EB0C 800A68BC 46025202 */  mul.s      $f8, $f10, $f2
    /* 4EB10 800A68C0 1632FFE6 */  bne        $s1, $s2, .L800A685C
    /* 4EB14 800A68C4 E628FFFC */   swc1      $f8, -0x4($s1)
    /* 4EB18 800A68C8 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* 4EB1C 800A68CC 44811000 */  mtc1       $at, $f2
    /* 4EB20 800A68D0 C7A00050 */  lwc1       $f0, 0x50($sp)
    /* 4EB24 800A68D4 46001032 */  c.eq.s     $f2, $f0
    /* 4EB28 800A68D8 00000000 */  nop
    /* 4EB2C 800A68DC 45030006 */  bc1tl      .L800A68F8
    /* 4EB30 800A68E0 46001032 */   c.eq.s    $f2, $f0
    /* 4EB34 800A68E4 4600B032 */  c.eq.s     $f22, $f0
    /* 4EB38 800A68E8 00000000 */  nop
    /* 4EB3C 800A68EC 45000017 */  bc1f       .L800A694C
    /* 4EB40 800A68F0 00000000 */   nop
    /* 4EB44 800A68F4 46001032 */  c.eq.s     $f2, $f0
  .L800A68F8:
    /* 4EB48 800A68F8 3C01800D */  lui        $at, %hi(D_800D5C68)
    /* 4EB4C 800A68FC 45000009 */  bc1f       .L800A6924
    /* 4EB50 800A6900 00000000 */   nop
    /* 4EB54 800A6904 3C01800D */  lui        $at, %hi(D_800D5C64)
    /* 4EB58 800A6908 C4305C64 */  lwc1       $f16, %lo(D_800D5C64)($at)
    /* 4EB5C 800A690C E6700004 */  swc1       $f16, 0x4($s3)
    /* 4EB60 800A6910 C7AE0058 */  lwc1       $f14, 0x58($sp)
    /* 4EB64 800A6914 0C0061C3 */  jal        atan2f
    /* 4EB68 800A6918 C7AC0054 */   lwc1      $f12, 0x54($sp)
    /* 4EB6C 800A691C 10000008 */  b          .L800A6940
    /* 4EB70 800A6920 E6600000 */   swc1      $f0, 0x0($s3)
  .L800A6924:
    /* 4EB74 800A6924 C4325C68 */  lwc1       $f18, %lo(D_800D5C68)($at)
    /* 4EB78 800A6928 E6720004 */  swc1       $f18, 0x4($s3)
    /* 4EB7C 800A692C C7AC0054 */  lwc1       $f12, 0x54($sp)
    /* 4EB80 800A6930 C7AE0058 */  lwc1       $f14, 0x58($sp)
    /* 4EB84 800A6934 0C0061C3 */  jal        atan2f
    /* 4EB88 800A6938 46006307 */   neg.s     $f12, $f12
    /* 4EB8C 800A693C E6600000 */  swc1       $f0, 0x0($s3)
  .L800A6940:
    /* 4EB90 800A6940 44802000 */  mtc1       $zero, $f4
    /* 4EB94 800A6944 1000000C */  b          .L800A6978
    /* 4EB98 800A6948 E6640008 */   swc1      $f4, 0x8($s3)
  .L800A694C:
    /* 4EB9C 800A694C 0C006203 */  jal        asinf
    /* 4EBA0 800A6950 46000307 */   neg.s     $f12, $f0
    /* 4EBA4 800A6954 E6600004 */  swc1       $f0, 0x4($s3)
    /* 4EBA8 800A6958 C7AE0068 */  lwc1       $f14, 0x68($sp)
    /* 4EBAC 800A695C 0C0061C3 */  jal        atan2f
    /* 4EBB0 800A6960 C7AC005C */   lwc1      $f12, 0x5C($sp)
    /* 4EBB4 800A6964 E6600000 */  swc1       $f0, 0x0($s3)
    /* 4EBB8 800A6968 C7AE0048 */  lwc1       $f14, 0x48($sp)
    /* 4EBBC 800A696C 0C0061C3 */  jal        atan2f
    /* 4EBC0 800A6970 C7AC004C */   lwc1      $f12, 0x4C($sp)
    /* 4EBC4 800A6974 E6600008 */  swc1       $f0, 0x8($s3)
  .L800A6978:
    /* 4EBC8 800A6978 8FBF0034 */  lw         $ra, 0x34($sp)
    /* 4EBCC 800A697C D7B40010 */  ldc1       $f20, 0x10($sp)
    /* 4EBD0 800A6980 D7B60018 */  ldc1       $f22, 0x18($sp)
    /* 4EBD4 800A6984 8FB00024 */  lw         $s0, 0x24($sp)
    /* 4EBD8 800A6988 8FB10028 */  lw         $s1, 0x28($sp)
    /* 4EBDC 800A698C 8FB2002C */  lw         $s2, 0x2C($sp)
    /* 4EBE0 800A6990 8FB30030 */  lw         $s3, 0x30($sp)
    /* 4EBE4 800A6994 03E00008 */  jr         $ra
    /* 4EBE8 800A6998 27BD0078 */   addiu     $sp, $sp, 0x78
endlabel func_800A6820
.size func_800A6820, . - func_800A6820
