.section .rodata
.align 2
nonmatching D_801288E0

dlabel D_801288E0
    /* B1350 801288E0 */ .asciz "Explosion(model) Request Error![effect.cc]\n"
    /* 4578706C6F73696F6E286D6F64656C292052657175657374204572726F72215B6566666563742E63635D0A00 */
.align 2
enddlabel D_801288E0
.size D_801288E0, . - D_801288E0


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800FD570, 0x1E4

glabel func_800FD570
    /* 85FE0 800FD570 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 85FE4 800FD574 44866000 */  mtc1       $a2, $f12
    /* 85FE8 800FD578 44877000 */  mtc1       $a3, $f14
    /* 85FEC 800FD57C 00803025 */  or         $a2, $a0, $zero
    /* 85FF0 800FD580 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 85FF4 800FD584 AFA40038 */  sw         $a0, 0x38($sp)
    /* 85FF8 800FD588 10800009 */  beqz       $a0, .L800FD5B0
    /* 85FFC 800FD58C AFA5003C */   sw        $a1, 0x3C($sp)
    /* 86000 800FD590 27A40028 */  addiu      $a0, $sp, 0x28
    /* 86004 800FD594 00C02825 */  or         $a1, $a2, $zero
    /* 86008 800FD598 E7AC0040 */  swc1       $f12, 0x40($sp)
    /* 8600C 800FD59C 0C0291E5 */  jal        utilGetTransformSRT
    /* 86010 800FD5A0 E7AE0044 */   swc1      $f14, 0x44($sp)
    /* 86014 800FD5A4 C7AC0040 */  lwc1       $f12, 0x40($sp)
    /* 86018 800FD5A8 10000015 */  b          .L800FD600
    /* 8601C 800FD5AC C7AE0044 */   lwc1      $f14, 0x44($sp)
  .L800FD5B0:
    /* 86020 800FD5B0 3C028005 */  lui        $v0, %hi(omCurrentObj)
    /* 86024 800FD5B4 8C42A7C4 */  lw         $v0, %lo(omCurrentObj)($v0)
    /* 86028 800FD5B8 3C01800E */  lui        $at, %hi(gEntitiesNextPosXArray)
    /* 8602C 800FD5BC 8C4E0000 */  lw         $t6, 0x0($v0)
    /* 86030 800FD5C0 000E7880 */  sll        $t7, $t6, 2
    /* 86034 800FD5C4 002F0821 */  addu       $at, $at, $t7
    /* 86038 800FD5C8 C42425D0 */  lwc1       $f4, %lo(gEntitiesNextPosXArray)($at)
    /* 8603C 800FD5CC 3C01800E */  lui        $at, %hi(gEntitiesNextPosYArray)
    /* 86040 800FD5D0 E7A40028 */  swc1       $f4, 0x28($sp)
    /* 86044 800FD5D4 8C580000 */  lw         $t8, 0x0($v0)
    /* 86048 800FD5D8 0018C880 */  sll        $t9, $t8, 2
    /* 8604C 800FD5DC 00390821 */  addu       $at, $at, $t9
    /* 86050 800FD5E0 C4262790 */  lwc1       $f6, %lo(gEntitiesNextPosYArray)($at)
    /* 86054 800FD5E4 3C01800E */  lui        $at, %hi(gEntitiesNextPosZArray)
    /* 86058 800FD5E8 E7A6002C */  swc1       $f6, 0x2C($sp)
    /* 8605C 800FD5EC 8C480000 */  lw         $t0, 0x0($v0)
    /* 86060 800FD5F0 00084880 */  sll        $t1, $t0, 2
    /* 86064 800FD5F4 00290821 */  addu       $at, $at, $t1
    /* 86068 800FD5F8 C4282950 */  lwc1       $f8, %lo(gEntitiesNextPosZArray)($at)
    /* 8606C 800FD5FC E7A80030 */  swc1       $f8, 0x30($sp)
  .L800FD600:
    /* 86070 800FD600 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 86074 800FD604 3C0C8012 */  lui        $t4, %hi(D_801245C4)
    /* 86078 800FD608 258C45C4 */  addiu      $t4, $t4, %lo(D_801245C4)
    /* 8607C 800FD60C 000A5880 */  sll        $t3, $t2, 2
    /* 86080 800FD610 016A5823 */  subu       $t3, $t3, $t2
    /* 86084 800FD614 000B5880 */  sll        $t3, $t3, 2
    /* 86088 800FD618 016C1021 */  addu       $v0, $t3, $t4
    /* 8608C 800FD61C 8C4D0000 */  lw         $t5, 0x0($v0)
    /* 86090 800FD620 3C0F8012 */  lui        $t7, %hi(D_80124630)
    /* 86094 800FD624 00002025 */  or         $a0, $zero, $zero
    /* 86098 800FD628 11A00025 */  beqz       $t5, .L800FD6C0
    /* 8609C 800FD62C 25EF4630 */   addiu     $t7, $t7, %lo(D_80124630)
    /* 860A0 800FD630 E7AC0040 */  swc1       $f12, 0x40($sp)
    /* 860A4 800FD634 0C03F675 */  jal        func_800FD9D4
    /* 860A8 800FD638 E7AE0044 */   swc1      $f14, 0x44($sp)
    /* 860AC 800FD63C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 860B0 800FD640 C7AC0040 */  lwc1       $f12, 0x40($sp)
    /* 860B4 800FD644 C7AE0044 */  lwc1       $f14, 0x44($sp)
    /* 860B8 800FD648 14410006 */  bne        $v0, $at, .L800FD664
    /* 860BC 800FD64C 00402025 */   or        $a0, $v0, $zero
    /* 860C0 800FD650 3C048013 */  lui        $a0, %hi(D_801288E0)
    /* 860C4 800FD654 0C02909C */  jal        utilPrintf
    /* 860C8 800FD658 248488E0 */   addiu     $a0, $a0, %lo(D_801288E0)
    /* 860CC 800FD65C 10000039 */  b          .L800FD744
    /* 860D0 800FD660 00001025 */   or        $v0, $zero, $zero
  .L800FD664:
    /* 860D4 800FD664 C7AA0028 */  lwc1       $f10, 0x28($sp)
    /* 860D8 800FD668 8FAE003C */  lw         $t6, 0x3C($sp)
    /* 860DC 800FD66C 00041880 */  sll        $v1, $a0, 2
    /* 860E0 800FD670 3C01800F */  lui        $at, %hi(D_800EC2E0)
    /* 860E4 800FD674 460C5400 */  add.s      $f16, $f10, $f12
    /* 860E8 800FD678 C7B2002C */  lwc1       $f18, 0x2C($sp)
    /* 860EC 800FD67C 00230821 */  addu       $at, $at, $v1
    /* 860F0 800FD680 AC2EC2E0 */  sw         $t6, %lo(D_800EC2E0)($at)
    /* 860F4 800FD684 3C01800E */  lui        $at, %hi(gEntitiesNextPosXArray)
    /* 860F8 800FD688 460E9100 */  add.s      $f4, $f18, $f14
    /* 860FC 800FD68C 00230821 */  addu       $at, $at, $v1
    /* 86100 800FD690 C7A60030 */  lwc1       $f6, 0x30($sp)
    /* 86104 800FD694 C7A80048 */  lwc1       $f8, 0x48($sp)
    /* 86108 800FD698 E43025D0 */  swc1       $f16, %lo(gEntitiesNextPosXArray)($at)
    /* 8610C 800FD69C 3C01800E */  lui        $at, %hi(gEntitiesNextPosYArray)
    /* 86110 800FD6A0 00230821 */  addu       $at, $at, $v1
    /* 86114 800FD6A4 46083280 */  add.s      $f10, $f6, $f8
    /* 86118 800FD6A8 E4242790 */  swc1       $f4, %lo(gEntitiesNextPosYArray)($at)
    /* 8611C 800FD6AC 3C01800E */  lui        $at, %hi(gEntitiesNextPosZArray)
    /* 86120 800FD6B0 00230821 */  addu       $at, $at, $v1
    /* 86124 800FD6B4 E42A2950 */  swc1       $f10, %lo(gEntitiesNextPosZArray)($at)
    /* 86128 800FD6B8 10000022 */  b          .L800FD744
    /* 8612C 800FD6BC 24020001 */   addiu     $v0, $zero, 0x1
  .L800FD6C0:
    /* 86130 800FD6C0 504F0012 */  beql       $v0, $t7, .L800FD70C
    /* 86134 800FD6C4 C7B20028 */   lwc1      $f18, 0x28($sp)
    /* 86138 800FD6C8 C7B20028 */  lwc1       $f18, 0x28($sp)
    /* 8613C 800FD6CC C7B0002C */  lwc1       $f16, 0x2C($sp)
    /* 86140 800FD6D0 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* 86144 800FD6D4 460C9480 */  add.s      $f18, $f18, $f12
    /* 86148 800FD6D8 C7A80048 */  lwc1       $f8, 0x48($sp)
    /* 8614C 800FD6DC 24040003 */  addiu      $a0, $zero, 0x3
    /* 86150 800FD6E0 460E8400 */  add.s      $f16, $f16, $f14
    /* 86154 800FD6E4 44079000 */  mfc1       $a3, $f18
    /* 86158 800FD6E8 24050002 */  addiu      $a1, $zero, 0x2
    /* 8615C 800FD6EC 46085200 */  add.s      $f8, $f10, $f8
    /* 86160 800FD6F0 8C460004 */  lw         $a2, 0x4($v0)
    /* 86164 800FD6F4 E7B00010 */  swc1       $f16, 0x10($sp)
    /* 86168 800FD6F8 0C029FDD */  jal        func_800A7F74
    /* 8616C 800FD6FC E7A80014 */   swc1      $f8, 0x14($sp)
    /* 86170 800FD700 10000010 */  b          .L800FD744
    /* 86174 800FD704 24020001 */   addiu     $v0, $zero, 0x1
    /* 86178 800FD708 C7B20028 */  lwc1       $f18, 0x28($sp)
  .L800FD70C:
    /* 8617C 800FD70C C7B0002C */  lwc1       $f16, 0x2C($sp)
    /* 86180 800FD710 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* 86184 800FD714 460C9480 */  add.s      $f18, $f18, $f12
    /* 86188 800FD718 C7A80048 */  lwc1       $f8, 0x48($sp)
    /* 8618C 800FD71C 00002025 */  or         $a0, $zero, $zero
    /* 86190 800FD720 460E8400 */  add.s      $f16, $f16, $f14
    /* 86194 800FD724 44079000 */  mfc1       $a3, $f18
    /* 86198 800FD728 24050002 */  addiu      $a1, $zero, 0x2
    /* 8619C 800FD72C 46085200 */  add.s      $f8, $f10, $f8
    /* 861A0 800FD730 8C460004 */  lw         $a2, 0x4($v0)
    /* 861A4 800FD734 E7B00010 */  swc1       $f16, 0x10($sp)
    /* 861A8 800FD738 0C029FDD */  jal        func_800A7F74
    /* 861AC 800FD73C E7A80014 */   swc1      $f8, 0x14($sp)
    /* 861B0 800FD740 24020001 */  addiu      $v0, $zero, 0x1
  .L800FD744:
    /* 861B4 800FD744 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 861B8 800FD748 27BD0038 */  addiu      $sp, $sp, 0x38
    /* 861BC 800FD74C 03E00008 */  jr         $ra
    /* 861C0 800FD750 00000000 */   nop
endlabel func_800FD570
.size func_800FD570, . - func_800FD570
