.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_801290D0, 0x4

dlabel D_801290D0
    /* 801290D0 */ .space 0x04

nonmatching D_801290D4, 0x4

dlabel D_801290D4
    /* 801290D4 */ .space 0x04

nonmatching D_801290D8, 0x4

dlabel D_801290D8
    /* 801290D8 */ .space 0x04

nonmatching D_801290DC, 0x4

dlabel D_801290DC
    /* 801290DC */ .space 0x04

nonmatching D_801290E0, 0x8

dlabel D_801290E0
    /* 801290E0 */ .space 0x08

nonmatching D_801290E8, 0x2C

dlabel D_801290E8
    /* 801290E8 */ .space 0x2C

nonmatching D_80129114, 0x4

dlabel D_80129114
    /* 80129114 */ .space 0x04

nonmatching D_80129118, 0x4

dlabel D_80129118
    /* 80129118 */ .space 0x04

nonmatching D_8012911C, 0x4

dlabel D_8012911C
    /* 8012911C */ .space 0x04

nonmatching D_80129120, 0x4

dlabel D_80129120
    /* 80129120 */ .space 0x04

nonmatching D_80129124, 0x4

dlabel D_80129124
    /* 80129124 */ .space 0x04

nonmatching D_80129128, 0x4

dlabel D_80129128
    /* 80129128 */ .space 0x04

nonmatching D_8012912C, 0x4

dlabel D_8012912C
    /* 8012912C */ .space 0x04

nonmatching D_80129130, 0x8

dlabel D_80129130
    /* 80129130 */ .space 0x08

nonmatching D_80129138, 0x4

dlabel D_80129138
    /* 80129138 */ .space 0x04

nonmatching D_8012913C, 0x4

dlabel D_8012913C
    /* 8012913C */ .space 0x04

nonmatching D_80129140, 0x4

dlabel D_80129140
    /* 80129140 */ .space 0x04

nonmatching D_80129144, 0xC

dlabel D_80129144
    /* 80129144 */ .space 0x0C

nonmatching D_80129150, 0x60

dlabel D_80129150
    /* 80129150 */ .space 0x60

nonmatching D_801291B0, 0x60

dlabel D_801291B0
    /* 801291B0 */ .space 0x60

nonmatching D_80129210, 0x60

dlabel D_80129210
    /* 80129210 */ .space 0x60

nonmatching D_80129270, 0x40

dlabel D_80129270
    /* 80129270 */ .space 0x40

nonmatching D_801292B0, 0x18

dlabel D_801292B0
    /* 801292B0 */ .space 0x18

nonmatching D_801292C8, 0x4

dlabel D_801292C8
    /* 801292C8 */ .space 0x04

nonmatching D_801292CC, 0x4

dlabel D_801292CC
    /* 801292CC */ .space 0x04

nonmatching D_801292D0, 0x4

dlabel D_801292D0
    /* 801292D0 */ .space 0x04

nonmatching D_801292D4, 0x4

dlabel D_801292D4
    /* 801292D4 */ .space 0x04

nonmatching D_801292D8, 0x4

dlabel D_801292D8
    /* 801292D8 */ .space 0x04

nonmatching D_801292DC, 0x4

dlabel D_801292DC
    /* 801292DC */ .space 0x04

nonmatching D_801292E0, 0x10

dlabel D_801292E0
    /* 801292E0 */ .space 0x10

nonmatching D_801292F0, 0x40

dlabel D_801292F0
    /* 801292F0 */ .space 0x40

nonmatching D_80129330, 0x40

dlabel D_80129330
    /* 80129330 */ .space 0x40

nonmatching D_80129370, 0x4

dlabel D_80129370
    /* 80129370 */ .space 0x04

nonmatching D_80129374, 0x4

dlabel D_80129374
    /* 80129374 */ .space 0x04

nonmatching D_80129378, 0x4

dlabel D_80129378
    /* 80129378 */ .space 0x04

nonmatching D_8012937C, 0x4

dlabel D_8012937C
    /* 8012937C */ .space 0x04

nonmatching D_80129380, 0x4

dlabel D_80129380
    /* 80129380 */ .space 0x04

nonmatching D_80129384, 0x28

dlabel D_80129384
    /* 80129384 */ .space 0x28

nonmatching D_801293AC, 0x4

dlabel D_801293AC
    /* 801293AC */ .space 0x04

nonmatching D_801293B0, 0x4

dlabel D_801293B0
    /* 801293B0 */ .space 0x04

nonmatching D_801293B4, 0x4

dlabel D_801293B4
    /* 801293B4 */ .space 0x04

nonmatching D_801293B8, 0x4

dlabel D_801293B8
    /* 801293B8 */ .space 0x04

nonmatching D_801293BC, 0x4

dlabel D_801293BC
    /* 801293BC */ .space 0x04

nonmatching D_801293C0, 0x4

dlabel D_801293C0
    /* 801293C0 */ .space 0x04

nonmatching D_801293C4, 0x4

dlabel D_801293C4
    /* 801293C4 */ .space 0x04

nonmatching D_801293C8, 0x4

dlabel D_801293C8
    /* 801293C8 */ .space 0x04

nonmatching D_801293CC, 0x4

dlabel D_801293CC
    /* 801293CC */ .space 0x04

nonmatching D_801293D0, 0x4

dlabel D_801293D0
    /* 801293D0 */ .space 0x04

nonmatching D_801293D4, 0x4

dlabel D_801293D4
    /* 801293D4 */ .space 0x04

nonmatching D_801293D8, 0x4

dlabel D_801293D8
    /* 801293D8 */ .space 0x04

nonmatching D_801293DC, 0x4

dlabel D_801293DC
    /* 801293DC */ .space 0x04

nonmatching D_801293E0, 0x4

dlabel D_801293E0
    /* 801293E0 */ .space 0x04

nonmatching D_801293E4, 0x4

dlabel D_801293E4
    /* 801293E4 */ .space 0x04

nonmatching D_801293E8, 0x4

dlabel D_801293E8
    /* 801293E8 */ .space 0x04

nonmatching D_801293EC, 0x4

dlabel D_801293EC
    /* 801293EC */ .space 0x04

nonmatching D_801293F0, 0x4

dlabel D_801293F0
    /* 801293F0 */ .space 0x04

nonmatching D_801293F4, 0x4

dlabel D_801293F4
    /* 801293F4 */ .space 0x04

nonmatching D_801293F8, 0x4

dlabel D_801293F8
    /* 801293F8 */ .space 0x04

nonmatching D_801293FC, 0x4

dlabel D_801293FC
    /* 801293FC */ .space 0x04

nonmatching D_80129400, 0x4

dlabel D_80129400
    /* 80129400 */ .space 0x04

nonmatching D_80129404, 0x4

dlabel D_80129404
    /* 80129404 */ .space 0x04

nonmatching D_80129408, 0x4

dlabel D_80129408
    /* 80129408 */ .space 0x04

nonmatching D_8012940C, 0x4

dlabel D_8012940C
    /* 8012940C */ .space 0x04

nonmatching D_80129410, 0x8

dlabel D_80129410
    /* 80129410 */ .space 0x08

nonmatching D_80129418, 0x78

dlabel D_80129418
    /* 80129418 */ .space 0x78

nonmatching D_80129490, 0x128

dlabel D_80129490
    /* 80129490 */ .space 0x128

nonmatching D_801295B8, 0x23D8

dlabel D_801295B8
    /* 801295B8 */ .space 0x23D8

nonmatching D_8012B990, 0x8

dlabel D_8012B990
    /* 8012B990 */ .space 0x08

nonmatching D_8012B998, 0x4

dlabel D_8012B998
    /* 8012B998 */ .space 0x04

nonmatching D_8012B99C, 0x4

dlabel D_8012B99C
    /* 8012B99C */ .space 0x04

nonmatching D_8012B9A0, 0xC

dlabel D_8012B9A0
    /* 8012B9A0 */ .space 0x0C

nonmatching D_8012B9AC, 0x4

dlabel D_8012B9AC
    /* 8012B9AC */ .space 0x04

nonmatching D_8012B9B0, 0x8

dlabel D_8012B9B0
    /* 8012B9B0 */ .space 0x08

nonmatching D_8012B9B8, 0x1E0

dlabel D_8012B9B8
    /* 8012B9B8 */ .space 0x1E0

nonmatching D_8012BB98, 0x60

dlabel D_8012BB98
    /* 8012BB98 */ .space 0x60

nonmatching D_8012BBF8, 0x10

dlabel D_8012BBF8
    /* 8012BBF8 */ .space 0x10

nonmatching D_8012BC08, 0x10

dlabel D_8012BC08
    /* 8012BC08 */ .space 0x10

nonmatching D_8012BC18, 0x80

dlabel D_8012BC18
    /* 8012BC18 */ .space 0x80

nonmatching D_8012BC98, 0x8

dlabel D_8012BC98
    /* 8012BC98 */ .space 0x08

nonmatching D_8012BCA0, 0x4

dlabel D_8012BCA0
    /* 8012BCA0 */ .space 0x04

nonmatching D_8012BCA4, 0x4

dlabel D_8012BCA4
    /* 8012BCA4 */ .space 0x04

nonmatching D_8012BCA8, 0xC

dlabel D_8012BCA8
    /* 8012BCA8 */ .space 0x0C

nonmatching D_8012BCB4, 0x8

dlabel D_8012BCB4
    /* 8012BCB4 */ .space 0x08

nonmatching D_8012BCBC, 0x4

dlabel D_8012BCBC
    /* 8012BCBC */ .space 0x04

nonmatching D_8012BCC0, 0x4

dlabel D_8012BCC0
    /* 8012BCC0 */ .space 0x04

nonmatching D_8012BCC4, 0x4

dlabel D_8012BCC4
    /* 8012BCC4 */ .space 0x04

nonmatching D_8012BCC8, 0x4

dlabel D_8012BCC8
    /* 8012BCC8 */ .space 0x04

nonmatching D_8012BCCC, 0x4

dlabel D_8012BCCC
    /* 8012BCCC */ .space 0x04

nonmatching D_8012BCD0, 0x4

dlabel D_8012BCD0
    /* 8012BCD0 */ .space 0x04

nonmatching D_8012BCD4, 0x4

dlabel D_8012BCD4
    /* 8012BCD4 */ .space 0x04

nonmatching D_8012BCD8, 0x4

dlabel D_8012BCD8
    /* 8012BCD8 */ .space 0x04

nonmatching D_8012BCDC, 0x4

dlabel D_8012BCDC
    /* 8012BCDC */ .space 0x04

nonmatching D_8012BCE0, 0x18

dlabel D_8012BCE0
    /* 8012BCE0 */ .space 0x18

nonmatching gCollisionState, 0x8

dlabel gCollisionState
    /* 8012BCF8 */ .space 0x08

nonmatching D_8012BD00, 0x4

dlabel D_8012BD00
    /* 8012BD00 */ .space 0x04

nonmatching D_8012BD04, 0x4

dlabel D_8012BD04
    /* 8012BD04 */ .space 0x04

nonmatching D_8012BD08, 0x4

dlabel D_8012BD08
    /* 8012BD08 */ .space 0x04

nonmatching D_8012BD0C, 0x4

dlabel D_8012BD0C
    /* 8012BD0C */ .space 0x04

nonmatching D_8012BD10, 0x4

dlabel D_8012BD10
    /* 8012BD10 */ .space 0x04

nonmatching D_8012BD14, 0x20

dlabel D_8012BD14
    /* 8012BD14 */ .space 0x20

nonmatching D_8012BD34, 0xC

dlabel D_8012BD34
    /* 8012BD34 */ .space 0x0C

nonmatching D_8012BD40, 0x4

dlabel D_8012BD40
    /* 8012BD40 */ .space 0x04

nonmatching D_8012BD44, 0x4

dlabel D_8012BD44
    /* 8012BD44 */ .space 0x04

nonmatching D_8012BD48, 0x4

dlabel D_8012BD48
    /* 8012BD48 */ .space 0x04

nonmatching D_8012BD4C, 0x4

dlabel D_8012BD4C
    /* 8012BD4C */ .space 0x04

nonmatching D_8012BD50, 0x5C

dlabel D_8012BD50
    /* 8012BD50 */ .space 0x5C

nonmatching D_8012BDAC, 0x5C

dlabel D_8012BDAC
    /* 8012BDAC */ .space 0x5C

nonmatching D_8012BE08, 0x5C

dlabel D_8012BE08
    /* 8012BE08 */ .space 0x5C

nonmatching D_8012BE64, 0x5C

dlabel D_8012BE64
    /* 8012BE64 */ .space 0x5C

nonmatching D_8012BEC0, 0x5C

dlabel D_8012BEC0
    /* 8012BEC0 */ .space 0x5C

nonmatching D_8012BF1C, 0x5C

dlabel D_8012BF1C
    /* 8012BF1C */ .space 0x5C

nonmatching D_8012BF78, 0x5C

dlabel D_8012BF78
    /* 8012BF78 */ .space 0x5C

nonmatching D_8012BFD4, 0x8FC

dlabel D_8012BFD4
    /* 8012BFD4 */ .space 0x8FC

nonmatching D_8012C8D0, 0x8

dlabel D_8012C8D0
    /* 8012C8D0 */ .space 0x08

nonmatching D_8012C8D8, 0x30

dlabel D_8012C8D8
    /* 8012C8D8 */ .space 0x30

nonmatching D_8012C908, 0x40

dlabel D_8012C908
    /* 8012C908 */ .space 0x40

nonmatching D_8012C948, 0x9C

dlabel D_8012C948
    /* 8012C948 */ .space 0x9C

nonmatching D_8012C9E4, 0x234

dlabel D_8012C9E4
    /* 8012C9E4 */ .space 0x234

nonmatching D_8012CC18, 0x40

dlabel D_8012CC18
    /* 8012CC18 */ .space 0x40

nonmatching D_8012CC58, 0x2D0

dlabel D_8012CC58
    /* 8012CC58 */ .space 0x2D0

nonmatching D_8012CF28, 0x8

dlabel D_8012CF28
    /* 8012CF28 */ .space 0x08

nonmatching D_8012CF30, 0x190

dlabel D_8012CF30
    /* 8012CF30 */ .space 0x190

nonmatching D_8012D0C0, 0x4

dlabel D_8012D0C0
    /* 8012D0C0 */ .space 0x04

nonmatching D_8012D0C4, 0x4

dlabel D_8012D0C4
    /* 8012D0C4 */ .space 0x04

nonmatching D_8012D0C8, 0xC8

dlabel D_8012D0C8
    /* 8012D0C8 */ .space 0xC8

nonmatching D_8012D190, 0x8

dlabel D_8012D190
    /* 8012D190 */ .space 0x08

nonmatching D_8012D198, 0x3E8

dlabel D_8012D198
    /* 8012D198 */ .space 0x3E8

nonmatching D_8012D580, 0x4

dlabel D_8012D580
    /* 8012D580 */ .space 0x04

nonmatching D_8012D584, 0x4

dlabel D_8012D584
    /* 8012D584 */ .space 0x04

nonmatching D_8012D588, 0x4

dlabel D_8012D588
    /* 8012D588 */ .space 0x04

nonmatching D_8012D58C, 0x4

dlabel D_8012D58C
    /* 8012D58C */ .space 0x04

nonmatching D_8012D590, 0xB8

dlabel D_8012D590
    /* 8012D590 */ .space 0xB8

nonmatching D_8012D648, 0x168

dlabel D_8012D648
    /* 8012D648 */ .space 0x168

nonmatching D_8012D7B0, 0xE1

dlabel D_8012D7B0
    /* 8012D7B0 */ .space 0xE1

nonmatching D_8012D891, 0x87

dlabel D_8012D891
    /* 8012D891 */ .space 0x87

nonmatching D_8012D918, 0x8

dlabel D_8012D918
    /* 8012D918 */ .space 0x08

nonmatching D_8012D920, 0x4

dlabel D_8012D920
    /* 8012D920 */ .space 0x04

nonmatching D_8012D924, 0xC

dlabel D_8012D924
    /* 8012D924 */ .space 0x0C

nonmatching D_8012D930, 0x4

dlabel D_8012D930
    /* 8012D930 */ .space 0x04

nonmatching D_8012D934, 0xC

dlabel D_8012D934
    /* 8012D934 */ .space 0x0C

nonmatching D_8012D940, 0x8

dlabel D_8012D940
    /* 8012D940 */ .space 0x08

nonmatching D_8012D948, 0x4

dlabel D_8012D948
    /* 8012D948 */ .space 0x04

nonmatching D_8012D94C, 0xB5

dlabel D_8012D94C
    /* 8012D94C */ .space 0xB5

nonmatching D_8012DA01, 0xDAF

dlabel D_8012DA01
    /* 8012DA01 */ .space 0xDAF

nonmatching D_8012E7B0, 0x4

dlabel D_8012E7B0
    /* 8012E7B0 */ .space 0x04

nonmatching D_8012E7B4, 0xC

dlabel D_8012E7B4
    /* 8012E7B4 */ .space 0x0C

nonmatching gKirbyState, 0x5

dlabel gKirbyState
    /* 8012E7C0 */ .space 0x05

nonmatching D_8012E7C5, 0x12

dlabel D_8012E7C5
    /* 8012E7C5 */ .space 0x12

nonmatching D_8012E7D7, 0x5

dlabel D_8012E7D7
    /* 8012E7D7 */ .space 0x05

nonmatching D_8012E7DC, 0xC

dlabel D_8012E7DC
    /* 8012E7DC */ .space 0x0C

nonmatching D_8012E7E8, 0x14

dlabel D_8012E7E8
    /* 8012E7E8 */ .space 0x14

nonmatching D_8012E7FC, 0x10

dlabel D_8012E7FC
    /* 8012E7FC */ .space 0x10

nonmatching D_8012E80C, 0xC

dlabel D_8012E80C
    /* 8012E80C */ .space 0x0C

nonmatching D_8012E818, 0x4

dlabel D_8012E818
    /* 8012E818 */ .space 0x04

nonmatching D_8012E81C, 0x4

dlabel D_8012E81C
    /* 8012E81C */ .space 0x04

nonmatching D_8012E820, 0x4

dlabel D_8012E820
    /* 8012E820 */ .space 0x04

nonmatching D_8012E824, 0x4

dlabel D_8012E824
    /* 8012E824 */ .space 0x04

nonmatching D_8012E828, 0x28

dlabel D_8012E828
    /* 8012E828 */ .space 0x28

nonmatching D_8012E850, 0x10

dlabel D_8012E850
    /* 8012E850 */ .space 0x10

nonmatching D_8012E860, 0x34

dlabel D_8012E860
    /* 8012E860 */ .space 0x34

nonmatching D_8012E894, 0x2E

dlabel D_8012E894
    /* 8012E894 */ .space 0x2E

nonmatching D_8012E8C2, 0x8

dlabel D_8012E8C2
    /* 8012E8C2 */ .space 0x08

nonmatching D_8012E8CA, 0x3A

dlabel D_8012E8CA
    /* 8012E8CA */ .space 0x3A

nonmatching D_8012E904, 0x4

dlabel D_8012E904
    /* 8012E904 */ .space 0x04

nonmatching D_8012E908, 0x4

dlabel D_8012E908
    /* 8012E908 */ .space 0x04

nonmatching D_8012E90C, 0x16

dlabel D_8012E90C
    /* 8012E90C */ .space 0x16

nonmatching D_8012E922, 0x22

dlabel D_8012E922
    /* 8012E922 */ .space 0x22

nonmatching D_8012E944, 0x24

dlabel D_8012E944
    /* 8012E944 */ .space 0x24

nonmatching gPositionState, 0x50

dlabel gPositionState
    /* 8012E968 */ .space 0x50

nonmatching D_8012E9B8, 0x124

dlabel D_8012E9B8
    /* 8012E9B8 */ .space 0x124

nonmatching D_8012EADC, 0x4

dlabel D_8012EADC
    /* 8012EADC */ .space 0x04

nonmatching D_8012EAE0, 0x10

dlabel D_8012EAE0
    /* 8012EAE0 */ .space 0x10
