.section .late_rodata
nonmatching jtbl_800417CC

dlabel jtbl_800417CC
    /* 423CC 800417CC 8002A5A4 */ .word .L8002A5A4
    /* 423D0 800417D0 8002A5B0 */ .word .L8002A5B0
    /* 423D4 800417D4 8002A5C8 */ .word .L8002A5C8
    /* 423D8 800417D8 8002A5D4 */ .word .L8002A5D4
    /* 423DC 800417DC 8002A5BC */ .word .L8002A5BC
    /* 423E0 800417E0 8002A5E0 */ .word .L8002A5E0
enddlabel jtbl_800417CC
.size jtbl_800417CC, . - jtbl_800417CC

nonmatching D_800417E4

dlabel D_800417E4
    /* 423E4 800417E4 482910DA */ .float 173123.4062
    /* 423E8 800417E8 00000000 */ .float 0
    /* 423EC 800417EC 00000000 */ .float 0
enddlabel D_800417E4
.size D_800417E4, . - D_800417E4


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8002A508, 0x400

glabel func_8002A508
    /* 2B108 8002A508 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 2B10C 8002A50C AFB00040 */  sw         $s0, 0x40($sp)
    /* 2B110 8002A510 00808025 */  or         $s0, $a0, $zero
    /* 2B114 8002A514 AFBF0064 */  sw         $ra, 0x64($sp)
    /* 2B118 8002A518 AFB60058 */  sw         $s6, 0x58($sp)
    /* 2B11C 8002A51C AFA5006C */  sw         $a1, 0x6C($sp)
    /* 2B120 8002A520 240E002C */  addiu      $t6, $zero, 0x2C
    /* 2B124 8002A524 00C0B025 */  or         $s6, $a2, $zero
    /* 2B128 8002A528 AFBE0060 */  sw         $fp, 0x60($sp)
    /* 2B12C 8002A52C AFB7005C */  sw         $s7, 0x5C($sp)
    /* 2B130 8002A530 AFB50054 */  sw         $s5, 0x54($sp)
    /* 2B134 8002A534 AFB40050 */  sw         $s4, 0x50($sp)
    /* 2B138 8002A538 AFB3004C */  sw         $s3, 0x4C($sp)
    /* 2B13C 8002A53C AFB20048 */  sw         $s2, 0x48($sp)
    /* 2B140 8002A540 AFB10044 */  sw         $s1, 0x44($sp)
    /* 2B144 8002A544 F7BA0038 */  sdc1       $f26, 0x38($sp)
    /* 2B148 8002A548 F7B80030 */  sdc1       $f24, 0x30($sp)
    /* 2B14C 8002A54C F7B60028 */  sdc1       $f22, 0x28($sp)
    /* 2B150 8002A550 F7B40020 */  sdc1       $f20, 0x20($sp)
    /* 2B154 8002A554 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 2B158 8002A558 00002825 */  or         $a1, $zero, $zero
    /* 2B15C 8002A55C 00002025 */  or         $a0, $zero, $zero
    /* 2B160 8002A560 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B164 8002A564 24070001 */   addiu     $a3, $zero, 0x1
    /* 2B168 8002A568 8FA3006C */  lw         $v1, 0x6C($sp)
    /* 2B16C 8002A56C AE020000 */  sw         $v0, 0x0($s0)
    /* 2B170 8002A570 3C138004 */  lui        $s3, %hi(D_8003F9E8)
    /* 2B174 8002A574 906F001C */  lbu        $t7, 0x1C($v1)
    /* 2B178 8002A578 0040A825 */  or         $s5, $v0, $zero
    /* 2B17C 8002A57C 2673F9E8 */  addiu      $s3, $s3, %lo(D_8003F9E8)
    /* 2B180 8002A580 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* 2B184 8002A584 2F010006 */  sltiu      $at, $t8, 0x6
    /* 2B188 8002A588 10200017 */  beqz       $at, .L8002A5E8
    /* 2B18C 8002A58C 0018C080 */   sll       $t8, $t8, 2
    /* 2B190 8002A590 3C018004 */  lui        $at, %hi(jtbl_800417CC)
    /* 2B194 8002A594 00380821 */  addu       $at, $at, $t8
    /* 2B198 8002A598 8C3817CC */  lw         $t8, %lo(jtbl_800417CC)($at)
    /* 2B19C 8002A59C 03000008 */  jr         $t8
    /* 2B1A0 8002A5A0 00000000 */   nop
  .L8002A5A4:
    /* 2B1A4 8002A5A4 3C138004 */  lui        $s3, %hi(D_8003F880)
    /* 2B1A8 8002A5A8 1000000F */  b          .L8002A5E8
    /* 2B1AC 8002A5AC 2673F880 */   addiu     $s3, $s3, %lo(D_8003F880)
  .L8002A5B0:
    /* 2B1B0 8002A5B0 3C138004 */  lui        $s3, %hi(D_8003F8E8)
    /* 2B1B4 8002A5B4 1000000C */  b          .L8002A5E8
    /* 2B1B8 8002A5B8 2673F8E8 */   addiu     $s3, $s3, %lo(D_8003F8E8)
  .L8002A5BC:
    /* 2B1BC 8002A5BC 3C138004 */  lui        $s3, %hi(D_8003F970)
    /* 2B1C0 8002A5C0 10000009 */  b          .L8002A5E8
    /* 2B1C4 8002A5C4 2673F970 */   addiu     $s3, $s3, %lo(D_8003F970)
  .L8002A5C8:
    /* 2B1C8 8002A5C8 3C138004 */  lui        $s3, %hi(D_8003F998)
    /* 2B1CC 8002A5CC 10000006 */  b          .L8002A5E8
    /* 2B1D0 8002A5D0 2673F998 */   addiu     $s3, $s3, %lo(D_8003F998)
  .L8002A5D4:
    /* 2B1D4 8002A5D4 3C138004 */  lui        $s3, %hi(D_8003F9C0)
    /* 2B1D8 8002A5D8 10000003 */  b          .L8002A5E8
    /* 2B1DC 8002A5DC 2673F9C0 */   addiu     $s3, $s3, %lo(D_8003F9C0)
  .L8002A5E0:
    /* 2B1E0 8002A5E0 10000001 */  b          .L8002A5E8
    /* 2B1E4 8002A5E4 8C730020 */   lw        $s3, 0x20($v1)
  .L8002A5E8:
    /* 2B1E8 8002A5E8 8E790000 */  lw         $t9, 0x0($s3)
    /* 2B1EC 8002A5EC 24090028 */  addiu      $t1, $zero, 0x28
    /* 2B1F0 8002A5F0 24110002 */  addiu      $s1, $zero, 0x2
    /* 2B1F4 8002A5F4 A2B90024 */  sb         $t9, 0x24($s5)
    /* 2B1F8 8002A5F8 8E680004 */  lw         $t0, 0x4($s3)
    /* 2B1FC 8002A5FC 00002025 */  or         $a0, $zero, $zero
    /* 2B200 8002A600 00002825 */  or         $a1, $zero, $zero
    /* 2B204 8002A604 AEA8001C */  sw         $t0, 0x1C($s5)
    /* 2B208 8002A608 AFA90010 */  sw         $t1, 0x10($sp)
    /* 2B20C 8002A60C 02C03025 */  or         $a2, $s6, $zero
    /* 2B210 8002A610 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B214 8002A614 332700FF */   andi      $a3, $t9, 0xFF
    /* 2B218 8002A618 AEA20020 */  sw         $v0, 0x20($s5)
    /* 2B21C 8002A61C 8EA7001C */  lw         $a3, 0x1C($s5)
    /* 2B220 8002A620 240A0002 */  addiu      $t2, $zero, 0x2
    /* 2B224 8002A624 AFAA0010 */  sw         $t2, 0x10($sp)
    /* 2B228 8002A628 00002025 */  or         $a0, $zero, $zero
    /* 2B22C 8002A62C 00002825 */  or         $a1, $zero, $zero
    /* 2B230 8002A630 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B234 8002A634 02C03025 */   or        $a2, $s6, $zero
    /* 2B238 8002A638 8EAB001C */  lw         $t3, 0x1C($s5)
    /* 2B23C 8002A63C AEA20014 */  sw         $v0, 0x14($s5)
    /* 2B240 8002A640 AEA20018 */  sw         $v0, 0x18($s5)
    /* 2B244 8002A644 1160000B */  beqz       $t3, .L8002A674
    /* 2B248 8002A648 00001825 */   or        $v1, $zero, $zero
    /* 2B24C 8002A64C 8EAC0014 */  lw         $t4, 0x14($s5)
  .L8002A650:
    /* 2B250 8002A650 00036840 */  sll        $t5, $v1, 1
    /* 2B254 8002A654 24630001 */  addiu      $v1, $v1, 0x1
    /* 2B258 8002A658 018D7021 */  addu       $t6, $t4, $t5
    /* 2B25C 8002A65C A5C00000 */  sh         $zero, 0x0($t6)
    /* 2B260 8002A660 8EAF001C */  lw         $t7, 0x1C($s5)
    /* 2B264 8002A664 3063FFFF */  andi       $v1, $v1, 0xFFFF
    /* 2B268 8002A668 006F082B */  sltu       $at, $v1, $t7
    /* 2B26C 8002A66C 5420FFF8 */  bnel       $at, $zero, .L8002A650
    /* 2B270 8002A670 8EAC0014 */   lw        $t4, 0x14($s5)
  .L8002A674:
    /* 2B274 8002A674 92B80024 */  lbu        $t8, 0x24($s5)
    /* 2B278 8002A678 0000A025 */  or         $s4, $zero, $zero
    /* 2B27C 8002A67C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 2B280 8002A680 1B000091 */  blez       $t8, .L8002A8C8
    /* 2B284 8002A684 241E0001 */   addiu     $fp, $zero, 0x1
    /* 2B288 8002A688 4481C000 */  mtc1       $at, $f24
    /* 2B28C 8002A68C 3C018004 */  lui        $at, %hi(D_800417E4)
    /* 2B290 8002A690 C43617E4 */  lwc1       $f22, %lo(D_800417E4)($at)
    /* 2B294 8002A694 3C01447A */  lui        $at, (0x447A0000 >> 16)
    /* 2B298 8002A698 4481A000 */  mtc1       $at, $f20
    /* 2B29C 8002A69C 4480D000 */  mtc1       $zero, $f26
    /* 2B2A0 8002A6A0 24170028 */  addiu      $s7, $zero, 0x28
  .L8002A6A4:
    /* 2B2A4 8002A6A4 02970019 */  multu      $s4, $s7
    /* 2B2A8 8002A6A8 00114880 */  sll        $t1, $s1, 2
    /* 2B2AC 8002A6AC 8EB90020 */  lw         $t9, 0x20($s5)
    /* 2B2B0 8002A6B0 02695021 */  addu       $t2, $s3, $t1
    /* 2B2B4 8002A6B4 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 2B2B8 8002A6B8 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B2BC 8002A6BC 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B2C0 8002A6C0 00116080 */  sll        $t4, $s1, 2
    /* 2B2C4 8002A6C4 026C6821 */  addu       $t5, $s3, $t4
    /* 2B2C8 8002A6C8 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B2CC 8002A6CC 00004012 */  mflo       $t0
    /* 2B2D0 8002A6D0 03288021 */  addu       $s0, $t9, $t0
    /* 2B2D4 8002A6D4 AE0B0000 */  sw         $t3, 0x0($s0)
    /* 2B2D8 8002A6D8 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 2B2DC 8002A6DC 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B2E0 8002A6E0 00117880 */  sll        $t7, $s1, 2
    /* 2B2E4 8002A6E4 026FC021 */  addu       $t8, $s3, $t7
    /* 2B2E8 8002A6E8 AE0E0004 */  sw         $t6, 0x4($s0)
    /* 2B2EC 8002A6EC 8F190000 */  lw         $t9, 0x0($t8)
    /* 2B2F0 8002A6F0 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B2F4 8002A6F4 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B2F8 8002A6F8 00114080 */  sll        $t0, $s1, 2
    /* 2B2FC 8002A6FC 02684821 */  addu       $t1, $s3, $t0
    /* 2B300 8002A700 A619000A */  sh         $t9, 0xA($s0)
    /* 2B304 8002A704 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 2B308 8002A708 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B30C 8002A70C 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B310 8002A710 00115880 */  sll        $t3, $s1, 2
    /* 2B314 8002A714 026B6021 */  addu       $t4, $s3, $t3
    /* 2B318 8002A718 A60A0008 */  sh         $t2, 0x8($s0)
    /* 2B31C 8002A71C 8D8D0000 */  lw         $t5, 0x0($t4)
    /* 2B320 8002A720 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B324 8002A724 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B328 8002A728 00117080 */  sll        $t6, $s1, 2
    /* 2B32C 8002A72C 026E7821 */  addu       $t7, $s3, $t6
    /* 2B330 8002A730 A60D000C */  sh         $t5, 0xC($s0)
    /* 2B334 8002A734 8DE20000 */  lw         $v0, 0x0($t7)
    /* 2B338 8002A738 5040003A */  beql       $v0, $zero, .L8002A824
    /* 2B33C 8002A73C 26310002 */   addiu     $s1, $s1, 0x2
    /* 2B340 8002A740 44822000 */  mtc1       $v0, $f4
    /* 2B344 8002A744 8FB8006C */  lw         $t8, 0x6C($sp)
    /* 2B348 8002A748 8E080004 */  lw         $t0, 0x4($s0)
    /* 2B34C 8002A74C 468021A0 */  cvt.s.w    $f6, $f4
    /* 2B350 8002A750 8F190018 */  lw         $t9, 0x18($t8)
    /* 2B354 8002A754 8E090000 */  lw         $t1, 0x0($s0)
    /* 2B358 8002A758 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B35C 8002A75C 44995000 */  mtc1       $t9, $f10
    /* 2B360 8002A760 01095023 */  subu       $t2, $t0, $t1
    /* 2B364 8002A764 46143003 */  div.s      $f0, $f6, $f20
    /* 2B368 8002A768 448A2000 */  mtc1       $t2, $f4
    /* 2B36C 8002A76C 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B370 8002A770 00115880 */  sll        $t3, $s1, 2
    /* 2B374 8002A774 46805420 */  cvt.s.w    $f16, $f10
    /* 2B378 8002A778 026B6021 */  addu       $t4, $s3, $t3
    /* 2B37C 8002A77C 3C014F80 */  lui        $at, (0x4F800000 >> 16)
    /* 2B380 8002A780 468021A0 */  cvt.s.w    $f6, $f4
    /* 2B384 8002A784 46000200 */  add.s      $f8, $f0, $f0
    /* 2B388 8002A788 46104483 */  div.s      $f18, $f8, $f16
    /* 2B38C 8002A78C 05410004 */  bgez       $t2, .L8002A7A0
    /* 2B390 8002A790 E6120010 */   swc1      $f18, 0x10($s0)
    /* 2B394 8002A794 44815000 */  mtc1       $at, $f10
    /* 2B398 8002A798 00000000 */  nop
    /* 2B39C 8002A79C 460A3180 */  add.s      $f6, $f6, $f10
  .L8002A7A0:
    /* 2B3A0 8002A7A0 8D8D0000 */  lw         $t5, 0x0($t4)
    /* 2B3A4 8002A7A4 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B3A8 8002A7A8 E6180014 */  swc1       $f24, 0x14($s0)
    /* 2B3AC 8002A7AC 448D4000 */  mtc1       $t5, $f8
    /* 2B3B0 8002A7B0 AE000018 */  sw         $zero, 0x18($s0)
    /* 2B3B4 8002A7B4 240E0034 */  addiu      $t6, $zero, 0x34
    /* 2B3B8 8002A7B8 46804420 */  cvt.s.w    $f16, $f8
    /* 2B3BC 8002A7BC 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B3C0 8002A7C0 00002025 */  or         $a0, $zero, $zero
    /* 2B3C4 8002A7C4 00002825 */  or         $a1, $zero, $zero
    /* 2B3C8 8002A7C8 02C03025 */  or         $a2, $s6, $zero
    /* 2B3CC 8002A7CC 03C03825 */  or         $a3, $fp, $zero
    /* 2B3D0 8002A7D0 46168483 */  div.s      $f18, $f16, $f22
    /* 2B3D4 8002A7D4 46069102 */  mul.s      $f4, $f18, $f6
    /* 2B3D8 8002A7D8 E604001C */  swc1       $f4, 0x1C($s0)
    /* 2B3DC 8002A7DC 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B3E0 8002A7E0 AFAE0010 */   sw        $t6, 0x10($sp)
    /* 2B3E4 8002A7E4 AE020024 */  sw         $v0, 0x24($s0)
    /* 2B3E8 8002A7E8 240F0020 */  addiu      $t7, $zero, 0x20
    /* 2B3EC 8002A7EC AFAF0010 */  sw         $t7, 0x10($sp)
    /* 2B3F0 8002A7F0 00002025 */  or         $a0, $zero, $zero
    /* 2B3F4 8002A7F4 00002825 */  or         $a1, $zero, $zero
    /* 2B3F8 8002A7F8 02C03025 */  or         $a2, $s6, $zero
    /* 2B3FC 8002A7FC 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B400 8002A800 03C03825 */   or        $a3, $fp, $zero
    /* 2B404 8002A804 8E180024 */  lw         $t8, 0x24($s0)
    /* 2B408 8002A808 AF020014 */  sw         $v0, 0x14($t8)
    /* 2B40C 8002A80C 8E190024 */  lw         $t9, 0x24($s0)
    /* 2B410 8002A810 E73A0020 */  swc1       $f26, 0x20($t9)
    /* 2B414 8002A814 8E080024 */  lw         $t0, 0x24($s0)
    /* 2B418 8002A818 10000004 */  b          .L8002A82C
    /* 2B41C 8002A81C AD1E0024 */   sw        $fp, 0x24($t0)
    /* 2B420 8002A820 26310002 */  addiu      $s1, $s1, 0x2
  .L8002A824:
    /* 2B424 8002A824 AE000024 */  sw         $zero, 0x24($s0)
    /* 2B428 8002A828 3231FFFF */  andi       $s1, $s1, 0xFFFF
  .L8002A82C:
    /* 2B42C 8002A82C 00114880 */  sll        $t1, $s1, 2
    /* 2B430 8002A830 02699021 */  addu       $s2, $s3, $t1
    /* 2B434 8002A834 8E4A0000 */  lw         $t2, 0x0($s2)
    /* 2B438 8002A838 00002025 */  or         $a0, $zero, $zero
    /* 2B43C 8002A83C 00002825 */  or         $a1, $zero, $zero
    /* 2B440 8002A840 11400018 */  beqz       $t2, .L8002A8A4
    /* 2B444 8002A844 02C03025 */   or        $a2, $s6, $zero
    /* 2B448 8002A848 240B0030 */  addiu      $t3, $zero, 0x30
    /* 2B44C 8002A84C AFAB0010 */  sw         $t3, 0x10($sp)
    /* 2B450 8002A850 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B454 8002A854 03C03825 */   or        $a3, $fp, $zero
    /* 2B458 8002A858 AE020020 */  sw         $v0, 0x20($s0)
    /* 2B45C 8002A85C 240C0008 */  addiu      $t4, $zero, 0x8
    /* 2B460 8002A860 AFAC0010 */  sw         $t4, 0x10($sp)
    /* 2B464 8002A864 00002025 */  or         $a0, $zero, $zero
    /* 2B468 8002A868 00002825 */  or         $a1, $zero, $zero
    /* 2B46C 8002A86C 02C03025 */  or         $a2, $s6, $zero
    /* 2B470 8002A870 0C0078F5 */  jal        alHeapDBAlloc
    /* 2B474 8002A874 03C03825 */   or        $a3, $fp, $zero
    /* 2B478 8002A878 8E0D0020 */  lw         $t5, 0x20($s0)
    /* 2B47C 8002A87C 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B480 8002A880 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B484 8002A884 ADA20028 */  sw         $v0, 0x28($t5)
    /* 2B488 8002A888 8E0F0020 */  lw         $t7, 0x20($s0)
    /* 2B48C 8002A88C 8E4E0000 */  lw         $t6, 0x0($s2)
    /* 2B490 8002A890 A5EE0000 */  sh         $t6, 0x0($t7)
    /* 2B494 8002A894 0C00A871 */  jal        func_8002A1C4
    /* 2B498 8002A898 8E040020 */   lw        $a0, 0x20($s0)
    /* 2B49C 8002A89C 10000005 */  b          .L8002A8B4
    /* 2B4A0 8002A8A0 92B80024 */   lbu       $t8, 0x24($s5)
  .L8002A8A4:
    /* 2B4A4 8002A8A4 26310001 */  addiu      $s1, $s1, 0x1
    /* 2B4A8 8002A8A8 AE000020 */  sw         $zero, 0x20($s0)
    /* 2B4AC 8002A8AC 3231FFFF */  andi       $s1, $s1, 0xFFFF
    /* 2B4B0 8002A8B0 92B80024 */  lbu        $t8, 0x24($s5)
  .L8002A8B4:
    /* 2B4B4 8002A8B4 26940001 */  addiu      $s4, $s4, 0x1
    /* 2B4B8 8002A8B8 3294FFFF */  andi       $s4, $s4, 0xFFFF
    /* 2B4BC 8002A8BC 0298082A */  slt        $at, $s4, $t8
    /* 2B4C0 8002A8C0 1420FF78 */  bnez       $at, .L8002A6A4
    /* 2B4C4 8002A8C4 00000000 */   nop
  .L8002A8C8:
    /* 2B4C8 8002A8C8 8FBF0064 */  lw         $ra, 0x64($sp)
    /* 2B4CC 8002A8CC D7B40020 */  ldc1       $f20, 0x20($sp)
    /* 2B4D0 8002A8D0 D7B60028 */  ldc1       $f22, 0x28($sp)
    /* 2B4D4 8002A8D4 D7B80030 */  ldc1       $f24, 0x30($sp)
    /* 2B4D8 8002A8D8 D7BA0038 */  ldc1       $f26, 0x38($sp)
    /* 2B4DC 8002A8DC 8FB00040 */  lw         $s0, 0x40($sp)
    /* 2B4E0 8002A8E0 8FB10044 */  lw         $s1, 0x44($sp)
    /* 2B4E4 8002A8E4 8FB20048 */  lw         $s2, 0x48($sp)
    /* 2B4E8 8002A8E8 8FB3004C */  lw         $s3, 0x4C($sp)
    /* 2B4EC 8002A8EC 8FB40050 */  lw         $s4, 0x50($sp)
    /* 2B4F0 8002A8F0 8FB50054 */  lw         $s5, 0x54($sp)
    /* 2B4F4 8002A8F4 8FB60058 */  lw         $s6, 0x58($sp)
    /* 2B4F8 8002A8F8 8FB7005C */  lw         $s7, 0x5C($sp)
    /* 2B4FC 8002A8FC 8FBE0060 */  lw         $fp, 0x60($sp)
    /* 2B500 8002A900 03E00008 */  jr         $ra
    /* 2B504 8002A904 27BD0068 */   addiu     $sp, $sp, 0x68
endlabel func_8002A508
.size func_8002A508, . - func_8002A508
    /* 2B508 8002A908 00000000 */  nop
    /* 2B50C 8002A90C 00000000 */  nop
