.section .late_rodata
nonmatching D_80128AD0

dlabel D_80128AD0
    /* B1540 80128AD0 3DCCCCCD */ .float 0.1000000015
enddlabel D_80128AD0
.size D_80128AD0, . - D_80128AD0

nonmatching D_80128AD4

dlabel D_80128AD4
    /* B1544 80128AD4 3DCCCCCD */ .float 0.1000000015
enddlabel D_80128AD4
.size D_80128AD4, . - D_80128AD4


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8010D42C, 0x23C

glabel func_8010D42C
    /* 95E9C 8010D42C 27BDFF90 */  addiu      $sp, $sp, -0x70
    /* 95EA0 8010D430 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 95EA4 8010D434 AFB00028 */  sw         $s0, 0x28($sp)
    /* 95EA8 8010D438 00808025 */  or         $s0, $a0, $zero
    /* 95EAC 8010D43C 0C0413EE */  jal        func_80104FB8
    /* 95EB0 8010D440 AFA50074 */   sw        $a1, 0x74($sp)
    /* 95EB4 8010D444 C6040004 */  lwc1       $f4, 0x4($s0)
    /* 95EB8 8010D448 44800000 */  mtc1       $zero, $f0
    /* 95EBC 8010D44C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 95EC0 8010D450 E7A40058 */  swc1       $f4, 0x58($sp)
    /* 95EC4 8010D454 C6080014 */  lwc1       $f8, 0x14($s0)
    /* 95EC8 8010D458 C6060008 */  lwc1       $f6, 0x8($s0)
    /* 95ECC 8010D45C C7B20058 */  lwc1       $f18, 0x58($sp)
    /* 95ED0 8010D460 27AE0064 */  addiu      $t6, $sp, 0x64
    /* 95ED4 8010D464 46083280 */  add.s      $f10, $f6, $f8
    /* 95ED8 8010D468 C7A60074 */  lwc1       $f6, 0x74($sp)
    /* 95EDC 8010D46C 27A40058 */  addiu      $a0, $sp, 0x58
    /* 95EE0 8010D470 27A5004C */  addiu      $a1, $sp, 0x4C
    /* 95EE4 8010D474 E7AA005C */  swc1       $f10, 0x5C($sp)
    /* 95EE8 8010D478 C610000C */  lwc1       $f16, 0xC($s0)
    /* 95EEC 8010D47C C7A4005C */  lwc1       $f4, 0x5C($sp)
    /* 95EF0 8010D480 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 95EF4 8010D484 E7B00060 */  swc1       $f16, 0x60($sp)
    /* 95EF8 8010D488 46062200 */  add.s      $f8, $f4, $f6
    /* 95EFC 8010D48C C7AA0060 */  lwc1       $f10, 0x60($sp)
    /* 95F00 8010D490 44818000 */  mtc1       $at, $f16
    /* 95F04 8010D494 AFA00018 */  sw         $zero, 0x18($sp)
    /* 95F08 8010D498 E7A80050 */  swc1       $f8, 0x50($sp)
    /* 95F0C 8010D49C AFA00014 */  sw         $zero, 0x14($sp)
    /* 95F10 8010D4A0 AFAE0010 */  sw         $t6, 0x10($sp)
    /* 95F14 8010D4A4 27A60040 */  addiu      $a2, $sp, 0x40
    /* 95F18 8010D4A8 00003825 */  or         $a3, $zero, $zero
    /* 95F1C 8010D4AC E7A00040 */  swc1       $f0, 0x40($sp)
    /* 95F20 8010D4B0 E7A00048 */  swc1       $f0, 0x48($sp)
    /* 95F24 8010D4B4 E7B2004C */  swc1       $f18, 0x4C($sp)
    /* 95F28 8010D4B8 E7AA0054 */  swc1       $f10, 0x54($sp)
    /* 95F2C 8010D4BC 0C040FA8 */  jal        func_80103EA0
    /* 95F30 8010D4C0 E7B00044 */   swc1      $f16, 0x44($sp)
    /* 95F34 8010D4C4 1040000A */  beqz       $v0, .L8010D4F0
    /* 95F38 8010D4C8 3C038013 */   lui       $v1, %hi(D_8012BD00)
    /* 95F3C 8010D4CC C7B20068 */  lwc1       $f18, 0x68($sp)
    /* 95F40 8010D4D0 C6040014 */  lwc1       $f4, 0x14($s0)
    /* 95F44 8010D4D4 3C018013 */  lui        $at, %hi(D_80128AD0)
    /* 95F48 8010D4D8 C4288AD0 */  lwc1       $f8, %lo(D_80128AD0)($at)
    /* 95F4C 8010D4DC 46049181 */  sub.s      $f6, $f18, $f4
    /* 95F50 8010D4E0 24020001 */  addiu      $v0, $zero, 0x1
    /* 95F54 8010D4E4 46083281 */  sub.s      $f10, $f6, $f8
    /* 95F58 8010D4E8 1000005A */  b          .L8010D654
    /* 95F5C 8010D4EC E60A0008 */   swc1      $f10, 0x8($s0)
  .L8010D4F0:
    /* 95F60 8010D4F0 2463BD00 */  addiu      $v1, $v1, %lo(D_8012BD00)
    /* 95F64 8010D4F4 C4720004 */  lwc1       $f18, 0x4($v1)
    /* 95F68 8010D4F8 C6100004 */  lwc1       $f16, 0x4($s0)
    /* 95F6C 8010D4FC C4680008 */  lwc1       $f8, 0x8($v1)
    /* 95F70 8010D500 27AF003C */  addiu      $t7, $sp, 0x3C
    /* 95F74 8010D504 46128100 */  add.s      $f4, $f16, $f18
    /* 95F78 8010D508 27A40058 */  addiu      $a0, $sp, 0x58
    /* 95F7C 8010D50C 27A5004C */  addiu      $a1, $sp, 0x4C
    /* 95F80 8010D510 27A60040 */  addiu      $a2, $sp, 0x40
    /* 95F84 8010D514 E7A40058 */  swc1       $f4, 0x58($sp)
    /* 95F88 8010D518 C606000C */  lwc1       $f6, 0xC($s0)
    /* 95F8C 8010D51C C7B00058 */  lwc1       $f16, 0x58($sp)
    /* 95F90 8010D520 AFA00038 */  sw         $zero, 0x38($sp)
    /* 95F94 8010D524 46083280 */  add.s      $f10, $f6, $f8
    /* 95F98 8010D528 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 95F9C 8010D52C AFA00018 */  sw         $zero, 0x18($sp)
    /* 95FA0 8010D530 AFAF0014 */  sw         $t7, 0x14($sp)
    /* 95FA4 8010D534 E7AA0060 */  swc1       $f10, 0x60($sp)
    /* 95FA8 8010D538 C7B20060 */  lwc1       $f18, 0x60($sp)
    /* 95FAC 8010D53C AFA00010 */  sw         $zero, 0x10($sp)
    /* 95FB0 8010D540 00003825 */  or         $a3, $zero, $zero
    /* 95FB4 8010D544 E7B0004C */  swc1       $f16, 0x4C($sp)
    /* 95FB8 8010D548 0C040FA8 */  jal        func_80103EA0
    /* 95FBC 8010D54C E7B20054 */   swc1      $f18, 0x54($sp)
    /* 95FC0 8010D550 3C038013 */  lui        $v1, %hi(D_8012BD00)
    /* 95FC4 8010D554 2463BD00 */  addiu      $v1, $v1, %lo(D_8012BD00)
    /* 95FC8 8010D558 10400003 */  beqz       $v0, .L8010D568
    /* 95FCC 8010D55C 8FA80038 */   lw        $t0, 0x38($sp)
    /* 95FD0 8010D560 1000001B */  b          .L8010D5D0
    /* 95FD4 8010D564 24080001 */   addiu     $t0, $zero, 0x1
  .L8010D568:
    /* 95FD8 8010D568 C6040004 */  lwc1       $f4, 0x4($s0)
    /* 95FDC 8010D56C C466000C */  lwc1       $f6, 0xC($v1)
    /* 95FE0 8010D570 C4700010 */  lwc1       $f16, 0x10($v1)
    /* 95FE4 8010D574 27B8003C */  addiu      $t8, $sp, 0x3C
    /* 95FE8 8010D578 46062200 */  add.s      $f8, $f4, $f6
    /* 95FEC 8010D57C 27A40058 */  addiu      $a0, $sp, 0x58
    /* 95FF0 8010D580 27A5004C */  addiu      $a1, $sp, 0x4C
    /* 95FF4 8010D584 27A60040 */  addiu      $a2, $sp, 0x40
    /* 95FF8 8010D588 E7A80058 */  swc1       $f8, 0x58($sp)
    /* 95FFC 8010D58C C60A000C */  lwc1       $f10, 0xC($s0)
    /* 96000 8010D590 C7A40058 */  lwc1       $f4, 0x58($sp)
    /* 96004 8010D594 AFA80038 */  sw         $t0, 0x38($sp)
    /* 96008 8010D598 46105480 */  add.s      $f18, $f10, $f16
    /* 9600C 8010D59C AFA0001C */  sw         $zero, 0x1C($sp)
    /* 96010 8010D5A0 AFA00018 */  sw         $zero, 0x18($sp)
    /* 96014 8010D5A4 AFB80014 */  sw         $t8, 0x14($sp)
    /* 96018 8010D5A8 E7B20060 */  swc1       $f18, 0x60($sp)
    /* 9601C 8010D5AC C7A60060 */  lwc1       $f6, 0x60($sp)
    /* 96020 8010D5B0 AFA00010 */  sw         $zero, 0x10($sp)
    /* 96024 8010D5B4 00003825 */  or         $a3, $zero, $zero
    /* 96028 8010D5B8 E7A4004C */  swc1       $f4, 0x4C($sp)
    /* 9602C 8010D5BC 0C040FA8 */  jal        func_80103EA0
    /* 96030 8010D5C0 E7A60054 */   swc1      $f6, 0x54($sp)
    /* 96034 8010D5C4 10400002 */  beqz       $v0, .L8010D5D0
    /* 96038 8010D5C8 8FA80038 */   lw        $t0, 0x38($sp)
    /* 9603C 8010D5CC 24080001 */  addiu      $t0, $zero, 0x1
  .L8010D5D0:
    /* 96040 8010D5D0 1100001F */  beqz       $t0, .L8010D650
    /* 96044 8010D5D4 8FB9003C */   lw        $t9, 0x3C($sp)
    /* 96048 8010D5D8 C7280000 */  lwc1       $f8, 0x0($t9)
    /* 9604C 8010D5DC C60A0004 */  lwc1       $f10, 0x4($s0)
    /* 96050 8010D5E0 C7320008 */  lwc1       $f18, 0x8($t9)
    /* 96054 8010D5E4 C604000C */  lwc1       $f4, 0xC($s0)
    /* 96058 8010D5E8 460A4402 */  mul.s      $f16, $f8, $f10
    /* 9605C 8010D5EC C72A000C */  lwc1       $f10, 0xC($t9)
    /* 96060 8010D5F0 46049182 */  mul.s      $f6, $f18, $f4
    /* 96064 8010D5F4 46068200 */  add.s      $f8, $f16, $f6
    /* 96068 8010D5F8 C7300004 */  lwc1       $f16, 0x4($t9)
    /* 9606C 8010D5FC C7A60050 */  lwc1       $f6, 0x50($sp)
    /* 96070 8010D600 460A4480 */  add.s      $f18, $f8, $f10
    /* 96074 8010D604 C7A8005C */  lwc1       $f8, 0x5C($sp)
    /* 96078 8010D608 46009107 */  neg.s      $f4, $f18
    /* 9607C 8010D60C 46102003 */  div.s      $f0, $f4, $f16
    /* 96080 8010D610 4606003E */  c.le.s     $f0, $f6
    /* 96084 8010D614 00000000 */  nop
    /* 96088 8010D618 4502000E */  bc1fl      .L8010D654
    /* 9608C 8010D61C 00001025 */   or        $v0, $zero, $zero
    /* 96090 8010D620 4600403E */  c.le.s     $f8, $f0
    /* 96094 8010D624 00000000 */  nop
    /* 96098 8010D628 4502000A */  bc1fl      .L8010D654
    /* 9609C 8010D62C 00001025 */   or        $v0, $zero, $zero
    /* 960A0 8010D630 C60A0014 */  lwc1       $f10, 0x14($s0)
    /* 960A4 8010D634 3C018013 */  lui        $at, %hi(D_80128AD4)
    /* 960A8 8010D638 C4248AD4 */  lwc1       $f4, %lo(D_80128AD4)($at)
    /* 960AC 8010D63C 460A0481 */  sub.s      $f18, $f0, $f10
    /* 960B0 8010D640 24020001 */  addiu      $v0, $zero, 0x1
    /* 960B4 8010D644 46049401 */  sub.s      $f16, $f18, $f4
    /* 960B8 8010D648 10000002 */  b          .L8010D654
    /* 960BC 8010D64C E6100008 */   swc1      $f16, 0x8($s0)
  .L8010D650:
    /* 960C0 8010D650 00001025 */  or         $v0, $zero, $zero
  .L8010D654:
    /* 960C4 8010D654 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 960C8 8010D658 8FB00028 */  lw         $s0, 0x28($sp)
    /* 960CC 8010D65C 27BD0070 */  addiu      $sp, $sp, 0x70
    /* 960D0 8010D660 03E00008 */  jr         $ra
    /* 960D4 8010D664 00000000 */   nop
endlabel func_8010D42C
.size func_8010D42C, . - func_8010D42C
