.section .late_rodata
nonmatching D_80128A80

dlabel D_80128A80
    /* B14F0 80128A80 3F8CCCCD */ .float 1.100000024
enddlabel D_80128A80
.size D_80128A80, . - D_80128A80


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_80105284, 0x2AC

glabel func_80105284
    /* 8DCF4 80105284 27BDFF80 */  addiu      $sp, $sp, -0x80
    /* 8DCF8 80105288 3C028013 */  lui        $v0, %hi(D_8012BD00)
    /* 8DCFC 8010528C 2442BD00 */  addiu      $v0, $v0, %lo(D_8012BD00)
    /* 8DD00 80105290 3C018013 */  lui        $at, %hi(D_80128A80)
    /* 8DD04 80105294 C4248A80 */  lwc1       $f4, %lo(D_80128A80)($at)
    /* 8DD08 80105298 C4460014 */  lwc1       $f6, 0x14($v0)
    /* 8DD0C 8010529C 44804000 */  mtc1       $zero, $f8
    /* 8DD10 801052A0 C44A0018 */  lwc1       $f10, 0x18($v0)
    /* 8DD14 801052A4 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 8DD18 801052A8 AFB10028 */  sw         $s1, 0x28($sp)
    /* 8DD1C 801052AC AFB00024 */  sw         $s0, 0x24($sp)
    /* 8DD20 801052B0 E7A40078 */  swc1       $f4, 0x78($sp)
    /* 8DD24 801052B4 E7A60054 */  swc1       $f6, 0x54($sp)
    /* 8DD28 801052B8 E7A80058 */  swc1       $f8, 0x58($sp)
    /* 8DD2C 801052BC E7AA005C */  swc1       $f10, 0x5C($sp)
    /* 8DD30 801052C0 C4900034 */  lwc1       $f16, 0x34($a0)
    /* 8DD34 801052C4 C4480004 */  lwc1       $f8, 0x4($v0)
    /* 8DD38 801052C8 00A08825 */  or         $s1, $a1, $zero
    /* 8DD3C 801052CC E7B0006C */  swc1       $f16, 0x6C($sp)
    /* 8DD40 801052D0 C492002C */  lwc1       $f18, 0x2C($a0)
    /* 8DD44 801052D4 3C0E8013 */  lui        $t6, %hi(D_8012BD34)
    /* 8DD48 801052D8 00808025 */  or         $s0, $a0, $zero
    /* 8DD4C 801052DC E7B20070 */  swc1       $f18, 0x70($sp)
    /* 8DD50 801052E0 C4840038 */  lwc1       $f4, 0x38($a0)
    /* 8DD54 801052E4 25CEBD34 */  addiu      $t6, $t6, %lo(D_8012BD34)
    /* 8DD58 801052E8 262F0024 */  addiu      $t7, $s1, 0x24
    /* 8DD5C 801052EC E7A40074 */  swc1       $f4, 0x74($sp)
    /* 8DD60 801052F0 C4860004 */  lwc1       $f6, 0x4($a0)
    /* 8DD64 801052F4 26380020 */  addiu      $t8, $s1, 0x20
    /* 8DD68 801052F8 2639001C */  addiu      $t9, $s1, 0x1C
    /* 8DD6C 801052FC 46083280 */  add.s      $f10, $f6, $f8
    /* 8DD70 80105300 C4480008 */  lwc1       $f8, 0x8($v0)
    /* 8DD74 80105304 27A50060 */  addiu      $a1, $sp, 0x60
    /* 8DD78 80105308 27A60054 */  addiu      $a2, $sp, 0x54
    /* 8DD7C 8010530C E7AA0060 */  swc1       $f10, 0x60($sp)
    /* 8DD80 80105310 C4920010 */  lwc1       $f18, 0x10($a0)
    /* 8DD84 80105314 C4900008 */  lwc1       $f16, 0x8($a0)
    /* 8DD88 80105318 27A70078 */  addiu      $a3, $sp, 0x78
    /* 8DD8C 8010531C 46128100 */  add.s      $f4, $f16, $f18
    /* 8DD90 80105320 E7A40064 */  swc1       $f4, 0x64($sp)
    /* 8DD94 80105324 C486000C */  lwc1       $f6, 0xC($a0)
    /* 8DD98 80105328 AFA00050 */  sw         $zero, 0x50($sp)
    /* 8DD9C 8010532C AFB9001C */  sw         $t9, 0x1C($sp)
    /* 8DDA0 80105330 46083280 */  add.s      $f10, $f6, $f8
    /* 8DDA4 80105334 AFB80018 */  sw         $t8, 0x18($sp)
    /* 8DDA8 80105338 AFAF0014 */  sw         $t7, 0x14($sp)
    /* 8DDAC 8010533C AFAE0010 */  sw         $t6, 0x10($sp)
    /* 8DDB0 80105340 E7AA0068 */  swc1       $f10, 0x68($sp)
    /* 8DDB4 80105344 0C04134B */  jal        func_80104D2C
    /* 8DDB8 80105348 27A4006C */   addiu     $a0, $sp, 0x6C
    /* 8DDBC 8010534C 10400002 */  beqz       $v0, .L80105358
    /* 8DDC0 80105350 8FA30050 */   lw        $v1, 0x50($sp)
    /* 8DDC4 80105354 24030001 */  addiu      $v1, $zero, 0x1
  .L80105358:
    /* 8DDC8 80105358 C6100048 */  lwc1       $f16, 0x48($s0)
    /* 8DDCC 8010535C 26080010 */  addiu      $t0, $s0, 0x10
    /* 8DDD0 80105360 27A90040 */  addiu      $t1, $sp, 0x40
    /* 8DDD4 80105364 E7B00070 */  swc1       $f16, 0x70($sp)
    /* 8DDD8 80105368 C5040008 */  lwc1       $f4, 0x8($t0)
    /* 8DDDC 8010536C C6120008 */  lwc1       $f18, 0x8($s0)
    /* 8DDE0 80105370 27AA003C */  addiu      $t2, $sp, 0x3C
    /* 8DDE4 80105374 27AB0038 */  addiu      $t3, $sp, 0x38
    /* 8DDE8 80105378 46049180 */  add.s      $f6, $f18, $f4
    /* 8DDEC 8010537C 27AC0034 */  addiu      $t4, $sp, 0x34
    /* 8DDF0 80105380 AFAC001C */  sw         $t4, 0x1C($sp)
    /* 8DDF4 80105384 AFAB0018 */  sw         $t3, 0x18($sp)
    /* 8DDF8 80105388 E7A60064 */  swc1       $f6, 0x64($sp)
    /* 8DDFC 8010538C AFAA0014 */  sw         $t2, 0x14($sp)
    /* 8DE00 80105390 AFA80030 */  sw         $t0, 0x30($sp)
    /* 8DE04 80105394 AFA30050 */  sw         $v1, 0x50($sp)
    /* 8DE08 80105398 AFA90010 */  sw         $t1, 0x10($sp)
    /* 8DE0C 8010539C 27A4006C */  addiu      $a0, $sp, 0x6C
    /* 8DE10 801053A0 27A50060 */  addiu      $a1, $sp, 0x60
    /* 8DE14 801053A4 27A60054 */  addiu      $a2, $sp, 0x54
    /* 8DE18 801053A8 0C04134B */  jal        func_80104D2C
    /* 8DE1C 801053AC 27A7004C */   addiu     $a3, $sp, 0x4C
    /* 8DE20 801053B0 8FA30050 */  lw         $v1, 0x50($sp)
    /* 8DE24 801053B4 1040001D */  beqz       $v0, .L8010542C
    /* 8DE28 801053B8 8FA80030 */   lw        $t0, 0x30($sp)
    /* 8DE2C 801053BC 10600009 */  beqz       $v1, .L801053E4
    /* 8DE30 801053C0 8FAD003C */   lw        $t5, 0x3C($sp)
    /* 8DE34 801053C4 8E2E0024 */  lw         $t6, 0x24($s1)
    /* 8DE38 801053C8 C7A8004C */  lwc1       $f8, 0x4C($sp)
    /* 8DE3C 801053CC C7AA0078 */  lwc1       $f10, 0x78($sp)
    /* 8DE40 801053D0 51AE0017 */  beql       $t5, $t6, .L80105430
    /* 8DE44 801053D4 C6120044 */   lwc1      $f18, 0x44($s0)
    /* 8DE48 801053D8 460A403C */  c.lt.s     $f8, $f10
    /* 8DE4C 801053DC 00000000 */  nop
    /* 8DE50 801053E0 45000012 */  bc1f       .L8010542C
  .L801053E4:
    /* 8DE54 801053E4 27B80040 */   addiu     $t8, $sp, 0x40
    /* 8DE58 801053E8 8F090000 */  lw         $t1, 0x0($t8)
    /* 8DE5C 801053EC 3C0F8013 */  lui        $t7, %hi(D_8012BD34)
    /* 8DE60 801053F0 25EFBD34 */  addiu      $t7, $t7, %lo(D_8012BD34)
    /* 8DE64 801053F4 ADE90000 */  sw         $t1, 0x0($t7)
    /* 8DE68 801053F8 8F090008 */  lw         $t1, 0x8($t8)
    /* 8DE6C 801053FC 8F190004 */  lw         $t9, 0x4($t8)
    /* 8DE70 80105400 24030004 */  addiu      $v1, $zero, 0x4
    /* 8DE74 80105404 ADE90008 */  sw         $t1, 0x8($t7)
    /* 8DE78 80105408 ADF90004 */  sw         $t9, 0x4($t7)
    /* 8DE7C 8010540C 8FAA003C */  lw         $t2, 0x3C($sp)
    /* 8DE80 80105410 AE2A0024 */  sw         $t2, 0x24($s1)
    /* 8DE84 80105414 8FAB0038 */  lw         $t3, 0x38($sp)
    /* 8DE88 80105418 AE2B0020 */  sw         $t3, 0x20($s1)
    /* 8DE8C 8010541C 8FAC0034 */  lw         $t4, 0x34($sp)
    /* 8DE90 80105420 AE2C001C */  sw         $t4, 0x1C($s1)
    /* 8DE94 80105424 C7B0004C */  lwc1       $f16, 0x4C($sp)
    /* 8DE98 80105428 E7B00078 */  swc1       $f16, 0x78($sp)
  .L8010542C:
    /* 8DE9C 8010542C C6120044 */  lwc1       $f18, 0x44($s0)
  .L80105430:
    /* 8DEA0 80105430 27AD0040 */  addiu      $t5, $sp, 0x40
    /* 8DEA4 80105434 27AE003C */  addiu      $t6, $sp, 0x3C
    /* 8DEA8 80105438 E7B20070 */  swc1       $f18, 0x70($sp)
    /* 8DEAC 8010543C C5060004 */  lwc1       $f6, 0x4($t0)
    /* 8DEB0 80105440 C6040008 */  lwc1       $f4, 0x8($s0)
    /* 8DEB4 80105444 27AF0038 */  addiu      $t7, $sp, 0x38
    /* 8DEB8 80105448 27B80034 */  addiu      $t8, $sp, 0x34
    /* 8DEBC 8010544C 46062200 */  add.s      $f8, $f4, $f6
    /* 8DEC0 80105450 AFB8001C */  sw         $t8, 0x1C($sp)
    /* 8DEC4 80105454 AFAF0018 */  sw         $t7, 0x18($sp)
    /* 8DEC8 80105458 AFA30050 */  sw         $v1, 0x50($sp)
    /* 8DECC 8010545C E7A80064 */  swc1       $f8, 0x64($sp)
    /* 8DED0 80105460 AFAE0014 */  sw         $t6, 0x14($sp)
    /* 8DED4 80105464 AFAD0010 */  sw         $t5, 0x10($sp)
    /* 8DED8 80105468 27A4006C */  addiu      $a0, $sp, 0x6C
    /* 8DEDC 8010546C 27A50060 */  addiu      $a1, $sp, 0x60
    /* 8DEE0 80105470 27A60054 */  addiu      $a2, $sp, 0x54
    /* 8DEE4 80105474 0C04134B */  jal        func_80104D2C
    /* 8DEE8 80105478 27A7004C */   addiu     $a3, $sp, 0x4C
    /* 8DEEC 8010547C 1040001B */  beqz       $v0, .L801054EC
    /* 8DEF0 80105480 8FA30050 */   lw        $v1, 0x50($sp)
    /* 8DEF4 80105484 10600009 */  beqz       $v1, .L801054AC
    /* 8DEF8 80105488 8FB9003C */   lw        $t9, 0x3C($sp)
    /* 8DEFC 8010548C 8E290024 */  lw         $t1, 0x24($s1)
    /* 8DF00 80105490 C7AA004C */  lwc1       $f10, 0x4C($sp)
    /* 8DF04 80105494 C7B00078 */  lwc1       $f16, 0x78($sp)
    /* 8DF08 80105498 13290014 */  beq        $t9, $t1, .L801054EC
    /* 8DF0C 8010549C 00000000 */   nop
    /* 8DF10 801054A0 4610503C */  c.lt.s     $f10, $f16
    /* 8DF14 801054A4 00000000 */  nop
    /* 8DF18 801054A8 45000010 */  bc1f       .L801054EC
  .L801054AC:
    /* 8DF1C 801054AC 27AB0040 */   addiu     $t3, $sp, 0x40
    /* 8DF20 801054B0 8D6D0000 */  lw         $t5, 0x0($t3)
    /* 8DF24 801054B4 3C0A8013 */  lui        $t2, %hi(D_8012BD34)
    /* 8DF28 801054B8 254ABD34 */  addiu      $t2, $t2, %lo(D_8012BD34)
    /* 8DF2C 801054BC AD4D0000 */  sw         $t5, 0x0($t2)
    /* 8DF30 801054C0 8D6D0008 */  lw         $t5, 0x8($t3)
    /* 8DF34 801054C4 8D6C0004 */  lw         $t4, 0x4($t3)
    /* 8DF38 801054C8 24030002 */  addiu      $v1, $zero, 0x2
    /* 8DF3C 801054CC AD4D0008 */  sw         $t5, 0x8($t2)
    /* 8DF40 801054D0 AD4C0004 */  sw         $t4, 0x4($t2)
    /* 8DF44 801054D4 8FAE003C */  lw         $t6, 0x3C($sp)
    /* 8DF48 801054D8 AE2E0024 */  sw         $t6, 0x24($s1)
    /* 8DF4C 801054DC 8FAF0038 */  lw         $t7, 0x38($sp)
    /* 8DF50 801054E0 AE2F0020 */  sw         $t7, 0x20($s1)
    /* 8DF54 801054E4 8FB80034 */  lw         $t8, 0x34($sp)
    /* 8DF58 801054E8 AE38001C */  sw         $t8, 0x1C($s1)
  .L801054EC:
    /* 8DF5C 801054EC 1060000B */  beqz       $v1, .L8010551C
    /* 8DF60 801054F0 00001025 */   or        $v0, $zero, $zero
    /* 8DF64 801054F4 8E390000 */  lw         $t9, 0x0($s1)
    /* 8DF68 801054F8 962D0000 */  lhu        $t5, 0x0($s1)
    /* 8DF6C 801054FC 24020001 */  addiu      $v0, $zero, 0x1
    /* 8DF70 80105500 00194CC2 */  srl        $t1, $t9, 19
    /* 8DF74 80105504 01235025 */  or         $t2, $t1, $v1
    /* 8DF78 80105508 000A60C0 */  sll        $t4, $t2, 3
    /* 8DF7C 8010550C 31AE0007 */  andi       $t6, $t5, 0x7
    /* 8DF80 80105510 018E7825 */  or         $t7, $t4, $t6
    /* 8DF84 80105514 10000001 */  b          .L8010551C
    /* 8DF88 80105518 A62F0000 */   sh        $t7, 0x0($s1)
  .L8010551C:
    /* 8DF8C 8010551C 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 8DF90 80105520 8FB00024 */  lw         $s0, 0x24($sp)
    /* 8DF94 80105524 8FB10028 */  lw         $s1, 0x28($sp)
    /* 8DF98 80105528 03E00008 */  jr         $ra
    /* 8DF9C 8010552C 27BD0080 */   addiu     $sp, $sp, 0x80
endlabel func_80105284
.size func_80105284, . - func_80105284
