.section .late_rodata
nonmatching D_80128AC0

dlabel D_80128AC0
    /* B1530 80128AC0 3E051EB8 */ .float 0.1299999952
enddlabel D_80128AC0
.size D_80128AC0, . - D_80128AC0


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8010B480, 0x1FC

glabel func_8010B480
    /* 93EF0 8010B480 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 93EF4 8010B484 AFB00028 */  sw         $s0, 0x28($sp)
    /* 93EF8 8010B488 00808025 */  or         $s0, $a0, $zero
    /* 93EFC 8010B48C AFBF002C */  sw         $ra, 0x2C($sp)
    /* 93F00 8010B490 3C048013 */  lui        $a0, %hi(D_8012BCA0)
    /* 93F04 8010B494 0C041486 */  jal        func_80105218
    /* 93F08 8010B498 2484BCA0 */   addiu     $a0, $a0, %lo(D_8012BCA0)
    /* 93F0C 8010B49C 0C0413EE */  jal        func_80104FB8
    /* 93F10 8010B4A0 02002025 */   or        $a0, $s0, $zero
    /* 93F14 8010B4A4 44800000 */  mtc1       $zero, $f0
    /* 93F18 8010B4A8 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 93F1C 8010B4AC 44812000 */  mtc1       $at, $f4
    /* 93F20 8010B4B0 E7A00034 */  swc1       $f0, 0x34($sp)
    /* 93F24 8010B4B4 E7A0003C */  swc1       $f0, 0x3C($sp)
    /* 93F28 8010B4B8 E7A40038 */  swc1       $f4, 0x38($sp)
    /* 93F2C 8010B4BC C6060004 */  lwc1       $f6, 0x4($s0)
    /* 93F30 8010B4C0 26030010 */  addiu      $v1, $s0, 0x10
    /* 93F34 8010B4C4 3C018013 */  lui        $at, %hi(D_80128AC0)
    /* 93F38 8010B4C8 E7A6004C */  swc1       $f6, 0x4C($sp)
    /* 93F3C 8010B4CC C46A0004 */  lwc1       $f10, 0x4($v1)
    /* 93F40 8010B4D0 C6080008 */  lwc1       $f8, 0x8($s0)
    /* 93F44 8010B4D4 C7A4004C */  lwc1       $f4, 0x4C($sp)
    /* 93F48 8010B4D8 27A4004C */  addiu      $a0, $sp, 0x4C
    /* 93F4C 8010B4DC 460A4400 */  add.s      $f16, $f8, $f10
    /* 93F50 8010B4E0 C4288AC0 */  lwc1       $f8, %lo(D_80128AC0)($at)
    /* 93F54 8010B4E4 27A50040 */  addiu      $a1, $sp, 0x40
    /* 93F58 8010B4E8 27A60034 */  addiu      $a2, $sp, 0x34
    /* 93F5C 8010B4EC E7B00050 */  swc1       $f16, 0x50($sp)
    /* 93F60 8010B4F0 C612000C */  lwc1       $f18, 0xC($s0)
    /* 93F64 8010B4F4 C7A60050 */  lwc1       $f6, 0x50($sp)
    /* 93F68 8010B4F8 AFA30030 */  sw         $v1, 0x30($sp)
    /* 93F6C 8010B4FC E7B20054 */  swc1       $f18, 0x54($sp)
    /* 93F70 8010B500 46083280 */  add.s      $f10, $f6, $f8
    /* 93F74 8010B504 C7B00054 */  lwc1       $f16, 0x54($sp)
    /* 93F78 8010B508 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 93F7C 8010B50C AFA00018 */  sw         $zero, 0x18($sp)
    /* 93F80 8010B510 E7AA0044 */  swc1       $f10, 0x44($sp)
    /* 93F84 8010B514 AFA00014 */  sw         $zero, 0x14($sp)
    /* 93F88 8010B518 AFA00010 */  sw         $zero, 0x10($sp)
    /* 93F8C 8010B51C 00003825 */  or         $a3, $zero, $zero
    /* 93F90 8010B520 E7A40040 */  swc1       $f4, 0x40($sp)
    /* 93F94 8010B524 0C040FA8 */  jal        func_80103EA0
    /* 93F98 8010B528 E7B00048 */   swc1      $f16, 0x48($sp)
    /* 93F9C 8010B52C 10400009 */  beqz       $v0, .L8010B554
    /* 93FA0 8010B530 8FA30030 */   lw        $v1, 0x30($sp)
    /* 93FA4 8010B534 3C0E8013 */  lui        $t6, %hi(D_8012BCA0)
    /* 93FA8 8010B538 95CEBCA0 */  lhu        $t6, %lo(D_8012BCA0)($t6)
    /* 93FAC 8010B53C 3C018013 */  lui        $at, %hi(D_8012BCA0)
    /* 93FB0 8010B540 24020001 */  addiu      $v0, $zero, 0x1
    /* 93FB4 8010B544 31CF0007 */  andi       $t7, $t6, 0x7
    /* 93FB8 8010B548 35F80200 */  ori        $t8, $t7, 0x200
    /* 93FBC 8010B54C 10000046 */  b          .L8010B668
    /* 93FC0 8010B550 A438BCA0 */   sh        $t8, %lo(D_8012BCA0)($at)
  .L8010B554:
    /* 93FC4 8010B554 3C088013 */  lui        $t0, %hi(D_8012BD00)
    /* 93FC8 8010B558 2508BD00 */  addiu      $t0, $t0, %lo(D_8012BD00)
    /* 93FCC 8010B55C C5040004 */  lwc1       $f4, 0x4($t0)
    /* 93FD0 8010B560 C6120004 */  lwc1       $f18, 0x4($s0)
    /* 93FD4 8010B564 27A4004C */  addiu      $a0, $sp, 0x4C
    /* 93FD8 8010B568 27A50040 */  addiu      $a1, $sp, 0x40
    /* 93FDC 8010B56C 46049180 */  add.s      $f6, $f18, $f4
    /* 93FE0 8010B570 C5040008 */  lwc1       $f4, 0x8($t0)
    /* 93FE4 8010B574 27A60034 */  addiu      $a2, $sp, 0x34
    /* 93FE8 8010B578 00003825 */  or         $a3, $zero, $zero
    /* 93FEC 8010B57C E7A6004C */  swc1       $f6, 0x4C($sp)
    /* 93FF0 8010B580 C46A0008 */  lwc1       $f10, 0x8($v1)
    /* 93FF4 8010B584 C6080008 */  lwc1       $f8, 0x8($s0)
    /* 93FF8 8010B588 460A4400 */  add.s      $f16, $f8, $f10
    /* 93FFC 8010B58C C7A8004C */  lwc1       $f8, 0x4C($sp)
    /* 94000 8010B590 E7B00050 */  swc1       $f16, 0x50($sp)
    /* 94004 8010B594 C612000C */  lwc1       $f18, 0xC($s0)
    /* 94008 8010B598 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 9400C 8010B59C AFA00018 */  sw         $zero, 0x18($sp)
    /* 94010 8010B5A0 46049180 */  add.s      $f6, $f18, $f4
    /* 94014 8010B5A4 AFA00014 */  sw         $zero, 0x14($sp)
    /* 94018 8010B5A8 AFA00010 */  sw         $zero, 0x10($sp)
    /* 9401C 8010B5AC E7A80040 */  swc1       $f8, 0x40($sp)
    /* 94020 8010B5B0 E7A60054 */  swc1       $f6, 0x54($sp)
    /* 94024 8010B5B4 C7AA0054 */  lwc1       $f10, 0x54($sp)
    /* 94028 8010B5B8 0C040FA8 */  jal        func_80103EA0
    /* 9402C 8010B5BC E7AA0048 */   swc1      $f10, 0x48($sp)
    /* 94030 8010B5C0 3C088013 */  lui        $t0, %hi(D_8012BD00)
    /* 94034 8010B5C4 10400009 */  beqz       $v0, .L8010B5EC
    /* 94038 8010B5C8 2508BD00 */   addiu     $t0, $t0, %lo(D_8012BD00)
    /* 9403C 8010B5CC 3C198013 */  lui        $t9, %hi(D_8012BCA0)
    /* 94040 8010B5D0 9739BCA0 */  lhu        $t9, %lo(D_8012BCA0)($t9)
    /* 94044 8010B5D4 3C018013 */  lui        $at, %hi(D_8012BCA0)
    /* 94048 8010B5D8 24020001 */  addiu      $v0, $zero, 0x1
    /* 9404C 8010B5DC 33290007 */  andi       $t1, $t9, 0x7
    /* 94050 8010B5E0 352A0800 */  ori        $t2, $t1, 0x800
    /* 94054 8010B5E4 10000020 */  b          .L8010B668
    /* 94058 8010B5E8 A42ABCA0 */   sh        $t2, %lo(D_8012BCA0)($at)
  .L8010B5EC:
    /* 9405C 8010B5EC C6100004 */  lwc1       $f16, 0x4($s0)
    /* 94060 8010B5F0 C512000C */  lwc1       $f18, 0xC($t0)
    /* 94064 8010B5F4 C5080010 */  lwc1       $f8, 0x10($t0)
    /* 94068 8010B5F8 27A4004C */  addiu      $a0, $sp, 0x4C
    /* 9406C 8010B5FC 46128100 */  add.s      $f4, $f16, $f18
    /* 94070 8010B600 27A50040 */  addiu      $a1, $sp, 0x40
    /* 94074 8010B604 27A60034 */  addiu      $a2, $sp, 0x34
    /* 94078 8010B608 00003825 */  or         $a3, $zero, $zero
    /* 9407C 8010B60C E7A4004C */  swc1       $f4, 0x4C($sp)
    /* 94080 8010B610 C606000C */  lwc1       $f6, 0xC($s0)
    /* 94084 8010B614 C7B0004C */  lwc1       $f16, 0x4C($sp)
    /* 94088 8010B618 AFA0001C */  sw         $zero, 0x1C($sp)
    /* 9408C 8010B61C 46083280 */  add.s      $f10, $f6, $f8
    /* 94090 8010B620 AFA00018 */  sw         $zero, 0x18($sp)
    /* 94094 8010B624 AFA00014 */  sw         $zero, 0x14($sp)
    /* 94098 8010B628 AFA00010 */  sw         $zero, 0x10($sp)
    /* 9409C 8010B62C E7AA0054 */  swc1       $f10, 0x54($sp)
    /* 940A0 8010B630 C7B20054 */  lwc1       $f18, 0x54($sp)
    /* 940A4 8010B634 E7B00040 */  swc1       $f16, 0x40($sp)
    /* 940A8 8010B638 0C040FA8 */  jal        func_80103EA0
    /* 940AC 8010B63C E7B20048 */   swc1      $f18, 0x48($sp)
    /* 940B0 8010B640 10400008 */  beqz       $v0, .L8010B664
    /* 940B4 8010B644 3C0B8013 */   lui       $t3, %hi(D_8012BCA0)
    /* 940B8 8010B648 956BBCA0 */  lhu        $t3, %lo(D_8012BCA0)($t3)
    /* 940BC 8010B64C 3C018013 */  lui        $at, %hi(D_8012BCA0)
    /* 940C0 8010B650 24020001 */  addiu      $v0, $zero, 0x1
    /* 940C4 8010B654 316C0007 */  andi       $t4, $t3, 0x7
    /* 940C8 8010B658 358D0400 */  ori        $t5, $t4, 0x400
    /* 940CC 8010B65C 10000002 */  b          .L8010B668
    /* 940D0 8010B660 A42DBCA0 */   sh        $t5, %lo(D_8012BCA0)($at)
  .L8010B664:
    /* 940D4 8010B664 00001025 */  or         $v0, $zero, $zero
  .L8010B668:
    /* 940D8 8010B668 8FBF002C */  lw         $ra, 0x2C($sp)
    /* 940DC 8010B66C 8FB00028 */  lw         $s0, 0x28($sp)
    /* 940E0 8010B670 27BD0060 */  addiu      $sp, $sp, 0x60
    /* 940E4 8010B674 03E00008 */  jr         $ra
    /* 940E8 8010B678 00000000 */   nop
endlabel func_8010B480
.size func_8010B480, . - func_8010B480
