.section .rodata
.align 2
nonmatching D_80128890

dlabel D_80128890
    /* B1300 80128890 */ .asciz "setUpDispose failed. DisType =%02d\n"
    /* 7365745570446973706F7365206661696C65642E2044697354797065203D253032640A00 */
.align 2
enddlabel D_80128890
.size D_80128890, . - D_80128890

.section .late_rodata
nonmatching jtbl_801288B4

dlabel jtbl_801288B4
    /* B1324 801288B4 800FCAC4 */ .word .L800FCAC4
    /* B1328 801288B8 800FCAE4 */ .word .L800FCAE4
    /* B132C 801288BC 800FCB04 */ .word .L800FCB04
    /* B1330 801288C0 800FCB24 */ .word .L800FCB24
    /* B1334 801288C4 800FCB74 */ .word .L800FCB74
    /* B1338 801288C8 800FCB44 */ .word .L800FCB44
    /* B133C 801288CC 800FCB74 */ .word .L800FCB74
    /* B1340 801288D0 800FCB4C */ .word .L800FCB4C
    /* B1344 801288D4 800FCB6C */ .word .L800FCB6C
enddlabel jtbl_801288B4
.size jtbl_801288B4, . - jtbl_801288B4


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching setUpDispose, 0x290

glabel setUpDispose
    /* 854F4 800FCA84 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* 854F8 800FCA88 AFA50034 */  sw         $a1, 0x34($sp)
    /* 854FC 800FCA8C 93AE0037 */  lbu        $t6, 0x37($sp)
    /* 85500 800FCA90 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 85504 800FCA94 AFA40030 */  sw         $a0, 0x30($sp)
    /* 85508 800FCA98 2DC10009 */  sltiu      $at, $t6, 0x9
    /* 8550C 800FCA9C AFA60038 */  sw         $a2, 0x38($sp)
    /* 85510 800FCAA0 AFA7003C */  sw         $a3, 0x3C($sp)
    /* 85514 800FCAA4 10200033 */  beqz       $at, .L800FCB74
    /* 85518 800FCAA8 AFAE001C */   sw        $t6, 0x1C($sp)
    /* 8551C 800FCAAC 000E7880 */  sll        $t7, $t6, 2
    /* 85520 800FCAB0 3C018013 */  lui        $at, %hi(jtbl_801288B4)
    /* 85524 800FCAB4 002F0821 */  addu       $at, $at, $t7
    /* 85528 800FCAB8 8C2F88B4 */  lw         $t7, %lo(jtbl_801288B4)($at)
    /* 8552C 800FCABC 01E00008 */  jr         $t7
    /* 85530 800FCAC0 00000000 */   nop
  .L800FCAC4:
    /* 85534 800FCAC4 93B8003B */  lbu        $t8, 0x3B($sp)
    /* 85538 800FCAC8 2B01006B */  slti       $at, $t8, 0x6B
    /* 8553C 800FCACC 14200003 */  bnez       $at, .L800FCADC
    /* 85540 800FCAD0 00000000 */   nop
    /* 85544 800FCAD4 1000008B */  b          .L800FCD04
    /* 85548 800FCAD8 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCADC:
    /* 8554C 800FCADC 1000002B */  b          .L800FCB8C
    /* 85550 800FCAE0 24040017 */   addiu     $a0, $zero, 0x17
  .L800FCAE4:
    /* 85554 800FCAE4 93B9003B */  lbu        $t9, 0x3B($sp)
    /* 85558 800FCAE8 2B210003 */  slti       $at, $t9, 0x3
    /* 8555C 800FCAEC 14200003 */  bnez       $at, .L800FCAFC
    /* 85560 800FCAF0 00000000 */   nop
    /* 85564 800FCAF4 10000083 */  b          .L800FCD04
    /* 85568 800FCAF8 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCAFC:
    /* 8556C 800FCAFC 10000023 */  b          .L800FCB8C
    /* 85570 800FCB00 24040018 */   addiu     $a0, $zero, 0x18
  .L800FCB04:
    /* 85574 800FCB04 93A8003B */  lbu        $t0, 0x3B($sp)
    /* 85578 800FCB08 29010007 */  slti       $at, $t0, 0x7
    /* 8557C 800FCB0C 14200003 */  bnez       $at, .L800FCB1C
    /* 85580 800FCB10 00000000 */   nop
    /* 85584 800FCB14 1000007B */  b          .L800FCD04
    /* 85588 800FCB18 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCB1C:
    /* 8558C 800FCB1C 1000001B */  b          .L800FCB8C
    /* 85590 800FCB20 24040019 */   addiu     $a0, $zero, 0x19
  .L800FCB24:
    /* 85594 800FCB24 93A9003B */  lbu        $t1, 0x3B($sp)
    /* 85598 800FCB28 2921000E */  slti       $at, $t1, 0xE
    /* 8559C 800FCB2C 14200003 */  bnez       $at, .L800FCB3C
    /* 855A0 800FCB30 00000000 */   nop
    /* 855A4 800FCB34 10000073 */  b          .L800FCD04
    /* 855A8 800FCB38 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCB3C:
    /* 855AC 800FCB3C 10000013 */  b          .L800FCB8C
    /* 855B0 800FCB40 2404001C */   addiu     $a0, $zero, 0x1C
  .L800FCB44:
    /* 855B4 800FCB44 1000006F */  b          .L800FCD04
    /* 855B8 800FCB48 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCB4C:
    /* 855BC 800FCB4C 93AA003B */  lbu        $t2, 0x3B($sp)
    /* 855C0 800FCB50 2941000B */  slti       $at, $t2, 0xB
    /* 855C4 800FCB54 14200003 */  bnez       $at, .L800FCB64
    /* 855C8 800FCB58 00000000 */   nop
    /* 855CC 800FCB5C 10000069 */  b          .L800FCD04
    /* 855D0 800FCB60 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCB64:
    /* 855D4 800FCB64 10000009 */  b          .L800FCB8C
    /* 855D8 800FCB68 24040020 */   addiu     $a0, $zero, 0x20
  .L800FCB6C:
    /* 855DC 800FCB6C 10000007 */  b          .L800FCB8C
    /* 855E0 800FCB70 24040021 */   addiu     $a0, $zero, 0x21
  .L800FCB74:
    /* 855E4 800FCB74 3C048013 */  lui        $a0, %hi(D_80128890)
    /* 855E8 800FCB78 24848890 */  addiu      $a0, $a0, %lo(D_80128890)
    /* 855EC 800FCB7C 0C02909C */  jal        utilPrintf
    /* 855F0 800FCB80 8FA5001C */   lw        $a1, 0x1C($sp)
    /* 855F4 800FCB84 1000005F */  b          .L800FCD04
    /* 855F8 800FCB88 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCB8C:
    /* 855FC 800FCB8C 2405001E */  addiu      $a1, $zero, 0x1E
    /* 85600 800FCB90 0C02BB02 */  jal        request_track_general
    /* 85604 800FCB94 2406003C */   addiu     $a2, $zero, 0x3C
    /* 85608 800FCB98 2401FFFF */  addiu      $at, $zero, -0x1
    /* 8560C 800FCB9C 14410003 */  bne        $v0, $at, .L800FCBAC
    /* 85610 800FCBA0 3C04800D */   lui       $a0, %hi(D_800D6E10)
    /* 85614 800FCBA4 10000057 */  b          .L800FCD04
    /* 85618 800FCBA8 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800FCBAC:
    /* 8561C 800FCBAC 24846E10 */  addiu      $a0, $a0, %lo(D_800D6E10)
    /* 85620 800FCBB0 8C8B0000 */  lw         $t3, 0x0($a0)
    /* 85624 800FCBB4 0002C840 */  sll        $t9, $v0, 1
    /* 85628 800FCBB8 240C0002 */  addiu      $t4, $zero, 0x2
    /* 8562C 800FCBBC 25630001 */  addiu      $v1, $t3, 0x1
    /* 85630 800FCBC0 28610100 */  slti       $at, $v1, 0x100
    /* 85634 800FCBC4 14200003 */  bnez       $at, .L800FCBD4
    /* 85638 800FCBC8 AC830000 */   sw        $v1, 0x0($a0)
    /* 8563C 800FCBCC 24030001 */  addiu      $v1, $zero, 0x1
    /* 85640 800FCBD0 AC830000 */  sw         $v1, 0x0($a0)
  .L800FCBD4:
    /* 85644 800FCBD4 3C01800E */  lui        $at, %hi(D_800E7650)
    /* 85648 800FCBD8 00220821 */  addu       $at, $at, $v0
    /* 8564C 800FCBDC 8FAE0030 */  lw         $t6, 0x30($sp)
    /* 85650 800FCBE0 A0237650 */  sb         $v1, %lo(D_800E7650)($at)
    /* 85654 800FCBE4 3C01800E */  lui        $at, %hi(D_800E76C0)
    /* 85658 800FCBE8 00220821 */  addu       $at, $at, $v0
    /* 8565C 800FCBEC 93AF0037 */  lbu        $t7, 0x37($sp)
    /* 85660 800FCBF0 A02E76C0 */  sb         $t6, %lo(D_800E76C0)($at)
    /* 85664 800FCBF4 3C01800E */  lui        $at, %hi(D_800E7730)
    /* 85668 800FCBF8 00220821 */  addu       $at, $at, $v0
    /* 8566C 800FCBFC 93B8003B */  lbu        $t8, 0x3B($sp)
    /* 85670 800FCC00 A02F7730 */  sb         $t7, %lo(D_800E7730)($at)
    /* 85674 800FCC04 3C01800E */  lui        $at, %hi(D_800E77A0)
    /* 85678 800FCC08 00390821 */  addu       $at, $at, $t9
    /* 8567C 800FCC0C 93A8003F */  lbu        $t0, 0x3F($sp)
    /* 85680 800FCC10 A43877A0 */  sh         $t8, %lo(D_800E77A0)($at)
    /* 85684 800FCC14 3C01800E */  lui        $at, %hi(D_800E7880)
    /* 85688 800FCC18 93AA0043 */  lbu        $t2, 0x43($sp)
    /* 8568C 800FCC1C 00220821 */  addu       $at, $at, $v0
    /* 85690 800FCC20 A0287880 */  sb         $t0, %lo(D_800E7880)($at)
    /* 85694 800FCC24 93A90047 */  lbu        $t1, 0x47($sp)
    /* 85698 800FCC28 3C01800E */  lui        $at, %hi(D_800E78F0)
    /* 8569C 800FCC2C 00220821 */  addu       $at, $at, $v0
    /* 856A0 800FCC30 314B0002 */  andi       $t3, $t2, 0x2
    /* 856A4 800FCC34 11600006 */  beqz       $t3, .L800FCC50
    /* 856A8 800FCC38 A02978F0 */   sb        $t1, %lo(D_800E78F0)($at)
    /* 856AC 800FCC3C 00021880 */  sll        $v1, $v0, 2
    /* 856B0 800FCC40 3C01800F */  lui        $at, %hi(D_800E8AE0)
    /* 856B4 800FCC44 00230821 */  addu       $at, $at, $v1
    /* 856B8 800FCC48 10000005 */  b          .L800FCC60
    /* 856BC 800FCC4C AC2C8AE0 */   sw        $t4, %lo(D_800E8AE0)($at)
  .L800FCC50:
    /* 856C0 800FCC50 00021880 */  sll        $v1, $v0, 2
    /* 856C4 800FCC54 3C01800F */  lui        $at, %hi(D_800E8AE0)
    /* 856C8 800FCC58 00230821 */  addu       $at, $at, $v1
    /* 856CC 800FCC5C AC208AE0 */  sw         $zero, %lo(D_800E8AE0)($at)
  .L800FCC60:
    /* 856D0 800FCC60 8FA4004C */  lw         $a0, 0x4C($sp)
    /* 856D4 800FCC64 3C01800E */  lui        $at, %hi(gEntitiesNextPosXArray)
    /* 856D8 800FCC68 00230821 */  addu       $at, $at, $v1
    /* 856DC 800FCC6C C4840000 */  lwc1       $f4, 0x0($a0)
    /* 856E0 800FCC70 8FA50050 */  lw         $a1, 0x50($sp)
    /* 856E4 800FCC74 87AD004A */  lh         $t5, 0x4A($sp)
    /* 856E8 800FCC78 E42425D0 */  swc1       $f4, %lo(gEntitiesNextPosXArray)($at)
    /* 856EC 800FCC7C C4860004 */  lwc1       $f6, 0x4($a0)
    /* 856F0 800FCC80 3C01800E */  lui        $at, %hi(gEntitiesNextPosYArray)
    /* 856F4 800FCC84 00230821 */  addu       $at, $at, $v1
    /* 856F8 800FCC88 E4262790 */  swc1       $f6, %lo(gEntitiesNextPosYArray)($at)
    /* 856FC 800FCC8C C4880008 */  lwc1       $f8, 0x8($a0)
    /* 85700 800FCC90 3C01800E */  lui        $at, %hi(gEntitiesNextPosZArray)
    /* 85704 800FCC94 00230821 */  addu       $at, $at, $v1
    /* 85708 800FCC98 E4282950 */  swc1       $f8, %lo(gEntitiesNextPosZArray)($at)
    /* 8570C 800FCC9C C4AA0000 */  lwc1       $f10, 0x0($a1)
    /* 85710 800FCCA0 3C01800E */  lui        $at, %hi(gEntitiesAngleXArray)
    /* 85714 800FCCA4 00230821 */  addu       $at, $at, $v1
    /* 85718 800FCCA8 E42A4010 */  swc1       $f10, %lo(gEntitiesAngleXArray)($at)
    /* 8571C 800FCCAC C4B00004 */  lwc1       $f16, 0x4($a1)
    /* 85720 800FCCB0 3C01800E */  lui        $at, %hi(gEntitiesAngleYArray)
    /* 85724 800FCCB4 00230821 */  addu       $at, $at, $v1
    /* 85728 800FCCB8 E43041D0 */  swc1       $f16, %lo(gEntitiesAngleYArray)($at)
    /* 8572C 800FCCBC C4B20008 */  lwc1       $f18, 0x8($a1)
    /* 85730 800FCCC0 3C01800E */  lui        $at, %hi(gEntitiesAngleZArray)
    /* 85734 800FCCC4 00230821 */  addu       $at, $at, $v1
    /* 85738 800FCCC8 E4324390 */  swc1       $f18, %lo(gEntitiesAngleZArray)($at)
    /* 8573C 800FCCCC 8FAE0054 */  lw         $t6, 0x54($sp)
    /* 85740 800FCCD0 3C01800F */  lui        $at, %hi(D_800E9020 + 0x1C0)
    /* 85744 800FCCD4 00230821 */  addu       $at, $at, $v1
    /* 85748 800FCCD8 AC2D91E0 */  sw         $t5, %lo(D_800E9020 + 0x1C0)($at)
    /* 8574C 800FCCDC C5C00000 */  lwc1       $f0, 0x0($t6)
    /* 85750 800FCCE0 3C01800E */  lui        $at, %hi(gEntitiesScaleZArray)
    /* 85754 800FCCE4 00230821 */  addu       $at, $at, $v1
    /* 85758 800FCCE8 E42048D0 */  swc1       $f0, %lo(gEntitiesScaleZArray)($at)
    /* 8575C 800FCCEC 3C01800E */  lui        $at, %hi(gEntitiesScaleYArray)
    /* 85760 800FCCF0 00230821 */  addu       $at, $at, $v1
    /* 85764 800FCCF4 E4204710 */  swc1       $f0, %lo(gEntitiesScaleYArray)($at)
    /* 85768 800FCCF8 3C01800E */  lui        $at, %hi(gEntitiesScaleXArray)
    /* 8576C 800FCCFC 00230821 */  addu       $at, $at, $v1
    /* 85770 800FCD00 E4204550 */  swc1       $f0, %lo(gEntitiesScaleXArray)($at)
  .L800FCD04:
    /* 85774 800FCD04 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 85778 800FCD08 27BD0030 */  addiu      $sp, $sp, 0x30
    /* 8577C 800FCD0C 03E00008 */  jr         $ra
    /* 85780 800FCD10 00000000 */   nop
endlabel setUpDispose
.size setUpDispose, . - setUpDispose
