.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_801E2E20_ovl12, 0x4

dlabel D_801E2E20_ovl12
    /* 801E2E20 */ .space 0x04

nonmatching D_801E2E24_ovl12, 0xC

dlabel D_801E2E24_ovl12
    /* 801E2E24 */ .space 0x0C
