.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_801E2AA0_ovl12

dlabel D_801E2AA0_ovl12
    /* 1F2DE0 801E2AA0 00000000 */ .float 0
    /* 1F2DE4 801E2AA4 3E567750 */ .float 0.2094395161
    /* 1F2DE8 801E2AA8 3E0EFA35 */ .float 0.1396263391
    /* 1F2DEC 801E2AAC 3D567750 */ .float 0.05235987902
enddlabel D_801E2AA0_ovl12
.size D_801E2AA0_ovl12, . - D_801E2AA0_ovl12

nonmatching D_801E2AB0_ovl12

dlabel D_801E2AB0_ovl12
    /* 1F2DF0 801E2AB0 442F0000 */ .float 700
    /* 1F2DF4 801E2AB4 40C00000 */ .float 6
    /* 1F2DF8 801E2AB8 40A00000 */ .float 5
    /* 1F2DFC 801E2ABC 40800000 */ .float 4
enddlabel D_801E2AB0_ovl12
.size D_801E2AB0_ovl12, . - D_801E2AB0_ovl12

nonmatching D_801E2AC0_ovl12

dlabel D_801E2AC0_ovl12
    /* 1F2E00 801E2AC0 801DB2DC */ .word func_801DB2DC_ovl12
    /* 1F2E04 801E2AC4 801DD02C */ .word func_801DD02C_ovl12
    /* 1F2E08 801E2AC8 801DD96C */ .word func_801DD96C_ovl12
    /* 1F2E0C 801E2ACC 801DE41C */ .word func_801DE41C_ovl12
    /* 1F2E10 801E2AD0 801DFFF0 */ .word func_801DFFF0_ovl12
enddlabel D_801E2AC0_ovl12
.size D_801E2AC0_ovl12, . - D_801E2AC0_ovl12

nonmatching D_801E2AD4_ovl12

dlabel D_801E2AD4_ovl12
    /* 1F2E14 801E2AD4 801DB494 */ .word func_801DB494_ovl12
    /* 1F2E18 801E2AD8 801DB544 */ .word func_801DB544_ovl12
    /* 1F2E1C 801E2ADC 801DB6D8 */ .word func_801DB6D8_ovl12
    /* 1F2E20 801E2AE0 801DBA88 */ .word func_801DBA88_ovl12
    /* 1F2E24 801E2AE4 801DC4A8 */ .word func_801DC4A8_ovl12
    /* 1F2E28 801E2AE8 801DC750 */ .word func_801DC750_ovl12
enddlabel D_801E2AD4_ovl12
.size D_801E2AD4_ovl12, . - D_801E2AD4_ovl12

nonmatching D_801E2AEC_ovl12

dlabel D_801E2AEC_ovl12
    /* 1F2E2C 801E2AEC 801DB4D0 */ .word func_801DB4D0_ovl12
    /* 1F2E30 801E2AF0 801DB66C */ .word func_801DB66C_ovl12
    /* 1F2E34 801E2AF4 801DB910 */ .word func_801DB910_ovl12
    /* 1F2E38 801E2AF8 801DBC2C */ .word func_801DBC2C_ovl12
    /* 1F2E3C 801E2AFC 801DC5F4 */ .word func_801DC5F4_ovl12
    /* 1F2E40 801E2B00 801DC804 */ .word func_801DC804_ovl12
enddlabel D_801E2AEC_ovl12
.size D_801E2AEC_ovl12, . - D_801E2AEC_ovl12

nonmatching D_801E2B04_ovl12

dlabel D_801E2B04_ovl12
    /* 1F2E44 801E2B04 801DD158 */ .word func_801DD158_ovl12
    /* 1F2E48 801E2B08 801DD290 */ .word func_801DD290_ovl12
    /* 1F2E4C 801E2B0C 801DD3A8 */ .word func_801DD3A8_ovl12
    /* 1F2E50 801E2B10 801DD508 */ .word func_801DD508_ovl12
    /* 1F2E54 801E2B14 801DD5E4 */ .word func_801DD5E4_ovl12
    /* 1F2E58 801E2B18 801DD6BC */ .word func_801DD6BC_ovl12
    /* 1F2E5C 801E2B1C 801DD7CC */ .word func_801DD7CC_ovl12
enddlabel D_801E2B04_ovl12
.size D_801E2B04_ovl12, . - D_801E2B04_ovl12

nonmatching D_801E2B20_ovl12

dlabel D_801E2B20_ovl12
    /* 1F2E60 801E2B20 801DD1C8 */ .word func_801DD1C8_ovl12
    /* 1F2E64 801E2B24 801DD33C */ .word func_801DD33C_ovl12
    /* 1F2E68 801E2B28 801DD400 */ .word func_801DD400_ovl12
    /* 1F2E6C 801E2B2C 801DD56C */ .word func_801DD56C_ovl12
    /* 1F2E70 801E2B30 801DD63C */ .word func_801DD63C_ovl12
    /* 1F2E74 801E2B34 801DD74C */ .word func_801DD74C_ovl12
    /* 1F2E78 801E2B38 801DD8FC */ .word func_801DD8FC_ovl12
enddlabel D_801E2B20_ovl12
.size D_801E2B20_ovl12, . - D_801E2B20_ovl12

nonmatching D_801E2B3C_ovl12

dlabel D_801E2B3C_ovl12
    /* 1F2E7C 801E2B3C 801DDA78 */ .word func_801DDA78_ovl12
    /* 1F2E80 801E2B40 801DDBC4 */ .word func_801DDBC4_ovl12
    /* 1F2E84 801E2B44 801DDCDC */ .word func_801DDCDC_ovl12
    /* 1F2E88 801E2B48 801DDF38 */ .word func_801DDF38_ovl12
    /* 1F2E8C 801E2B4C 801DE16C */ .word func_801DE16C_ovl12
    /* 1F2E90 801E2B50 801DE27C */ .word func_801DE27C_ovl12
enddlabel D_801E2B3C_ovl12
.size D_801E2B3C_ovl12, . - D_801E2B3C_ovl12

nonmatching D_801E2B54_ovl12

dlabel D_801E2B54_ovl12
    /* 1F2E94 801E2B54 801DDAE8 */ .word func_801DDAE8_ovl12
    /* 1F2E98 801E2B58 801DDC70 */ .word func_801DDC70_ovl12
    /* 1F2E9C 801E2B5C 801DDDA8 */ .word func_801DDDA8_ovl12
    /* 1F2EA0 801E2B60 801DE0E4 */ .word func_801DE0E4_ovl12
    /* 1F2EA4 801E2B64 801DE1FC */ .word func_801DE1FC_ovl12
    /* 1F2EA8 801E2B68 801DE3AC */ .word func_801DE3AC_ovl12
enddlabel D_801E2B54_ovl12
.size D_801E2B54_ovl12, . - D_801E2B54_ovl12

nonmatching D_801E2B6C_ovl12

dlabel D_801E2B6C_ovl12
    /* 1F2EAC 801E2B6C 801DE528 */ .word func_801DE528_ovl12
    /* 1F2EB0 801E2B70 801DE678 */ .word func_801DE678_ovl12
    /* 1F2EB4 801E2B74 801DE790 */ .word func_801DE790_ovl12
    /* 1F2EB8 801E2B78 801DE8A8 */ .word func_801DE8A8_ovl12
    /* 1F2EBC 801E2B7C 801DE9C4 */ .word func_801DE9C4_ovl12
enddlabel D_801E2B6C_ovl12
.size D_801E2B6C_ovl12, . - D_801E2B6C_ovl12

nonmatching D_801E2B80_ovl12

dlabel D_801E2B80_ovl12
    /* 1F2EC0 801E2B80 801DE598 */ .word func_801DE598_ovl12
    /* 1F2EC4 801E2B84 801DE724 */ .word func_801DE724_ovl12
    /* 1F2EC8 801E2B88 801DE7E8 */ .word func_801DE7E8_ovl12
    /* 1F2ECC 801E2B8C 801DE944 */ .word func_801DE944_ovl12
    /* 1F2ED0 801E2B90 801DEAF4 */ .word func_801DEAF4_ovl12
enddlabel D_801E2B80_ovl12
.size D_801E2B80_ovl12, . - D_801E2B80_ovl12

nonmatching D_801E2B94_ovl12

dlabel D_801E2B94_ovl12
    /* 1F2ED4 801E2B94 99000000 */ .word 0x99000000
enddlabel D_801E2B94_ovl12
.size D_801E2B94_ovl12, . - D_801E2B94_ovl12

.align 2
nonmatching D_801E2B98_ovl12

dlabel D_801E2B98_ovl12
    /* 1F2ED8 801E2B98 */ .asciz "f"
    /* 66000000 */
.align 2
enddlabel D_801E2B98_ovl12
.size D_801E2B98_ovl12, . - D_801E2B98_ovl12

nonmatching D_801E2B9C_ovl12

dlabel D_801E2B9C_ovl12
    /* 1F2EDC 801E2B9C FF666600 */ .word 0xFF666600
enddlabel D_801E2B9C_ovl12
.size D_801E2B9C_ovl12, . - D_801E2B9C_ovl12

nonmatching D_801E2BA0_ovl12

dlabel D_801E2BA0_ovl12
    /* 1F2EE0 801E2BA0 7F191900 */ .word 0x7F191900
enddlabel D_801E2BA0_ovl12
.size D_801E2BA0_ovl12, . - D_801E2BA0_ovl12

nonmatching D_801E2BA4_ovl12

dlabel D_801E2BA4_ovl12
    /* 1F2EE4 801E2BA4 FF000000 */ .word 0xFF000000
enddlabel D_801E2BA4_ovl12
.size D_801E2BA4_ovl12, . - D_801E2BA4_ovl12

nonmatching D_801E2BA8_ovl12

dlabel D_801E2BA8_ovl12
    /* 1F2EE8 801E2BA8 7F000000 */ .word 0x7F000000
enddlabel D_801E2BA8_ovl12
.size D_801E2BA8_ovl12, . - D_801E2BA8_ovl12

nonmatching D_801E2BAC_ovl12

dlabel D_801E2BAC_ovl12
    /* 1F2EEC 801E2BAC 00990000 */ .word 0x00990000
enddlabel D_801E2BAC_ovl12
.size D_801E2BAC_ovl12, . - D_801E2BAC_ovl12

nonmatching D_801E2BB0_ovl12

dlabel D_801E2BB0_ovl12
    /* 1F2EF0 801E2BB0 00660000 */ .word 0x00660000
enddlabel D_801E2BB0_ovl12
.size D_801E2BB0_ovl12, . - D_801E2BB0_ovl12

nonmatching D_801E2BB4_ovl12

dlabel D_801E2BB4_ovl12
    /* 1F2EF4 801E2BB4 66FF6600 */ .word 0x66FF6600
enddlabel D_801E2BB4_ovl12
.size D_801E2BB4_ovl12, . - D_801E2BB4_ovl12

nonmatching D_801E2BB8_ovl12

dlabel D_801E2BB8_ovl12
    /* 1F2EF8 801E2BB8 197F1900 */ .word 0x197F1900
enddlabel D_801E2BB8_ovl12
.size D_801E2BB8_ovl12, . - D_801E2BB8_ovl12

nonmatching D_801E2BBC_ovl12

dlabel D_801E2BBC_ovl12
    /* 1F2EFC 801E2BBC 00FF0000 */ .word 0x00FF0000
enddlabel D_801E2BBC_ovl12
.size D_801E2BBC_ovl12, . - D_801E2BBC_ovl12

nonmatching D_801E2BC0_ovl12

dlabel D_801E2BC0_ovl12
    /* 1F2F00 801E2BC0 007F0000 */ .word 0x007F0000
enddlabel D_801E2BC0_ovl12
.size D_801E2BC0_ovl12, . - D_801E2BC0_ovl12

nonmatching D_801E2BC4_ovl12

dlabel D_801E2BC4_ovl12
    /* 1F2F04 801E2BC4 00009900 */ .word 0x00009900
enddlabel D_801E2BC4_ovl12
.size D_801E2BC4_ovl12, . - D_801E2BC4_ovl12

nonmatching D_801E2BC8_ovl12

dlabel D_801E2BC8_ovl12
    /* 1F2F08 801E2BC8 00006600 */ .word 0x00006600
enddlabel D_801E2BC8_ovl12
.size D_801E2BC8_ovl12, . - D_801E2BC8_ovl12

nonmatching D_801E2BCC_ovl12

dlabel D_801E2BCC_ovl12
    /* 1F2F0C 801E2BCC 6666FF00 */ .word 0x6666FF00
enddlabel D_801E2BCC_ovl12
.size D_801E2BCC_ovl12, . - D_801E2BCC_ovl12

nonmatching D_801E2BD0_ovl12

dlabel D_801E2BD0_ovl12
    /* 1F2F10 801E2BD0 19197F00 */ .word 0x19197F00
enddlabel D_801E2BD0_ovl12
.size D_801E2BD0_ovl12, . - D_801E2BD0_ovl12

nonmatching D_801E2BD4_ovl12

dlabel D_801E2BD4_ovl12
    /* 1F2F14 801E2BD4 0000FF00 */ .word 0x0000FF00
enddlabel D_801E2BD4_ovl12
.size D_801E2BD4_ovl12, . - D_801E2BD4_ovl12

nonmatching D_801E2BD8_ovl12

dlabel D_801E2BD8_ovl12
    /* 1F2F18 801E2BD8 00007F00 */ .word 0x00007F00
enddlabel D_801E2BD8_ovl12
.size D_801E2BD8_ovl12, . - D_801E2BD8_ovl12

nonmatching D_801E2BDC_ovl12

dlabel D_801E2BDC_ovl12
    /* 1F2F1C 801E2BDC 801E2BA4 */ .word D_801E2BA4_ovl12
    /* 1F2F20 801E2BE0 801E2B94 */ .word D_801E2B94_ovl12
    /* 1F2F24 801E2BE4 801E2B9C */ .word D_801E2B9C_ovl12
    /* 1F2F28 801E2BE8 801E2BBC */ .word D_801E2BBC_ovl12
    /* 1F2F2C 801E2BEC 801E2BAC */ .word D_801E2BAC_ovl12
    /* 1F2F30 801E2BF0 801E2BB4 */ .word D_801E2BB4_ovl12
    /* 1F2F34 801E2BF4 801E2BD4 */ .word D_801E2BD4_ovl12
    /* 1F2F38 801E2BF8 801E2BC4 */ .word D_801E2BC4_ovl12
    /* 1F2F3C 801E2BFC 801E2BCC */ .word D_801E2BCC_ovl12
enddlabel D_801E2BDC_ovl12
.size D_801E2BDC_ovl12, . - D_801E2BDC_ovl12

nonmatching D_801E2C00_ovl12

dlabel D_801E2C00_ovl12
    /* 1F2F40 801E2C00 801E2BA8 */ .word D_801E2BA8_ovl12
    /* 1F2F44 801E2C04 801E2B98 */ .word D_801E2B98_ovl12
    /* 1F2F48 801E2C08 801E2BA0 */ .word D_801E2BA0_ovl12
    /* 1F2F4C 801E2C0C 801E2BC0 */ .word D_801E2BC0_ovl12
    /* 1F2F50 801E2C10 801E2BB0 */ .word D_801E2BB0_ovl12
    /* 1F2F54 801E2C14 801E2BB8 */ .word D_801E2BB8_ovl12
    /* 1F2F58 801E2C18 801E2BD8 */ .word D_801E2BD8_ovl12
    /* 1F2F5C 801E2C1C 801E2BC8 */ .word D_801E2BC8_ovl12
    /* 1F2F60 801E2C20 801E2BD0 */ .word D_801E2BD0_ovl12
enddlabel D_801E2C00_ovl12
.size D_801E2C00_ovl12, . - D_801E2C00_ovl12

nonmatching D_801E2C24_ovl12

dlabel D_801E2C24_ovl12
    /* 1F2F64 801E2C24 00000000 */ .word 0x00000000
enddlabel D_801E2C24_ovl12
.size D_801E2C24_ovl12, . - D_801E2C24_ovl12

nonmatching D_801E2C28_ovl12

dlabel D_801E2C28_ovl12
    /* 1F2F68 801E2C28 00000000 */ .word 0x00000000
enddlabel D_801E2C28_ovl12
.size D_801E2C28_ovl12, . - D_801E2C28_ovl12

nonmatching D_801E2C2C_ovl12

dlabel D_801E2C2C_ovl12
    /* 1F2F6C 801E2C2C FFFFFF00 */ .word 0xFFFFFF00
enddlabel D_801E2C2C_ovl12
.size D_801E2C2C_ovl12, . - D_801E2C2C_ovl12

nonmatching D_801E2C30_ovl12

dlabel D_801E2C30_ovl12
    /* 1F2F70 801E2C30 7F7F7F00 */ .word 0x7F7F7F00
enddlabel D_801E2C30_ovl12
.size D_801E2C30_ovl12, . - D_801E2C30_ovl12

nonmatching D_801E2C34_ovl12

dlabel D_801E2C34_ovl12
    /* 1F2F74 801E2C34 00000000 */ .word 0x00000000
enddlabel D_801E2C34_ovl12
.size D_801E2C34_ovl12, . - D_801E2C34_ovl12

nonmatching D_801E2C38_ovl12

dlabel D_801E2C38_ovl12
    /* 1F2F78 801E2C38 00000000 */ .word 0x00000000
enddlabel D_801E2C38_ovl12
.size D_801E2C38_ovl12, . - D_801E2C38_ovl12

nonmatching D_801E2C3C_ovl12

dlabel D_801E2C3C_ovl12
    /* 1F2F7C 801E2C3C FFFFFF00 */ .word 0xFFFFFF00
enddlabel D_801E2C3C_ovl12
.size D_801E2C3C_ovl12, . - D_801E2C3C_ovl12

nonmatching D_801E2C40_ovl12

dlabel D_801E2C40_ovl12
    /* 1F2F80 801E2C40 7F7F7F00 */ .word 0x7F7F7F00
enddlabel D_801E2C40_ovl12
.size D_801E2C40_ovl12, . - D_801E2C40_ovl12

nonmatching D_801E2C44_ovl12

dlabel D_801E2C44_ovl12
    /* 1F2F84 801E2C44 00000000 */ .word 0x00000000
enddlabel D_801E2C44_ovl12
.size D_801E2C44_ovl12, . - D_801E2C44_ovl12

nonmatching D_801E2C48_ovl12

dlabel D_801E2C48_ovl12
    /* 1F2F88 801E2C48 00000000 */ .word 0x00000000
enddlabel D_801E2C48_ovl12
.size D_801E2C48_ovl12, . - D_801E2C48_ovl12

nonmatching D_801E2C4C_ovl12

dlabel D_801E2C4C_ovl12
    /* 1F2F8C 801E2C4C FFFFFF00 */ .word 0xFFFFFF00
enddlabel D_801E2C4C_ovl12
.size D_801E2C4C_ovl12, . - D_801E2C4C_ovl12

nonmatching D_801E2C50_ovl12

dlabel D_801E2C50_ovl12
    /* 1F2F90 801E2C50 7F7F7F00 */ .word 0x7F7F7F00
enddlabel D_801E2C50_ovl12
.size D_801E2C50_ovl12, . - D_801E2C50_ovl12

nonmatching D_801E2C54_ovl12

dlabel D_801E2C54_ovl12
    /* 1F2F94 801E2C54 801E2BA4 */ .word D_801E2BA4_ovl12
    /* 1F2F98 801E2C58 801E2C24 */ .word D_801E2C24_ovl12
    /* 1F2F9C 801E2C5C 801E2C2C */ .word D_801E2C2C_ovl12
    /* 1F2FA0 801E2C60 801E2BBC */ .word D_801E2BBC_ovl12
    /* 1F2FA4 801E2C64 801E2C34 */ .word D_801E2C34_ovl12
    /* 1F2FA8 801E2C68 801E2C3C */ .word D_801E2C3C_ovl12
    /* 1F2FAC 801E2C6C 801E2BD4 */ .word D_801E2BD4_ovl12
    /* 1F2FB0 801E2C70 801E2C44 */ .word D_801E2C44_ovl12
    /* 1F2FB4 801E2C74 801E2C4C */ .word D_801E2C4C_ovl12
enddlabel D_801E2C54_ovl12
.size D_801E2C54_ovl12, . - D_801E2C54_ovl12

nonmatching D_801E2C78_ovl12

dlabel D_801E2C78_ovl12
    /* 1F2FB8 801E2C78 801E2BA8 */ .word D_801E2BA8_ovl12
    /* 1F2FBC 801E2C7C 801E2C28 */ .word D_801E2C28_ovl12
    /* 1F2FC0 801E2C80 801E2C30 */ .word D_801E2C30_ovl12
    /* 1F2FC4 801E2C84 801E2BC0 */ .word D_801E2BC0_ovl12
    /* 1F2FC8 801E2C88 801E2C38 */ .word D_801E2C38_ovl12
    /* 1F2FCC 801E2C8C 801E2C40 */ .word D_801E2C40_ovl12
    /* 1F2FD0 801E2C90 801E2BD8 */ .word D_801E2BD8_ovl12
    /* 1F2FD4 801E2C94 801E2C48 */ .word D_801E2C48_ovl12
    /* 1F2FD8 801E2C98 801E2C50 */ .word D_801E2C50_ovl12
enddlabel D_801E2C78_ovl12
.size D_801E2C78_ovl12, . - D_801E2C78_ovl12

nonmatching D_801E2C9C_ovl12

dlabel D_801E2C9C_ovl12
    /* 1F2FDC 801E2C9C 801E016C */ .word func_801E016C_ovl12
    /* 1F2FE0 801E2CA0 801E03B0 */ .word func_801E03B0_ovl12
    /* 1F2FE4 801E2CA4 801E0714 */ .word func_801E0714_ovl12
    /* 1F2FE8 801E2CA8 801E0D24 */ .word func_801E0D24_ovl12
    /* 1F2FEC 801E2CAC 801E11CC */ .word func_801E11CC_ovl12
    /* 1F2FF0 801E2CB0 801E0938 */ .word func_801E0938_ovl12
    /* 1F2FF4 801E2CB4 801E0B58 */ .word func_801E0B58_ovl12
    /* 1F2FF8 801E2CB8 801E0DF8 */ .word func_801E0DF8_ovl12
    /* 1F2FFC 801E2CBC 801E10C4 */ .word func_801E10C4_ovl12
    /* 1F3000 801E2CC0 801E12D0 */ .word func_801E12D0_ovl12
enddlabel D_801E2C9C_ovl12
.size D_801E2C9C_ovl12, . - D_801E2C9C_ovl12

nonmatching D_801E2CC4_ovl12

dlabel D_801E2CC4_ovl12
    /* 1F3004 801E2CC4 801E0298 */ .word func_801E0298_ovl12
    /* 1F3008 801E2CC8 801E05E8 */ .word func_801E05E8_ovl12
    /* 1F300C 801E2CCC 801E0824 */ .word func_801E0824_ovl12
    /* 1F3010 801E2CD0 801E0D64 */ .word func_801E0D64_ovl12
    /* 1F3014 801E2CD4 801E123C */ .word func_801E123C_ovl12
    /* 1F3018 801E2CD8 801E0A70 */ .word func_801E0A70_ovl12
    /* 1F301C 801E2CDC 801E0C54 */ .word func_801E0C54_ovl12
    /* 1F3020 801E2CE0 801E0FC8 */ .word func_801E0FC8_ovl12
    /* 1F3024 801E2CE4 801E1124 */ .word func_801E1124_ovl12
    /* 1F3028 801E2CE8 801E1500 */ .word func_801E1500_ovl12
    /* 1F302C 801E2CEC 00000000 */ .word 0x00000000
enddlabel D_801E2CC4_ovl12
.size D_801E2CC4_ovl12, . - D_801E2CC4_ovl12

nonmatching D_801E2CF0_ovl12

dlabel D_801E2CF0_ovl12
    /* 1F3030 801E2CF0 801E1B90 */ .word func_801E1B90_ovl12
    /* 1F3034 801E2CF4 801E1890 */ .word func_801E1890_ovl12
enddlabel D_801E2CF0_ovl12
.size D_801E2CF0_ovl12, . - D_801E2CF0_ovl12

nonmatching D_801E2CF8_ovl12

dlabel D_801E2CF8_ovl12
    /* 1F3038 801E2CF8 801E1CD4 */ .word func_801E1CD4_ovl12
    /* 1F303C 801E2CFC 801E1A60 */ .word func_801E1A60_ovl12
enddlabel D_801E2CF8_ovl12
.size D_801E2CF8_ovl12, . - D_801E2CF8_ovl12

nonmatching D_801E2D00_ovl12

dlabel D_801E2D00_ovl12
    /* 1F3040 801E2D00 801E23A0 */ .word func_801E23A0_ovl12
    /* 1F3044 801E2D04 801E2298 */ .word func_801E2298_ovl12
    /* 1F3048 801E2D08 801E2494 */ .word func_801E2494_ovl12
enddlabel D_801E2D00_ovl12
.size D_801E2D00_ovl12, . - D_801E2D00_ovl12

nonmatching D_801E2D0C_ovl12

dlabel D_801E2D0C_ovl12
    /* 1F304C 801E2D0C 801E23F8 */ .word func_801E23F8_ovl12
    /* 1F3050 801E2D10 801E22D8 */ .word func_801E22D8_ovl12
    /* 1F3054 801E2D14 801E2528 */ .word func_801E2528_ovl12
    /* 1F3058 801E2D18 00000000 */ .word 0x00000000
    /* 1F305C 801E2D1C 00000000 */ .word 0x00000000
enddlabel D_801E2D0C_ovl12
.size D_801E2D0C_ovl12, . - D_801E2D0C_ovl12
