.section .late_rodata
nonmatching jtbl_80128F60

dlabel jtbl_80128F60
    /* B19D0 80128F60 8011F2E0 */ .word .L8011F2E0
    /* B19D4 80128F64 8011F388 */ .word .L8011F388
    /* B19D8 80128F68 8011EDD4 */ .word .L8011EDD4
    /* B19DC 80128F6C 8011EDD4 */ .word .L8011EDD4
    /* B19E0 80128F70 8011F388 */ .word .L8011F388
    /* B19E4 80128F74 8011F388 */ .word .L8011F388
    /* B19E8 80128F78 8011EDD4 */ .word .L8011EDD4
    /* B19EC 80128F7C 8011F234 */ .word .L8011F234
    /* B19F0 80128F80 8011F388 */ .word .L8011F388
    /* B19F4 80128F84 8011F388 */ .word .L8011F388
    /* B19F8 80128F88 8011F388 */ .word .L8011F388
    /* B19FC 80128F8C 8011EDD4 */ .word .L8011EDD4
    /* B1A00 80128F90 8011F388 */ .word .L8011F388
    /* B1A04 80128F94 8011F388 */ .word .L8011F388
    /* B1A08 80128F98 8011F388 */ .word .L8011F388
    /* B1A0C 80128F9C 8011EFC0 */ .word .L8011EFC0
    /* B1A10 80128FA0 8011F388 */ .word .L8011F388
    /* B1A14 80128FA4 8011F388 */ .word .L8011F388
    /* B1A18 80128FA8 8011F388 */ .word .L8011F388
    /* B1A1C 80128FAC 8011F388 */ .word .L8011F388
    /* B1A20 80128FB0 8011EE60 */ .word .L8011EE60
    /* B1A24 80128FB4 8011F388 */ .word .L8011F388
    /* B1A28 80128FB8 8011F388 */ .word .L8011F388
    /* B1A2C 80128FBC 8011F18C */ .word .L8011F18C
    /* B1A30 80128FC0 8011F388 */ .word .L8011F388
    /* B1A34 80128FC4 8011F388 */ .word .L8011F388
    /* B1A38 80128FC8 8011F388 */ .word .L8011F388
    /* B1A3C 80128FCC 8011F388 */ .word .L8011F388
    /* B1A40 80128FD0 8011F388 */ .word .L8011F388
    /* B1A44 80128FD4 8011F388 */ .word .L8011F388
    /* B1A48 80128FD8 8011F388 */ .word .L8011F388
    /* B1A4C 80128FDC 8011F234 */ .word .L8011F234
    /* B1A50 80128FE0 8011F0F4 */ .word .L8011F0F4
    /* B1A54 80128FE4 8011EDD4 */ .word .L8011EDD4
    /* B1A58 80128FE8 8011F18C */ .word .L8011F18C
enddlabel jtbl_80128F60
.size jtbl_80128F60, . - jtbl_80128F60

nonmatching jtbl_80128FEC

dlabel jtbl_80128FEC
    /* B1A5C 80128FEC 8011EEA0 */ .word .L8011EEA0
    /* B1A60 80128FF0 8011F680 */ .word .L8011F680
    /* B1A64 80128FF4 8011EF18 */ .word .L8011EF18
    /* B1A68 80128FF8 8011EEA0 */ .word .L8011EEA0
    /* B1A6C 80128FFC 8011EF18 */ .word .L8011EF18
    /* B1A70 80129000 8011EF70 */ .word .L8011EF70
enddlabel jtbl_80128FEC
.size jtbl_80128FEC, . - jtbl_80128FEC

nonmatching D_80129004

dlabel D_80129004
    /* B1A74 80129004 3FCCCCCD */ .float 1.600000024
enddlabel D_80129004
.size D_80129004, . - D_80129004

nonmatching D_80129008

dlabel D_80129008
    /* B1A78 80129008 3F4CCCCD */ .float 0.8000000119
enddlabel D_80129008
.size D_80129008, . - D_80129008

nonmatching D_8012900C

dlabel D_8012900C
    /* B1A7C 8012900C 3F4CCCCD */ .float 0.8000000119
enddlabel D_8012900C
.size D_8012900C, . - D_8012900C

nonmatching D_80129010

dlabel D_80129010
    /* B1A80 80129010 3F4CCCCD */ .float 0.8000000119
enddlabel D_80129010
.size D_80129010, . - D_80129010

nonmatching D_80129014

dlabel D_80129014
    /* B1A84 80129014 3FCCCCCD */ .float 1.600000024
enddlabel D_80129014
.size D_80129014, . - D_80129014


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8011ED68, 0x928

glabel func_8011ED68
    /* A77D8 8011ED68 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* A77DC 8011ED6C AFBF0014 */  sw         $ra, 0x14($sp)
    /* A77E0 8011ED70 0C0482BE */  jal        func_80120AF8
    /* A77E4 8011ED74 27A4002C */   addiu     $a0, $sp, 0x2C
    /* A77E8 8011ED78 3C07800D */  lui        $a3, %hi(gKirbyController)
    /* A77EC 8011ED7C 94E76FE8 */  lhu        $a3, %lo(gKirbyController)($a3)
    /* A77F0 8011ED80 3C048013 */  lui        $a0, %hi(gKirbyState)
    /* A77F4 8011ED84 2484E7C0 */  addiu      $a0, $a0, %lo(gKirbyState)
    /* A77F8 8011ED88 30EE0300 */  andi       $t6, $a3, 0x300
    /* A77FC 8011ED8C 11C001FF */  beqz       $t6, .L8011F58C
    /* A7800 8011ED90 00000000 */   nop
    /* A7804 8011ED94 908F0017 */  lbu        $t7, 0x17($a0)
    /* A7808 8011ED98 3C18800D */  lui        $t8, %hi(D_800D6F58 + 0x54)
    /* A780C 8011ED9C 15E001FB */  bnez       $t7, .L8011F58C
    /* A7810 8011EDA0 00000000 */   nop
    /* A7814 8011EDA4 8F186FAC */  lw         $t8, %lo(D_800D6F58 + 0x54)($t8)
    /* A7818 8011EDA8 170001F8 */  bnez       $t8, .L8011F58C
    /* A781C 8011EDAC 00000000 */   nop
    /* A7820 8011EDB0 8C9900A0 */  lw         $t9, 0xA0($a0)
    /* A7824 8011EDB4 2F210023 */  sltiu      $at, $t9, 0x23
    /* A7828 8011EDB8 10200173 */  beqz       $at, .L8011F388
    /* A782C 8011EDBC 0019C880 */   sll       $t9, $t9, 2
    /* A7830 8011EDC0 3C018013 */  lui        $at, %hi(jtbl_80128F60)
    /* A7834 8011EDC4 00390821 */  addu       $at, $at, $t9
    /* A7838 8011EDC8 8C398F60 */  lw         $t9, %lo(jtbl_80128F60)($at)
    /* A783C 8011EDCC 03200008 */  jr         $t9
    /* A7840 8011EDD0 00000000 */   nop
  .L8011EDD4:
    /* A7844 8011EDD4 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7848 8011EDD8 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A784C 8011EDDC 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7850 8011EDE0 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7854 8011EDE4 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7858 8011EDE8 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A785C 8011EDEC C7A60030 */  lwc1       $f6, 0x30($sp)
    /* A7860 8011EDF0 00052880 */  sll        $a1, $a1, 2
    /* A7864 8011EDF4 00651821 */  addu       $v1, $v1, $a1
    /* A7868 8011EDF8 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A786C 8011EDFC 30630006 */  andi       $v1, $v1, 0x6
    /* A7870 8011EE00 54600008 */  bnel       $v1, $zero, .L8011EE24
    /* A7874 8011EE04 44814000 */   mtc1      $at, $f8
    /* A7878 8011EE08 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A787C 8011EE0C 44812000 */  mtc1       $at, $f4
    /* A7880 8011EE10 00000000 */  nop
    /* A7884 8011EE14 46062082 */  mul.s      $f2, $f4, $f6
    /* A7888 8011EE18 10000008 */  b          .L8011EE3C
    /* A788C 8011EE1C 00000000 */   nop
    /* A7890 8011EE20 44814000 */  mtc1       $at, $f8
  .L8011EE24:
    /* A7894 8011EE24 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7898 8011EE28 44819000 */  mtc1       $at, $f18
    /* A789C 8011EE2C 460A4402 */  mul.s      $f16, $f8, $f10
    /* A78A0 8011EE30 00000000 */  nop
    /* A78A4 8011EE34 46128082 */  mul.s      $f2, $f16, $f18
    /* A78A8 8011EE38 00000000 */  nop
  .L8011EE3C:
    /* A78AC 8011EE3C 14600005 */  bnez       $v1, .L8011EE54
    /* A78B0 8011EE40 3C013F80 */   lui       $at, (0x3F800000 >> 16)
    /* A78B4 8011EE44 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* A78B8 8011EE48 44810000 */  mtc1       $at, $f0
    /* A78BC 8011EE4C 100001A4 */  b          .L8011F4E0
    /* A78C0 8011EE50 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EE54:
    /* A78C4 8011EE54 44810000 */  mtc1       $at, $f0
    /* A78C8 8011EE58 100001A1 */  b          .L8011F4E0
    /* A78CC 8011EE5C 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EE60:
    /* A78D0 8011EE60 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A78D4 8011EE64 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A78D8 8011EE68 3C08800F */  lui        $t0, %hi(D_800E98E0)
    /* A78DC 8011EE6C 8CC50000 */  lw         $a1, 0x0($a2)
    /* A78E0 8011EE70 00052880 */  sll        $a1, $a1, 2
    /* A78E4 8011EE74 01054021 */  addu       $t0, $t0, $a1
    /* A78E8 8011EE78 8D0898E0 */  lw         $t0, %lo(D_800E98E0)($t0)
    /* A78EC 8011EE7C 2509FFFE */  addiu      $t1, $t0, -0x2
    /* A78F0 8011EE80 2D210006 */  sltiu      $at, $t1, 0x6
    /* A78F4 8011EE84 10200006 */  beqz       $at, .L8011EEA0
    /* A78F8 8011EE88 00094880 */   sll       $t1, $t1, 2
    /* A78FC 8011EE8C 3C018013 */  lui        $at, %hi(jtbl_80128FEC)
    /* A7900 8011EE90 00290821 */  addu       $at, $at, $t1
    /* A7904 8011EE94 8C298FEC */  lw         $t1, %lo(jtbl_80128FEC)($at)
    /* A7908 8011EE98 01200008 */  jr         $t1
    /* A790C 8011EE9C 00000000 */   nop
  .L8011EEA0:
    /* A7910 8011EEA0 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7914 8011EEA4 00651821 */  addu       $v1, $v1, $a1
    /* A7918 8011EEA8 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A791C 8011EEAC 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7920 8011EEB0 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7924 8011EEB4 30630006 */  andi       $v1, $v1, 0x6
    /* A7928 8011EEB8 14600007 */  bnez       $v1, .L8011EED8
    /* A792C 8011EEBC C7A60030 */   lwc1      $f6, 0x30($sp)
    /* A7930 8011EEC0 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7934 8011EEC4 44812000 */  mtc1       $at, $f4
    /* A7938 8011EEC8 00000000 */  nop
    /* A793C 8011EECC 46062082 */  mul.s      $f2, $f4, $f6
    /* A7940 8011EED0 10000008 */  b          .L8011EEF4
    /* A7944 8011EED4 00000000 */   nop
  .L8011EED8:
    /* A7948 8011EED8 44814000 */  mtc1       $at, $f8
    /* A794C 8011EEDC 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7950 8011EEE0 44819000 */  mtc1       $at, $f18
    /* A7954 8011EEE4 460A4402 */  mul.s      $f16, $f8, $f10
    /* A7958 8011EEE8 00000000 */  nop
    /* A795C 8011EEEC 46128082 */  mul.s      $f2, $f16, $f18
    /* A7960 8011EEF0 00000000 */  nop
  .L8011EEF4:
    /* A7964 8011EEF4 14600005 */  bnez       $v1, .L8011EF0C
    /* A7968 8011EEF8 3C013F80 */   lui       $at, (0x3F800000 >> 16)
    /* A796C 8011EEFC 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* A7970 8011EF00 44810000 */  mtc1       $at, $f0
    /* A7974 8011EF04 10000176 */  b          .L8011F4E0
    /* A7978 8011EF08 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EF0C:
    /* A797C 8011EF0C 44810000 */  mtc1       $at, $f0
    /* A7980 8011EF10 10000173 */  b          .L8011F4E0
    /* A7984 8011EF14 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EF18:
    /* A7988 8011EF18 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A798C 8011EF1C 00651821 */  addu       $v1, $v1, $a1
    /* A7990 8011EF20 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7994 8011EF24 3C013E00 */  lui        $at, (0x3E000000 >> 16)
    /* A7998 8011EF28 30630006 */  andi       $v1, $v1, 0x6
    /* A799C 8011EF2C 54600006 */  bnel       $v1, $zero, .L8011EF48
    /* A79A0 8011EF30 44811000 */   mtc1      $at, $f2
    /* A79A4 8011EF34 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A79A8 8011EF38 44811000 */  mtc1       $at, $f2
    /* A79AC 8011EF3C 10000003 */  b          .L8011EF4C
    /* A79B0 8011EF40 00000000 */   nop
    /* A79B4 8011EF44 44811000 */  mtc1       $at, $f2
  .L8011EF48:
    /* A79B8 8011EF48 00000000 */  nop
  .L8011EF4C:
    /* A79BC 8011EF4C 14600005 */  bnez       $v1, .L8011EF64
    /* A79C0 8011EF50 3C013F80 */   lui       $at, (0x3F800000 >> 16)
    /* A79C4 8011EF54 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* A79C8 8011EF58 44810000 */  mtc1       $at, $f0
    /* A79CC 8011EF5C 10000160 */  b          .L8011F4E0
    /* A79D0 8011EF60 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EF64:
    /* A79D4 8011EF64 44810000 */  mtc1       $at, $f0
    /* A79D8 8011EF68 1000015D */  b          .L8011F4E0
    /* A79DC 8011EF6C 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EF70:
    /* A79E0 8011EF70 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A79E4 8011EF74 00651821 */  addu       $v1, $v1, $a1
    /* A79E8 8011EF78 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A79EC 8011EF7C 3C018013 */  lui        $at, %hi(D_80129008)
    /* A79F0 8011EF80 30630006 */  andi       $v1, $v1, 0x6
    /* A79F4 8011EF84 14600004 */  bnez       $v1, .L8011EF98
    /* A79F8 8011EF88 00000000 */   nop
    /* A79FC 8011EF8C 3C018013 */  lui        $at, %hi(D_80129004)
    /* A7A00 8011EF90 10000002 */  b          .L8011EF9C
    /* A7A04 8011EF94 C4229004 */   lwc1      $f2, %lo(D_80129004)($at)
  .L8011EF98:
    /* A7A08 8011EF98 C4229008 */  lwc1       $f2, %lo(D_80129008)($at)
  .L8011EF9C:
    /* A7A0C 8011EF9C 14600005 */  bnez       $v1, .L8011EFB4
    /* A7A10 8011EFA0 3C014040 */   lui       $at, (0x40400000 >> 16)
    /* A7A14 8011EFA4 3C0140C0 */  lui        $at, (0x40C00000 >> 16)
    /* A7A18 8011EFA8 44810000 */  mtc1       $at, $f0
    /* A7A1C 8011EFAC 1000014C */  b          .L8011F4E0
    /* A7A20 8011EFB0 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EFB4:
    /* A7A24 8011EFB4 44810000 */  mtc1       $at, $f0
    /* A7A28 8011EFB8 10000149 */  b          .L8011F4E0
    /* A7A2C 8011EFBC 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011EFC0:
    /* A7A30 8011EFC0 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* A7A34 8011EFC4 44812000 */  mtc1       $at, $f4
    /* A7A38 8011EFC8 C4860038 */  lwc1       $f6, 0x38($a0)
    /* A7A3C 8011EFCC 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7A40 8011EFD0 46062032 */  c.eq.s     $f4, $f6
    /* A7A44 8011EFD4 00000000 */  nop
    /* A7A48 8011EFD8 45000024 */  bc1f       .L8011F06C
    /* A7A4C 8011EFDC 00000000 */   nop
    /* A7A50 8011EFE0 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7A54 8011EFE4 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7A58 8011EFE8 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7A5C 8011EFEC 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7A60 8011EFF0 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7A64 8011EFF4 C7B20030 */  lwc1       $f18, 0x30($sp)
    /* A7A68 8011EFF8 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7A6C 8011EFFC 00052880 */  sll        $a1, $a1, 2
    /* A7A70 8011F000 00651821 */  addu       $v1, $v1, $a1
    /* A7A74 8011F004 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7A78 8011F008 30630006 */  andi       $v1, $v1, 0x6
    /* A7A7C 8011F00C 54600008 */  bnel       $v1, $zero, .L8011F030
    /* A7A80 8011F010 44818000 */   mtc1      $at, $f16
    /* A7A84 8011F014 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7A88 8011F018 44814000 */  mtc1       $at, $f8
    /* A7A8C 8011F01C 00000000 */  nop
    /* A7A90 8011F020 460A4082 */  mul.s      $f2, $f8, $f10
    /* A7A94 8011F024 10000008 */  b          .L8011F048
    /* A7A98 8011F028 00000000 */   nop
    /* A7A9C 8011F02C 44818000 */  mtc1       $at, $f16
  .L8011F030:
    /* A7AA0 8011F030 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7AA4 8011F034 44813000 */  mtc1       $at, $f6
    /* A7AA8 8011F038 46128102 */  mul.s      $f4, $f16, $f18
    /* A7AAC 8011F03C 00000000 */  nop
    /* A7AB0 8011F040 46062082 */  mul.s      $f2, $f4, $f6
    /* A7AB4 8011F044 00000000 */  nop
  .L8011F048:
    /* A7AB8 8011F048 14600005 */  bnez       $v1, .L8011F060
    /* A7ABC 8011F04C 3C013F80 */   lui       $at, (0x3F800000 >> 16)
    /* A7AC0 8011F050 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* A7AC4 8011F054 44810000 */  mtc1       $at, $f0
    /* A7AC8 8011F058 10000121 */  b          .L8011F4E0
    /* A7ACC 8011F05C 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F060:
    /* A7AD0 8011F060 44810000 */  mtc1       $at, $f0
    /* A7AD4 8011F064 1000011E */  b          .L8011F4E0
    /* A7AD8 8011F068 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F06C:
    /* A7ADC 8011F06C 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7AE0 8011F070 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7AE4 8011F074 3C013F20 */  lui        $at, (0x3F200000 >> 16)
    /* A7AE8 8011F078 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7AEC 8011F07C C7B20030 */  lwc1       $f18, 0x30($sp)
    /* A7AF0 8011F080 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7AF4 8011F084 00052880 */  sll        $a1, $a1, 2
    /* A7AF8 8011F088 00651821 */  addu       $v1, $v1, $a1
    /* A7AFC 8011F08C 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7B00 8011F090 30630006 */  andi       $v1, $v1, 0x6
    /* A7B04 8011F094 54600008 */  bnel       $v1, $zero, .L8011F0B8
    /* A7B08 8011F098 44818000 */   mtc1      $at, $f16
    /* A7B0C 8011F09C 3C013F20 */  lui        $at, (0x3F200000 >> 16)
    /* A7B10 8011F0A0 44814000 */  mtc1       $at, $f8
    /* A7B14 8011F0A4 00000000 */  nop
    /* A7B18 8011F0A8 460A4082 */  mul.s      $f2, $f8, $f10
    /* A7B1C 8011F0AC 10000008 */  b          .L8011F0D0
    /* A7B20 8011F0B0 00000000 */   nop
    /* A7B24 8011F0B4 44818000 */  mtc1       $at, $f16
  .L8011F0B8:
    /* A7B28 8011F0B8 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7B2C 8011F0BC 44813000 */  mtc1       $at, $f6
    /* A7B30 8011F0C0 46128102 */  mul.s      $f4, $f16, $f18
    /* A7B34 8011F0C4 00000000 */  nop
    /* A7B38 8011F0C8 46062082 */  mul.s      $f2, $f4, $f6
    /* A7B3C 8011F0CC 00000000 */  nop
  .L8011F0D0:
    /* A7B40 8011F0D0 14600005 */  bnez       $v1, .L8011F0E8
    /* A7B44 8011F0D4 3C014020 */   lui       $at, (0x40200000 >> 16)
    /* A7B48 8011F0D8 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* A7B4C 8011F0DC 44810000 */  mtc1       $at, $f0
    /* A7B50 8011F0E0 100000FF */  b          .L8011F4E0
    /* A7B54 8011F0E4 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F0E8:
    /* A7B58 8011F0E8 44810000 */  mtc1       $at, $f0
    /* A7B5C 8011F0EC 100000FC */  b          .L8011F4E0
    /* A7B60 8011F0F0 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F0F4:
    /* A7B64 8011F0F4 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7B68 8011F0F8 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7B6C 8011F0FC 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7B70 8011F100 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7B74 8011F104 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7B78 8011F108 C7B20030 */  lwc1       $f18, 0x30($sp)
    /* A7B7C 8011F10C C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7B80 8011F110 00052880 */  sll        $a1, $a1, 2
    /* A7B84 8011F114 00651821 */  addu       $v1, $v1, $a1
    /* A7B88 8011F118 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7B8C 8011F11C C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7B90 8011F120 30630006 */  andi       $v1, $v1, 0x6
    /* A7B94 8011F124 54600008 */  bnel       $v1, $zero, .L8011F148
    /* A7B98 8011F128 44818000 */   mtc1      $at, $f16
    /* A7B9C 8011F12C 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7BA0 8011F130 44814000 */  mtc1       $at, $f8
    /* A7BA4 8011F134 00000000 */  nop
    /* A7BA8 8011F138 460A4082 */  mul.s      $f2, $f8, $f10
    /* A7BAC 8011F13C 10000008 */  b          .L8011F160
    /* A7BB0 8011F140 00000000 */   nop
    /* A7BB4 8011F144 44818000 */  mtc1       $at, $f16
  .L8011F148:
    /* A7BB8 8011F148 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7BBC 8011F14C 44813000 */  mtc1       $at, $f6
    /* A7BC0 8011F150 46128102 */  mul.s      $f4, $f16, $f18
    /* A7BC4 8011F154 00000000 */  nop
    /* A7BC8 8011F158 46062082 */  mul.s      $f2, $f4, $f6
    /* A7BCC 8011F15C 00000000 */  nop
  .L8011F160:
    /* A7BD0 8011F160 14600004 */  bnez       $v1, .L8011F174
    /* A7BD4 8011F164 3C013F00 */   lui       $at, (0x3F000000 >> 16)
    /* A7BD8 8011F168 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7BDC 8011F16C 100000DB */  b          .L8011F4DC
    /* A7BE0 8011F170 460C6000 */   add.s     $f0, $f12, $f12
  .L8011F174:
    /* A7BE4 8011F174 460C6200 */  add.s      $f8, $f12, $f12
    /* A7BE8 8011F178 44815000 */  mtc1       $at, $f10
    /* A7BEC 8011F17C 00000000 */  nop
    /* A7BF0 8011F180 460A4002 */  mul.s      $f0, $f8, $f10
    /* A7BF4 8011F184 100000D6 */  b          .L8011F4E0
    /* A7BF8 8011F188 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F18C:
    /* A7BFC 8011F18C 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7C00 8011F190 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7C04 8011F194 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7C08 8011F198 3C018013 */  lui        $at, %hi(D_80129010)
    /* A7C0C 8011F19C 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7C10 8011F1A0 C7A60030 */  lwc1       $f6, 0x30($sp)
    /* A7C14 8011F1A4 C7B20030 */  lwc1       $f18, 0x30($sp)
    /* A7C18 8011F1A8 00052880 */  sll        $a1, $a1, 2
    /* A7C1C 8011F1AC 00651821 */  addu       $v1, $v1, $a1
    /* A7C20 8011F1B0 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7C24 8011F1B4 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7C28 8011F1B8 30630006 */  andi       $v1, $v1, 0x6
    /* A7C2C 8011F1BC 14600006 */  bnez       $v1, .L8011F1D8
    /* A7C30 8011F1C0 00000000 */   nop
    /* A7C34 8011F1C4 3C018013 */  lui        $at, %hi(D_8012900C)
    /* A7C38 8011F1C8 C430900C */  lwc1       $f16, %lo(D_8012900C)($at)
    /* A7C3C 8011F1CC 46128082 */  mul.s      $f2, $f16, $f18
    /* A7C40 8011F1D0 10000008 */  b          .L8011F1F4
    /* A7C44 8011F1D4 00000000 */   nop
  .L8011F1D8:
    /* A7C48 8011F1D8 C4249010 */  lwc1       $f4, %lo(D_80129010)($at)
    /* A7C4C 8011F1DC 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7C50 8011F1E0 44815000 */  mtc1       $at, $f10
    /* A7C54 8011F1E4 46062202 */  mul.s      $f8, $f4, $f6
    /* A7C58 8011F1E8 00000000 */  nop
    /* A7C5C 8011F1EC 460A4082 */  mul.s      $f2, $f8, $f10
    /* A7C60 8011F1F0 00000000 */  nop
  .L8011F1F4:
    /* A7C64 8011F1F4 14600007 */  bnez       $v1, .L8011F214
    /* A7C68 8011F1F8 3C0140C0 */   lui       $at, (0x40C00000 >> 16)
    /* A7C6C 8011F1FC 3C0140C0 */  lui        $at, (0x40C00000 >> 16)
    /* A7C70 8011F200 44818000 */  mtc1       $at, $f16
    /* A7C74 8011F204 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7C78 8011F208 460C8002 */  mul.s      $f0, $f16, $f12
    /* A7C7C 8011F20C 100000B4 */  b          .L8011F4E0
    /* A7C80 8011F210 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F214:
    /* A7C84 8011F214 44819000 */  mtc1       $at, $f18
    /* A7C88 8011F218 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7C8C 8011F21C 44813000 */  mtc1       $at, $f6
    /* A7C90 8011F220 460C9102 */  mul.s      $f4, $f18, $f12
    /* A7C94 8011F224 00000000 */  nop
    /* A7C98 8011F228 46062002 */  mul.s      $f0, $f4, $f6
    /* A7C9C 8011F22C 100000AB */  b          .L8011F4DC
    /* A7CA0 8011F230 00000000 */   nop
  .L8011F234:
    /* A7CA4 8011F234 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7CA8 8011F238 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7CAC 8011F23C 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7CB0 8011F240 3C013F20 */  lui        $at, (0x3F200000 >> 16)
    /* A7CB4 8011F244 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7CB8 8011F248 C7B20030 */  lwc1       $f18, 0x30($sp)
    /* A7CBC 8011F24C C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7CC0 8011F250 00052880 */  sll        $a1, $a1, 2
    /* A7CC4 8011F254 00651821 */  addu       $v1, $v1, $a1
    /* A7CC8 8011F258 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7CCC 8011F25C C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7CD0 8011F260 30630006 */  andi       $v1, $v1, 0x6
    /* A7CD4 8011F264 54600008 */  bnel       $v1, $zero, .L8011F288
    /* A7CD8 8011F268 44818000 */   mtc1      $at, $f16
    /* A7CDC 8011F26C 3C013F20 */  lui        $at, (0x3F200000 >> 16)
    /* A7CE0 8011F270 44814000 */  mtc1       $at, $f8
    /* A7CE4 8011F274 00000000 */  nop
    /* A7CE8 8011F278 460A4082 */  mul.s      $f2, $f8, $f10
    /* A7CEC 8011F27C 10000008 */  b          .L8011F2A0
    /* A7CF0 8011F280 00000000 */   nop
    /* A7CF4 8011F284 44818000 */  mtc1       $at, $f16
  .L8011F288:
    /* A7CF8 8011F288 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7CFC 8011F28C 44813000 */  mtc1       $at, $f6
    /* A7D00 8011F290 46128102 */  mul.s      $f4, $f16, $f18
    /* A7D04 8011F294 00000000 */  nop
    /* A7D08 8011F298 46062082 */  mul.s      $f2, $f4, $f6
    /* A7D0C 8011F29C 00000000 */  nop
  .L8011F2A0:
    /* A7D10 8011F2A0 14600007 */  bnez       $v1, .L8011F2C0
    /* A7D14 8011F2A4 3C0140A0 */   lui       $at, (0x40A00000 >> 16)
    /* A7D18 8011F2A8 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* A7D1C 8011F2AC 44814000 */  mtc1       $at, $f8
    /* A7D20 8011F2B0 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7D24 8011F2B4 460C4002 */  mul.s      $f0, $f8, $f12
    /* A7D28 8011F2B8 10000089 */  b          .L8011F4E0
    /* A7D2C 8011F2BC 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F2C0:
    /* A7D30 8011F2C0 44815000 */  mtc1       $at, $f10
    /* A7D34 8011F2C4 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7D38 8011F2C8 44819000 */  mtc1       $at, $f18
    /* A7D3C 8011F2CC 460C5402 */  mul.s      $f16, $f10, $f12
    /* A7D40 8011F2D0 00000000 */  nop
    /* A7D44 8011F2D4 46128002 */  mul.s      $f0, $f16, $f18
    /* A7D48 8011F2D8 10000080 */  b          .L8011F4DC
    /* A7D4C 8011F2DC 00000000 */   nop
  .L8011F2E0:
    /* A7D50 8011F2E0 908A0005 */  lbu        $t2, 0x5($a0)
    /* A7D54 8011F2E4 24010018 */  addiu      $at, $zero, 0x18
    /* A7D58 8011F2E8 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7D5C 8011F2EC 15410026 */  bne        $t2, $at, .L8011F388
    /* A7D60 8011F2F0 00000000 */   nop
    /* A7D64 8011F2F4 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7D68 8011F2F8 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7D6C 8011F2FC 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7D70 8011F300 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7D74 8011F304 C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7D78 8011F308 C7A60030 */  lwc1       $f6, 0x30($sp)
    /* A7D7C 8011F30C 00052880 */  sll        $a1, $a1, 2
    /* A7D80 8011F310 00651821 */  addu       $v1, $v1, $a1
    /* A7D84 8011F314 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7D88 8011F318 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7D8C 8011F31C 30630006 */  andi       $v1, $v1, 0x6
    /* A7D90 8011F320 54600008 */  bnel       $v1, $zero, .L8011F344
    /* A7D94 8011F324 44814000 */   mtc1      $at, $f8
    /* A7D98 8011F328 3C013E80 */  lui        $at, (0x3E800000 >> 16)
    /* A7D9C 8011F32C 44812000 */  mtc1       $at, $f4
    /* A7DA0 8011F330 00000000 */  nop
    /* A7DA4 8011F334 46062082 */  mul.s      $f2, $f4, $f6
    /* A7DA8 8011F338 10000008 */  b          .L8011F35C
    /* A7DAC 8011F33C 00000000 */   nop
    /* A7DB0 8011F340 44814000 */  mtc1       $at, $f8
  .L8011F344:
    /* A7DB4 8011F344 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7DB8 8011F348 44819000 */  mtc1       $at, $f18
    /* A7DBC 8011F34C 460A4402 */  mul.s      $f16, $f8, $f10
    /* A7DC0 8011F350 00000000 */  nop
    /* A7DC4 8011F354 46128082 */  mul.s      $f2, $f16, $f18
    /* A7DC8 8011F358 00000000 */  nop
  .L8011F35C:
    /* A7DCC 8011F35C 14600004 */  bnez       $v1, .L8011F370
    /* A7DD0 8011F360 3C013F00 */   lui       $at, (0x3F000000 >> 16)
    /* A7DD4 8011F364 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7DD8 8011F368 1000005C */  b          .L8011F4DC
    /* A7DDC 8011F36C 460C6000 */   add.s     $f0, $f12, $f12
  .L8011F370:
    /* A7DE0 8011F370 460C6100 */  add.s      $f4, $f12, $f12
    /* A7DE4 8011F374 44813000 */  mtc1       $at, $f6
    /* A7DE8 8011F378 00000000 */  nop
    /* A7DEC 8011F37C 46062002 */  mul.s      $f0, $f4, $f6
    /* A7DF0 8011F380 10000057 */  b          .L8011F4E0
    /* A7DF4 8011F384 30EE0100 */   andi      $t6, $a3, 0x100
  .L8011F388:
    /* A7DF8 8011F388 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A7DFC 8011F38C 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A7E00 8011F390 3C0B800F */  lui        $t3, %hi(D_800E8920)
    /* A7E04 8011F394 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7E08 8011F398 8CC50000 */  lw         $a1, 0x0($a2)
    /* A7E0C 8011F39C 00052880 */  sll        $a1, $a1, 2
    /* A7E10 8011F3A0 01655821 */  addu       $t3, $t3, $a1
    /* A7E14 8011F3A4 8D6B8920 */  lw         $t3, %lo(D_800E8920)($t3)
    /* A7E18 8011F3A8 00651821 */  addu       $v1, $v1, $a1
    /* A7E1C 8011F3AC 1160002D */  beqz       $t3, .L8011F464
    /* A7E20 8011F3B0 00000000 */   nop
    /* A7E24 8011F3B4 3C03800F */  lui        $v1, %hi(D_800E8AE0)
    /* A7E28 8011F3B8 00651821 */  addu       $v1, $v1, $a1
    /* A7E2C 8011F3BC 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7E30 8011F3C0 3C198013 */  lui        $t9, %hi(D_80128338)
    /* A7E34 8011F3C4 3C0E8013 */  lui        $t6, %hi(D_80128338)
    /* A7E38 8011F3C8 30630006 */  andi       $v1, $v1, 0x6
    /* A7E3C 8011F3CC 1460000A */  bnez       $v1, .L8011F3F8
    /* A7E40 8011F3D0 C7AC002C */   lwc1      $f12, 0x2C($sp)
    /* A7E44 8011F3D4 908C0007 */  lbu        $t4, 0x7($a0)
    /* A7E48 8011F3D8 25CE8338 */  addiu      $t6, $t6, %lo(D_80128338)
    /* A7E4C 8011F3DC C7AA0030 */  lwc1       $f10, 0x30($sp)
    /* A7E50 8011F3E0 000C68C0 */  sll        $t5, $t4, 3
    /* A7E54 8011F3E4 01AE1021 */  addu       $v0, $t5, $t6
    /* A7E58 8011F3E8 C4480000 */  lwc1       $f8, 0x0($v0)
    /* A7E5C 8011F3EC 460A4082 */  mul.s      $f2, $f8, $f10
    /* A7E60 8011F3F0 1000000D */  b          .L8011F428
    /* A7E64 8011F3F4 00000000 */   nop
  .L8011F3F8:
    /* A7E68 8011F3F8 908F0007 */  lbu        $t7, 0x7($a0)
    /* A7E6C 8011F3FC 27398338 */  addiu      $t9, $t9, %lo(D_80128338)
    /* A7E70 8011F400 C7B20030 */  lwc1       $f18, 0x30($sp)
    /* A7E74 8011F404 000FC0C0 */  sll        $t8, $t7, 3
    /* A7E78 8011F408 03191021 */  addu       $v0, $t8, $t9
    /* A7E7C 8011F40C C4500000 */  lwc1       $f16, 0x0($v0)
    /* A7E80 8011F410 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7E84 8011F414 44813000 */  mtc1       $at, $f6
    /* A7E88 8011F418 46128102 */  mul.s      $f4, $f16, $f18
    /* A7E8C 8011F41C 00000000 */  nop
    /* A7E90 8011F420 46062082 */  mul.s      $f2, $f4, $f6
    /* A7E94 8011F424 00000000 */  nop
  .L8011F428:
    /* A7E98 8011F428 54600007 */  bnel       $v1, $zero, .L8011F448
    /* A7E9C 8011F42C C44A0004 */   lwc1      $f10, 0x4($v0)
    /* A7EA0 8011F430 C7AC002C */  lwc1       $f12, 0x2C($sp)
    /* A7EA4 8011F434 C4480004 */  lwc1       $f8, 0x4($v0)
    /* A7EA8 8011F438 460C4002 */  mul.s      $f0, $f8, $f12
    /* A7EAC 8011F43C 10000028 */  b          .L8011F4E0
    /* A7EB0 8011F440 30EE0100 */   andi      $t6, $a3, 0x100
    /* A7EB4 8011F444 C44A0004 */  lwc1       $f10, 0x4($v0)
  .L8011F448:
    /* A7EB8 8011F448 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7EBC 8011F44C 44819000 */  mtc1       $at, $f18
    /* A7EC0 8011F450 460C5402 */  mul.s      $f16, $f10, $f12
    /* A7EC4 8011F454 00000000 */  nop
    /* A7EC8 8011F458 46128002 */  mul.s      $f0, $f16, $f18
    /* A7ECC 8011F45C 1000001F */  b          .L8011F4DC
    /* A7ED0 8011F460 00000000 */   nop
  .L8011F464:
    /* A7ED4 8011F464 8C638AE0 */  lw         $v1, %lo(D_800E8AE0)($v1)
    /* A7ED8 8011F468 3C0D8013 */  lui        $t5, %hi(D_80128338)
    /* A7EDC 8011F46C 25AD8338 */  addiu      $t5, $t5, %lo(D_80128338)
    /* A7EE0 8011F470 30630006 */  andi       $v1, $v1, 0x6
    /* A7EE4 8011F474 54600009 */  bnel       $v1, $zero, .L8011F49C
    /* A7EE8 8011F478 908B0007 */   lbu       $t3, 0x7($a0)
    /* A7EEC 8011F47C 90880007 */  lbu        $t0, 0x7($a0)
    /* A7EF0 8011F480 3C0A8013 */  lui        $t2, %hi(D_80128338)
    /* A7EF4 8011F484 254A8338 */  addiu      $t2, $t2, %lo(D_80128338)
    /* A7EF8 8011F488 000848C0 */  sll        $t1, $t0, 3
    /* A7EFC 8011F48C 012A1021 */  addu       $v0, $t1, $t2
    /* A7F00 8011F490 10000009 */  b          .L8011F4B8
    /* A7F04 8011F494 C4420000 */   lwc1      $f2, 0x0($v0)
    /* A7F08 8011F498 908B0007 */  lbu        $t3, 0x7($a0)
  .L8011F49C:
    /* A7F0C 8011F49C 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* A7F10 8011F4A0 44813000 */  mtc1       $at, $f6
    /* A7F14 8011F4A4 000B60C0 */  sll        $t4, $t3, 3
    /* A7F18 8011F4A8 018D1021 */  addu       $v0, $t4, $t5
    /* A7F1C 8011F4AC C4440000 */  lwc1       $f4, 0x0($v0)
    /* A7F20 8011F4B0 46062082 */  mul.s      $f2, $f4, $f6
    /* A7F24 8011F4B4 00000000 */  nop
  .L8011F4B8:
    /* A7F28 8011F4B8 14600003 */  bnez       $v1, .L8011F4C8
    /* A7F2C 8011F4BC 3C013F00 */   lui       $at, (0x3F000000 >> 16)
    /* A7F30 8011F4C0 10000006 */  b          .L8011F4DC
    /* A7F34 8011F4C4 C4400004 */   lwc1      $f0, 0x4($v0)
  .L8011F4C8:
    /* A7F38 8011F4C8 C4480004 */  lwc1       $f8, 0x4($v0)
    /* A7F3C 8011F4CC 44815000 */  mtc1       $at, $f10
    /* A7F40 8011F4D0 00000000 */  nop
    /* A7F44 8011F4D4 460A4002 */  mul.s      $f0, $f8, $f10
    /* A7F48 8011F4D8 00000000 */  nop
  .L8011F4DC:
    /* A7F4C 8011F4DC 30EE0100 */  andi       $t6, $a3, 0x100
  .L8011F4E0:
    /* A7F50 8011F4E0 51C00016 */  beql       $t6, $zero, .L8011F53C
    /* A7F54 8011F4E4 44803000 */   mtc1      $zero, $f6
    /* A7F58 8011F4E8 44808000 */  mtc1       $zero, $f16
    /* A7F5C 8011F4EC 3C01800E */  lui        $at, %hi(D_800E6690)
    /* A7F60 8011F4F0 00250821 */  addu       $at, $at, $a1
    /* A7F64 8011F4F4 4610003C */  c.lt.s     $f0, $f16
    /* A7F68 8011F4F8 E4226690 */  swc1       $f2, %lo(D_800E6690)($at)
    /* A7F6C 8011F4FC 45020009 */  bc1fl      .L8011F524
    /* A7F70 8011F500 8CD90000 */   lw        $t9, 0x0($a2)
    /* A7F74 8011F504 8CCF0000 */  lw         $t7, 0x0($a2)
    /* A7F78 8011F508 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A7F7C 8011F50C 46000487 */  neg.s      $f18, $f0
    /* A7F80 8011F510 000FC080 */  sll        $t8, $t7, 2
    /* A7F84 8011F514 00380821 */  addu       $at, $at, $t8
    /* A7F88 8011F518 10000059 */  b          .L8011F680
    /* A7F8C 8011F51C E4326850 */   swc1      $f18, %lo(D_800E6850)($at)
    /* A7F90 8011F520 8CD90000 */  lw         $t9, 0x0($a2)
  .L8011F524:
    /* A7F94 8011F524 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A7F98 8011F528 00194080 */  sll        $t0, $t9, 2
    /* A7F9C 8011F52C 00280821 */  addu       $at, $at, $t0
    /* A7FA0 8011F530 10000053 */  b          .L8011F680
    /* A7FA4 8011F534 E4206850 */   swc1      $f0, %lo(D_800E6850)($at)
    /* A7FA8 8011F538 44803000 */  mtc1       $zero, $f6
  .L8011F53C:
    /* A7FAC 8011F53C 3C01800E */  lui        $at, %hi(D_800E6690)
    /* A7FB0 8011F540 46001107 */  neg.s      $f4, $f2
    /* A7FB4 8011F544 4606003C */  c.lt.s     $f0, $f6
    /* A7FB8 8011F548 00250821 */  addu       $at, $at, $a1
    /* A7FBC 8011F54C E4246690 */  swc1       $f4, %lo(D_800E6690)($at)
    /* A7FC0 8011F550 45020009 */  bc1fl      .L8011F578
    /* A7FC4 8011F554 8CCB0000 */   lw        $t3, 0x0($a2)
    /* A7FC8 8011F558 8CC90000 */  lw         $t1, 0x0($a2)
    /* A7FCC 8011F55C 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A7FD0 8011F560 46000207 */  neg.s      $f8, $f0
    /* A7FD4 8011F564 00095080 */  sll        $t2, $t1, 2
    /* A7FD8 8011F568 002A0821 */  addu       $at, $at, $t2
    /* A7FDC 8011F56C 10000044 */  b          .L8011F680
    /* A7FE0 8011F570 E4286850 */   swc1      $f8, %lo(D_800E6850)($at)
    /* A7FE4 8011F574 8CCB0000 */  lw         $t3, 0x0($a2)
  .L8011F578:
    /* A7FE8 8011F578 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A7FEC 8011F57C 000B6080 */  sll        $t4, $t3, 2
    /* A7FF0 8011F580 002C0821 */  addu       $at, $at, $t4
    /* A7FF4 8011F584 1000003E */  b          .L8011F680
    /* A7FF8 8011F588 E4206850 */   swc1      $f0, %lo(D_800E6850)($at)
  .L8011F58C:
    /* A7FFC 8011F58C 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A8000 8011F590 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A8004 8011F594 3C0D800F */  lui        $t5, %hi(D_800E8920)
    /* A8008 8011F598 3C0E800F */  lui        $t6, %hi(D_800E8AE0)
    /* A800C 8011F59C 8CC50000 */  lw         $a1, 0x0($a2)
    /* A8010 8011F5A0 3C01800E */  lui        $at, %hi(D_800E6A10)
    /* A8014 8011F5A4 C7A80034 */  lwc1       $f8, 0x34($sp)
    /* A8018 8011F5A8 00052880 */  sll        $a1, $a1, 2
    /* A801C 8011F5AC 01A56821 */  addu       $t5, $t5, $a1
    /* A8020 8011F5B0 8DAD8920 */  lw         $t5, %lo(D_800E8920)($t5)
    /* A8024 8011F5B4 01C57021 */  addu       $t6, $t6, $a1
    /* A8028 8011F5B8 00250821 */  addu       $at, $at, $a1
    /* A802C 8011F5BC 11A00025 */  beqz       $t5, .L8011F654
    /* A8030 8011F5C0 00000000 */   nop
    /* A8034 8011F5C4 8DCE8AE0 */  lw         $t6, %lo(D_800E8AE0)($t6)
    /* A8038 8011F5C8 C7B00034 */  lwc1       $f16, 0x34($sp)
    /* A803C 8011F5CC C7A60034 */  lwc1       $f6, 0x34($sp)
    /* A8040 8011F5D0 31CF0006 */  andi       $t7, $t6, 0x6
    /* A8044 8011F5D4 11E0000F */  beqz       $t7, .L8011F614
    /* A8048 8011F5D8 3C018013 */   lui       $at, %hi(D_80129014)
    /* A804C 8011F5DC 3C01800E */  lui        $at, %hi(D_800E6A10)
    /* A8050 8011F5E0 00250821 */  addu       $at, $at, $a1
    /* A8054 8011F5E4 C42A6A10 */  lwc1       $f10, %lo(D_800E6A10)($at)
    /* A8058 8011F5E8 3C01800E */  lui        $at, %hi(D_800E6690)
    /* A805C 8011F5EC 00250821 */  addu       $at, $at, $a1
    /* A8060 8011F5F0 46105482 */  mul.s      $f18, $f10, $f16
    /* A8064 8011F5F4 44802000 */  mtc1       $zero, $f4
    /* A8068 8011F5F8 E4326690 */  swc1       $f18, %lo(D_800E6690)($at)
    /* A806C 8011F5FC 8CD80000 */  lw         $t8, 0x0($a2)
    /* A8070 8011F600 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A8074 8011F604 0018C880 */  sll        $t9, $t8, 2
    /* A8078 8011F608 00390821 */  addu       $at, $at, $t9
    /* A807C 8011F60C 1000001C */  b          .L8011F680
    /* A8080 8011F610 E4246850 */   swc1      $f4, %lo(D_800E6850)($at)
  .L8011F614:
    /* A8084 8011F614 C4289014 */  lwc1       $f8, %lo(D_80129014)($at)
    /* A8088 8011F618 3C01800E */  lui        $at, %hi(D_800E6A10)
    /* A808C 8011F61C 00250821 */  addu       $at, $at, $a1
    /* A8090 8011F620 46083282 */  mul.s      $f10, $f6, $f8
    /* A8094 8011F624 C4306A10 */  lwc1       $f16, %lo(D_800E6A10)($at)
    /* A8098 8011F628 3C01800E */  lui        $at, %hi(D_800E6690)
    /* A809C 8011F62C 00250821 */  addu       $at, $at, $a1
    /* A80A0 8011F630 44802000 */  mtc1       $zero, $f4
    /* A80A4 8011F634 460A8482 */  mul.s      $f18, $f16, $f10
    /* A80A8 8011F638 E4326690 */  swc1       $f18, %lo(D_800E6690)($at)
    /* A80AC 8011F63C 8CC80000 */  lw         $t0, 0x0($a2)
    /* A80B0 8011F640 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A80B4 8011F644 00084880 */  sll        $t1, $t0, 2
    /* A80B8 8011F648 00290821 */  addu       $at, $at, $t1
    /* A80BC 8011F64C 1000000C */  b          .L8011F680
    /* A80C0 8011F650 E4246850 */   swc1      $f4, %lo(D_800E6850)($at)
  .L8011F654:
    /* A80C4 8011F654 C4266A10 */  lwc1       $f6, %lo(D_800E6A10)($at)
    /* A80C8 8011F658 3C01800E */  lui        $at, %hi(D_800E6690)
    /* A80CC 8011F65C 00250821 */  addu       $at, $at, $a1
    /* A80D0 8011F660 46083402 */  mul.s      $f16, $f6, $f8
    /* A80D4 8011F664 44805000 */  mtc1       $zero, $f10
    /* A80D8 8011F668 E4306690 */  swc1       $f16, %lo(D_800E6690)($at)
    /* A80DC 8011F66C 8CCA0000 */  lw         $t2, 0x0($a2)
    /* A80E0 8011F670 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A80E4 8011F674 000A5880 */  sll        $t3, $t2, 2
    /* A80E8 8011F678 002B0821 */  addu       $at, $at, $t3
    /* A80EC 8011F67C E42A6850 */  swc1       $f10, %lo(D_800E6850)($at)
  .L8011F680:
    /* A80F0 8011F680 8FBF0014 */  lw         $ra, 0x14($sp)
    /* A80F4 8011F684 27BD0040 */  addiu      $sp, $sp, 0x40
    /* A80F8 8011F688 03E00008 */  jr         $ra
    /* A80FC 8011F68C 00000000 */   nop
endlabel func_8011ED68
.size func_8011ED68, . - func_8011ED68
