.section .late_rodata
nonmatching jtbl_80129018

dlabel jtbl_80129018
    /* B1A88 80129018 8011F730 */ .word .L8011F730
    /* B1A8C 8012901C 8011F848 */ .word .L8011F848
    /* B1A90 80129020 8011FA98 */ .word .L8011FA98
    /* B1A94 80129024 8011FA3C */ .word .L8011FA3C
    /* B1A98 80129028 8011FC24 */ .word .L8011FC24
    /* B1A9C 8012902C 8011FC14 */ .word .L8011FC14
enddlabel jtbl_80129018
.size jtbl_80129018, . - jtbl_80129018

nonmatching D_80129030

dlabel D_80129030
    /* B1AA0 80129030 477FFF00 */ .float 65535
enddlabel D_80129030
.size D_80129030, . - D_80129030


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8011F690, 0x868

glabel func_8011F690
    /* A8100 8011F690 3C088013 */  lui        $t0, %hi(gKirbyState)
    /* A8104 8011F694 2508E7C0 */  addiu      $t0, $t0, %lo(gKirbyState)
    /* A8108 8011F698 910E0017 */  lbu        $t6, 0x17($t0)
    /* A810C 8011F69C 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* A8110 8011F6A0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* A8114 8011F6A4 11C00003 */  beqz       $t6, .L8011F6B4
    /* A8118 8011F6A8 3C0F8005 */   lui       $t7, %hi(omCurrentObj)
    /* A811C 8011F6AC 1000020E */  b          .L8011FEE8
    /* A8120 8011F6B0 00001025 */   or        $v0, $zero, $zero
  .L8011F6B4:
    /* A8124 8011F6B4 8DEFA7C4 */  lw         $t7, %lo(omCurrentObj)($t7)
    /* A8128 8011F6B8 3C18800F */  lui        $t8, %hi(D_800E98E0)
    /* A812C 8011F6BC 3C01800F */  lui        $at, %hi(D_800E9AA0)
    /* A8130 8011F6C0 8DE60000 */  lw         $a2, 0x0($t7)
    /* A8134 8011F6C4 3C048013 */  lui        $a0, %hi(gPositionState)
    /* A8138 8011F6C8 2484E968 */  addiu      $a0, $a0, %lo(gPositionState)
    /* A813C 8011F6CC 00063080 */  sll        $a2, $a2, 2
    /* A8140 8011F6D0 0306C021 */  addu       $t8, $t8, $a2
    /* A8144 8011F6D4 8F1898E0 */  lw         $t8, %lo(D_800E98E0)($t8)
    /* A8148 8011F6D8 00260821 */  addu       $at, $at, $a2
    /* A814C 8011F6DC 0C0431CD */  jal        func_8010C734
    /* A8150 8011F6E0 AC389AA0 */   sw        $t8, %lo(D_800E9AA0)($at)
    /* A8154 8011F6E4 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A8158 8011F6E8 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A815C 8011F6EC 3C09800F */  lui        $t1, %hi(D_800E98E0)
    /* A8160 8011F6F0 252998E0 */  addiu      $t1, $t1, %lo(D_800E98E0)
    /* A8164 8011F6F4 8CE60000 */  lw         $a2, 0x0($a3)
    /* A8168 8011F6F8 3C088013 */  lui        $t0, %hi(gKirbyState)
    /* A816C 8011F6FC 2508E7C0 */  addiu      $t0, $t0, %lo(gKirbyState)
    /* A8170 8011F700 00063080 */  sll        $a2, $a2, 2
    /* A8174 8011F704 01261821 */  addu       $v1, $t1, $a2
    /* A8178 8011F708 8C650000 */  lw         $a1, 0x0($v1)
    /* A817C 8011F70C 24B9FFFF */  addiu      $t9, $a1, -0x1
    /* A8180 8011F710 2F210006 */  sltiu      $at, $t9, 0x6
    /* A8184 8011F714 10200143 */  beqz       $at, .L8011FC24
    /* A8188 8011F718 0019C880 */   sll       $t9, $t9, 2
    /* A818C 8011F71C 3C018013 */  lui        $at, %hi(jtbl_80129018)
    /* A8190 8011F720 00390821 */  addu       $at, $at, $t9
    /* A8194 8011F724 8C399018 */  lw         $t9, %lo(jtbl_80129018)($at)
    /* A8198 8011F728 03200008 */  jr         $t9
    /* A819C 8011F72C 00000000 */   nop
  .L8011F730:
    /* A81A0 8011F730 3C0A800F */  lui        $t2, %hi(D_800E8920)
    /* A81A4 8011F734 01465021 */  addu       $t2, $t2, $a2
    /* A81A8 8011F738 8D4A8920 */  lw         $t2, %lo(D_800E8920)($t2)
    /* A81AC 8011F73C 11400022 */  beqz       $t2, .L8011F7C8
    /* A81B0 8011F740 00000000 */   nop
    /* A81B4 8011F744 0C048465 */  jal        func_80121194
    /* A81B8 8011F748 00000000 */   nop
    /* A81BC 8011F74C 3C09800F */  lui        $t1, %hi(D_800E98E0)
    /* A81C0 8011F750 1040001D */  beqz       $v0, .L8011F7C8
    /* A81C4 8011F754 252998E0 */   addiu     $t1, $t1, %lo(D_800E98E0)
    /* A81C8 8011F758 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A81CC 8011F75C 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A81D0 8011F760 44802000 */  mtc1       $zero, $f4
    /* A81D4 8011F764 3C02800E */  lui        $v0, %hi(D_800E6690)
    /* A81D8 8011F768 8CEB0000 */  lw         $t3, 0x0($a3)
    /* A81DC 8011F76C 24426690 */  addiu      $v0, $v0, %lo(D_800E6690)
    /* A81E0 8011F770 3C01800E */  lui        $at, %hi(D_800E64D0)
    /* A81E4 8011F774 000B6080 */  sll        $t4, $t3, 2
    /* A81E8 8011F778 004C6821 */  addu       $t5, $v0, $t4
    /* A81EC 8011F77C E5A40000 */  swc1       $f4, 0x0($t5)
    /* A81F0 8011F780 8CE60000 */  lw         $a2, 0x0($a3)
    /* A81F4 8011F784 00002025 */  or         $a0, $zero, $zero
    /* A81F8 8011F788 24050001 */  addiu      $a1, $zero, 0x1
    /* A81FC 8011F78C 00063080 */  sll        $a2, $a2, 2
    /* A8200 8011F790 00467021 */  addu       $t6, $v0, $a2
    /* A8204 8011F794 C5C60000 */  lwc1       $f6, 0x0($t6)
    /* A8208 8011F798 00260821 */  addu       $at, $at, $a2
    /* A820C 8011F79C E42664D0 */  swc1       $f6, %lo(D_800E64D0)($at)
    /* A8210 8011F7A0 8CEF0000 */  lw         $t7, 0x0($a3)
    /* A8214 8011F7A4 3C018013 */  lui        $at, %hi(D_80129030)
    /* A8218 8011F7A8 C4289030 */  lwc1       $f8, %lo(D_80129030)($at)
    /* A821C 8011F7AC 3C01800E */  lui        $at, %hi(D_800E6850)
    /* A8220 8011F7B0 000FC080 */  sll        $t8, $t7, 2
    /* A8224 8011F7B4 00380821 */  addu       $at, $at, $t8
    /* A8228 8011F7B8 0C048BDB */  jal        set_kirby_action_1
    /* A822C 8011F7BC E4286850 */   swc1      $f8, %lo(D_800E6850)($at)
    /* A8230 8011F7C0 100001C9 */  b          .L8011FEE8
    /* A8234 8011F7C4 00001025 */   or        $v0, $zero, $zero
  .L8011F7C8:
    /* A8238 8011F7C8 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A823C 8011F7CC 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A8240 8011F7D0 3C19800D */  lui        $t9, %hi(D_800D6F58 + 0x54)
    /* A8244 8011F7D4 8F396FAC */  lw         $t9, %lo(D_800D6F58 + 0x54)($t9)
    /* A8248 8011F7D8 8CE60000 */  lw         $a2, 0x0($a3)
    /* A824C 8011F7DC 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A8250 8011F7E0 00063080 */  sll        $a2, $a2, 2
    /* A8254 8011F7E4 17200016 */  bnez       $t9, .L8011F840
    /* A8258 8011F7E8 01261821 */   addu      $v1, $t1, $a2
    /* A825C 8011F7EC 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A8260 8011F7F0 3C0C800F */  lui        $t4, %hi(D_800E8920)
    /* A8264 8011F7F4 240B0002 */  addiu      $t3, $zero, 0x2
    /* A8268 8011F7F8 304A0800 */  andi       $t2, $v0, 0x800
    /* A826C 8011F7FC 11400006 */  beqz       $t2, .L8011F818
    /* A8270 8011F800 01866021 */   addu      $t4, $t4, $a2
    /* A8274 8011F804 AC6B0000 */  sw         $t3, 0x0($v1)
    /* A8278 8011F808 8CE60000 */  lw         $a2, 0x0($a3)
    /* A827C 8011F80C 00063080 */  sll        $a2, $a2, 2
    /* A8280 8011F810 1000000B */  b          .L8011F840
    /* A8284 8011F814 01261821 */   addu      $v1, $t1, $a2
  .L8011F818:
    /* A8288 8011F818 8D8C8920 */  lw         $t4, %lo(D_800E8920)($t4)
    /* A828C 8011F81C 304D0400 */  andi       $t5, $v0, 0x400
    /* A8290 8011F820 15800007 */  bnez       $t4, .L8011F840
    /* A8294 8011F824 00000000 */   nop
    /* A8298 8011F828 11A00005 */  beqz       $t5, .L8011F840
    /* A829C 8011F82C 240E0003 */   addiu     $t6, $zero, 0x3
    /* A82A0 8011F830 AC6E0000 */  sw         $t6, 0x0($v1)
    /* A82A4 8011F834 8CE60000 */  lw         $a2, 0x0($a3)
    /* A82A8 8011F838 00063080 */  sll        $a2, $a2, 2
    /* A82AC 8011F83C 01261821 */  addu       $v1, $t1, $a2
  .L8011F840:
    /* A82B0 8011F840 100000F8 */  b          .L8011FC24
    /* A82B4 8011F844 8C650000 */   lw        $a1, 0x0($v1)
  .L8011F848:
    /* A82B8 8011F848 8D0F00E4 */  lw         $t7, 0xE4($t0)
    /* A82BC 8011F84C 3C01800E */  lui        $at, %hi(D_800E6A10)
    /* A82C0 8011F850 00260821 */  addu       $at, $at, $a2
    /* A82C4 8011F854 15E00030 */  bnez       $t7, .L8011F918
    /* A82C8 8011F858 00000000 */   nop
    /* A82CC 8011F85C C4206A10 */  lwc1       $f0, %lo(D_800E6A10)($at)
    /* A82D0 8011F860 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* A82D4 8011F864 44815000 */  mtc1       $at, $f10
    /* A82D8 8011F868 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* A82DC 8011F86C 3C188013 */  lui        $t8, %hi(D_8012BCA0)
    /* A82E0 8011F870 46005032 */  c.eq.s     $f10, $f0
    /* A82E4 8011F874 00000000 */  nop
    /* A82E8 8011F878 45020007 */  bc1fl      .L8011F898
    /* A82EC 8011F87C 44818000 */   mtc1      $at, $f16
    /* A82F0 8011F880 8F18BCA0 */  lw         $t8, %lo(D_8012BCA0)($t8)
    /* A82F4 8011F884 0018CCC2 */  srl        $t9, $t8, 19
    /* A82F8 8011F888 332A0002 */  andi       $t2, $t9, 0x2
    /* A82FC 8011F88C 1140000C */  beqz       $t2, .L8011F8C0
    /* A8300 8011F890 00000000 */   nop
    /* A8304 8011F894 44818000 */  mtc1       $at, $f16
  .L8011F898:
    /* A8308 8011F898 3C0B8013 */  lui        $t3, %hi(D_8012BCA0)
    /* A830C 8011F89C 46008032 */  c.eq.s     $f16, $f0
    /* A8310 8011F8A0 00000000 */  nop
    /* A8314 8011F8A4 4500001C */  bc1f       .L8011F918
    /* A8318 8011F8A8 00000000 */   nop
    /* A831C 8011F8AC 8D6BBCA0 */  lw         $t3, %lo(D_8012BCA0)($t3)
    /* A8320 8011F8B0 000B64C2 */  srl        $t4, $t3, 19
    /* A8324 8011F8B4 318D0010 */  andi       $t5, $t4, 0x10
    /* A8328 8011F8B8 15A00017 */  bnez       $t5, .L8011F918
    /* A832C 8011F8BC 00000000 */   nop
  .L8011F8C0:
    /* A8330 8011F8C0 0C048465 */  jal        func_80121194
    /* A8334 8011F8C4 00000000 */   nop
    /* A8338 8011F8C8 3C09800F */  lui        $t1, %hi(D_800E98E0)
    /* A833C 8011F8CC 10400006 */  beqz       $v0, .L8011F8E8
    /* A8340 8011F8D0 252998E0 */   addiu     $t1, $t1, %lo(D_800E98E0)
    /* A8344 8011F8D4 24040003 */  addiu      $a0, $zero, 0x3
    /* A8348 8011F8D8 0C048BDB */  jal        set_kirby_action_1
    /* A834C 8011F8DC 24050005 */   addiu     $a1, $zero, 0x5
    /* A8350 8011F8E0 10000181 */  b          .L8011FEE8
    /* A8354 8011F8E4 00001025 */   or        $v0, $zero, $zero
  .L8011F8E8:
    /* A8358 8011F8E8 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A835C 8011F8EC 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A8360 8011F8F0 240E0005 */  addiu      $t6, $zero, 0x5
    /* A8364 8011F8F4 8CEF0000 */  lw         $t7, 0x0($a3)
    /* A8368 8011F8F8 000FC080 */  sll        $t8, $t7, 2
    /* A836C 8011F8FC 0138C821 */  addu       $t9, $t1, $t8
    /* A8370 8011F900 AF2E0000 */  sw         $t6, 0x0($t9)
    /* A8374 8011F904 8CE60000 */  lw         $a2, 0x0($a3)
    /* A8378 8011F908 00063080 */  sll        $a2, $a2, 2
    /* A837C 8011F90C 01265021 */  addu       $t2, $t1, $a2
    /* A8380 8011F910 100000C4 */  b          .L8011FC24
    /* A8384 8011F914 8D450000 */   lw        $a1, 0x0($t2)
  .L8011F918:
    /* A8388 8011F918 3C0B800D */  lui        $t3, %hi(D_800D6F58 + 0x54)
    /* A838C 8011F91C 8D6B6FAC */  lw         $t3, %lo(D_800D6F58 + 0x54)($t3)
    /* A8390 8011F920 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A8394 8011F924 240F0001 */  addiu      $t7, $zero, 0x1
    /* A8398 8011F928 5560003F */  bnel       $t3, $zero, .L8011FA28
    /* A839C 8011F92C AC6F0000 */   sw        $t7, 0x0($v1)
    /* A83A0 8011F930 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A83A4 8011F934 3C0C800F */  lui        $t4, %hi(D_800E9720)
    /* A83A8 8011F938 258C9720 */  addiu      $t4, $t4, %lo(D_800E9720)
    /* A83AC 8011F93C 30480800 */  andi       $t0, $v0, 0x800
    /* A83B0 8011F940 15000010 */  bnez       $t0, .L8011F984
    /* A83B4 8011F944 00CC2021 */   addu      $a0, $a2, $t4
    /* A83B8 8011F948 8C8D0000 */  lw         $t5, 0x0($a0)
    /* A83BC 8011F94C 29A10007 */  slti       $at, $t5, 0x7
    /* A83C0 8011F950 1420000C */  bnez       $at, .L8011F984
    /* A83C4 8011F954 00000000 */   nop
    /* A83C8 8011F958 AC800000 */  sw         $zero, 0x0($a0)
    /* A83CC 8011F95C 8CF80000 */  lw         $t8, 0x0($a3)
    /* A83D0 8011F960 240F0001 */  addiu      $t7, $zero, 0x1
    /* A83D4 8011F964 00187080 */  sll        $t6, $t8, 2
    /* A83D8 8011F968 012EC821 */  addu       $t9, $t1, $t6
    /* A83DC 8011F96C AF2F0000 */  sw         $t7, 0x0($t9)
    /* A83E0 8011F970 8CE60000 */  lw         $a2, 0x0($a3)
    /* A83E4 8011F974 00063080 */  sll        $a2, $a2, 2
    /* A83E8 8011F978 01265021 */  addu       $t2, $t1, $a2
    /* A83EC 8011F97C 100000A9 */  b          .L8011FC24
    /* A83F0 8011F980 8D450000 */   lw        $a1, 0x0($t2)
  .L8011F984:
    /* A83F4 8011F984 3C0C800F */  lui        $t4, %hi(D_800E8920)
    /* A83F8 8011F988 01866021 */  addu       $t4, $t4, $a2
    /* A83FC 8011F98C 8D8C8920 */  lw         $t4, %lo(D_800E8920)($t4)
    /* A8400 8011F990 3C0B800F */  lui        $t3, %hi(D_800E9720)
    /* A8404 8011F994 256B9720 */  addiu      $t3, $t3, %lo(D_800E9720)
    /* A8408 8011F998 1580000F */  bnez       $t4, .L8011F9D8
    /* A840C 8011F99C 00CB2021 */   addu      $a0, $a2, $t3
    /* A8410 8011F9A0 304D0400 */  andi       $t5, $v0, 0x400
    /* A8414 8011F9A4 11A0000C */  beqz       $t5, .L8011F9D8
    /* A8418 8011F9A8 00000000 */   nop
    /* A841C 8011F9AC AC800000 */  sw         $zero, 0x0($a0)
    /* A8420 8011F9B0 8CEE0000 */  lw         $t6, 0x0($a3)
    /* A8424 8011F9B4 24180003 */  addiu      $t8, $zero, 0x3
    /* A8428 8011F9B8 000E7880 */  sll        $t7, $t6, 2
    /* A842C 8011F9BC 012FC821 */  addu       $t9, $t1, $t7
    /* A8430 8011F9C0 AF380000 */  sw         $t8, 0x0($t9)
    /* A8434 8011F9C4 8CE60000 */  lw         $a2, 0x0($a3)
    /* A8438 8011F9C8 00063080 */  sll        $a2, $a2, 2
    /* A843C 8011F9CC 01265021 */  addu       $t2, $t1, $a2
    /* A8440 8011F9D0 10000094 */  b          .L8011FC24
    /* A8444 8011F9D4 8D450000 */   lw        $a1, 0x0($t2)
  .L8011F9D8:
    /* A8448 8011F9D8 1100000B */  beqz       $t0, .L8011FA08
    /* A844C 8011F9DC 8C830000 */   lw        $v1, 0x0($a0)
    /* A8450 8011F9E0 18600090 */  blez       $v1, .L8011FC24
    /* A8454 8011F9E4 28610007 */   slti      $at, $v1, 0x7
    /* A8458 8011F9E8 1020008E */  beqz       $at, .L8011FC24
    /* A845C 8011F9EC 240B0004 */   addiu     $t3, $zero, 0x4
    /* A8460 8011F9F0 AC8B0000 */  sw         $t3, 0x0($a0)
    /* A8464 8011F9F4 8CE60000 */  lw         $a2, 0x0($a3)
    /* A8468 8011F9F8 00063080 */  sll        $a2, $a2, 2
    /* A846C 8011F9FC 01266021 */  addu       $t4, $t1, $a2
    /* A8470 8011FA00 10000088 */  b          .L8011FC24
    /* A8474 8011FA04 8D850000 */   lw        $a1, 0x0($t4)
  .L8011FA08:
    /* A8478 8011FA08 246D0001 */  addiu      $t5, $v1, 0x1
    /* A847C 8011FA0C AC8D0000 */  sw         $t5, 0x0($a0)
    /* A8480 8011FA10 8CE60000 */  lw         $a2, 0x0($a3)
    /* A8484 8011FA14 00063080 */  sll        $a2, $a2, 2
    /* A8488 8011FA18 01267021 */  addu       $t6, $t1, $a2
    /* A848C 8011FA1C 10000081 */  b          .L8011FC24
    /* A8490 8011FA20 8DC50000 */   lw        $a1, 0x0($t6)
    /* A8494 8011FA24 AC6F0000 */  sw         $t7, 0x0($v1)
  .L8011FA28:
    /* A8498 8011FA28 8CE60000 */  lw         $a2, 0x0($a3)
    /* A849C 8011FA2C 00063080 */  sll        $a2, $a2, 2
    /* A84A0 8011FA30 0126C021 */  addu       $t8, $t1, $a2
    /* A84A4 8011FA34 1000007B */  b          .L8011FC24
    /* A84A8 8011FA38 8F050000 */   lw        $a1, 0x0($t8)
  .L8011FA3C:
    /* A84AC 8011FA3C 3C19800D */  lui        $t9, %hi(D_800D6F58 + 0x54)
    /* A84B0 8011FA40 8F396FAC */  lw         $t9, %lo(D_800D6F58 + 0x54)($t9)
    /* A84B4 8011FA44 3C0A800D */  lui        $t2, %hi(gKirbyController)
    /* A84B8 8011FA48 5720000D */  bnel       $t9, $zero, .L8011FA80
    /* A84BC 8011FA4C 240E0001 */   addiu     $t6, $zero, 0x1
    /* A84C0 8011FA50 954A6FE8 */  lhu        $t2, %lo(gKirbyController)($t2)
    /* A84C4 8011FA54 3C0C800F */  lui        $t4, %hi(D_800E8920)
    /* A84C8 8011FA58 01866021 */  addu       $t4, $t4, $a2
    /* A84CC 8011FA5C 314B0400 */  andi       $t3, $t2, 0x400
    /* A84D0 8011FA60 11600004 */  beqz       $t3, .L8011FA74
    /* A84D4 8011FA64 240D0001 */   addiu     $t5, $zero, 0x1
    /* A84D8 8011FA68 8D8C8920 */  lw         $t4, %lo(D_800E8920)($t4)
    /* A84DC 8011FA6C 51800046 */  beql       $t4, $zero, .L8011FB88
    /* A84E0 8011FA70 8D1800E8 */   lw        $t8, 0xE8($t0)
  .L8011FA74:
    /* A84E4 8011FA74 10000003 */  b          .L8011FA84
    /* A84E8 8011FA78 AC6D0000 */   sw        $t5, 0x0($v1)
    /* A84EC 8011FA7C 240E0001 */  addiu      $t6, $zero, 0x1
  .L8011FA80:
    /* A84F0 8011FA80 AC6E0000 */  sw         $t6, 0x0($v1)
  .L8011FA84:
    /* A84F4 8011FA84 8CE60000 */  lw         $a2, 0x0($a3)
    /* A84F8 8011FA88 00063080 */  sll        $a2, $a2, 2
    /* A84FC 8011FA8C 01267821 */  addu       $t7, $t1, $a2
    /* A8500 8011FA90 10000064 */  b          .L8011FC24
    /* A8504 8011FA94 8DE50000 */   lw        $a1, 0x0($t7)
  .L8011FA98:
    /* A8508 8011FA98 3C18800D */  lui        $t8, %hi(D_800D6F58 + 0x54)
    /* A850C 8011FA9C 8F186FAC */  lw         $t8, %lo(D_800D6F58 + 0x54)($t8)
    /* A8510 8011FAA0 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A8514 8011FAA4 57000038 */  bnel       $t8, $zero, .L8011FB88
    /* A8518 8011FAA8 8D1800E8 */   lw        $t8, 0xE8($t0)
    /* A851C 8011FAAC 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A8520 8011FAB0 3C0E800F */  lui        $t6, %hi(D_800E8920)
    /* A8524 8011FAB4 3C01800F */  lui        $at, %hi(D_800E9720)
    /* A8528 8011FAB8 30590800 */  andi       $t9, $v0, 0x800
    /* A852C 8011FABC 1320000B */  beqz       $t9, .L8011FAEC
    /* A8530 8011FAC0 01C67021 */   addu      $t6, $t6, $a2
    /* A8534 8011FAC4 00260821 */  addu       $at, $at, $a2
    /* A8538 8011FAC8 AC209720 */  sw         $zero, %lo(D_800E9720)($at)
    /* A853C 8011FACC 8CEB0000 */  lw         $t3, 0x0($a3)
    /* A8540 8011FAD0 240A0002 */  addiu      $t2, $zero, 0x2
    /* A8544 8011FAD4 000B6080 */  sll        $t4, $t3, 2
    /* A8548 8011FAD8 012C6821 */  addu       $t5, $t1, $t4
    /* A854C 8011FADC ADAA0000 */  sw         $t2, 0x0($t5)
    /* A8550 8011FAE0 8CE60000 */  lw         $a2, 0x0($a3)
    /* A8554 8011FAE4 10000027 */  b          .L8011FB84
    /* A8558 8011FAE8 00063080 */   sll       $a2, $a2, 2
  .L8011FAEC:
    /* A855C 8011FAEC 8DCE8920 */  lw         $t6, %lo(D_800E8920)($t6)
    /* A8560 8011FAF0 3C0F800F */  lui        $t7, %hi(D_800E9720)
    /* A8564 8011FAF4 25EF9720 */  addiu      $t7, $t7, %lo(D_800E9720)
    /* A8568 8011FAF8 15C00005 */  bnez       $t6, .L8011FB10
    /* A856C 8011FAFC 00CF2021 */   addu      $a0, $a2, $t7
    /* A8570 8011FB00 8C830000 */  lw         $v1, 0x0($a0)
    /* A8574 8011FB04 304A0400 */  andi       $t2, $v0, 0x400
    /* A8578 8011FB08 28610007 */  slti       $at, $v1, 0x7
    /* A857C 8011FB0C 1420000B */  bnez       $at, .L8011FB3C
  .L8011FB10:
    /* A8580 8011FB10 3C01800F */   lui       $at, %hi(D_800E9720)
    /* A8584 8011FB14 00260821 */  addu       $at, $at, $a2
    /* A8588 8011FB18 AC209720 */  sw         $zero, %lo(D_800E9720)($at)
    /* A858C 8011FB1C 8CF90000 */  lw         $t9, 0x0($a3)
    /* A8590 8011FB20 24180001 */  addiu      $t8, $zero, 0x1
    /* A8594 8011FB24 00195880 */  sll        $t3, $t9, 2
    /* A8598 8011FB28 012B6021 */  addu       $t4, $t1, $t3
    /* A859C 8011FB2C AD980000 */  sw         $t8, 0x0($t4)
    /* A85A0 8011FB30 8CE60000 */  lw         $a2, 0x0($a3)
    /* A85A4 8011FB34 10000013 */  b          .L8011FB84
    /* A85A8 8011FB38 00063080 */   sll       $a2, $a2, 2
  .L8011FB3C:
    /* A85AC 8011FB3C 1140000E */  beqz       $t2, .L8011FB78
    /* A85B0 8011FB40 246B0001 */   addiu     $t3, $v1, 0x1
    /* A85B4 8011FB44 1860000F */  blez       $v1, .L8011FB84
    /* A85B8 8011FB48 28610007 */   slti      $at, $v1, 0x7
    /* A85BC 8011FB4C 5020000E */  beql       $at, $zero, .L8011FB88
    /* A85C0 8011FB50 8D1800E8 */   lw        $t8, 0xE8($t0)
    /* A85C4 8011FB54 AC800000 */  sw         $zero, 0x0($a0)
    /* A85C8 8011FB58 8CEE0000 */  lw         $t6, 0x0($a3)
    /* A85CC 8011FB5C 240D0004 */  addiu      $t5, $zero, 0x4
    /* A85D0 8011FB60 000E7880 */  sll        $t7, $t6, 2
    /* A85D4 8011FB64 012FC821 */  addu       $t9, $t1, $t7
    /* A85D8 8011FB68 AF2D0000 */  sw         $t5, 0x0($t9)
    /* A85DC 8011FB6C 8CE60000 */  lw         $a2, 0x0($a3)
    /* A85E0 8011FB70 10000004 */  b          .L8011FB84
    /* A85E4 8011FB74 00063080 */   sll       $a2, $a2, 2
  .L8011FB78:
    /* A85E8 8011FB78 AC8B0000 */  sw         $t3, 0x0($a0)
    /* A85EC 8011FB7C 8CE60000 */  lw         $a2, 0x0($a3)
    /* A85F0 8011FB80 00063080 */  sll        $a2, $a2, 2
  .L8011FB84:
    /* A85F4 8011FB84 8D1800E8 */  lw         $t8, 0xE8($t0)
  .L8011FB88:
    /* A85F8 8011FB88 3C01800E */  lui        $at, %hi(D_800E6A10)
    /* A85FC 8011FB8C 00260821 */  addu       $at, $at, $a2
    /* A8600 8011FB90 1700001E */  bnez       $t8, .L8011FC0C
    /* A8604 8011FB94 01265821 */   addu      $t3, $t1, $a2
    /* A8608 8011FB98 C4206A10 */  lwc1       $f0, %lo(D_800E6A10)($at)
    /* A860C 8011FB9C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* A8610 8011FBA0 44819000 */  mtc1       $at, $f18
    /* A8614 8011FBA4 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* A8618 8011FBA8 3C0C8013 */  lui        $t4, %hi(D_8012BCA0)
    /* A861C 8011FBAC 46009032 */  c.eq.s     $f18, $f0
    /* A8620 8011FBB0 00000000 */  nop
    /* A8624 8011FBB4 45020007 */  bc1fl      .L8011FBD4
    /* A8628 8011FBB8 44812000 */   mtc1      $at, $f4
    /* A862C 8011FBBC 8D8CBCA0 */  lw         $t4, %lo(D_8012BCA0)($t4)
    /* A8630 8011FBC0 000C54C2 */  srl        $t2, $t4, 19
    /* A8634 8011FBC4 314E0004 */  andi       $t6, $t2, 0x4
    /* A8638 8011FBC8 51C0000C */  beql       $t6, $zero, .L8011FBFC
    /* A863C 8011FBCC 24040006 */   addiu     $a0, $zero, 0x6
    /* A8640 8011FBD0 44812000 */  mtc1       $at, $f4
  .L8011FBD4:
    /* A8644 8011FBD4 3C0F8013 */  lui        $t7, %hi(D_8012BCA0)
    /* A8648 8011FBD8 46002032 */  c.eq.s     $f4, $f0
    /* A864C 8011FBDC 00000000 */  nop
    /* A8650 8011FBE0 4500000A */  bc1f       .L8011FC0C
    /* A8654 8011FBE4 00000000 */   nop
    /* A8658 8011FBE8 8DEFBCA0 */  lw         $t7, %lo(D_8012BCA0)($t7)
    /* A865C 8011FBEC 000F6CC2 */  srl        $t5, $t7, 19
    /* A8660 8011FBF0 31B90020 */  andi       $t9, $t5, 0x20
    /* A8664 8011FBF4 17200005 */  bnez       $t9, .L8011FC0C
    /* A8668 8011FBF8 24040006 */   addiu     $a0, $zero, 0x6
  .L8011FBFC:
    /* A866C 8011FBFC 0C048BDB */  jal        set_kirby_action_1
    /* A8670 8011FC00 24050006 */   addiu     $a1, $zero, 0x6
    /* A8674 8011FC04 100000B8 */  b          .L8011FEE8
    /* A8678 8011FC08 00001025 */   or        $v0, $zero, $zero
  .L8011FC0C:
    /* A867C 8011FC0C 10000005 */  b          .L8011FC24
    /* A8680 8011FC10 8D650000 */   lw        $a1, 0x0($t3)
  .L8011FC14:
    /* A8684 8011FC14 0C04759F */  jal        func_8011D67C
    /* A8688 8011FC18 00000000 */   nop
    /* A868C 8011FC1C 100000B2 */  b          .L8011FEE8
    /* A8690 8011FC20 00001025 */   or        $v0, $zero, $zero
  .L8011FC24:
    /* A8694 8011FC24 24010001 */  addiu      $at, $zero, 0x1
    /* A8698 8011FC28 10A10003 */  beq        $a1, $at, .L8011FC38
    /* A869C 8011FC2C 24010005 */   addiu     $at, $zero, 0x5
    /* A86A0 8011FC30 54A10009 */  bnel       $a1, $at, .L8011FC58
    /* A86A4 8011FC34 24010004 */   addiu     $at, $zero, 0x4
  .L8011FC38:
    /* A86A8 8011FC38 0C0473D6 */  jal        func_8011CF58
    /* A86AC 8011FC3C 00000000 */   nop
    /* A86B0 8011FC40 3C09800F */  lui        $t1, %hi(D_800E98E0)
    /* A86B4 8011FC44 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A86B8 8011FC48 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A86BC 8011FC4C 1000009A */  b          .L8011FEB8
    /* A86C0 8011FC50 252998E0 */   addiu     $t1, $t1, %lo(D_800E98E0)
    /* A86C4 8011FC54 24010004 */  addiu      $at, $zero, 0x4
  .L8011FC58:
    /* A86C8 8011FC58 10A1005F */  beq        $a1, $at, .L8011FDD8
    /* A86CC 8011FC5C 3C02800F */   lui       $v0, %hi(D_800E8AE0)
    /* A86D0 8011FC60 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A86D4 8011FC64 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A86D8 8011FC68 3C01800E */  lui        $at, %hi(D_800E3210)
    /* A86DC 8011FC6C 00260821 */  addu       $at, $at, $a2
    /* A86E0 8011FC70 30580C00 */  andi       $t8, $v0, 0xC00
    /* A86E4 8011FC74 13000036 */  beqz       $t8, .L8011FD50
    /* A86E8 8011FC78 304C0800 */   andi      $t4, $v0, 0x800
    /* A86EC 8011FC7C 1180000F */  beqz       $t4, .L8011FCBC
    /* A86F0 8011FC80 3C0F800F */   lui       $t7, %hi(D_800E8AE0)
    /* A86F4 8011FC84 3C0A800F */  lui        $t2, %hi(D_800E8AE0)
    /* A86F8 8011FC88 01465021 */  addu       $t2, $t2, $a2
    /* A86FC 8011FC8C 8D4A8AE0 */  lw         $t2, %lo(D_800E8AE0)($t2)
    /* A8700 8011FC90 3C014020 */  lui        $at, (0x40200000 >> 16)
    /* A8704 8011FC94 314E0006 */  andi       $t6, $t2, 0x6
    /* A8708 8011FC98 55C00006 */  bnel       $t6, $zero, .L8011FCB4
    /* A870C 8011FC9C 44810000 */   mtc1      $at, $f0
    /* A8710 8011FCA0 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* A8714 8011FCA4 44810000 */  mtc1       $at, $f0
    /* A8718 8011FCA8 10000010 */  b          .L8011FCEC
    /* A871C 8011FCAC 00000000 */   nop
    /* A8720 8011FCB0 44810000 */  mtc1       $at, $f0
  .L8011FCB4:
    /* A8724 8011FCB4 1000000D */  b          .L8011FCEC
    /* A8728 8011FCB8 00000000 */   nop
  .L8011FCBC:
    /* A872C 8011FCBC 01E67821 */  addu       $t7, $t7, $a2
    /* A8730 8011FCC0 8DEF8AE0 */  lw         $t7, %lo(D_800E8AE0)($t7)
    /* A8734 8011FCC4 3C01C020 */  lui        $at, (0xC0200000 >> 16)
    /* A8738 8011FCC8 31ED0006 */  andi       $t5, $t7, 0x6
    /* A873C 8011FCCC 55A00006 */  bnel       $t5, $zero, .L8011FCE8
    /* A8740 8011FCD0 44810000 */   mtc1      $at, $f0
    /* A8744 8011FCD4 3C01C0A0 */  lui        $at, (0xC0A00000 >> 16)
    /* A8748 8011FCD8 44810000 */  mtc1       $at, $f0
    /* A874C 8011FCDC 10000003 */  b          .L8011FCEC
    /* A8750 8011FCE0 00000000 */   nop
    /* A8754 8011FCE4 44810000 */  mtc1       $at, $f0
  .L8011FCE8:
    /* A8758 8011FCE8 00000000 */  nop
  .L8011FCEC:
    /* A875C 8011FCEC 3C01800E */  lui        $at, %hi(D_800E3210)
    /* A8760 8011FCF0 44803000 */  mtc1       $zero, $f6
    /* A8764 8011FCF4 00260821 */  addu       $at, $at, $a2
    /* A8768 8011FCF8 E4203210 */  swc1       $f0, %lo(D_800E3210)($at)
    /* A876C 8011FCFC 8CF90000 */  lw         $t9, 0x0($a3)
    /* A8770 8011FD00 4606003C */  c.lt.s     $f0, $f6
    /* A8774 8011FD04 44806000 */  mtc1       $zero, $f12
    /* A8778 8011FD08 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A877C 8011FD0C 00195880 */  sll        $t3, $t9, 2
    /* A8780 8011FD10 002B0821 */  addu       $at, $at, $t3
    /* A8784 8011FD14 45000008 */  bc1f       .L8011FD38
    /* A8788 8011FD18 E42C3750 */   swc1      $f12, %lo(D_800E3750)($at)
    /* A878C 8011FD1C 8CF80000 */  lw         $t8, 0x0($a3)
    /* A8790 8011FD20 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8794 8011FD24 46000207 */  neg.s      $f8, $f0
    /* A8798 8011FD28 00186080 */  sll        $t4, $t8, 2
    /* A879C 8011FD2C 002C0821 */  addu       $at, $at, $t4
    /* A87A0 8011FD30 10000022 */  b          .L8011FDBC
    /* A87A4 8011FD34 E4283C90 */   swc1      $f8, %lo(D_800E3C90)($at)
  .L8011FD38:
    /* A87A8 8011FD38 8CEA0000 */  lw         $t2, 0x0($a3)
    /* A87AC 8011FD3C 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A87B0 8011FD40 000A7080 */  sll        $t6, $t2, 2
    /* A87B4 8011FD44 002E0821 */  addu       $at, $at, $t6
    /* A87B8 8011FD48 1000001C */  b          .L8011FDBC
    /* A87BC 8011FD4C E4203C90 */   swc1      $f0, %lo(D_800E3C90)($at)
  .L8011FD50:
    /* A87C0 8011FD50 44806000 */  mtc1       $zero, $f12
    /* A87C4 8011FD54 C42A3210 */  lwc1       $f10, %lo(D_800E3210)($at)
    /* A87C8 8011FD58 3C013F40 */  lui        $at, (0x3F400000 >> 16)
    /* A87CC 8011FD5C 460A603C */  c.lt.s     $f12, $f10
    /* A87D0 8011FD60 00000000 */  nop
    /* A87D4 8011FD64 4502000D */  bc1fl      .L8011FD9C
    /* A87D8 8011FD68 44819000 */   mtc1      $at, $f18
    /* A87DC 8011FD6C 3C01BF40 */  lui        $at, (0xBF400000 >> 16)
    /* A87E0 8011FD70 44818000 */  mtc1       $at, $f16
    /* A87E4 8011FD74 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A87E8 8011FD78 00260821 */  addu       $at, $at, $a2
    /* A87EC 8011FD7C E4303750 */  swc1       $f16, %lo(D_800E3750)($at)
    /* A87F0 8011FD80 8CEF0000 */  lw         $t7, 0x0($a3)
    /* A87F4 8011FD84 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A87F8 8011FD88 000F6880 */  sll        $t5, $t7, 2
    /* A87FC 8011FD8C 002D0821 */  addu       $at, $at, $t5
    /* A8800 8011FD90 1000000A */  b          .L8011FDBC
    /* A8804 8011FD94 E42C3C90 */   swc1      $f12, %lo(D_800E3C90)($at)
    /* A8808 8011FD98 44819000 */  mtc1       $at, $f18
  .L8011FD9C:
    /* A880C 8011FD9C 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A8810 8011FDA0 00260821 */  addu       $at, $at, $a2
    /* A8814 8011FDA4 E4323750 */  swc1       $f18, %lo(D_800E3750)($at)
    /* A8818 8011FDA8 8CF90000 */  lw         $t9, 0x0($a3)
    /* A881C 8011FDAC 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8820 8011FDB0 00195880 */  sll        $t3, $t9, 2
    /* A8824 8011FDB4 002B0821 */  addu       $at, $at, $t3
    /* A8828 8011FDB8 E42C3C90 */  swc1       $f12, %lo(D_800E3C90)($at)
  .L8011FDBC:
    /* A882C 8011FDBC 0C0473D6 */  jal        func_8011CF58
    /* A8830 8011FDC0 00000000 */   nop
    /* A8834 8011FDC4 3C09800F */  lui        $t1, %hi(D_800E98E0)
    /* A8838 8011FDC8 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A883C 8011FDCC 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A8840 8011FDD0 10000039 */  b          .L8011FEB8
    /* A8844 8011FDD4 252998E0 */   addiu     $t1, $t1, %lo(D_800E98E0)
  .L8011FDD8:
    /* A8848 8011FDD8 00461021 */  addu       $v0, $v0, $a2
    /* A884C 8011FDDC 8C428AE0 */  lw         $v0, %lo(D_800E8AE0)($v0)
    /* A8850 8011FDE0 3C013FC0 */  lui        $at, (0x3FC00000 >> 16)
    /* A8854 8011FDE4 30420006 */  andi       $v0, $v0, 0x6
    /* A8858 8011FDE8 54400006 */  bnel       $v0, $zero, .L8011FE04
    /* A885C 8011FDEC 44816000 */   mtc1      $at, $f12
    /* A8860 8011FDF0 3C014040 */  lui        $at, (0x40400000 >> 16)
    /* A8864 8011FDF4 44816000 */  mtc1       $at, $f12
    /* A8868 8011FDF8 10000003 */  b          .L8011FE08
    /* A886C 8011FDFC 00000000 */   nop
    /* A8870 8011FE00 44816000 */  mtc1       $at, $f12
  .L8011FE04:
    /* A8874 8011FE04 00000000 */  nop
  .L8011FE08:
    /* A8878 8011FE08 14400005 */  bnez       $v0, .L8011FE20
    /* A887C 8011FE0C 3C014090 */   lui       $at, (0x40900000 >> 16)
    /* A8880 8011FE10 3C014110 */  lui        $at, (0x41100000 >> 16)
    /* A8884 8011FE14 44810000 */  mtc1       $at, $f0
    /* A8888 8011FE18 10000004 */  b          .L8011FE2C
    /* A888C 8011FE1C E7A00020 */   swc1      $f0, 0x20($sp)
  .L8011FE20:
    /* A8890 8011FE20 44810000 */  mtc1       $at, $f0
    /* A8894 8011FE24 00000000 */  nop
    /* A8898 8011FE28 E7A00020 */  swc1       $f0, 0x20($sp)
  .L8011FE2C:
    /* A889C 8011FE2C 0C02BB30 */  jal        func_800AECC0
    /* A88A0 8011FE30 E7AC001C */   swc1      $f12, 0x1C($sp)
    /* A88A4 8011FE34 0C02BB48 */  jal        func_800AED20
    /* A88A8 8011FE38 C7AC001C */   lwc1      $f12, 0x1C($sp)
    /* A88AC 8011FE3C 3C078005 */  lui        $a3, %hi(omCurrentObj)
    /* A88B0 8011FE40 8CE7A7C4 */  lw         $a3, %lo(omCurrentObj)($a3)
    /* A88B4 8011FE44 C7A00020 */  lwc1       $f0, 0x20($sp)
    /* A88B8 8011FE48 3C01800E */  lui        $at, %hi(D_800E3210)
    /* A88BC 8011FE4C 8CF80000 */  lw         $t8, 0x0($a3)
    /* A88C0 8011FE50 46000087 */  neg.s      $f2, $f0
    /* A88C4 8011FE54 44802000 */  mtc1       $zero, $f4
    /* A88C8 8011FE58 00186080 */  sll        $t4, $t8, 2
    /* A88CC 8011FE5C 002C0821 */  addu       $at, $at, $t4
    /* A88D0 8011FE60 E4223210 */  swc1       $f2, %lo(D_800E3210)($at)
    /* A88D4 8011FE64 8CEA0000 */  lw         $t2, 0x0($a3)
    /* A88D8 8011FE68 4604003C */  c.lt.s     $f0, $f4
    /* A88DC 8011FE6C 44806000 */  mtc1       $zero, $f12
    /* A88E0 8011FE70 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A88E4 8011FE74 000A7080 */  sll        $t6, $t2, 2
    /* A88E8 8011FE78 3C09800F */  lui        $t1, %hi(D_800E98E0)
    /* A88EC 8011FE7C 002E0821 */  addu       $at, $at, $t6
    /* A88F0 8011FE80 252998E0 */  addiu      $t1, $t1, %lo(D_800E98E0)
    /* A88F4 8011FE84 45000007 */  bc1f       .L8011FEA4
    /* A88F8 8011FE88 E42C3750 */   swc1      $f12, %lo(D_800E3750)($at)
    /* A88FC 8011FE8C 8CEF0000 */  lw         $t7, 0x0($a3)
    /* A8900 8011FE90 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8904 8011FE94 000F6880 */  sll        $t5, $t7, 2
    /* A8908 8011FE98 002D0821 */  addu       $at, $at, $t5
    /* A890C 8011FE9C 10000006 */  b          .L8011FEB8
    /* A8910 8011FEA0 E4223C90 */   swc1      $f2, %lo(D_800E3C90)($at)
  .L8011FEA4:
    /* A8914 8011FEA4 8CF90000 */  lw         $t9, 0x0($a3)
    /* A8918 8011FEA8 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A891C 8011FEAC 00195880 */  sll        $t3, $t9, 2
    /* A8920 8011FEB0 002B0821 */  addu       $at, $at, $t3
    /* A8924 8011FEB4 E4203C90 */  swc1       $f0, %lo(D_800E3C90)($at)
  .L8011FEB8:
    /* A8928 8011FEB8 8CE60000 */  lw         $a2, 0x0($a3)
    /* A892C 8011FEBC 3C0C800F */  lui        $t4, %hi(D_800E9AA0)
    /* A8930 8011FEC0 00001025 */  or         $v0, $zero, $zero
    /* A8934 8011FEC4 00063080 */  sll        $a2, $a2, 2
    /* A8938 8011FEC8 0126C021 */  addu       $t8, $t1, $a2
    /* A893C 8011FECC 01866021 */  addu       $t4, $t4, $a2
    /* A8940 8011FED0 8D8C9AA0 */  lw         $t4, %lo(D_800E9AA0)($t4)
    /* A8944 8011FED4 8F050000 */  lw         $a1, 0x0($t8)
    /* A8948 8011FED8 10AC0003 */  beq        $a1, $t4, .L8011FEE8
    /* A894C 8011FEDC 00000000 */   nop
    /* A8950 8011FEE0 10000001 */  b          .L8011FEE8
    /* A8954 8011FEE4 00A01025 */   or        $v0, $a1, $zero
  .L8011FEE8:
    /* A8958 8011FEE8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* A895C 8011FEEC 27BD0028 */  addiu      $sp, $sp, 0x28
    /* A8960 8011FEF0 03E00008 */  jr         $ra
    /* A8964 8011FEF4 00000000 */   nop
endlabel func_8011F690
.size func_8011F690, . - func_8011F690
