.section .late_rodata
nonmatching jtbl_80129034

dlabel jtbl_80129034
    /* B1AA4 80129034 8011FFA8 */ .word .L8011FFA8
    /* B1AA8 80129038 801200BC */ .word .L801200BC
    /* B1AAC 8012903C 8012024C */ .word .L8012024C
    /* B1AB0 80129040 801201E0 */ .word .L801201E0
    /* B1AB4 80129044 801203C0 */ .word .L801203C0
    /* B1AB8 80129048 80120378 */ .word .L80120378
enddlabel jtbl_80129034
.size jtbl_80129034, . - jtbl_80129034

nonmatching D_8012904C

dlabel D_8012904C
    /* B1ABC 8012904C 3EC90FF9 */ .float 0.3926999867
enddlabel D_8012904C
.size D_8012904C, . - D_8012904C

nonmatching D_80129050

dlabel D_80129050
    /* B1AC0 80129050 3E490FF9 */ .float 0.1963499933
enddlabel D_80129050
.size D_80129050, . - D_80129050

nonmatching D_80129054

dlabel D_80129054
    /* B1AC4 80129054 40490FDB */ .float 3.141592741
enddlabel D_80129054
.size D_80129054, . - D_80129054

nonmatching D_80129058

dlabel D_80129058
    /* B1AC8 80129058 C0F33333 */ .float -7.599999905
enddlabel D_80129058
.size D_80129058, . - D_80129058

nonmatching D_8012905C

dlabel D_8012905C
    /* B1ACC 8012905C 40F33333 */ .float 7.599999905
enddlabel D_8012905C
.size D_8012905C, . - D_8012905C

nonmatching D_80129060

dlabel D_80129060
    /* B1AD0 80129060 C083D70A */ .float -4.119999886
enddlabel D_80129060
.size D_80129060, . - D_80129060

nonmatching D_80129064

dlabel D_80129064
    /* B1AD4 80129064 4083D70A */ .float 4.119999886
enddlabel D_80129064
.size D_80129064, . - D_80129064


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_8011FEF8, 0xB30

glabel func_8011FEF8
    /* A8968 8011FEF8 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A896C 8011FEFC 2529E7C0 */  addiu      $t1, $t1, %lo(gKirbyState)
    /* A8970 8011FF00 8D23003C */  lw         $v1, 0x3C($t1)
    /* A8974 8011FF04 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* A8978 8011FF08 AFBF0014 */  sw         $ra, 0x14($sp)
    /* A897C 8011FF0C 14600005 */  bnez       $v1, .L8011FF24
    /* A8980 8011FF10 3C068005 */   lui       $a2, %hi(omCurrentObj)
    /* A8984 8011FF14 912E0017 */  lbu        $t6, 0x17($t1)
    /* A8988 8011FF18 3C0F8005 */  lui        $t7, %hi(omCurrentObj)
    /* A898C 8011FF1C 11C00003 */  beqz       $t6, .L8011FF2C
    /* A8990 8011FF20 00000000 */   nop
  .L8011FF24:
    /* A8994 8011FF24 100001D0 */  b          .L80120668
    /* A8998 8011FF28 8CC6A7C4 */   lw        $a2, %lo(omCurrentObj)($a2)
  .L8011FF2C:
    /* A899C 8011FF2C 8DEFA7C4 */  lw         $t7, %lo(omCurrentObj)($t7)
    /* A89A0 8011FF30 3C18800F */  lui        $t8, %hi(D_800E98E0)
    /* A89A4 8011FF34 3C01800F */  lui        $at, %hi(D_800E9AA0)
    /* A89A8 8011FF38 8DE30000 */  lw         $v1, 0x0($t7)
    /* A89AC 8011FF3C 3C048013 */  lui        $a0, %hi(gPositionState)
    /* A89B0 8011FF40 2484E968 */  addiu      $a0, $a0, %lo(gPositionState)
    /* A89B4 8011FF44 00031880 */  sll        $v1, $v1, 2
    /* A89B8 8011FF48 0303C021 */  addu       $t8, $t8, $v1
    /* A89BC 8011FF4C 8F1898E0 */  lw         $t8, %lo(D_800E98E0)($t8)
    /* A89C0 8011FF50 00230821 */  addu       $at, $at, $v1
    /* A89C4 8011FF54 0C0432AF */  jal        func_8010CABC
    /* A89C8 8011FF58 AC389AA0 */   sw        $t8, %lo(D_800E9AA0)($at)
    /* A89CC 8011FF5C 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A89D0 8011FF60 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A89D4 8011FF64 3C0A800F */  lui        $t2, %hi(D_800E98E0)
    /* A89D8 8011FF68 254A98E0 */  addiu      $t2, $t2, %lo(D_800E98E0)
    /* A89DC 8011FF6C 8CC30000 */  lw         $v1, 0x0($a2)
    /* A89E0 8011FF70 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A89E4 8011FF74 2529E7C0 */  addiu      $t1, $t1, %lo(gKirbyState)
    /* A89E8 8011FF78 00031880 */  sll        $v1, $v1, 2
    /* A89EC 8011FF7C 01432021 */  addu       $a0, $t2, $v1
    /* A89F0 8011FF80 8C870000 */  lw         $a3, 0x0($a0)
    /* A89F4 8011FF84 24F9FFFF */  addiu      $t9, $a3, -0x1
    /* A89F8 8011FF88 2F210006 */  sltiu      $at, $t9, 0x6
    /* A89FC 8011FF8C 1020010E */  beqz       $at, .L801203C8
    /* A8A00 8011FF90 0019C880 */   sll       $t9, $t9, 2
    /* A8A04 8011FF94 3C018013 */  lui        $at, %hi(jtbl_80129034)
    /* A8A08 8011FF98 00390821 */  addu       $at, $at, $t9
    /* A8A0C 8011FF9C 8C399034 */  lw         $t9, %lo(jtbl_80129034)($at)
    /* A8A10 8011FFA0 03200008 */  jr         $t9
    /* A8A14 8011FFA4 00000000 */   nop
  .L8011FFA8:
    /* A8A18 8011FFA8 3C0B800F */  lui        $t3, %hi(D_800E8920)
    /* A8A1C 8011FFAC 01635821 */  addu       $t3, $t3, $v1
    /* A8A20 8011FFB0 8D6B8920 */  lw         $t3, %lo(D_800E8920)($t3)
    /* A8A24 8011FFB4 51600018 */  beql       $t3, $zero, .L80120018
    /* A8A28 8011FFB8 8D38003C */   lw        $t8, 0x3C($t1)
    /* A8A2C 8011FFBC 8D2C003C */  lw         $t4, 0x3C($t1)
    /* A8A30 8011FFC0 55800015 */  bnel       $t4, $zero, .L80120018
    /* A8A34 8011FFC4 8D38003C */   lw        $t8, 0x3C($t1)
    /* A8A38 8011FFC8 0C048465 */  jal        func_80121194
    /* A8A3C 8011FFCC 00000000 */   nop
    /* A8A40 8011FFD0 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A8A44 8011FFD4 1040000F */  beqz       $v0, .L80120014
    /* A8A48 8011FFD8 2529E7C0 */   addiu     $t1, $t1, %lo(gKirbyState)
    /* A8A4C 8011FFDC 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A8A50 8011FFE0 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A8A54 8011FFE4 3C01800F */  lui        $at, %hi(D_800E98E0)
    /* A8A58 8011FFE8 240D0005 */  addiu      $t5, $zero, 0x5
    /* A8A5C 8011FFEC 8CCE0000 */  lw         $t6, 0x0($a2)
    /* A8A60 8011FFF0 3C07800F */  lui        $a3, %hi(D_800E98E0)
    /* A8A64 8011FFF4 000E7880 */  sll        $t7, $t6, 2
    /* A8A68 8011FFF8 002F0821 */  addu       $at, $at, $t7
    /* A8A6C 8011FFFC AC2D98E0 */  sw         $t5, %lo(D_800E98E0)($at)
    /* A8A70 80120000 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8A74 80120004 00031880 */  sll        $v1, $v1, 2
    /* A8A78 80120008 00E33821 */  addu       $a3, $a3, $v1
    /* A8A7C 8012000C 100000EE */  b          .L801203C8
    /* A8A80 80120010 8CE798E0 */   lw        $a3, %lo(D_800E98E0)($a3)
  .L80120014:
    /* A8A84 80120014 8D38003C */  lw         $t8, 0x3C($t1)
  .L80120018:
    /* A8A88 80120018 3C0A800F */  lui        $t2, %hi(D_800E98E0)
    /* A8A8C 8012001C 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A8A90 80120020 254A98E0 */  addiu      $t2, $t2, %lo(D_800E98E0)
    /* A8A94 80120024 17000007 */  bnez       $t8, .L80120044
    /* A8A98 80120028 8CC6A7C4 */   lw        $a2, %lo(omCurrentObj)($a2)
    /* A8A9C 8012002C 3C19800D */  lui        $t9, %hi(gKirbyController)
    /* A8AA0 80120030 97396FE8 */  lhu        $t9, %lo(gKirbyController)($t9)
    /* A8AA4 80120034 332B0300 */  andi       $t3, $t9, 0x300
    /* A8AA8 80120038 55600003 */  bnel       $t3, $zero, .L80120048
    /* A8AAC 8012003C 8CC30000 */   lw        $v1, 0x0($a2)
    /* A8AB0 80120040 A1200007 */  sb         $zero, 0x7($t1)
  .L80120044:
    /* A8AB4 80120044 8CC30000 */  lw         $v1, 0x0($a2)
  .L80120048:
    /* A8AB8 80120048 3C0C800D */  lui        $t4, %hi(D_800D6F58 + 0x54)
    /* A8ABC 8012004C 8D8C6FAC */  lw         $t4, %lo(D_800D6F58 + 0x54)($t4)
    /* A8AC0 80120050 00031880 */  sll        $v1, $v1, 2
    /* A8AC4 80120054 01432021 */  addu       $a0, $t2, $v1
    /* A8AC8 80120058 15800016 */  bnez       $t4, .L801200B4
    /* A8ACC 8012005C 3C02800D */   lui       $v0, %hi(gKirbyController)
    /* A8AD0 80120060 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A8AD4 80120064 3C0F800F */  lui        $t7, %hi(D_800E8920)
    /* A8AD8 80120068 240D0002 */  addiu      $t5, $zero, 0x2
    /* A8ADC 8012006C 304E0800 */  andi       $t6, $v0, 0x800
    /* A8AE0 80120070 11C00006 */  beqz       $t6, .L8012008C
    /* A8AE4 80120074 01E37821 */   addu      $t7, $t7, $v1
    /* A8AE8 80120078 AC8D0000 */  sw         $t5, 0x0($a0)
    /* A8AEC 8012007C 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8AF0 80120080 00031880 */  sll        $v1, $v1, 2
    /* A8AF4 80120084 1000000B */  b          .L801200B4
    /* A8AF8 80120088 01432021 */   addu      $a0, $t2, $v1
  .L8012008C:
    /* A8AFC 8012008C 8DEF8920 */  lw         $t7, %lo(D_800E8920)($t7)
    /* A8B00 80120090 30580400 */  andi       $t8, $v0, 0x400
    /* A8B04 80120094 15E00007 */  bnez       $t7, .L801200B4
    /* A8B08 80120098 00000000 */   nop
    /* A8B0C 8012009C 13000005 */  beqz       $t8, .L801200B4
    /* A8B10 801200A0 24190003 */   addiu     $t9, $zero, 0x3
    /* A8B14 801200A4 AC990000 */  sw         $t9, 0x0($a0)
    /* A8B18 801200A8 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8B1C 801200AC 00031880 */  sll        $v1, $v1, 2
    /* A8B20 801200B0 01432021 */  addu       $a0, $t2, $v1
  .L801200B4:
    /* A8B24 801200B4 100000C4 */  b          .L801203C8
    /* A8B28 801200B8 8C870000 */   lw        $a3, 0x0($a0)
  .L801200BC:
    /* A8B2C 801200BC 3C0B800D */  lui        $t3, %hi(D_800D6F58 + 0x54)
    /* A8B30 801200C0 8D6B6FAC */  lw         $t3, %lo(D_800D6F58 + 0x54)($t3)
    /* A8B34 801200C4 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A8B38 801200C8 24180001 */  addiu      $t8, $zero, 0x1
    /* A8B3C 801200CC 5560003F */  bnel       $t3, $zero, .L801201CC
    /* A8B40 801200D0 AC980000 */   sw        $t8, 0x0($a0)
    /* A8B44 801200D4 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A8B48 801200D8 3C0C800F */  lui        $t4, %hi(D_800E9720)
    /* A8B4C 801200DC 258C9720 */  addiu      $t4, $t4, %lo(D_800E9720)
    /* A8B50 801200E0 30480800 */  andi       $t0, $v0, 0x800
    /* A8B54 801200E4 15000010 */  bnez       $t0, .L80120128
    /* A8B58 801200E8 006C2821 */   addu      $a1, $v1, $t4
    /* A8B5C 801200EC 8CAE0000 */  lw         $t6, 0x0($a1)
    /* A8B60 801200F0 29C10007 */  slti       $at, $t6, 0x7
    /* A8B64 801200F4 1420000C */  bnez       $at, .L80120128
    /* A8B68 801200F8 00000000 */   nop
    /* A8B6C 801200FC ACA00000 */  sw         $zero, 0x0($a1)
    /* A8B70 80120100 8CCF0000 */  lw         $t7, 0x0($a2)
    /* A8B74 80120104 240D0001 */  addiu      $t5, $zero, 0x1
    /* A8B78 80120108 000FC080 */  sll        $t8, $t7, 2
    /* A8B7C 8012010C 0158C821 */  addu       $t9, $t2, $t8
    /* A8B80 80120110 AF2D0000 */  sw         $t5, 0x0($t9)
    /* A8B84 80120114 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8B88 80120118 00031880 */  sll        $v1, $v1, 2
    /* A8B8C 8012011C 01435821 */  addu       $t3, $t2, $v1
    /* A8B90 80120120 100000A9 */  b          .L801203C8
    /* A8B94 80120124 8D670000 */   lw        $a3, 0x0($t3)
  .L80120128:
    /* A8B98 80120128 3C0E800F */  lui        $t6, %hi(D_800E8920)
    /* A8B9C 8012012C 01C37021 */  addu       $t6, $t6, $v1
    /* A8BA0 80120130 8DCE8920 */  lw         $t6, %lo(D_800E8920)($t6)
    /* A8BA4 80120134 3C0C800F */  lui        $t4, %hi(D_800E9720)
    /* A8BA8 80120138 258C9720 */  addiu      $t4, $t4, %lo(D_800E9720)
    /* A8BAC 8012013C 15C0000F */  bnez       $t6, .L8012017C
    /* A8BB0 80120140 006C2821 */   addu      $a1, $v1, $t4
    /* A8BB4 80120144 304F0400 */  andi       $t7, $v0, 0x400
    /* A8BB8 80120148 11E0000C */  beqz       $t7, .L8012017C
    /* A8BBC 8012014C 00000000 */   nop
    /* A8BC0 80120150 ACA00000 */  sw         $zero, 0x0($a1)
    /* A8BC4 80120154 8CCD0000 */  lw         $t5, 0x0($a2)
    /* A8BC8 80120158 24180003 */  addiu      $t8, $zero, 0x3
    /* A8BCC 8012015C 000DC880 */  sll        $t9, $t5, 2
    /* A8BD0 80120160 01595821 */  addu       $t3, $t2, $t9
    /* A8BD4 80120164 AD780000 */  sw         $t8, 0x0($t3)
    /* A8BD8 80120168 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8BDC 8012016C 00031880 */  sll        $v1, $v1, 2
    /* A8BE0 80120170 01436021 */  addu       $t4, $t2, $v1
    /* A8BE4 80120174 10000094 */  b          .L801203C8
    /* A8BE8 80120178 8D870000 */   lw        $a3, 0x0($t4)
  .L8012017C:
    /* A8BEC 8012017C 1100000B */  beqz       $t0, .L801201AC
    /* A8BF0 80120180 8CA40000 */   lw        $a0, 0x0($a1)
    /* A8BF4 80120184 18800090 */  blez       $a0, .L801203C8
    /* A8BF8 80120188 28810007 */   slti      $at, $a0, 0x7
    /* A8BFC 8012018C 1020008E */  beqz       $at, .L801203C8
    /* A8C00 80120190 240E0004 */   addiu     $t6, $zero, 0x4
    /* A8C04 80120194 ACAE0000 */  sw         $t6, 0x0($a1)
    /* A8C08 80120198 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8C0C 8012019C 00031880 */  sll        $v1, $v1, 2
    /* A8C10 801201A0 01437821 */  addu       $t7, $t2, $v1
    /* A8C14 801201A4 10000088 */  b          .L801203C8
    /* A8C18 801201A8 8DE70000 */   lw        $a3, 0x0($t7)
  .L801201AC:
    /* A8C1C 801201AC 248D0001 */  addiu      $t5, $a0, 0x1
    /* A8C20 801201B0 ACAD0000 */  sw         $t5, 0x0($a1)
    /* A8C24 801201B4 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8C28 801201B8 00031880 */  sll        $v1, $v1, 2
    /* A8C2C 801201BC 0143C821 */  addu       $t9, $t2, $v1
    /* A8C30 801201C0 10000081 */  b          .L801203C8
    /* A8C34 801201C4 8F270000 */   lw        $a3, 0x0($t9)
    /* A8C38 801201C8 AC980000 */  sw         $t8, 0x0($a0)
  .L801201CC:
    /* A8C3C 801201CC 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8C40 801201D0 00031880 */  sll        $v1, $v1, 2
    /* A8C44 801201D4 01435821 */  addu       $t3, $t2, $v1
    /* A8C48 801201D8 1000007B */  b          .L801203C8
    /* A8C4C 801201DC 8D670000 */   lw        $a3, 0x0($t3)
  .L801201E0:
    /* A8C50 801201E0 3C0C800D */  lui        $t4, %hi(D_800D6F58 + 0x54)
    /* A8C54 801201E4 8D8C6FAC */  lw         $t4, %lo(D_800D6F58 + 0x54)($t4)
    /* A8C58 801201E8 3C0E800D */  lui        $t6, %hi(gKirbyController)
    /* A8C5C 801201EC 240B0001 */  addiu      $t3, $zero, 0x1
    /* A8C60 801201F0 55800011 */  bnel       $t4, $zero, .L80120238
    /* A8C64 801201F4 AC8B0000 */   sw        $t3, 0x0($a0)
    /* A8C68 801201F8 95CE6FE8 */  lhu        $t6, %lo(gKirbyController)($t6)
    /* A8C6C 801201FC 3C0D800F */  lui        $t5, %hi(D_800E8920)
    /* A8C70 80120200 01A36821 */  addu       $t5, $t5, $v1
    /* A8C74 80120204 31CF0400 */  andi       $t7, $t6, 0x400
    /* A8C78 80120208 11E00004 */  beqz       $t7, .L8012021C
    /* A8C7C 8012020C 24190001 */   addiu     $t9, $zero, 0x1
    /* A8C80 80120210 8DAD8920 */  lw         $t5, %lo(D_800E8920)($t5)
    /* A8C84 80120214 51A0006D */  beql       $t5, $zero, .L801203CC
    /* A8C88 80120218 24010001 */   addiu     $at, $zero, 0x1
  .L8012021C:
    /* A8C8C 8012021C AC990000 */  sw         $t9, 0x0($a0)
    /* A8C90 80120220 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8C94 80120224 00031880 */  sll        $v1, $v1, 2
    /* A8C98 80120228 0143C021 */  addu       $t8, $t2, $v1
    /* A8C9C 8012022C 10000066 */  b          .L801203C8
    /* A8CA0 80120230 8F070000 */   lw        $a3, 0x0($t8)
    /* A8CA4 80120234 AC8B0000 */  sw         $t3, 0x0($a0)
  .L80120238:
    /* A8CA8 80120238 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8CAC 8012023C 00031880 */  sll        $v1, $v1, 2
    /* A8CB0 80120240 01436021 */  addu       $t4, $t2, $v1
    /* A8CB4 80120244 10000060 */  b          .L801203C8
    /* A8CB8 80120248 8D870000 */   lw        $a3, 0x0($t4)
  .L8012024C:
    /* A8CBC 8012024C 3C0E800D */  lui        $t6, %hi(D_800D6F58 + 0x54)
    /* A8CC0 80120250 8DCE6FAC */  lw         $t6, %lo(D_800D6F58 + 0x54)($t6)
    /* A8CC4 80120254 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A8CC8 80120258 24180001 */  addiu      $t8, $zero, 0x1
    /* A8CCC 8012025C 55C00041 */  bnel       $t6, $zero, .L80120364
    /* A8CD0 80120260 AC980000 */   sw        $t8, 0x0($a0)
    /* A8CD4 80120264 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A8CD8 80120268 3C0E800F */  lui        $t6, %hi(D_800E8920)
    /* A8CDC 8012026C 3C01800F */  lui        $at, %hi(D_800E9720)
    /* A8CE0 80120270 304F0800 */  andi       $t7, $v0, 0x800
    /* A8CE4 80120274 11E0000D */  beqz       $t7, .L801202AC
    /* A8CE8 80120278 01C37021 */   addu      $t6, $t6, $v1
    /* A8CEC 8012027C 00230821 */  addu       $at, $at, $v1
    /* A8CF0 80120280 AC209720 */  sw         $zero, %lo(D_800E9720)($at)
    /* A8CF4 80120284 8CD90000 */  lw         $t9, 0x0($a2)
    /* A8CF8 80120288 240D0002 */  addiu      $t5, $zero, 0x2
    /* A8CFC 8012028C 0019C080 */  sll        $t8, $t9, 2
    /* A8D00 80120290 01585821 */  addu       $t3, $t2, $t8
    /* A8D04 80120294 AD6D0000 */  sw         $t5, 0x0($t3)
    /* A8D08 80120298 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8D0C 8012029C 00031880 */  sll        $v1, $v1, 2
    /* A8D10 801202A0 01436021 */  addu       $t4, $t2, $v1
    /* A8D14 801202A4 10000048 */  b          .L801203C8
    /* A8D18 801202A8 8D870000 */   lw        $a3, 0x0($t4)
  .L801202AC:
    /* A8D1C 801202AC 8DCE8920 */  lw         $t6, %lo(D_800E8920)($t6)
    /* A8D20 801202B0 3C0F800F */  lui        $t7, %hi(D_800E9720)
    /* A8D24 801202B4 25EF9720 */  addiu      $t7, $t7, %lo(D_800E9720)
    /* A8D28 801202B8 15C00005 */  bnez       $t6, .L801202D0
    /* A8D2C 801202BC 006F2821 */   addu      $a1, $v1, $t7
    /* A8D30 801202C0 8CA40000 */  lw         $a0, 0x0($a1)
    /* A8D34 801202C4 304E0400 */  andi       $t6, $v0, 0x400
    /* A8D38 801202C8 28810007 */  slti       $at, $a0, 0x7
    /* A8D3C 801202CC 1420000D */  bnez       $at, .L80120304
  .L801202D0:
    /* A8D40 801202D0 3C01800F */   lui       $at, %hi(D_800E9720)
    /* A8D44 801202D4 00230821 */  addu       $at, $at, $v1
    /* A8D48 801202D8 AC209720 */  sw         $zero, %lo(D_800E9720)($at)
    /* A8D4C 801202DC 8CD80000 */  lw         $t8, 0x0($a2)
    /* A8D50 801202E0 24190001 */  addiu      $t9, $zero, 0x1
    /* A8D54 801202E4 00186880 */  sll        $t5, $t8, 2
    /* A8D58 801202E8 014D5821 */  addu       $t3, $t2, $t5
    /* A8D5C 801202EC AD790000 */  sw         $t9, 0x0($t3)
    /* A8D60 801202F0 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8D64 801202F4 00031880 */  sll        $v1, $v1, 2
    /* A8D68 801202F8 01436021 */  addu       $t4, $t2, $v1
    /* A8D6C 801202FC 10000032 */  b          .L801203C8
    /* A8D70 80120300 8D870000 */   lw        $a3, 0x0($t4)
  .L80120304:
    /* A8D74 80120304 11C00010 */  beqz       $t6, .L80120348
    /* A8D78 80120308 248C0001 */   addiu     $t4, $a0, 0x1
    /* A8D7C 8012030C 1880002E */  blez       $a0, .L801203C8
    /* A8D80 80120310 28810007 */   slti      $at, $a0, 0x7
    /* A8D84 80120314 5020002D */  beql       $at, $zero, .L801203CC
    /* A8D88 80120318 24010001 */   addiu     $at, $zero, 0x1
    /* A8D8C 8012031C ACA00000 */  sw         $zero, 0x0($a1)
    /* A8D90 80120320 8CD80000 */  lw         $t8, 0x0($a2)
    /* A8D94 80120324 240F0004 */  addiu      $t7, $zero, 0x4
    /* A8D98 80120328 00186880 */  sll        $t5, $t8, 2
    /* A8D9C 8012032C 014DC821 */  addu       $t9, $t2, $t5
    /* A8DA0 80120330 AF2F0000 */  sw         $t7, 0x0($t9)
    /* A8DA4 80120334 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8DA8 80120338 00031880 */  sll        $v1, $v1, 2
    /* A8DAC 8012033C 01435821 */  addu       $t3, $t2, $v1
    /* A8DB0 80120340 10000021 */  b          .L801203C8
    /* A8DB4 80120344 8D670000 */   lw        $a3, 0x0($t3)
  .L80120348:
    /* A8DB8 80120348 ACAC0000 */  sw         $t4, 0x0($a1)
    /* A8DBC 8012034C 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8DC0 80120350 00031880 */  sll        $v1, $v1, 2
    /* A8DC4 80120354 01437021 */  addu       $t6, $t2, $v1
    /* A8DC8 80120358 1000001B */  b          .L801203C8
    /* A8DCC 8012035C 8DC70000 */   lw        $a3, 0x0($t6)
    /* A8DD0 80120360 AC980000 */  sw         $t8, 0x0($a0)
  .L80120364:
    /* A8DD4 80120364 8CC30000 */  lw         $v1, 0x0($a2)
    /* A8DD8 80120368 00031880 */  sll        $v1, $v1, 2
    /* A8DDC 8012036C 01436821 */  addu       $t5, $t2, $v1
    /* A8DE0 80120370 10000015 */  b          .L801203C8
    /* A8DE4 80120374 8DA70000 */   lw        $a3, 0x0($t5)
  .L80120378:
    /* A8DE8 80120378 912F0007 */  lbu        $t7, 0x7($t1)
    /* A8DEC 8012037C 24010001 */  addiu      $at, $zero, 0x1
    /* A8DF0 80120380 55E1000D */  bnel       $t7, $at, .L801203B8
    /* A8DF4 80120384 00002025 */   or        $a0, $zero, $zero
    /* A8DF8 80120388 8D390034 */  lw         $t9, 0x34($t1)
    /* A8DFC 8012038C 44802000 */  mtc1       $zero, $f4
    /* A8E00 80120390 AD200044 */  sw         $zero, 0x44($t1)
    /* A8E04 80120394 372B0001 */  ori        $t3, $t9, 0x1
    /* A8E08 80120398 AD2B0034 */  sw         $t3, 0x34($t1)
    /* A8E0C 8012039C 24040002 */  addiu      $a0, $zero, 0x2
    /* A8E10 801203A0 24050004 */  addiu      $a1, $zero, 0x4
    /* A8E14 801203A4 0C048BDB */  jal        set_kirby_action_1
    /* A8E18 801203A8 E5240038 */   swc1      $f4, 0x38($t1)
    /* A8E1C 801203AC 1000019A */  b          .L80120A18
    /* A8E20 801203B0 00001025 */   or        $v0, $zero, $zero
    /* A8E24 801203B4 00002025 */  or         $a0, $zero, $zero
  .L801203B8:
    /* A8E28 801203B8 0C048BDB */  jal        set_kirby_action_1
    /* A8E2C 801203BC 24050001 */   addiu     $a1, $zero, 0x1
  .L801203C0:
    /* A8E30 801203C0 10000195 */  b          .L80120A18
    /* A8E34 801203C4 00001025 */   or        $v0, $zero, $zero
  .L801203C8:
    /* A8E38 801203C8 24010001 */  addiu      $at, $zero, 0x1
  .L801203CC:
    /* A8E3C 801203CC 10E10003 */  beq        $a3, $at, .L801203DC
    /* A8E40 801203D0 24010005 */   addiu     $at, $zero, 0x5
    /* A8E44 801203D4 54E10009 */  bnel       $a3, $at, .L801203FC
    /* A8E48 801203D8 24010004 */   addiu     $at, $zero, 0x4
  .L801203DC:
    /* A8E4C 801203DC 0C0473D6 */  jal        func_8011CF58
    /* A8E50 801203E0 00000000 */   nop
    /* A8E54 801203E4 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A8E58 801203E8 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A8E5C 801203EC 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A8E60 801203F0 1000009C */  b          .L80120664
    /* A8E64 801203F4 2529E7C0 */   addiu     $t1, $t1, %lo(gKirbyState)
    /* A8E68 801203F8 24010004 */  addiu      $at, $zero, 0x4
  .L801203FC:
    /* A8E6C 801203FC 10E10061 */  beq        $a3, $at, .L80120584
    /* A8E70 80120400 3C02800F */   lui       $v0, %hi(D_800E8AE0)
    /* A8E74 80120404 3C02800D */  lui        $v0, %hi(gKirbyController)
    /* A8E78 80120408 94426FE8 */  lhu        $v0, %lo(gKirbyController)($v0)
    /* A8E7C 8012040C 3C01800E */  lui        $at, %hi(D_800E3210)
    /* A8E80 80120410 00230821 */  addu       $at, $at, $v1
    /* A8E84 80120414 304C0C00 */  andi       $t4, $v0, 0xC00
    /* A8E88 80120418 11800036 */  beqz       $t4, .L801204F4
    /* A8E8C 8012041C 304E0800 */   andi      $t6, $v0, 0x800
    /* A8E90 80120420 11C0000F */  beqz       $t6, .L80120460
    /* A8E94 80120424 3C0F800F */   lui       $t7, %hi(D_800E8AE0)
    /* A8E98 80120428 3C18800F */  lui        $t8, %hi(D_800E8AE0)
    /* A8E9C 8012042C 0303C021 */  addu       $t8, $t8, $v1
    /* A8EA0 80120430 8F188AE0 */  lw         $t8, %lo(D_800E8AE0)($t8)
    /* A8EA4 80120434 3C014020 */  lui        $at, (0x40200000 >> 16)
    /* A8EA8 80120438 330D0006 */  andi       $t5, $t8, 0x6
    /* A8EAC 8012043C 55A00006 */  bnel       $t5, $zero, .L80120458
    /* A8EB0 80120440 44810000 */   mtc1      $at, $f0
    /* A8EB4 80120444 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
    /* A8EB8 80120448 44810000 */  mtc1       $at, $f0
    /* A8EBC 8012044C 10000010 */  b          .L80120490
    /* A8EC0 80120450 00000000 */   nop
    /* A8EC4 80120454 44810000 */  mtc1       $at, $f0
  .L80120458:
    /* A8EC8 80120458 1000000D */  b          .L80120490
    /* A8ECC 8012045C 00000000 */   nop
  .L80120460:
    /* A8ED0 80120460 01E37821 */  addu       $t7, $t7, $v1
    /* A8ED4 80120464 8DEF8AE0 */  lw         $t7, %lo(D_800E8AE0)($t7)
    /* A8ED8 80120468 3C01C020 */  lui        $at, (0xC0200000 >> 16)
    /* A8EDC 8012046C 31F90006 */  andi       $t9, $t7, 0x6
    /* A8EE0 80120470 57200006 */  bnel       $t9, $zero, .L8012048C
    /* A8EE4 80120474 44810000 */   mtc1      $at, $f0
    /* A8EE8 80120478 3C01C0A0 */  lui        $at, (0xC0A00000 >> 16)
    /* A8EEC 8012047C 44810000 */  mtc1       $at, $f0
    /* A8EF0 80120480 10000003 */  b          .L80120490
    /* A8EF4 80120484 00000000 */   nop
    /* A8EF8 80120488 44810000 */  mtc1       $at, $f0
  .L8012048C:
    /* A8EFC 8012048C 00000000 */  nop
  .L80120490:
    /* A8F00 80120490 3C01800E */  lui        $at, %hi(D_800E3210)
    /* A8F04 80120494 44804000 */  mtc1       $zero, $f8
    /* A8F08 80120498 00230821 */  addu       $at, $at, $v1
    /* A8F0C 8012049C E4203210 */  swc1       $f0, %lo(D_800E3210)($at)
    /* A8F10 801204A0 8CCB0000 */  lw         $t3, 0x0($a2)
    /* A8F14 801204A4 4608003C */  c.lt.s     $f0, $f8
    /* A8F18 801204A8 44803000 */  mtc1       $zero, $f6
    /* A8F1C 801204AC 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A8F20 801204B0 000B6080 */  sll        $t4, $t3, 2
    /* A8F24 801204B4 002C0821 */  addu       $at, $at, $t4
    /* A8F28 801204B8 45000008 */  bc1f       .L801204DC
    /* A8F2C 801204BC E4263750 */   swc1      $f6, %lo(D_800E3750)($at)
    /* A8F30 801204C0 8CCE0000 */  lw         $t6, 0x0($a2)
    /* A8F34 801204C4 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8F38 801204C8 46000287 */  neg.s      $f10, $f0
    /* A8F3C 801204CC 000EC080 */  sll        $t8, $t6, 2
    /* A8F40 801204D0 00380821 */  addu       $at, $at, $t8
    /* A8F44 801204D4 10000024 */  b          .L80120568
    /* A8F48 801204D8 E42A3C90 */   swc1      $f10, %lo(D_800E3C90)($at)
  .L801204DC:
    /* A8F4C 801204DC 8CCD0000 */  lw         $t5, 0x0($a2)
    /* A8F50 801204E0 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8F54 801204E4 000D7880 */  sll        $t7, $t5, 2
    /* A8F58 801204E8 002F0821 */  addu       $at, $at, $t7
    /* A8F5C 801204EC 1000001E */  b          .L80120568
    /* A8F60 801204F0 E4203C90 */   swc1      $f0, %lo(D_800E3C90)($at)
  .L801204F4:
    /* A8F64 801204F4 44808000 */  mtc1       $zero, $f16
    /* A8F68 801204F8 C4323210 */  lwc1       $f18, %lo(D_800E3210)($at)
    /* A8F6C 801204FC 3C013F40 */  lui        $at, (0x3F400000 >> 16)
    /* A8F70 80120500 4612803C */  c.lt.s     $f16, $f18
    /* A8F74 80120504 00000000 */  nop
    /* A8F78 80120508 4502000E */  bc1fl      .L80120544
    /* A8F7C 8012050C 44814000 */   mtc1      $at, $f8
    /* A8F80 80120510 3C01BF40 */  lui        $at, (0xBF400000 >> 16)
    /* A8F84 80120514 44812000 */  mtc1       $at, $f4
    /* A8F88 80120518 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A8F8C 8012051C 00230821 */  addu       $at, $at, $v1
    /* A8F90 80120520 E4243750 */  swc1       $f4, %lo(D_800E3750)($at)
    /* A8F94 80120524 8CD90000 */  lw         $t9, 0x0($a2)
    /* A8F98 80120528 44803000 */  mtc1       $zero, $f6
    /* A8F9C 8012052C 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8FA0 80120530 00195880 */  sll        $t3, $t9, 2
    /* A8FA4 80120534 002B0821 */  addu       $at, $at, $t3
    /* A8FA8 80120538 1000000B */  b          .L80120568
    /* A8FAC 8012053C E4263C90 */   swc1      $f6, %lo(D_800E3C90)($at)
    /* A8FB0 80120540 44814000 */  mtc1       $at, $f8
  .L80120544:
    /* A8FB4 80120544 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A8FB8 80120548 00230821 */  addu       $at, $at, $v1
    /* A8FBC 8012054C E4283750 */  swc1       $f8, %lo(D_800E3750)($at)
    /* A8FC0 80120550 8CCC0000 */  lw         $t4, 0x0($a2)
    /* A8FC4 80120554 44805000 */  mtc1       $zero, $f10
    /* A8FC8 80120558 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A8FCC 8012055C 000C7080 */  sll        $t6, $t4, 2
    /* A8FD0 80120560 002E0821 */  addu       $at, $at, $t6
    /* A8FD4 80120564 E42A3C90 */  swc1       $f10, %lo(D_800E3C90)($at)
  .L80120568:
    /* A8FD8 80120568 0C0473D6 */  jal        func_8011CF58
    /* A8FDC 8012056C 00000000 */   nop
    /* A8FE0 80120570 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A8FE4 80120574 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A8FE8 80120578 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A8FEC 8012057C 10000039 */  b          .L80120664
    /* A8FF0 80120580 2529E7C0 */   addiu     $t1, $t1, %lo(gKirbyState)
  .L80120584:
    /* A8FF4 80120584 00431021 */  addu       $v0, $v0, $v1
    /* A8FF8 80120588 8C428AE0 */  lw         $v0, %lo(D_800E8AE0)($v0)
    /* A8FFC 8012058C 3C013FC0 */  lui        $at, (0x3FC00000 >> 16)
    /* A9000 80120590 30420006 */  andi       $v0, $v0, 0x6
    /* A9004 80120594 54400006 */  bnel       $v0, $zero, .L801205B0
    /* A9008 80120598 44816000 */   mtc1      $at, $f12
    /* A900C 8012059C 3C014040 */  lui        $at, (0x40400000 >> 16)
    /* A9010 801205A0 44816000 */  mtc1       $at, $f12
    /* A9014 801205A4 10000003 */  b          .L801205B4
    /* A9018 801205A8 00000000 */   nop
    /* A901C 801205AC 44816000 */  mtc1       $at, $f12
  .L801205B0:
    /* A9020 801205B0 00000000 */  nop
  .L801205B4:
    /* A9024 801205B4 14400005 */  bnez       $v0, .L801205CC
    /* A9028 801205B8 3C014090 */   lui       $at, (0x40900000 >> 16)
    /* A902C 801205BC 3C014110 */  lui        $at, (0x41100000 >> 16)
    /* A9030 801205C0 44810000 */  mtc1       $at, $f0
    /* A9034 801205C4 10000004 */  b          .L801205D8
    /* A9038 801205C8 E7A00058 */   swc1      $f0, 0x58($sp)
  .L801205CC:
    /* A903C 801205CC 44810000 */  mtc1       $at, $f0
    /* A9040 801205D0 00000000 */  nop
    /* A9044 801205D4 E7A00058 */  swc1       $f0, 0x58($sp)
  .L801205D8:
    /* A9048 801205D8 0C02BB30 */  jal        func_800AECC0
    /* A904C 801205DC E7AC0054 */   swc1      $f12, 0x54($sp)
    /* A9050 801205E0 0C02BB48 */  jal        func_800AED20
    /* A9054 801205E4 C7AC0054 */   lwc1      $f12, 0x54($sp)
    /* A9058 801205E8 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A905C 801205EC 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A9060 801205F0 C7A00058 */  lwc1       $f0, 0x58($sp)
    /* A9064 801205F4 3C01800E */  lui        $at, %hi(D_800E3210)
    /* A9068 801205F8 8CD80000 */  lw         $t8, 0x0($a2)
    /* A906C 801205FC 46000087 */  neg.s      $f2, $f0
    /* A9070 80120600 44809000 */  mtc1       $zero, $f18
    /* A9074 80120604 00186880 */  sll        $t5, $t8, 2
    /* A9078 80120608 002D0821 */  addu       $at, $at, $t5
    /* A907C 8012060C E4223210 */  swc1       $f2, %lo(D_800E3210)($at)
    /* A9080 80120610 8CCF0000 */  lw         $t7, 0x0($a2)
    /* A9084 80120614 4612003C */  c.lt.s     $f0, $f18
    /* A9088 80120618 44808000 */  mtc1       $zero, $f16
    /* A908C 8012061C 3C01800E */  lui        $at, %hi(D_800E3750)
    /* A9090 80120620 000FC880 */  sll        $t9, $t7, 2
    /* A9094 80120624 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A9098 80120628 00390821 */  addu       $at, $at, $t9
    /* A909C 8012062C 2529E7C0 */  addiu      $t1, $t1, %lo(gKirbyState)
    /* A90A0 80120630 45000007 */  bc1f       .L80120650
    /* A90A4 80120634 E4303750 */   swc1      $f16, %lo(D_800E3750)($at)
    /* A90A8 80120638 8CCB0000 */  lw         $t3, 0x0($a2)
    /* A90AC 8012063C 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A90B0 80120640 000B6080 */  sll        $t4, $t3, 2
    /* A90B4 80120644 002C0821 */  addu       $at, $at, $t4
    /* A90B8 80120648 10000006 */  b          .L80120664
    /* A90BC 8012064C E4223C90 */   swc1      $f2, %lo(D_800E3C90)($at)
  .L80120650:
    /* A90C0 80120650 8CCE0000 */  lw         $t6, 0x0($a2)
    /* A90C4 80120654 3C01800E */  lui        $at, %hi(D_800E3C90)
    /* A90C8 80120658 000EC080 */  sll        $t8, $t6, 2
    /* A90CC 8012065C 00380821 */  addu       $at, $at, $t8
    /* A90D0 80120660 E4203C90 */  swc1       $f0, %lo(D_800E3C90)($at)
  .L80120664:
    /* A90D4 80120664 8D23003C */  lw         $v1, 0x3C($t1)
  .L80120668:
    /* A90D8 80120668 54600028 */  bnel       $v1, $zero, .L8012070C
    /* A90DC 8012066C 8CCB0000 */   lw        $t3, 0x0($a2)
    /* A90E0 80120670 8CC30000 */  lw         $v1, 0x0($a2)
    /* A90E4 80120674 3C0D800F */  lui        $t5, %hi(D_800E98E0)
    /* A90E8 80120678 3C0F800F */  lui        $t7, %hi(D_800E9AA0)
    /* A90EC 8012067C 00031880 */  sll        $v1, $v1, 2
    /* A90F0 80120680 01A36821 */  addu       $t5, $t5, $v1
    /* A90F4 80120684 01E37821 */  addu       $t7, $t7, $v1
    /* A90F8 80120688 8DEF9AA0 */  lw         $t7, %lo(D_800E9AA0)($t7)
    /* A90FC 8012068C 8DAD98E0 */  lw         $t5, %lo(D_800E98E0)($t5)
    /* A9100 80120690 15AF0012 */  bne        $t5, $t7, .L801206DC
    /* A9104 80120694 00000000 */   nop
    /* A9108 80120698 0C04843F */  jal        func_801210FC
    /* A910C 8012069C 00000000 */   nop
    /* A9110 801206A0 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A9114 801206A4 1040000D */  beqz       $v0, .L801206DC
    /* A9118 801206A8 2529E7C0 */   addiu     $t1, $t1, %lo(gKirbyState)
    /* A911C 801206AC 3C0B8005 */  lui        $t3, %hi(omCurrentObj)
    /* A9120 801206B0 8D6BA7C4 */  lw         $t3, %lo(omCurrentObj)($t3)
    /* A9124 801206B4 8D39015C */  lw         $t9, 0x15C($t1)
    /* A9128 801206B8 3C01800F */  lui        $at, %hi(D_800EA360)
    /* A912C 801206BC 8D6C0000 */  lw         $t4, 0x0($t3)
    /* A9130 801206C0 000C7080 */  sll        $t6, $t4, 2
    /* A9134 801206C4 002E0821 */  addu       $at, $at, $t6
    /* A9138 801206C8 AC39A360 */  sw         $t9, %lo(D_800EA360)($at)
    /* A913C 801206CC 8D38003C */  lw         $t8, 0x3C($t1)
    /* A9140 801206D0 AD20015C */  sw         $zero, 0x15C($t1)
    /* A9144 801206D4 270D0001 */  addiu      $t5, $t8, 0x1
    /* A9148 801206D8 AD2D003C */  sw         $t5, 0x3C($t1)
  .L801206DC:
    /* A914C 801206DC 3C0F8005 */  lui        $t7, %hi(omCurrentObj)
    /* A9150 801206E0 8DEFA7C4 */  lw         $t7, %lo(omCurrentObj)($t7)
    /* A9154 801206E4 3C07800F */  lui        $a3, %hi(D_800E98E0)
    /* A9158 801206E8 3C04800F */  lui        $a0, %hi(D_800E9AA0)
    /* A915C 801206EC 8DE30000 */  lw         $v1, 0x0($t7)
    /* A9160 801206F0 00031880 */  sll        $v1, $v1, 2
    /* A9164 801206F4 00E33821 */  addu       $a3, $a3, $v1
    /* A9168 801206F8 00832021 */  addu       $a0, $a0, $v1
    /* A916C 801206FC 8C849AA0 */  lw         $a0, %lo(D_800E9AA0)($a0)
    /* A9170 80120700 100000C1 */  b          .L80120A08
    /* A9174 80120704 8CE798E0 */   lw        $a3, %lo(D_800E98E0)($a3)
    /* A9178 80120708 8CCB0000 */  lw         $t3, 0x0($a2)
  .L8012070C:
    /* A917C 8012070C 3C02800F */  lui        $v0, %hi(D_800E8AE0)
    /* A9180 80120710 3C018013 */  lui        $at, %hi(D_80129050)
    /* A9184 80120714 000B6080 */  sll        $t4, $t3, 2
    /* A9188 80120718 004C1021 */  addu       $v0, $v0, $t4
    /* A918C 8012071C 8C428AE0 */  lw         $v0, %lo(D_800E8AE0)($v0)
    /* A9190 80120720 3C0F800D */  lui        $t7, %hi(D_800D7088)
    /* A9194 80120724 30420006 */  andi       $v0, $v0, 0x6
    /* A9198 80120728 14400004 */  bnez       $v0, .L8012073C
    /* A919C 8012072C 00000000 */   nop
    /* A91A0 80120730 3C018013 */  lui        $at, %hi(D_8012904C)
    /* A91A4 80120734 10000002 */  b          .L80120740
    /* A91A8 80120738 C420904C */   lwc1      $f0, %lo(D_8012904C)($at)
  .L8012073C:
    /* A91AC 8012073C C4209050 */  lwc1       $f0, %lo(D_80129050)($at)
  .L80120740:
    /* A91B0 80120740 50400004 */  beql       $v0, $zero, .L80120754
    /* A91B4 80120744 24020008 */   addiu     $v0, $zero, 0x8
    /* A91B8 80120748 10000002 */  b          .L80120754
    /* A91BC 8012074C 24020010 */   addiu     $v0, $zero, 0x10
    /* A91C0 80120750 24020008 */  addiu      $v0, $zero, 0x8
  .L80120754:
    /* A91C4 80120754 0062082A */  slt        $at, $v1, $v0
    /* A91C8 80120758 10200014 */  beqz       $at, .L801207AC
    /* A91CC 8012075C 00000000 */   nop
    /* A91D0 80120760 8CD9003C */  lw         $t9, 0x3C($a2)
    /* A91D4 80120764 3C0D8005 */  lui        $t5, %hi(omCurrentObj)
    /* A91D8 80120768 3C07800F */  lui        $a3, %hi(D_800E98E0)
    /* A91DC 8012076C 8F220010 */  lw         $v0, 0x10($t9)
    /* A91E0 80120770 3C04800F */  lui        $a0, %hi(D_800E9AA0)
    /* A91E4 80120774 C4440034 */  lwc1       $f4, 0x34($v0)
    /* A91E8 80120778 46002181 */  sub.s      $f6, $f4, $f0
    /* A91EC 8012077C E4460034 */  swc1       $f6, 0x34($v0)
    /* A91F0 80120780 8D2E003C */  lw         $t6, 0x3C($t1)
    /* A91F4 80120784 25D80001 */  addiu      $t8, $t6, 0x1
    /* A91F8 80120788 AD38003C */  sw         $t8, 0x3C($t1)
    /* A91FC 8012078C 8DADA7C4 */  lw         $t5, %lo(omCurrentObj)($t5)
    /* A9200 80120790 8DA30000 */  lw         $v1, 0x0($t5)
    /* A9204 80120794 00031880 */  sll        $v1, $v1, 2
    /* A9208 80120798 00E33821 */  addu       $a3, $a3, $v1
    /* A920C 8012079C 00832021 */  addu       $a0, $a0, $v1
    /* A9210 801207A0 8C849AA0 */  lw         $a0, %lo(D_800E9AA0)($a0)
    /* A9214 801207A4 10000098 */  b          .L80120A08
    /* A9218 801207A8 8CE798E0 */   lw        $a3, %lo(D_800E98E0)($a3)
  .L801207AC:
    /* A921C 801207AC 8DEF7088 */  lw         $t7, %lo(D_800D7088)($t7)
    /* A9220 801207B0 3C018000 */  lui        $at, (0x8000FFFF >> 16)
    /* A9224 801207B4 3421FFFF */  ori        $at, $at, (0x8000FFFF & 0xFFFF)
    /* A9228 801207B8 01E15824 */  and        $t3, $t7, $at
    /* A922C 801207BC 24010003 */  addiu      $at, $zero, 0x3
    /* A9230 801207C0 51610008 */  beql       $t3, $at, .L801207E4
    /* A9234 801207C4 8CCC003C */   lw        $t4, 0x3C($a2)
    /* A9238 801207C8 0C03EF87 */  jal        func_800FBE1C
    /* A923C 801207CC 00000000 */   nop
    /* A9240 801207D0 0C03E905 */  jal        func_800FA414
    /* A9244 801207D4 24040003 */   addiu     $a0, $zero, 0x3
    /* A9248 801207D8 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A924C 801207DC 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A9250 801207E0 8CCC003C */  lw         $t4, 0x3C($a2)
  .L801207E4:
    /* A9254 801207E4 44804000 */  mtc1       $zero, $f8
    /* A9258 801207E8 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A925C 801207EC 8D990010 */  lw         $t9, 0x10($t4)
    /* A9260 801207F0 3C05800E */  lui        $a1, %hi(D_800E6A10)
    /* A9264 801207F4 24A56A10 */  addiu      $a1, $a1, %lo(D_800E6A10)
    /* A9268 801207F8 E7280034 */  swc1       $f8, 0x34($t9)
    /* A926C 801207FC 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A9270 80120800 3C07800E */  lui        $a3, %hi(D_800E17D0)
    /* A9274 80120804 24E717D0 */  addiu      $a3, $a3, %lo(D_800E17D0)
    /* A9278 80120808 8CCE0000 */  lw         $t6, 0x0($a2)
    /* A927C 8012080C 3C018013 */  lui        $at, %hi(D_80129054)
    /* A9280 80120810 3C0C800D */  lui        $t4, %hi(D_800D6FB2)
    /* A9284 80120814 000EC080 */  sll        $t8, $t6, 2
    /* A9288 80120818 00B81021 */  addu       $v0, $a1, $t8
    /* A928C 8012081C C44A0000 */  lwc1       $f10, 0x0($v0)
    /* A9290 80120820 3C188013 */  lui        $t8, %hi(D_80129114)
    /* A9294 80120824 46005407 */  neg.s      $f16, $f10
    /* A9298 80120828 E4500000 */  swc1       $f16, 0x0($v0)
    /* A929C 8012082C 8CCD0000 */  lw         $t5, 0x0($a2)
    /* A92A0 80120830 C4249054 */  lwc1       $f4, %lo(D_80129054)($at)
    /* A92A4 80120834 3C01800E */  lui        $at, %hi(gEntitiesAngleYArray)
    /* A92A8 80120838 000D7880 */  sll        $t7, $t5, 2
    /* A92AC 8012083C 00EF2021 */  addu       $a0, $a3, $t7
    /* A92B0 80120840 C4920000 */  lwc1       $f18, 0x0($a0)
    /* A92B4 80120844 3C0F800E */  lui        $t7, %hi(D_800E5F90)
    /* A92B8 80120848 46049181 */  sub.s      $f6, $f18, $f4
    /* A92BC 8012084C E4860000 */  swc1       $f6, 0x0($a0)
    /* A92C0 80120850 8CC30000 */  lw         $v1, 0x0($a2)
    /* A92C4 80120854 958C6FB2 */  lhu        $t4, %lo(D_800D6FB2)($t4)
    /* A92C8 80120858 00031880 */  sll        $v1, $v1, 2
    /* A92CC 8012085C 00E35821 */  addu       $t3, $a3, $v1
    /* A92D0 80120860 C5680000 */  lwc1       $f8, 0x0($t3)
    /* A92D4 80120864 00230821 */  addu       $at, $at, $v1
    /* A92D8 80120868 E42841D0 */  swc1       $f8, %lo(gEntitiesAngleYArray)($at)
    /* A92DC 8012086C 24010002 */  addiu      $at, $zero, 0x2
    /* A92E0 80120870 55810012 */  bnel       $t4, $at, .L801208BC
    /* A92E4 80120874 8CC30000 */   lw        $v1, 0x0($a2)
    /* A92E8 80120878 8CC30000 */  lw         $v1, 0x0($a2)
    /* A92EC 8012087C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* A92F0 80120880 44815000 */  mtc1       $at, $f10
    /* A92F4 80120884 00031880 */  sll        $v1, $v1, 2
    /* A92F8 80120888 00A3C821 */  addu       $t9, $a1, $v1
    /* A92FC 8012088C C7300000 */  lwc1       $f16, 0x0($t9)
    /* A9300 80120890 3C018013 */  lui        $at, %hi(D_8012905C)
    /* A9304 80120894 46105032 */  c.eq.s     $f10, $f16
    /* A9308 80120898 00000000 */  nop
    /* A930C 8012089C 45000004 */  bc1f       .L801208B0
    /* A9310 801208A0 00000000 */   nop
    /* A9314 801208A4 3C018013 */  lui        $at, %hi(D_80129058)
    /* A9318 801208A8 10000012 */  b          .L801208F4
    /* A931C 801208AC C4209058 */   lwc1      $f0, %lo(D_80129058)($at)
  .L801208B0:
    /* A9320 801208B0 10000010 */  b          .L801208F4
    /* A9324 801208B4 C420905C */   lwc1      $f0, %lo(D_8012905C)($at)
    /* A9328 801208B8 8CC30000 */  lw         $v1, 0x0($a2)
  .L801208BC:
    /* A932C 801208BC 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* A9330 801208C0 44819000 */  mtc1       $at, $f18
    /* A9334 801208C4 00031880 */  sll        $v1, $v1, 2
    /* A9338 801208C8 00A37021 */  addu       $t6, $a1, $v1
    /* A933C 801208CC C5C40000 */  lwc1       $f4, 0x0($t6)
    /* A9340 801208D0 3C018013 */  lui        $at, %hi(D_80129064)
    /* A9344 801208D4 46049032 */  c.eq.s     $f18, $f4
    /* A9348 801208D8 00000000 */  nop
    /* A934C 801208DC 45000004 */  bc1f       .L801208F0
    /* A9350 801208E0 00000000 */   nop
    /* A9354 801208E4 3C018013 */  lui        $at, %hi(D_80129060)
    /* A9358 801208E8 10000002 */  b          .L801208F4
    /* A935C 801208EC C4209060 */   lwc1      $f0, %lo(D_80129060)($at)
  .L801208F0:
    /* A9360 801208F0 C4209064 */  lwc1       $f0, %lo(D_80129064)($at)
  .L801208F4:
    /* A9364 801208F4 8F189114 */  lw         $t8, %lo(D_80129114)($t8)
    /* A9368 801208F8 01E37821 */  addu       $t7, $t7, $v1
    /* A936C 801208FC 8DEF5F90 */  lw         $t7, %lo(D_800E5F90)($t7)
    /* A9370 80120900 8F0D0004 */  lw         $t5, 0x4($t8)
    /* A9374 80120904 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* A9378 80120908 000F5900 */  sll        $t3, $t7, 4
    /* A937C 8012090C 01AB6021 */  addu       $t4, $t5, $t3
    /* A9380 80120910 8D850004 */  lw         $a1, 0x4($t4)
    /* A9384 80120914 44813000 */  mtc1       $at, $f6
    /* A9388 80120918 3C19800E */  lui        $t9, %hi(D_800E6BD0)
    /* A938C 8012091C C4A8000C */  lwc1       $f8, 0xC($a1)
    /* A9390 80120920 27396BD0 */  addiu      $t9, $t9, %lo(D_800E6BD0)
    /* A9394 80120924 00791021 */  addu       $v0, $v1, $t9
    /* A9398 80120928 46083283 */  div.s      $f10, $f6, $f8
    /* A939C 8012092C C4520000 */  lwc1       $f18, 0x0($v0)
    /* A93A0 80120930 46005402 */  mul.s      $f16, $f10, $f0
    /* A93A4 80120934 46109100 */  add.s      $f4, $f18, $f16
    /* A93A8 80120938 E4440000 */  swc1       $f4, 0x0($v0)
    /* A93AC 8012093C 0C03E15C */  jal        func_800F8570
    /* A93B0 80120940 8CC40000 */   lw        $a0, 0x0($a2)
    /* A93B4 80120944 3C0E8005 */  lui        $t6, %hi(omCurrentObj)
    /* A93B8 80120948 8DCEA7C4 */  lw         $t6, %lo(omCurrentObj)($t6)
    /* A93BC 8012094C 3C188013 */  lui        $t8, %hi(D_80129114)
    /* A93C0 80120950 8F189114 */  lw         $t8, %lo(D_80129114)($t8)
    /* A93C4 80120954 8DC30000 */  lw         $v1, 0x0($t6)
    /* A93C8 80120958 3C0D800E */  lui        $t5, %hi(D_800E5F90)
    /* A93CC 8012095C 8F0F0004 */  lw         $t7, 0x4($t8)
    /* A93D0 80120960 00031880 */  sll        $v1, $v1, 2
    /* A93D4 80120964 01A36821 */  addu       $t5, $t5, $v1
    /* A93D8 80120968 8DAD5F90 */  lw         $t5, %lo(D_800E5F90)($t5)
    /* A93DC 8012096C 3C06800E */  lui        $a2, %hi(D_800E6BD0)
    /* A93E0 80120970 00C33021 */  addu       $a2, $a2, $v1
    /* A93E4 80120974 000D5900 */  sll        $t3, $t5, 4
    /* A93E8 80120978 01EB6021 */  addu       $t4, $t7, $t3
    /* A93EC 8012097C 8D850004 */  lw         $a1, 0x4($t4)
    /* A93F0 80120980 8CC66BD0 */  lw         $a2, %lo(D_800E6BD0)($a2)
    /* A93F4 80120984 0C0078C0 */  jal        mtxGetInterpolatedPosition
    /* A93F8 80120988 27A4003C */   addiu     $a0, $sp, 0x3C
    /* A93FC 8012098C 3C068005 */  lui        $a2, %hi(omCurrentObj)
    /* A9400 80120990 8CC6A7C4 */  lw         $a2, %lo(omCurrentObj)($a2)
    /* A9404 80120994 C7A6003C */  lwc1       $f6, 0x3C($sp)
    /* A9408 80120998 3C01800E */  lui        $at, %hi(gEntitiesNextPosXArray)
    /* A940C 8012099C 8CD90000 */  lw         $t9, 0x0($a2)
    /* A9410 801209A0 C7A80044 */  lwc1       $f8, 0x44($sp)
    /* A9414 801209A4 3C0C800F */  lui        $t4, %hi(D_800EA360)
    /* A9418 801209A8 00197080 */  sll        $t6, $t9, 2
    /* A941C 801209AC 002E0821 */  addu       $at, $at, $t6
    /* A9420 801209B0 E42625D0 */  swc1       $f6, %lo(gEntitiesNextPosXArray)($at)
    /* A9424 801209B4 8CD80000 */  lw         $t8, 0x0($a2)
    /* A9428 801209B8 3C01800E */  lui        $at, %hi(gEntitiesNextPosZArray)
    /* A942C 801209BC 3C098013 */  lui        $t1, %hi(gKirbyState)
    /* A9430 801209C0 00186880 */  sll        $t5, $t8, 2
    /* A9434 801209C4 002D0821 */  addu       $at, $at, $t5
    /* A9438 801209C8 E4282950 */  swc1       $f8, %lo(gEntitiesNextPosZArray)($at)
    /* A943C 801209CC 8CCF0000 */  lw         $t7, 0x0($a2)
    /* A9440 801209D0 2529E7C0 */  addiu      $t1, $t1, %lo(gKirbyState)
    /* A9444 801209D4 3C07800F */  lui        $a3, %hi(D_800E98E0)
    /* A9448 801209D8 000F5880 */  sll        $t3, $t7, 2
    /* A944C 801209DC 018B6021 */  addu       $t4, $t4, $t3
    /* A9450 801209E0 8D8CA360 */  lw         $t4, %lo(D_800EA360)($t4)
    /* A9454 801209E4 AD20003C */  sw         $zero, 0x3C($t1)
    /* A9458 801209E8 3C04800F */  lui        $a0, %hi(D_800E9AA0)
    /* A945C 801209EC AD2C015C */  sw         $t4, 0x15C($t1)
    /* A9460 801209F0 8CC30000 */  lw         $v1, 0x0($a2)
    /* A9464 801209F4 00031880 */  sll        $v1, $v1, 2
    /* A9468 801209F8 00E33821 */  addu       $a3, $a3, $v1
    /* A946C 801209FC 00832021 */  addu       $a0, $a0, $v1
    /* A9470 80120A00 8C849AA0 */  lw         $a0, %lo(D_800E9AA0)($a0)
    /* A9474 80120A04 8CE798E0 */  lw         $a3, %lo(D_800E98E0)($a3)
  .L80120A08:
    /* A9478 80120A08 10E40003 */  beq        $a3, $a0, .L80120A18
    /* A947C 80120A0C 00001025 */   or        $v0, $zero, $zero
    /* A9480 80120A10 10000001 */  b          .L80120A18
    /* A9484 80120A14 00E01025 */   or        $v0, $a3, $zero
  .L80120A18:
    /* A9488 80120A18 8FBF0014 */  lw         $ra, 0x14($sp)
    /* A948C 80120A1C 27BD0060 */  addiu      $sp, $sp, 0x60
    /* A9490 80120A20 03E00008 */  jr         $ra
    /* A9494 80120A24 00000000 */   nop
endlabel func_8011FEF8
.size func_8011FEF8, . - func_8011FEF8
