.section .late_rodata
nonmatching jtbl_800D5D9C

dlabel jtbl_800D5D9C
    /* 7DFEC 800D5D9C 800A969C */ .word .L800A969C
    /* 7DFF0 800D5DA0 800A969C */ .word .L800A969C
    /* 7DFF4 800D5DA4 800A969C */ .word .L800A969C
    /* 7DFF8 800D5DA8 800A969C */ .word .L800A969C
    /* 7DFFC 800D5DAC 800A969C */ .word .L800A969C
    /* 7E000 800D5DB0 800A969C */ .word .L800A969C
    /* 7E004 800D5DB4 800A96F8 */ .word .L800A96F8
    /* 7E008 800D5DB8 800A96F8 */ .word .L800A96F8
    /* 7E00C 800D5DBC 800A96F8 */ .word .L800A96F8
    /* 7E010 800D5DC0 800A96F8 */ .word .L800A96F8
    /* 7E014 800D5DC4 800A96F8 */ .word .L800A96F8
    /* 7E018 800D5DC8 800A96F8 */ .word .L800A96F8
    /* 7E01C 800D5DCC 800A96F8 */ .word .L800A96F8
    /* 7E020 800D5DD0 800A96F8 */ .word .L800A96F8
    /* 7E024 800D5DD4 800A974C */ .word .L800A974C
enddlabel jtbl_800D5D9C
.size jtbl_800D5D9C, . - jtbl_800D5D9C


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800A9648, 0x118

glabel func_800A9648
    /* 51898 800A9648 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 5189C 800A964C AFBF001C */  sw         $ra, 0x1C($sp)
    /* 518A0 800A9650 AFB00018 */  sw         $s0, 0x18($sp)
    /* 518A4 800A9654 8C850008 */  lw         $a1, 0x8($a0)
    /* 518A8 800A9658 00808025 */  or         $s0, $a0, $zero
    /* 518AC 800A965C 2CA10020 */  sltiu      $at, $a1, 0x20
    /* 518B0 800A9660 14200006 */  bnez       $at, .L800A967C
    /* 518B4 800A9664 24AEFFEF */   addiu     $t6, $a1, -0x11
    /* 518B8 800A9668 240103E7 */  addiu      $at, $zero, 0x3E7
    /* 518BC 800A966C 50A10038 */  beql       $a1, $at, .L800A9750
    /* 518C0 800A9670 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 518C4 800A9674 10000036 */  b          .L800A9750
    /* 518C8 800A9678 8FBF001C */   lw        $ra, 0x1C($sp)
  .L800A967C:
    /* 518CC 800A967C 2DC1000F */  sltiu      $at, $t6, 0xF
    /* 518D0 800A9680 10200032 */  beqz       $at, .L800A974C
    /* 518D4 800A9684 000E7080 */   sll       $t6, $t6, 2
    /* 518D8 800A9688 3C01800D */  lui        $at, %hi(jtbl_800D5D9C)
    /* 518DC 800A968C 002E0821 */  addu       $at, $at, $t6
    /* 518E0 800A9690 8C2E5D9C */  lw         $t6, %lo(jtbl_800D5D9C)($at)
    /* 518E4 800A9694 01C00008 */  jr         $t6
    /* 518E8 800A9698 00000000 */   nop
  .L800A969C:
    /* 518EC 800A969C 3C028005 */  lui        $v0, %hi(omCurrentObj)
    /* 518F0 800A96A0 8C42A7C4 */  lw         $v0, %lo(omCurrentObj)($v0)
    /* 518F4 800A96A4 8E040000 */  lw         $a0, 0x0($s0)
    /* 518F8 800A96A8 3C01800E */  lui        $at, %hi(D_800DFA10)
    /* 518FC 800A96AC 8C4F0000 */  lw         $t7, 0x0($v0)
    /* 51900 800A96B0 3C06800E */  lui        $a2, %hi(D_800DFBD0)
    /* 51904 800A96B4 000FC080 */  sll        $t8, $t7, 2
    /* 51908 800A96B8 00380821 */  addu       $at, $at, $t8
    /* 5190C 800A96BC AC24FA10 */  sw         $a0, %lo(D_800DFA10)($at)
    /* 51910 800A96C0 8C590000 */  lw         $t9, 0x0($v0)
    /* 51914 800A96C4 8E070004 */  lw         $a3, 0x4($s0)
    /* 51918 800A96C8 3C01800E */  lui        $at, %hi(D_800DFD90)
    /* 5191C 800A96CC 00194080 */  sll        $t0, $t9, 2
    /* 51920 800A96D0 00280821 */  addu       $at, $at, $t0
    /* 51924 800A96D4 AC27FD90 */  sw         $a3, %lo(D_800DFD90)($at)
    /* 51928 800A96D8 8C490000 */  lw         $t1, 0x0($v0)
    /* 5192C 800A96DC 00E02825 */  or         $a1, $a3, $zero
    /* 51930 800A96E0 00095080 */  sll        $t2, $t1, 2
    /* 51934 800A96E4 00CA3021 */  addu       $a2, $a2, $t2
    /* 51938 800A96E8 0C02BD86 */  jal        func_800AF618
    /* 5193C 800A96EC 8CC6FBD0 */   lw        $a2, %lo(D_800DFBD0)($a2)
    /* 51940 800A96F0 10000017 */  b          .L800A9750
    /* 51944 800A96F4 8FBF001C */   lw        $ra, 0x1C($sp)
  .L800A96F8:
    /* 51948 800A96F8 3C028005 */  lui        $v0, %hi(omCurrentObj)
    /* 5194C 800A96FC 8C42A7C4 */  lw         $v0, %lo(omCurrentObj)($v0)
    /* 51950 800A9700 8E070000 */  lw         $a3, 0x0($s0)
    /* 51954 800A9704 3C01800E */  lui        $at, %hi(D_800DFA10)
    /* 51958 800A9708 8C4B0000 */  lw         $t3, 0x0($v0)
    /* 5195C 800A970C 3C06800E */  lui        $a2, %hi(D_800DFBD0)
    /* 51960 800A9710 00E02025 */  or         $a0, $a3, $zero
    /* 51964 800A9714 000B6080 */  sll        $t4, $t3, 2
    /* 51968 800A9718 002C0821 */  addu       $at, $at, $t4
    /* 5196C 800A971C AC27FA10 */  sw         $a3, %lo(D_800DFA10)($at)
    /* 51970 800A9720 8C4D0000 */  lw         $t5, 0x0($v0)
    /* 51974 800A9724 8E050004 */  lw         $a1, 0x4($s0)
    /* 51978 800A9728 3C01800E */  lui        $at, %hi(D_800DFD90)
    /* 5197C 800A972C 000D7080 */  sll        $t6, $t5, 2
    /* 51980 800A9730 002E0821 */  addu       $at, $at, $t6
    /* 51984 800A9734 AC25FD90 */  sw         $a1, %lo(D_800DFD90)($at)
    /* 51988 800A9738 8C4F0000 */  lw         $t7, 0x0($v0)
    /* 5198C 800A973C 000FC080 */  sll        $t8, $t7, 2
    /* 51990 800A9740 00D83021 */  addu       $a2, $a2, $t8
    /* 51994 800A9744 0C02BD2F */  jal        func_800AF4BC
    /* 51998 800A9748 8CC6FBD0 */   lw        $a2, %lo(D_800DFBD0)($a2)
  .L800A974C:
    /* 5199C 800A974C 8FBF001C */  lw         $ra, 0x1C($sp)
  .L800A9750:
    /* 519A0 800A9750 02001025 */  or         $v0, $s0, $zero
    /* 519A4 800A9754 8FB00018 */  lw         $s0, 0x18($sp)
    /* 519A8 800A9758 03E00008 */  jr         $ra
    /* 519AC 800A975C 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800A9648
.size func_800A9648, . - func_800A9648
