.section .late_rodata
nonmatching D_800D5DE4

dlabel D_800D5DE4
    /* 7E034 800D5DE4 FF7FFFFF */ .float -3.402823466e+38
enddlabel D_800D5DE4
.size D_800D5DE4, . - D_800D5DE4


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800AA608, 0x184

glabel func_800AA608
    /* 52858 800AA608 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 5285C 800AA60C 3C038005 */  lui        $v1, %hi(omCurrentObj)
    /* 52860 800AA610 8C63A7C4 */  lw         $v1, %lo(omCurrentObj)($v1)
    /* 52864 800AA614 AFBF002C */  sw         $ra, 0x2C($sp)
    /* 52868 800AA618 AFB00028 */  sw         $s0, 0x28($sp)
    /* 5286C 800AA61C F7B40020 */  sdc1       $f20, 0x20($sp)
    /* 52870 800AA620 AFA5003C */  sw         $a1, 0x3C($sp)
    /* 52874 800AA624 00077402 */  srl        $t6, $a3, 16
    /* 52878 800AA628 8C6A0000 */  lw         $t2, 0x0($v1)
    /* 5287C 800AA62C 000E7880 */  sll        $t7, $t6, 2
    /* 52880 800AA630 3C18800D */  lui        $t8, %hi(D_800D00C4)
    /* 52884 800AA634 030FC021 */  addu       $t8, $t8, $t7
    /* 52888 800AA638 8F1800C4 */  lw         $t8, %lo(D_800D00C4)($t8)
    /* 5288C 800AA63C 30F9FFFF */  andi       $t9, $a3, 0xFFFF
    /* 52890 800AA640 3C01800E */  lui        $at, %hi(D_800E02D0)
    /* 52894 800AA644 000A5880 */  sll        $t3, $t2, 2
    /* 52898 800AA648 4486A000 */  mtc1       $a2, $f20
    /* 5289C 800AA64C 00194880 */  sll        $t1, $t9, 2
    /* 528A0 800AA650 002B0821 */  addu       $at, $at, $t3
    /* 528A4 800AA654 AC2702D0 */  sw         $a3, %lo(D_800E02D0)($at)
    /* 528A8 800AA658 03093021 */  addu       $a2, $t8, $t1
    /* 528AC 800AA65C 8CC80000 */  lw         $t0, 0x0($a2)
    /* 528B0 800AA660 00808025 */  or         $s0, $a0, $zero
    /* 528B4 800AA664 00E02025 */  or         $a0, $a3, $zero
    /* 528B8 800AA668 1100000E */  beqz       $t0, .L800AA6A4
    /* 528BC 800AA66C 24050003 */   addiu     $a1, $zero, 0x3
    /* 528C0 800AA670 8C6C0000 */  lw         $t4, 0x0($v1)
    /* 528C4 800AA674 3C01800E */  lui        $at, %hi(gSegment4StartArray)
    /* 528C8 800AA678 24050001 */  addiu      $a1, $zero, 0x1
    /* 528CC 800AA67C 000C6880 */  sll        $t5, $t4, 2
    /* 528D0 800AA680 002D0821 */  addu       $at, $at, $t5
    /* 528D4 800AA684 AC28F4D0 */  sw         $t0, %lo(gSegment4StartArray)($at)
    /* 528D8 800AA688 8CC40000 */  lw         $a0, 0x0($a2)
    /* 528DC 800AA68C 0C02A159 */  jal        func_800A8564
    /* 528E0 800AA690 AFA80034 */   sw        $t0, 0x34($sp)
    /* 528E4 800AA694 3C038005 */  lui        $v1, %hi(omCurrentObj)
    /* 528E8 800AA698 8C63A7C4 */  lw         $v1, %lo(omCurrentObj)($v1)
    /* 528EC 800AA69C 1000000D */  b          .L800AA6D4
    /* 528F0 800AA6A0 8FA70034 */   lw        $a3, 0x34($sp)
  .L800AA6A4:
    /* 528F4 800AA6A4 0C02A494 */  jal        func_800A9250
    /* 528F8 800AA6A8 AFA60030 */   sw        $a2, 0x30($sp)
    /* 528FC 800AA6AC 8FA60030 */  lw         $a2, 0x30($sp)
    /* 52900 800AA6B0 3C038005 */  lui        $v1, %hi(omCurrentObj)
    /* 52904 800AA6B4 3C01800E */  lui        $at, %hi(gSegment4StartArray)
    /* 52908 800AA6B8 ACC20000 */  sw         $v0, 0x0($a2)
    /* 5290C 800AA6BC 8C63A7C4 */  lw         $v1, %lo(omCurrentObj)($v1)
    /* 52910 800AA6C0 00403825 */  or         $a3, $v0, $zero
    /* 52914 800AA6C4 8C6E0000 */  lw         $t6, 0x0($v1)
    /* 52918 800AA6C8 000E7880 */  sll        $t7, $t6, 2
    /* 5291C 800AA6CC 002F0821 */  addu       $at, $at, $t7
    /* 52920 800AA6D0 AC22F4D0 */  sw         $v0, %lo(gSegment4StartArray)($at)
  .L800AA6D4:
    /* 52924 800AA6D4 8C780000 */  lw         $t8, 0x0($v1)
    /* 52928 800AA6D8 8CF90000 */  lw         $t9, 0x0($a3)
    /* 5292C 800AA6DC 3C01800E */  lui        $at, %hi(D_800DFA10)
    /* 52930 800AA6E0 00184880 */  sll        $t1, $t8, 2
    /* 52934 800AA6E4 00290821 */  addu       $at, $at, $t1
    /* 52938 800AA6E8 AC39FA10 */  sw         $t9, %lo(D_800DFA10)($at)
    /* 5293C 800AA6EC 8C6B0000 */  lw         $t3, 0x0($v1)
    /* 52940 800AA6F0 8CEA0004 */  lw         $t2, 0x4($a3)
    /* 52944 800AA6F4 3C01800E */  lui        $at, %hi(D_800DFD90)
    /* 52948 800AA6F8 000B6080 */  sll        $t4, $t3, 2
    /* 5294C 800AA6FC 002C0821 */  addu       $at, $at, $t4
    /* 52950 800AA700 8FA4003C */  lw         $a0, 0x3C($sp)
    /* 52954 800AA704 0C02A6D2 */  jal        func_800A9B48
    /* 52958 800AA708 AC2AFD90 */   sw        $t2, %lo(D_800DFD90)($at)
    /* 5295C 800AA70C 3C0D8005 */  lui        $t5, %hi(omCurrentObj)
    /* 52960 800AA710 8DADA7C4 */  lw         $t5, %lo(omCurrentObj)($t5)
    /* 52964 800AA714 3C0E800E */  lui        $t6, %hi(D_800DF690)
    /* 52968 800AA718 C7A40048 */  lwc1       $f4, 0x48($sp)
    /* 5296C 800AA71C 8DA30000 */  lw         $v1, 0x0($t5)
    /* 52970 800AA720 3C07800E */  lui        $a3, %hi(D_800DFA10)
    /* 52974 800AA724 4406A000 */  mfc1       $a2, $f20
    /* 52978 800AA728 00031880 */  sll        $v1, $v1, 2
    /* 5297C 800AA72C 01C37021 */  addu       $t6, $t6, $v1
    /* 52980 800AA730 8DCEF690 */  lw         $t6, %lo(D_800DF690)($t6)
    /* 52984 800AA734 00E33821 */  addu       $a3, $a3, $v1
    /* 52988 800AA738 8CE7FA10 */  lw         $a3, %lo(D_800DFA10)($a3)
    /* 5298C 800AA73C 8DC50000 */  lw         $a1, 0x0($t6)
    /* 52990 800AA740 02002025 */  or         $a0, $s0, $zero
    /* 52994 800AA744 0C02C7F4 */  jal        func_800B1FD0
    /* 52998 800AA748 E7A40010 */   swc1      $f4, 0x10($sp)
    /* 5299C 800AA74C 3C01800D */  lui        $at, %hi(D_800D5DE4)
    /* 529A0 800AA750 C4345DE4 */  lwc1       $f20, %lo(D_800D5DE4)($at)
    /* 529A4 800AA754 C6060074 */  lwc1       $f6, 0x74($s0)
  .L800AA758:
    /* 529A8 800AA758 4606A032 */  c.eq.s     $f20, $f6
    /* 529AC 800AA75C 00000000 */  nop
    /* 529B0 800AA760 45030006 */  bc1tl      .L800AA77C
    /* 529B4 800AA764 8FBF002C */   lw        $ra, 0x2C($sp)
    /* 529B8 800AA768 0C002DAF */  jal        ohSleep
    /* 529BC 800AA76C 24040001 */   addiu     $a0, $zero, 0x1
    /* 529C0 800AA770 1000FFF9 */  b          .L800AA758
    /* 529C4 800AA774 C6060074 */   lwc1      $f6, 0x74($s0)
    /* 529C8 800AA778 8FBF002C */  lw         $ra, 0x2C($sp)
  .L800AA77C:
    /* 529CC 800AA77C D7B40020 */  ldc1       $f20, 0x20($sp)
    /* 529D0 800AA780 8FB00028 */  lw         $s0, 0x28($sp)
    /* 529D4 800AA784 03E00008 */  jr         $ra
    /* 529D8 800AA788 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_800AA608
.size func_800AA608, . - func_800AA608
