.section .late_rodata
nonmatching jtbl_800D5A18

dlabel jtbl_800D5A18
    /* 7DC68 800D5A18 800A1C2C */ .word .L800A1C2C
    /* 7DC6C 800D5A1C 800A1C94 */ .word .L800A1C94
    /* 7DC70 800D5A20 800A1CD4 */ .word .L800A1CD4
    /* 7DC74 800D5A24 800A1C2C */ .word .L800A1C2C
    /* 7DC78 800D5A28 800A1C2C */ .word .L800A1C2C
    /* 7DC7C 800D5A2C 800A1D58 */ .word .L800A1D58
    /* 7DC80 800D5A30 800A1CDC */ .word .L800A1CDC
    /* 7DC84 800D5A34 800A1CDC */ .word .L800A1CDC
    /* 7DC88 800D5A38 800A1E34 */ .word .L800A1E34
enddlabel jtbl_800D5A18
.size jtbl_800D5A18, . - jtbl_800D5A18

nonmatching D_800D5A3C

dlabel D_800D5A3C
    /* 7DC8C 800D5A3C 40C90FDB */ .float 6.283185482
enddlabel D_800D5A3C
.size D_800D5A3C, . - D_800D5A3C

nonmatching D_800D5A40

dlabel D_800D5A40
    /* 7DC90 800D5A40 40C90FDB */ .float 6.283185482
enddlabel D_800D5A40
.size D_800D5A40, . - D_800D5A40


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800A19EC, 0x544

glabel func_800A19EC
    /* 49C3C 800A19EC 30820007 */  andi       $v0, $a0, 0x7
    /* 49C40 800A19F0 27BDFFB8 */  addiu      $sp, $sp, -0x48
    /* 49C44 800A19F4 28410008 */  slti       $at, $v0, 0x8
    /* 49C48 800A19F8 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 49C4C 800A19FC AFB00018 */  sw         $s0, 0x18($sp)
    /* 49C50 800A1A00 00803025 */  or         $a2, $a0, $zero
    /* 49C54 800A1A04 14200003 */  bnez       $at, .L800A1A14
    /* 49C58 800A1A08 00A03825 */   or        $a3, $a1, $zero
    /* 49C5C 800A1A0C 10000143 */  b          .L800A1F1C
    /* 49C60 800A1A10 00001025 */   or        $v0, $zero, $zero
  .L800A1A14:
    /* 49C64 800A1A14 00022880 */  sll        $a1, $v0, 2
    /* 49C68 800A1A18 3C0E800D */  lui        $t6, %hi(D_800D6A38)
    /* 49C6C 800A1A1C 01C57021 */  addu       $t6, $t6, $a1
    /* 49C70 800A1A20 8DCE6A38 */  lw         $t6, %lo(D_800D6A38)($t6)
    /* 49C74 800A1A24 00EE082A */  slt        $at, $a3, $t6
    /* 49C78 800A1A28 54200004 */  bnel       $at, $zero, .L800A1A3C
    /* 49C7C 800A1A2C AFA50028 */   sw        $a1, 0x28($sp)
    /* 49C80 800A1A30 1000013A */  b          .L800A1F1C
    /* 49C84 800A1A34 00001025 */   or        $v0, $zero, $zero
    /* 49C88 800A1A38 AFA50028 */  sw         $a1, 0x28($sp)
  .L800A1A3C:
    /* 49C8C 800A1A3C AFA60048 */  sw         $a2, 0x48($sp)
    /* 49C90 800A1A40 0C028653 */  jal        func_800A194C
    /* 49C94 800A1A44 AFA7004C */   sw        $a3, 0x4C($sp)
    /* 49C98 800A1A48 8FA50028 */  lw         $a1, 0x28($sp)
    /* 49C9C 800A1A4C 8FA60048 */  lw         $a2, 0x48($sp)
    /* 49CA0 800A1A50 8FA7004C */  lw         $a3, 0x4C($sp)
    /* 49CA4 800A1A54 10400130 */  beqz       $v0, .L800A1F18
    /* 49CA8 800A1A58 00408025 */   or        $s0, $v0, $zero
    /* 49CAC 800A1A5C 3C0F800D */  lui        $t7, %hi(D_800D6A78)
    /* 49CB0 800A1A60 25EF6A78 */  addiu      $t7, $t7, %lo(D_800D6A78)
    /* 49CB4 800A1A64 00AF2021 */  addu       $a0, $a1, $t7
    /* 49CB8 800A1A68 8C980000 */  lw         $t8, 0x0($a0)
    /* 49CBC 800A1A6C 00071880 */  sll        $v1, $a3, 2
    /* 49CC0 800A1A70 44800000 */  mtc1       $zero, $f0
    /* 49CC4 800A1A74 0303C821 */  addu       $t9, $t8, $v1
    /* 49CC8 800A1A78 8F280000 */  lw         $t0, 0x0($t9)
    /* 49CCC 800A1A7C 95090000 */  lhu        $t1, 0x0($t0)
    /* 49CD0 800A1A80 A046000A */  sb         $a2, 0xA($v0)
    /* 49CD4 800A1A84 A0490009 */  sb         $t1, 0x9($v0)
    /* 49CD8 800A1A88 8C8A0000 */  lw         $t2, 0x0($a0)
    /* 49CDC 800A1A8C 01435821 */  addu       $t3, $t2, $v1
    /* 49CE0 800A1A90 8D6C0000 */  lw         $t4, 0x0($t3)
    /* 49CE4 800A1A94 958D000A */  lhu        $t5, 0xA($t4)
    /* 49CE8 800A1A98 A44D0006 */  sh         $t5, 0x6($v0)
    /* 49CEC 800A1A9C 8C8E0000 */  lw         $t6, 0x0($a0)
    /* 49CF0 800A1AA0 01C37821 */  addu       $t7, $t6, $v1
    /* 49CF4 800A1AA4 8DF80000 */  lw         $t8, 0x0($t7)
    /* 49CF8 800A1AA8 97190008 */  lhu        $t9, 0x8($t8)
    /* 49CFC 800A1AAC A0590008 */  sb         $t9, 0x8($v0)
    /* 49D00 800A1AB0 8C880000 */  lw         $t0, 0x0($a0)
    /* 49D04 800A1AB4 01034821 */  addu       $t1, $t0, $v1
    /* 49D08 800A1AB8 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 49D0C 800A1ABC 954B0002 */  lhu        $t3, 0x2($t2)
    /* 49D10 800A1AC0 A04B000B */  sb         $t3, 0xB($v0)
    /* 49D14 800A1AC4 8C8C0000 */  lw         $t4, 0x0($a0)
    /* 49D18 800A1AC8 01836821 */  addu       $t5, $t4, $v1
    /* 49D1C 800A1ACC 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 49D20 800A1AD0 95CF0006 */  lhu        $t7, 0x6($t6)
    /* 49D24 800A1AD4 A44F000C */  sh         $t7, 0xC($v0)
    /* 49D28 800A1AD8 8C980000 */  lw         $t8, 0x0($a0)
    /* 49D2C 800A1ADC 0303C821 */  addu       $t9, $t8, $v1
    /* 49D30 800A1AE0 8F280000 */  lw         $t0, 0x0($t9)
    /* 49D34 800A1AE4 95090004 */  lhu        $t1, 0x4($t0)
    /* 49D38 800A1AE8 E4400014 */  swc1       $f0, 0x14($v0)
    /* 49D3C 800A1AEC E4400018 */  swc1       $f0, 0x18($v0)
    /* 49D40 800A1AF0 E440001C */  swc1       $f0, 0x1C($v0)
    /* 49D44 800A1AF4 A449000E */  sh         $t1, 0xE($v0)
    /* 49D48 800A1AF8 8C8A0000 */  lw         $t2, 0x0($a0)
    /* 49D4C 800A1AFC 01435821 */  addu       $t3, $t2, $v1
    /* 49D50 800A1B00 8D6C0000 */  lw         $t4, 0x0($t3)
    /* 49D54 800A1B04 C5840014 */  lwc1       $f4, 0x14($t4)
    /* 49D58 800A1B08 E4440020 */  swc1       $f4, 0x20($v0)
    /* 49D5C 800A1B0C 8C8D0000 */  lw         $t5, 0x0($a0)
    /* 49D60 800A1B10 01A37021 */  addu       $t6, $t5, $v1
    /* 49D64 800A1B14 8DCF0000 */  lw         $t7, 0x0($t6)
    /* 49D68 800A1B18 C5E60018 */  lwc1       $f6, 0x18($t7)
    /* 49D6C 800A1B1C E4460024 */  swc1       $f6, 0x24($v0)
    /* 49D70 800A1B20 8C980000 */  lw         $t8, 0x0($a0)
    /* 49D74 800A1B24 0303C821 */  addu       $t9, $t8, $v1
    /* 49D78 800A1B28 8F280000 */  lw         $t0, 0x0($t9)
    /* 49D7C 800A1B2C C508001C */  lwc1       $f8, 0x1C($t0)
    /* 49D80 800A1B30 E4480028 */  swc1       $f8, 0x28($v0)
    /* 49D84 800A1B34 8C890000 */  lw         $t1, 0x0($a0)
    /* 49D88 800A1B38 01235021 */  addu       $t2, $t1, $v1
    /* 49D8C 800A1B3C 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 49D90 800A1B40 C56A000C */  lwc1       $f10, 0xC($t3)
    /* 49D94 800A1B44 E44A002C */  swc1       $f10, 0x2C($v0)
    /* 49D98 800A1B48 8C8C0000 */  lw         $t4, 0x0($a0)
    /* 49D9C 800A1B4C 01836821 */  addu       $t5, $t4, $v1
    /* 49DA0 800A1B50 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 49DA4 800A1B54 C5D00010 */  lwc1       $f16, 0x10($t6)
    /* 49DA8 800A1B58 E4500030 */  swc1       $f16, 0x30($v0)
    /* 49DAC 800A1B5C 8C8F0000 */  lw         $t7, 0x0($a0)
    /* 49DB0 800A1B60 01E3C021 */  addu       $t8, $t7, $v1
    /* 49DB4 800A1B64 8F190000 */  lw         $t9, 0x0($t8)
    /* 49DB8 800A1B68 C732002C */  lwc1       $f18, 0x2C($t9)
    /* 49DBC 800A1B6C E4520034 */  swc1       $f18, 0x34($v0)
    /* 49DC0 800A1B70 8C880000 */  lw         $t0, 0x0($a0)
    /* 49DC4 800A1B74 01034821 */  addu       $t1, $t0, $v1
    /* 49DC8 800A1B78 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 49DCC 800A1B7C 254B003C */  addiu      $t3, $t2, 0x3C
    /* 49DD0 800A1B80 AC4B0010 */  sw         $t3, 0x10($v0)
    /* 49DD4 800A1B84 8C8C0000 */  lw         $t4, 0x0($a0)
    /* 49DD8 800A1B88 3C0B800D */  lui        $t3, %hi(D_800D6A98)
    /* 49DDC 800A1B8C 01655821 */  addu       $t3, $t3, $a1
    /* 49DE0 800A1B90 01836821 */  addu       $t5, $t4, $v1
    /* 49DE4 800A1B94 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 49DE8 800A1B98 C5C40020 */  lwc1       $f4, 0x20($t6)
    /* 49DEC 800A1B9C E4440038 */  swc1       $f4, 0x38($v0)
    /* 49DF0 800A1BA0 8C8F0000 */  lw         $t7, 0x0($a0)
    /* 49DF4 800A1BA4 01E3C021 */  addu       $t8, $t7, $v1
    /* 49DF8 800A1BA8 8F190000 */  lw         $t9, 0x0($t8)
    /* 49DFC 800A1BAC C7260024 */  lwc1       $f6, 0x24($t9)
    /* 49E00 800A1BB0 E446003C */  swc1       $f6, 0x3C($v0)
    /* 49E04 800A1BB4 8C880000 */  lw         $t0, 0x0($a0)
    /* 49E08 800A1BB8 01034821 */  addu       $t1, $t0, $v1
    /* 49E0C 800A1BBC 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 49E10 800A1BC0 C5480028 */  lwc1       $f8, 0x28($t2)
    /* 49E14 800A1BC4 E4400044 */  swc1       $f0, 0x44($v0)
    /* 49E18 800A1BC8 E4480040 */  swc1       $f8, 0x40($v0)
    /* 49E1C 800A1BCC 8C8C0000 */  lw         $t4, 0x0($a0)
    /* 49E20 800A1BD0 8D6B6A98 */  lw         $t3, %lo(D_800D6A98)($t3)
    /* 49E24 800A1BD4 01836821 */  addu       $t5, $t4, $v1
    /* 49E28 800A1BD8 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 49E2C 800A1BDC 95CF0002 */  lhu        $t7, 0x2($t6)
    /* 49E30 800A1BE0 000FC080 */  sll        $t8, $t7, 2
    /* 49E34 800A1BE4 0178C821 */  addu       $t9, $t3, $t8
    /* 49E38 800A1BE8 8F280000 */  lw         $t0, 0x0($t9)
    /* 49E3C 800A1BEC 95090016 */  lhu        $t1, 0x16($t0)
    /* 49E40 800A1BF0 51200005 */  beql       $t1, $zero, .L800A1C08
    /* 49E44 800A1BF4 904D0009 */   lbu       $t5, 0x9($v0)
    /* 49E48 800A1BF8 944A0006 */  lhu        $t2, 0x6($v0)
    /* 49E4C 800A1BFC 354C0010 */  ori        $t4, $t2, 0x10
    /* 49E50 800A1C00 A44C0006 */  sh         $t4, 0x6($v0)
    /* 49E54 800A1C04 904D0009 */  lbu        $t5, 0x9($v0)
  .L800A1C08:
    /* 49E58 800A1C08 AC400048 */  sw         $zero, 0x48($v0)
    /* 49E5C 800A1C0C 2DA10009 */  sltiu      $at, $t5, 0x9
    /* 49E60 800A1C10 102000B1 */  beqz       $at, .L800A1ED8
    /* 49E64 800A1C14 000D6880 */   sll       $t5, $t5, 2
    /* 49E68 800A1C18 3C01800D */  lui        $at, %hi(jtbl_800D5A18)
    /* 49E6C 800A1C1C 002D0821 */  addu       $at, $at, $t5
    /* 49E70 800A1C20 8C2D5A18 */  lw         $t5, %lo(jtbl_800D5A18)($at)
    /* 49E74 800A1C24 01A00008 */  jr         $t5
    /* 49E78 800A1C28 00000000 */   nop
  .L800A1C2C:
    /* 49E7C 800A1C2C 8C8E0000 */  lw         $t6, 0x0($a0)
    /* 49E80 800A1C30 01C37821 */  addu       $t7, $t6, $v1
    /* 49E84 800A1C34 8DE50000 */  lw         $a1, 0x0($t7)
    /* 49E88 800A1C38 C4A20030 */  lwc1       $f2, 0x30($a1)
    /* 49E8C 800A1C3C 46020032 */  c.eq.s     $f0, $f2
    /* 49E90 800A1C40 00000000 */  nop
    /* 49E94 800A1C44 4502000D */  bc1fl      .L800A1C7C
    /* 49E98 800A1C48 E4420050 */   swc1      $f2, 0x50($v0)
    /* 49E9C 800A1C4C C4AA0034 */  lwc1       $f10, 0x34($a1)
    /* 49EA0 800A1C50 460A0032 */  c.eq.s     $f0, $f10
    /* 49EA4 800A1C54 00000000 */  nop
    /* 49EA8 800A1C58 45020008 */  bc1fl      .L800A1C7C
    /* 49EAC 800A1C5C E4420050 */   swc1      $f2, 0x50($v0)
    /* 49EB0 800A1C60 44808000 */  mtc1       $zero, $f16
    /* 49EB4 800A1C64 3C01800D */  lui        $at, %hi(D_800D5A3C)
    /* 49EB8 800A1C68 E4500050 */  swc1       $f16, 0x50($v0)
    /* 49EBC 800A1C6C C4325A3C */  lwc1       $f18, %lo(D_800D5A3C)($at)
    /* 49EC0 800A1C70 1000009F */  b          .L800A1EF0
    /* 49EC4 800A1C74 E4520054 */   swc1      $f18, 0x54($v0)
    /* 49EC8 800A1C78 E4420050 */  swc1       $f2, 0x50($v0)
  .L800A1C7C:
    /* 49ECC 800A1C7C 8C8B0000 */  lw         $t3, 0x0($a0)
    /* 49ED0 800A1C80 0163C021 */  addu       $t8, $t3, $v1
    /* 49ED4 800A1C84 8F190000 */  lw         $t9, 0x0($t8)
    /* 49ED8 800A1C88 C7240034 */  lwc1       $f4, 0x34($t9)
    /* 49EDC 800A1C8C 10000098 */  b          .L800A1EF0
    /* 49EE0 800A1C90 E4440054 */   swc1      $f4, 0x54($v0)
  .L800A1C94:
    /* 49EE4 800A1C94 8C880000 */  lw         $t0, 0x0($a0)
    /* 49EE8 800A1C98 01034821 */  addu       $t1, $t0, $v1
    /* 49EEC 800A1C9C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 49EF0 800A1CA0 C5460030 */  lwc1       $f6, 0x30($t2)
    /* 49EF4 800A1CA4 E4460050 */  swc1       $f6, 0x50($v0)
    /* 49EF8 800A1CA8 8C8C0000 */  lw         $t4, 0x0($a0)
    /* 49EFC 800A1CAC 01836821 */  addu       $t5, $t4, $v1
    /* 49F00 800A1CB0 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 49F04 800A1CB4 C5C80034 */  lwc1       $f8, 0x34($t6)
    /* 49F08 800A1CB8 E4480054 */  swc1       $f8, 0x54($v0)
    /* 49F0C 800A1CBC 8C8F0000 */  lw         $t7, 0x0($a0)
    /* 49F10 800A1CC0 01E35821 */  addu       $t3, $t7, $v1
    /* 49F14 800A1CC4 8D780000 */  lw         $t8, 0x0($t3)
    /* 49F18 800A1CC8 C70A0038 */  lwc1       $f10, 0x38($t8)
    /* 49F1C 800A1CCC 10000088 */  b          .L800A1EF0
    /* 49F20 800A1CD0 E44A0058 */   swc1      $f10, 0x58($v0)
  .L800A1CD4:
    /* 49F24 800A1CD4 10000086 */  b          .L800A1EF0
    /* 49F28 800A1CD8 A4400054 */   sh        $zero, 0x54($v0)
  .L800A1CDC:
    /* 49F2C 800A1CDC 8C990000 */  lw         $t9, 0x0($a0)
    /* 49F30 800A1CE0 03234021 */  addu       $t0, $t9, $v1
    /* 49F34 800A1CE4 8D050000 */  lw         $a1, 0x0($t0)
    /* 49F38 800A1CE8 C4A20030 */  lwc1       $f2, 0x30($a1)
    /* 49F3C 800A1CEC 46020032 */  c.eq.s     $f0, $f2
    /* 49F40 800A1CF0 00000000 */  nop
    /* 49F44 800A1CF4 4502000D */  bc1fl      .L800A1D2C
    /* 49F48 800A1CF8 E4420050 */   swc1      $f2, 0x50($v0)
    /* 49F4C 800A1CFC C4B00034 */  lwc1       $f16, 0x34($a1)
    /* 49F50 800A1D00 46100032 */  c.eq.s     $f0, $f16
    /* 49F54 800A1D04 00000000 */  nop
    /* 49F58 800A1D08 45020008 */  bc1fl      .L800A1D2C
    /* 49F5C 800A1D0C E4420050 */   swc1      $f2, 0x50($v0)
    /* 49F60 800A1D10 44809000 */  mtc1       $zero, $f18
    /* 49F64 800A1D14 3C01800D */  lui        $at, %hi(D_800D5A40)
    /* 49F68 800A1D18 E4520050 */  swc1       $f18, 0x50($v0)
    /* 49F6C 800A1D1C C4245A40 */  lwc1       $f4, %lo(D_800D5A40)($at)
    /* 49F70 800A1D20 10000007 */  b          .L800A1D40
    /* 49F74 800A1D24 E4440054 */   swc1      $f4, 0x54($v0)
    /* 49F78 800A1D28 E4420050 */  swc1       $f2, 0x50($v0)
  .L800A1D2C:
    /* 49F7C 800A1D2C 8C890000 */  lw         $t1, 0x0($a0)
    /* 49F80 800A1D30 01235021 */  addu       $t2, $t1, $v1
    /* 49F84 800A1D34 8D4C0000 */  lw         $t4, 0x0($t2)
    /* 49F88 800A1D38 C5860034 */  lwc1       $f6, 0x34($t4)
    /* 49F8C 800A1D3C E4460054 */  swc1       $f6, 0x54($v0)
  .L800A1D40:
    /* 49F90 800A1D40 8C8D0000 */  lw         $t5, 0x0($a0)
    /* 49F94 800A1D44 01A37021 */  addu       $t6, $t5, $v1
    /* 49F98 800A1D48 8DCF0000 */  lw         $t7, 0x0($t6)
    /* 49F9C 800A1D4C C5E80038 */  lwc1       $f8, 0x38($t7)
    /* 49FA0 800A1D50 10000067 */  b          .L800A1EF0
    /* 49FA4 800A1D54 E4480058 */   swc1      $f8, 0x58($v0)
  .L800A1D58:
    /* 49FA8 800A1D58 8C8B0000 */  lw         $t3, 0x0($a0)
    /* 49FAC 800A1D5C 0163C021 */  addu       $t8, $t3, $v1
    /* 49FB0 800A1D60 8F190000 */  lw         $t9, 0x0($t8)
    /* 49FB4 800A1D64 C72A0030 */  lwc1       $f10, 0x30($t9)
    /* 49FB8 800A1D68 34190001 */  ori        $t9, $zero, 0x1
    /* 49FBC 800A1D6C E44A0050 */  swc1       $f10, 0x50($v0)
    /* 49FC0 800A1D70 8C880000 */  lw         $t0, 0x0($a0)
    /* 49FC4 800A1D74 01034821 */  addu       $t1, $t0, $v1
    /* 49FC8 800A1D78 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 49FCC 800A1D7C C5500034 */  lwc1       $f16, 0x34($t2)
    /* 49FD0 800A1D80 E4500060 */  swc1       $f16, 0x60($v0)
    /* 49FD4 800A1D84 8C8C0000 */  lw         $t4, 0x0($a0)
    /* 49FD8 800A1D88 01836821 */  addu       $t5, $t4, $v1
    /* 49FDC 800A1D8C 8DAE0000 */  lw         $t6, 0x0($t5)
    /* 49FE0 800A1D90 C5D20038 */  lwc1       $f18, 0x38($t6)
    /* 49FE4 800A1D94 E4400054 */  swc1       $f0, 0x54($v0)
    /* 49FE8 800A1D98 E4400058 */  swc1       $f0, 0x58($v0)
    /* 49FEC 800A1D9C E440005C */  swc1       $f0, 0x5C($v0)
    /* 49FF0 800A1DA0 E4400064 */  swc1       $f0, 0x64($v0)
    /* 49FF4 800A1DA4 E4400068 */  swc1       $f0, 0x68($v0)
    /* 49FF8 800A1DA8 E440006C */  swc1       $f0, 0x6C($v0)
    /* 49FFC 800A1DAC A4400074 */  sh         $zero, 0x74($v0)
    /* 4A000 800A1DB0 E4520070 */  swc1       $f18, 0x70($v0)
    /* 4A004 800A1DB4 8C8F0000 */  lw         $t7, 0x0($a0)
    /* 4A008 800A1DB8 01E35821 */  addu       $t3, $t7, $v1
    /* 4A00C 800A1DBC 8D650000 */  lw         $a1, 0x0($t3)
    /* 4A010 800A1DC0 C4A40030 */  lwc1       $f4, 0x30($a1)
    /* 4A014 800A1DC4 4600203C */  c.lt.s     $f4, $f0
    /* 4A018 800A1DC8 00000000 */  nop
    /* 4A01C 800A1DCC 45020006 */  bc1fl      .L800A1DE8
    /* 4A020 800A1DD0 C4A60034 */   lwc1      $f6, 0x34($a1)
    /* 4A024 800A1DD4 A4590074 */  sh         $t9, 0x74($v0)
    /* 4A028 800A1DD8 8C880000 */  lw         $t0, 0x0($a0)
    /* 4A02C 800A1DDC 01034821 */  addu       $t1, $t0, $v1
    /* 4A030 800A1DE0 8D250000 */  lw         $a1, 0x0($t1)
    /* 4A034 800A1DE4 C4A60034 */  lwc1       $f6, 0x34($a1)
  .L800A1DE8:
    /* 4A038 800A1DE8 4600303C */  c.lt.s     $f6, $f0
    /* 4A03C 800A1DEC 00000000 */  nop
    /* 4A040 800A1DF0 45020008 */  bc1fl      .L800A1E14
    /* 4A044 800A1DF4 C4A80038 */   lwc1      $f8, 0x38($a1)
    /* 4A048 800A1DF8 944A0074 */  lhu        $t2, 0x74($v0)
    /* 4A04C 800A1DFC 354C0002 */  ori        $t4, $t2, 0x2
    /* 4A050 800A1E00 A44C0074 */  sh         $t4, 0x74($v0)
    /* 4A054 800A1E04 8C8D0000 */  lw         $t5, 0x0($a0)
    /* 4A058 800A1E08 01A37021 */  addu       $t6, $t5, $v1
    /* 4A05C 800A1E0C 8DC50000 */  lw         $a1, 0x0($t6)
    /* 4A060 800A1E10 C4A80038 */  lwc1       $f8, 0x38($a1)
  .L800A1E14:
    /* 4A064 800A1E14 4600403C */  c.lt.s     $f8, $f0
    /* 4A068 800A1E18 00000000 */  nop
    /* 4A06C 800A1E1C 45020035 */  bc1fl      .L800A1EF4
    /* 4A070 800A1E20 920D0008 */   lbu       $t5, 0x8($s0)
    /* 4A074 800A1E24 944F0074 */  lhu        $t7, 0x74($v0)
    /* 4A078 800A1E28 35EB0004 */  ori        $t3, $t7, 0x4
    /* 4A07C 800A1E2C 10000030 */  b          .L800A1EF0
    /* 4A080 800A1E30 A44B0074 */   sh        $t3, 0x74($v0)
  .L800A1E34:
    /* 4A084 800A1E34 C6000020 */  lwc1       $f0, 0x20($s0)
    /* 4A088 800A1E38 C6020024 */  lwc1       $f2, 0x24($s0)
    /* 4A08C 800A1E3C C60E0028 */  lwc1       $f14, 0x28($s0)
    /* 4A090 800A1E40 46000282 */  mul.s      $f10, $f0, $f0
    /* 4A094 800A1E44 AFA40024 */  sw         $a0, 0x24($sp)
    /* 4A098 800A1E48 AFA3002C */  sw         $v1, 0x2C($sp)
    /* 4A09C 800A1E4C 46021402 */  mul.s      $f16, $f2, $f2
    /* 4A0A0 800A1E50 46105480 */  add.s      $f18, $f10, $f16
    /* 4A0A4 800A1E54 460E7102 */  mul.s      $f4, $f14, $f14
    /* 4A0A8 800A1E58 0C00CAC8 */  jal        sqrtf
    /* 4A0AC 800A1E5C 46049300 */   add.s     $f12, $f18, $f4
    /* 4A0B0 800A1E60 C6060014 */  lwc1       $f6, 0x14($s0)
    /* 4A0B4 800A1E64 C6080020 */  lwc1       $f8, 0x20($s0)
    /* 4A0B8 800A1E68 C60E0028 */  lwc1       $f14, 0x28($s0)
    /* 4A0BC 800A1E6C E6000050 */  swc1       $f0, 0x50($s0)
    /* 4A0C0 800A1E70 46083282 */  mul.s      $f10, $f6, $f8
    /* 4A0C4 800A1E74 00000000 */  nop
    /* 4A0C8 800A1E78 460E7402 */  mul.s      $f16, $f14, $f14
    /* 4A0CC 800A1E7C 0C00CAC8 */  jal        sqrtf
    /* 4A0D0 800A1E80 46105300 */   add.s     $f12, $f10, $f16
    /* 4A0D4 800A1E84 C60C0024 */  lwc1       $f12, 0x24($s0)
    /* 4A0D8 800A1E88 0C0061C3 */  jal        atan2f
    /* 4A0DC 800A1E8C 46000386 */   mov.s     $f14, $f0
    /* 4A0E0 800A1E90 E6000054 */  swc1       $f0, 0x54($s0)
    /* 4A0E4 800A1E94 C60C0028 */  lwc1       $f12, 0x28($s0)
    /* 4A0E8 800A1E98 0C0061C3 */  jal        atan2f
    /* 4A0EC 800A1E9C C60E0020 */   lwc1      $f14, 0x20($s0)
    /* 4A0F0 800A1EA0 8FA40024 */  lw         $a0, 0x24($sp)
    /* 4A0F4 800A1EA4 8FA3002C */  lw         $v1, 0x2C($sp)
    /* 4A0F8 800A1EA8 E600005C */  swc1       $f0, 0x5C($s0)
    /* 4A0FC 800A1EAC 8C980000 */  lw         $t8, 0x0($a0)
    /* 4A100 800A1EB0 0303C821 */  addu       $t9, $t8, $v1
    /* 4A104 800A1EB4 8F280000 */  lw         $t0, 0x0($t9)
    /* 4A108 800A1EB8 C5120030 */  lwc1       $f18, 0x30($t0)
    /* 4A10C 800A1EBC E6120058 */  swc1       $f18, 0x58($s0)
    /* 4A110 800A1EC0 8C890000 */  lw         $t1, 0x0($a0)
    /* 4A114 800A1EC4 01235021 */  addu       $t2, $t1, $v1
    /* 4A118 800A1EC8 8D4C0000 */  lw         $t4, 0x0($t2)
    /* 4A11C 800A1ECC C5840034 */  lwc1       $f4, 0x34($t4)
    /* 4A120 800A1ED0 10000007 */  b          .L800A1EF0
    /* 4A124 800A1ED4 E6040060 */   swc1      $f4, 0x60($s0)
  .L800A1ED8:
    /* 4A128 800A1ED8 3C02800D */  lui        $v0, %hi(D_800D6ADC)
    /* 4A12C 800A1EDC 8C426ADC */  lw         $v0, %lo(D_800D6ADC)($v0)
    /* 4A130 800A1EE0 50400004 */  beql       $v0, $zero, .L800A1EF4
    /* 4A134 800A1EE4 920D0008 */   lbu       $t5, 0x8($s0)
    /* 4A138 800A1EE8 0040F809 */  jalr       $v0
    /* 4A13C 800A1EEC 02002025 */   or        $a0, $s0, $zero
  .L800A1EF0:
    /* 4A140 800A1EF0 920D0008 */  lbu        $t5, 0x8($s0)
  .L800A1EF4:
    /* 4A144 800A1EF4 31AE0002 */  andi       $t6, $t5, 0x2
    /* 4A148 800A1EF8 11C00007 */  beqz       $t6, .L800A1F18
    /* 4A14C 800A1EFC 00002025 */   or        $a0, $zero, $zero
    /* 4A150 800A1F00 0C026D7A */  jal        func_8009B5E8
    /* 4A154 800A1F04 96050004 */   lhu       $a1, 0x4($s0)
    /* 4A158 800A1F08 10400003 */  beqz       $v0, .L800A1F18
    /* 4A15C 800A1F0C AE02004C */   sw        $v0, 0x4C($s0)
    /* 4A160 800A1F10 240F0001 */  addiu      $t7, $zero, 0x1
    /* 4A164 800A1F14 A04F00BA */  sb         $t7, 0xBA($v0)
  .L800A1F18:
    /* 4A168 800A1F18 02001025 */  or         $v0, $s0, $zero
  .L800A1F1C:
    /* 4A16C 800A1F1C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 4A170 800A1F20 8FB00018 */  lw         $s0, 0x18($sp)
    /* 4A174 800A1F24 27BD0048 */  addiu      $sp, $sp, 0x48
    /* 4A178 800A1F28 03E00008 */  jr         $ra
    /* 4A17C 800A1F2C 00000000 */   nop
endlabel func_800A19EC
.size func_800A19EC, . - func_800A19EC
