.section .late_rodata
nonmatching D_80128814

dlabel D_80128814
    /* B1284 80128814 461C3C00 */ .float 9999
enddlabel D_80128814
.size D_80128814, . - D_80128814

nonmatching D_80128818

dlabel D_80128818
    /* B1288 80128818 40490FDB */ .float 3.141592741
enddlabel D_80128818
.size D_80128818, . - D_80128818


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800FAC74, 0x4F0

glabel func_800FAC74
    /* 836E4 800FAC74 3C188013 */  lui        $t8, %hi(D_801292E0)
    /* 836E8 800FAC78 8F1892E0 */  lw         $t8, %lo(D_801292E0)($t8)
    /* 836EC 800FAC7C 3C018013 */  lui        $at, %hi(D_80128814)
    /* 836F0 800FAC80 C4248814 */  lwc1       $f4, %lo(D_80128814)($at)
    /* 836F4 800FAC84 44983000 */  mtc1       $t8, $f6
    /* 836F8 800FAC88 27BDFFA0 */  addiu      $sp, $sp, -0x60
    /* 836FC 800FAC8C 3C0E800D */  lui        $t6, %hi(D_800D799C)
    /* 83700 800FAC90 46803220 */  cvt.s.w    $f8, $f6
    /* 83704 800FAC94 8DCE799C */  lw         $t6, %lo(D_800D799C)($t6)
    /* 83708 800FAC98 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 8370C 800FAC9C AFB00018 */  sw         $s0, 0x18($sp)
    /* 83710 800FACA0 AFA50064 */  sw         $a1, 0x64($sp)
    /* 83714 800FACA4 8DCF003C */  lw         $t7, 0x3C($t6)
    /* 83718 800FACA8 46082032 */  c.eq.s     $f4, $f8
    /* 8371C 800FACAC 00C08025 */  or         $s0, $a2, $zero
    /* 83720 800FACB0 00803825 */  or         $a3, $a0, $zero
    /* 83724 800FACB4 3C038005 */  lui        $v1, %hi(gPlayerControllers)
    /* 83728 800FACB8 4500000D */  bc1f       .L800FACF0
    /* 8372C 800FACBC AFAF005C */   sw        $t7, 0x5C($sp)
    /* 83730 800FACC0 00C04825 */  or         $t1, $a2, $zero
    /* 83734 800FACC4 00805025 */  or         $t2, $a0, $zero
    /* 83738 800FACC8 24CB003C */  addiu      $t3, $a2, 0x3C
  .L800FACCC:
    /* 8373C 800FACCC 8D280000 */  lw         $t0, 0x0($t1)
    /* 83740 800FACD0 2529000C */  addiu      $t1, $t1, 0xC
    /* 83744 800FACD4 254A000C */  addiu      $t2, $t2, 0xC
    /* 83748 800FACD8 AD48FFF4 */  sw         $t0, -0xC($t2)
    /* 8374C 800FACDC 8D39FFF8 */  lw         $t9, -0x8($t1)
    /* 83750 800FACE0 AD59FFF8 */  sw         $t9, -0x8($t2)
    /* 83754 800FACE4 8D28FFFC */  lw         $t0, -0x4($t1)
    /* 83758 800FACE8 152BFFF8 */  bne        $t1, $t3, .L800FACCC
    /* 8375C 800FACEC AD48FFFC */   sw        $t0, -0x4($t2)
  .L800FACF0:
    /* 83760 800FACF0 94638F20 */  lhu        $v1, %lo(gPlayerControllers)($v1)
    /* 83764 800FACF4 00001025 */  or         $v0, $zero, $zero
    /* 83768 800FACF8 3C0E800C */  lui        $t6, %hi(D_800BE4F8)
    /* 8376C 800FACFC 306C0100 */  andi       $t4, $v1, 0x100
    /* 83770 800FAD00 11800002 */  beqz       $t4, .L800FAD0C
    /* 83774 800FAD04 306D0200 */   andi      $t5, $v1, 0x200
    /* 83778 800FAD08 24020001 */  addiu      $v0, $zero, 0x1
  .L800FAD0C:
    /* 8377C 800FAD0C 11A00002 */  beqz       $t5, .L800FAD18
    /* 83780 800FAD10 27A40038 */   addiu     $a0, $sp, 0x38
    /* 83784 800FAD14 2442FFFF */  addiu      $v0, $v0, -0x1
  .L800FAD18:
    /* 83788 800FAD18 8DCEE4F8 */  lw         $t6, %lo(D_800BE4F8)($t6)
    /* 8378C 800FAD1C 24010001 */  addiu      $at, $zero, 0x1
    /* 83790 800FAD20 26050018 */  addiu      $a1, $s0, 0x18
    /* 83794 800FAD24 15C10080 */  bne        $t6, $at, .L800FAF28
    /* 83798 800FAD28 26060024 */   addiu     $a2, $s0, 0x24
    /* 8379C 800FAD2C 1040003C */  beqz       $v0, .L800FAE20
    /* 837A0 800FAD30 8FAF0064 */   lw        $t7, 0x64($sp)
    /* 837A4 800FAD34 91F8001E */  lbu        $t8, 0x1E($t7)
    /* 837A8 800FAD38 3C038013 */  lui        $v1, %hi(D_801293AC)
    /* 837AC 800FAD3C 3C018013 */  lui        $at, %hi(D_801293C4)
    /* 837B0 800FAD40 13000037 */  beqz       $t8, .L800FAE20
    /* 837B4 800FAD44 246393AC */   addiu     $v1, $v1, %lo(D_801293AC)
    /* 837B8 800FAD48 18400019 */  blez       $v0, .L800FADB0
    /* 837BC 800FAD4C C42293C4 */   lwc1      $f2, %lo(D_801293C4)($at)
    /* 837C0 800FAD50 3C028013 */  lui        $v0, %hi(D_801293BC)
    /* 837C4 800FAD54 244293BC */  addiu      $v0, $v0, %lo(D_801293BC)
    /* 837C8 800FAD58 44808000 */  mtc1       $zero, $f16
    /* 837CC 800FAD5C C4400000 */  lwc1       $f0, 0x0($v0)
    /* 837D0 800FAD60 3C018013 */  lui        $at, %hi(D_801293CC)
    /* 837D4 800FAD64 4610003C */  c.lt.s     $f0, $f16
    /* 837D8 800FAD68 00000000 */  nop
    /* 837DC 800FAD6C 45020005 */  bc1fl      .L800FAD84
    /* 837E0 800FAD70 46020180 */   add.s     $f6, $f0, $f2
    /* 837E4 800FAD74 C42A93CC */  lwc1       $f10, %lo(D_801293CC)($at)
    /* 837E8 800FAD78 460A1082 */  mul.s      $f2, $f2, $f10
    /* 837EC 800FAD7C 00000000 */  nop
    /* 837F0 800FAD80 46020180 */  add.s      $f6, $f0, $f2
  .L800FAD84:
    /* 837F4 800FAD84 3C018013 */  lui        $at, %hi(D_801293B4)
    /* 837F8 800FAD88 E4460000 */  swc1       $f6, 0x0($v0)
    /* 837FC 800FAD8C C42C93B4 */  lwc1       $f12, %lo(D_801293B4)($at)
    /* 83800 800FAD90 C4400000 */  lwc1       $f0, 0x0($v0)
    /* 83804 800FAD94 4600603E */  c.le.s     $f12, $f0
    /* 83808 800FAD98 00000000 */  nop
    /* 8380C 800FAD9C 4502001D */  bc1fl      .L800FAE14
    /* 83810 800FADA0 C46A0000 */   lwc1      $f10, 0x0($v1)
    /* 83814 800FADA4 E44C0000 */  swc1       $f12, 0x0($v0)
    /* 83818 800FADA8 10000019 */  b          .L800FAE10
    /* 8381C 800FADAC C4400000 */   lwc1      $f0, 0x0($v0)
  .L800FADB0:
    /* 83820 800FADB0 3C028013 */  lui        $v0, %hi(D_801293BC)
    /* 83824 800FADB4 244293BC */  addiu      $v0, $v0, %lo(D_801293BC)
    /* 83828 800FADB8 44808000 */  mtc1       $zero, $f16
    /* 8382C 800FADBC C4400000 */  lwc1       $f0, 0x0($v0)
    /* 83830 800FADC0 3C018013 */  lui        $at, %hi(D_801293CC)
    /* 83834 800FADC4 4600803C */  c.lt.s     $f16, $f0
    /* 83838 800FADC8 00000000 */  nop
    /* 8383C 800FADCC 45020005 */  bc1fl      .L800FADE4
    /* 83840 800FADD0 46020201 */   sub.s     $f8, $f0, $f2
    /* 83844 800FADD4 C42493CC */  lwc1       $f4, %lo(D_801293CC)($at)
    /* 83848 800FADD8 46041082 */  mul.s      $f2, $f2, $f4
    /* 8384C 800FADDC 00000000 */  nop
    /* 83850 800FADE0 46020201 */  sub.s      $f8, $f0, $f2
  .L800FADE4:
    /* 83854 800FADE4 3C018013 */  lui        $at, %hi(D_801293B4)
    /* 83858 800FADE8 E4480000 */  swc1       $f8, 0x0($v0)
    /* 8385C 800FADEC C42C93B4 */  lwc1       $f12, %lo(D_801293B4)($at)
    /* 83860 800FADF0 C4400000 */  lwc1       $f0, 0x0($v0)
    /* 83864 800FADF4 46006307 */  neg.s      $f12, $f12
    /* 83868 800FADF8 460C003E */  c.le.s     $f0, $f12
    /* 8386C 800FADFC 00000000 */  nop
    /* 83870 800FAE00 45020004 */  bc1fl      .L800FAE14
    /* 83874 800FAE04 C46A0000 */   lwc1      $f10, 0x0($v1)
    /* 83878 800FAE08 E44C0000 */  swc1       $f12, 0x0($v0)
    /* 8387C 800FAE0C C4400000 */  lwc1       $f0, 0x0($v0)
  .L800FAE10:
    /* 83880 800FAE10 C46A0000 */  lwc1       $f10, 0x0($v1)
  .L800FAE14:
    /* 83884 800FAE14 46005180 */  add.s      $f6, $f10, $f0
    /* 83888 800FAE18 10000043 */  b          .L800FAF28
    /* 8388C 800FAE1C E4660000 */   swc1      $f6, 0x0($v1)
  .L800FAE20:
    /* 83890 800FAE20 3C038013 */  lui        $v1, %hi(D_801293AC)
    /* 83894 800FAE24 246393AC */  addiu      $v1, $v1, %lo(D_801293AC)
    /* 83898 800FAE28 44808000 */  mtc1       $zero, $f16
    /* 8389C 800FAE2C C4620000 */  lwc1       $f2, 0x0($v1)
    /* 838A0 800FAE30 3C028013 */  lui        $v0, %hi(D_801293BC)
    /* 838A4 800FAE34 244293BC */  addiu      $v0, $v0, %lo(D_801293BC)
    /* 838A8 800FAE38 4602803C */  c.lt.s     $f16, $f2
    /* 838AC 800FAE3C 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* 838B0 800FAE40 45020019 */  bc1fl      .L800FAEA8
    /* 838B4 800FAE44 4610103C */   c.lt.s    $f2, $f16
    /* 838B8 800FAE48 44816000 */  mtc1       $at, $f12
    /* 838BC 800FAE4C 3C018013 */  lui        $at, %hi(D_801293C4)
    /* 838C0 800FAE50 C42893C4 */  lwc1       $f8, %lo(D_801293C4)($at)
    /* 838C4 800FAE54 C4440000 */  lwc1       $f4, 0x0($v0)
    /* 838C8 800FAE58 46082281 */  sub.s      $f10, $f4, $f8
    /* 838CC 800FAE5C E44A0000 */  swc1       $f10, 0x0($v0)
    /* 838D0 800FAE60 C4400000 */  lwc1       $f0, 0x0($v0)
    /* 838D4 800FAE64 460C003E */  c.le.s     $f0, $f12
    /* 838D8 800FAE68 00000000 */  nop
    /* 838DC 800FAE6C 45020004 */  bc1fl      .L800FAE80
    /* 838E0 800FAE70 46001180 */   add.s     $f6, $f2, $f0
    /* 838E4 800FAE74 E44C0000 */  swc1       $f12, 0x0($v0)
    /* 838E8 800FAE78 C4400000 */  lwc1       $f0, 0x0($v0)
    /* 838EC 800FAE7C 46001180 */  add.s      $f6, $f2, $f0
  .L800FAE80:
    /* 838F0 800FAE80 E4660000 */  swc1       $f6, 0x0($v1)
    /* 838F4 800FAE84 C4640000 */  lwc1       $f4, 0x0($v1)
    /* 838F8 800FAE88 4610203E */  c.le.s     $f4, $f16
    /* 838FC 800FAE8C 00000000 */  nop
    /* 83900 800FAE90 45020026 */  bc1fl      .L800FAF2C
    /* 83904 800FAE94 8FAB0064 */   lw        $t3, 0x64($sp)
    /* 83908 800FAE98 E4700000 */  swc1       $f16, 0x0($v1)
    /* 8390C 800FAE9C 10000022 */  b          .L800FAF28
    /* 83910 800FAEA0 E4500000 */   swc1      $f16, 0x0($v0)
    /* 83914 800FAEA4 4610103C */  c.lt.s     $f2, $f16
  .L800FAEA8:
    /* 83918 800FAEA8 3C028013 */  lui        $v0, %hi(D_801293BC)
    /* 8391C 800FAEAC 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 83920 800FAEB0 244293BC */  addiu      $v0, $v0, %lo(D_801293BC)
    /* 83924 800FAEB4 4502001B */  bc1fl      .L800FAF24
    /* 83928 800FAEB8 E4700000 */   swc1      $f16, 0x0($v1)
    /* 8392C 800FAEBC 44816000 */  mtc1       $at, $f12
    /* 83930 800FAEC0 3C028013 */  lui        $v0, %hi(D_801293BC)
    /* 83934 800FAEC4 244293BC */  addiu      $v0, $v0, %lo(D_801293BC)
    /* 83938 800FAEC8 3C018013 */  lui        $at, %hi(D_801293C4)
    /* 8393C 800FAECC C42A93C4 */  lwc1       $f10, %lo(D_801293C4)($at)
    /* 83940 800FAED0 C4480000 */  lwc1       $f8, 0x0($v0)
    /* 83944 800FAED4 460A4180 */  add.s      $f6, $f8, $f10
    /* 83948 800FAED8 E4460000 */  swc1       $f6, 0x0($v0)
    /* 8394C 800FAEDC C4400000 */  lwc1       $f0, 0x0($v0)
    /* 83950 800FAEE0 4600603E */  c.le.s     $f12, $f0
    /* 83954 800FAEE4 00000000 */  nop
    /* 83958 800FAEE8 45020004 */  bc1fl      .L800FAEFC
    /* 8395C 800FAEEC 46001100 */   add.s     $f4, $f2, $f0
    /* 83960 800FAEF0 E44C0000 */  swc1       $f12, 0x0($v0)
    /* 83964 800FAEF4 C4400000 */  lwc1       $f0, 0x0($v0)
    /* 83968 800FAEF8 46001100 */  add.s      $f4, $f2, $f0
  .L800FAEFC:
    /* 8396C 800FAEFC E4640000 */  swc1       $f4, 0x0($v1)
    /* 83970 800FAF00 C4680000 */  lwc1       $f8, 0x0($v1)
    /* 83974 800FAF04 4608803E */  c.le.s     $f16, $f8
    /* 83978 800FAF08 00000000 */  nop
    /* 8397C 800FAF0C 45020007 */  bc1fl      .L800FAF2C
    /* 83980 800FAF10 8FAB0064 */   lw        $t3, 0x64($sp)
    /* 83984 800FAF14 E4700000 */  swc1       $f16, 0x0($v1)
    /* 83988 800FAF18 10000003 */  b          .L800FAF28
    /* 8398C 800FAF1C E4500000 */   swc1      $f16, 0x0($v0)
    /* 83990 800FAF20 E4700000 */  swc1       $f16, 0x0($v1)
  .L800FAF24:
    /* 83994 800FAF24 E4500000 */  swc1       $f16, 0x0($v0)
  .L800FAF28:
    /* 83998 800FAF28 8FAB0064 */  lw         $t3, 0x64($sp)
  .L800FAF2C:
    /* 8399C 800FAF2C 3C038013 */  lui        $v1, %hi(D_801293AC)
    /* 839A0 800FAF30 246393AC */  addiu      $v1, $v1, %lo(D_801293AC)
    /* 839A4 800FAF34 C4620000 */  lwc1       $f2, 0x0($v1)
    /* 839A8 800FAF38 C560005C */  lwc1       $f0, 0x5C($t3)
    /* 839AC 800FAF3C 4602003E */  c.le.s     $f0, $f2
    /* 839B0 800FAF40 00000000 */  nop
    /* 839B4 800FAF44 45020006 */  bc1fl      .L800FAF60
    /* 839B8 800FAF48 46000307 */   neg.s     $f12, $f0
    /* 839BC 800FAF4C 8FA90064 */  lw         $t1, 0x64($sp)
    /* 839C0 800FAF50 E4600000 */  swc1       $f0, 0x0($v1)
    /* 839C4 800FAF54 C4620000 */  lwc1       $f2, 0x0($v1)
    /* 839C8 800FAF58 C520005C */  lwc1       $f0, 0x5C($t1)
    /* 839CC 800FAF5C 46000307 */  neg.s      $f12, $f0
  .L800FAF60:
    /* 839D0 800FAF60 460C103E */  c.le.s     $f2, $f12
    /* 839D4 800FAF64 00000000 */  nop
    /* 839D8 800FAF68 45000002 */  bc1f       .L800FAF74
    /* 839DC 800FAF6C 00000000 */   nop
    /* 839E0 800FAF70 E46C0000 */  swc1       $f12, 0x0($v1)
  .L800FAF74:
    /* 839E4 800FAF74 0C00637B */  jal        lbvector_Diff
    /* 839E8 800FAF78 AFA70060 */   sw        $a3, 0x60($sp)
    /* 839EC 800FAF7C C7AE0038 */  lwc1       $f14, 0x38($sp)
    /* 839F0 800FAF80 C7AC0040 */  lwc1       $f12, 0x40($sp)
    /* 839F4 800FAF84 0C0061C3 */  jal        atan2f
    /* 839F8 800FAF88 46007387 */   neg.s     $f14, $f14
    /* 839FC 800FAF8C 3C018013 */  lui        $at, %hi(D_80128818)
    /* 83A00 800FAF90 C42E8818 */  lwc1       $f14, %lo(D_80128818)($at)
    /* 83A04 800FAF94 3C014334 */  lui        $at, (0x43340000 >> 16)
    /* 83A08 800FAF98 44819000 */  mtc1       $at, $f18
    /* 83A0C 800FAF9C 460E0283 */  div.s      $f10, $f0, $f14
    /* 83A10 800FAFA0 44808000 */  mtc1       $zero, $f16
    /* 83A14 800FAFA4 3C038013 */  lui        $v1, %hi(D_801293AC)
    /* 83A18 800FAFA8 246393AC */  addiu      $v1, $v1, %lo(D_801293AC)
    /* 83A1C 800FAFAC 3C0143B4 */  lui        $at, (0x43B40000 >> 16)
    /* 83A20 800FAFB0 8FA70060 */  lw         $a3, 0x60($sp)
    /* 83A24 800FAFB4 46125302 */  mul.s      $f12, $f10, $f18
    /* 83A28 800FAFB8 4610603C */  c.lt.s     $f12, $f16
    /* 83A2C 800FAFBC 46006086 */  mov.s      $f2, $f12
    /* 83A30 800FAFC0 45020005 */  bc1fl      .L800FAFD8
    /* 83A34 800FAFC4 3C0143B4 */   lui       $at, (0x43B40000 >> 16)
    /* 83A38 800FAFC8 44810000 */  mtc1       $at, $f0
    /* 83A3C 800FAFCC 00000000 */  nop
    /* 83A40 800FAFD0 46006080 */  add.s      $f2, $f12, $f0
    /* 83A44 800FAFD4 3C0143B4 */  lui        $at, (0x43B40000 >> 16)
  .L800FAFD8:
    /* 83A48 800FAFD8 44810000 */  mtc1       $at, $f0
    /* 83A4C 800FAFDC 3C0142B4 */  lui        $at, (0x42B40000 >> 16)
    /* 83A50 800FAFE0 44813000 */  mtc1       $at, $f6
    /* 83A54 800FAFE4 00000000 */  nop
    /* 83A58 800FAFE8 46061080 */  add.s      $f2, $f2, $f6
    /* 83A5C 800FAFEC 4602003E */  c.le.s     $f0, $f2
    /* 83A60 800FAFF0 00000000 */  nop
    /* 83A64 800FAFF4 45000002 */  bc1f       .L800FB000
    /* 83A68 800FAFF8 00000000 */   nop
    /* 83A6C 800FAFFC 46001081 */  sub.s      $f2, $f2, $f0
  .L800FB000:
    /* 83A70 800FB000 460E1282 */  mul.s      $f10, $f2, $f14
    /* 83A74 800FB004 C4640000 */  lwc1       $f4, 0x0($v1)
    /* 83A78 800FB008 8FA5005C */  lw         $a1, 0x5C($sp)
    /* 83A7C 800FB00C E7B0003C */  swc1       $f16, 0x3C($sp)
    /* 83A80 800FB010 46002207 */  neg.s      $f8, $f4
    /* 83A84 800FB014 E7B00040 */  swc1       $f16, 0x40($sp)
    /* 83A88 800FB018 E7A80038 */  swc1       $f8, 0x38($sp)
    /* 83A8C 800FB01C 46125183 */  div.s      $f6, $f10, $f18
    /* 83A90 800FB020 27A40038 */  addiu      $a0, $sp, 0x38
    /* 83A94 800FB024 AFA70060 */  sw         $a3, 0x60($sp)
    /* 83A98 800FB028 24A50054 */  addiu      $a1, $a1, 0x54
    /* 83A9C 800FB02C 44063000 */  mfc1       $a2, $f6
    /* 83AA0 800FB030 0C00647E */  jal        func_800191F8
    /* 83AA4 800FB034 00000000 */   nop
    /* 83AA8 800FB038 8FA70060 */  lw         $a3, 0x60($sp)
    /* 83AAC 800FB03C C6040024 */  lwc1       $f4, 0x24($s0)
    /* 83AB0 800FB040 3C018013 */  lui        $at, %hi(D_801293D8)
    /* 83AB4 800FB044 3C068013 */  lui        $a2, %hi(D_801293C0)
    /* 83AB8 800FB048 E4E40024 */  swc1       $f4, 0x24($a3)
    /* 83ABC 800FB04C C608002C */  lwc1       $f8, 0x2C($s0)
    /* 83AC0 800FB050 3C088013 */  lui        $t0, %hi(D_801293D8)
    /* 83AC4 800FB054 E4E8002C */  swc1       $f8, 0x2C($a3)
    /* 83AC8 800FB058 C7A60038 */  lwc1       $f6, 0x38($sp)
    /* 83ACC 800FB05C C60A0018 */  lwc1       $f10, 0x18($s0)
    /* 83AD0 800FB060 46065101 */  sub.s      $f4, $f10, $f6
    /* 83AD4 800FB064 E4E40018 */  swc1       $f4, 0x18($a3)
    /* 83AD8 800FB068 C7AA0040 */  lwc1       $f10, 0x40($sp)
    /* 83ADC 800FB06C C6080020 */  lwc1       $f8, 0x20($s0)
    /* 83AE0 800FB070 460A4181 */  sub.s      $f6, $f8, $f10
    /* 83AE4 800FB074 E4E60020 */  swc1       $f6, 0x20($a3)
    /* 83AE8 800FB078 8FAA0064 */  lw         $t2, 0x64($sp)
    /* 83AEC 800FB07C 9159001F */  lbu        $t9, 0x1F($t2)
    /* 83AF0 800FB080 13200011 */  beqz       $t9, .L800FB0C8
    /* 83AF4 800FB084 00000000 */   nop
    /* 83AF8 800FB088 AC2093D8 */  sw         $zero, %lo(D_801293D8)($at)
    /* 83AFC 800FB08C C60E0028 */  lwc1       $f14, 0x28($s0)
    /* 83B00 800FB090 C4EC0028 */  lwc1       $f12, 0x28($a3)
    /* 83B04 800FB094 AFA70060 */  sw         $a3, 0x60($sp)
    /* 83B08 800FB098 0C03EE05 */  jal        func_800FB814
    /* 83B0C 800FB09C 8CC693C0 */   lw        $a2, %lo(D_801293C0)($a2)
    /* 83B10 800FB0A0 8FA70060 */  lw         $a3, 0x60($sp)
    /* 83B14 800FB0A4 3C068013 */  lui        $a2, %hi(D_801293C0)
    /* 83B18 800FB0A8 E4E00028 */  swc1       $f0, 0x28($a3)
    /* 83B1C 800FB0AC 8CC693C0 */  lw         $a2, %lo(D_801293C0)($a2)
    /* 83B20 800FB0B0 C60E001C */  lwc1       $f14, 0x1C($s0)
    /* 83B24 800FB0B4 0C03EE05 */  jal        func_800FB814
    /* 83B28 800FB0B8 C4EC001C */   lwc1      $f12, 0x1C($a3)
    /* 83B2C 800FB0BC 8FA70060 */  lw         $a3, 0x60($sp)
    /* 83B30 800FB0C0 10000023 */  b          .L800FB150
    /* 83B34 800FB0C4 E4E0001C */   swc1      $f0, 0x1C($a3)
  .L800FB0C8:
    /* 83B38 800FB0C8 8D0893D8 */  lw         $t0, %lo(D_801293D8)($t0)
    /* 83B3C 800FB0CC 3C068013 */  lui        $a2, %hi(D_801293D4)
    /* 83B40 800FB0D0 51000007 */  beql       $t0, $zero, .L800FB0F0
    /* 83B44 800FB0D4 C4EC0028 */   lwc1      $f12, 0x28($a3)
    /* 83B48 800FB0D8 C6040028 */  lwc1       $f4, 0x28($s0)
    /* 83B4C 800FB0DC E4E40028 */  swc1       $f4, 0x28($a3)
    /* 83B50 800FB0E0 C608001C */  lwc1       $f8, 0x1C($s0)
    /* 83B54 800FB0E4 1000001A */  b          .L800FB150
    /* 83B58 800FB0E8 E4E8001C */   swc1      $f8, 0x1C($a3)
    /* 83B5C 800FB0EC C4EC0028 */  lwc1       $f12, 0x28($a3)
  .L800FB0F0:
    /* 83B60 800FB0F0 C60E0028 */  lwc1       $f14, 0x28($s0)
    /* 83B64 800FB0F4 AFA70060 */  sw         $a3, 0x60($sp)
    /* 83B68 800FB0F8 0C03EE05 */  jal        func_800FB814
    /* 83B6C 800FB0FC 8CC693D4 */   lw        $a2, %lo(D_801293D4)($a2)
    /* 83B70 800FB100 8FA70060 */  lw         $a3, 0x60($sp)
    /* 83B74 800FB104 3C068013 */  lui        $a2, %hi(D_801293D4)
    /* 83B78 800FB108 E4E00028 */  swc1       $f0, 0x28($a3)
    /* 83B7C 800FB10C 8CC693D4 */  lw         $a2, %lo(D_801293D4)($a2)
    /* 83B80 800FB110 C60E001C */  lwc1       $f14, 0x1C($s0)
    /* 83B84 800FB114 0C03EE05 */  jal        func_800FB814
    /* 83B88 800FB118 C4EC001C */   lwc1      $f12, 0x1C($a3)
    /* 83B8C 800FB11C 8FA70060 */  lw         $a3, 0x60($sp)
    /* 83B90 800FB120 3C028013 */  lui        $v0, %hi(D_801293D8)
    /* 83B94 800FB124 244293D8 */  addiu      $v0, $v0, %lo(D_801293D8)
    /* 83B98 800FB128 E4E0001C */  swc1       $f0, 0x1C($a3)
    /* 83B9C 800FB12C C60A0028 */  lwc1       $f10, 0x28($s0)
    /* 83BA0 800FB130 C4E60028 */  lwc1       $f6, 0x28($a3)
    /* 83BA4 800FB134 46065032 */  c.eq.s     $f10, $f6
    /* 83BA8 800FB138 00000000 */  nop
    /* 83BAC 800FB13C 45020005 */  bc1fl      .L800FB154
    /* 83BB0 800FB140 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 83BB4 800FB144 8C4C0000 */  lw         $t4, 0x0($v0)
    /* 83BB8 800FB148 258D0001 */  addiu      $t5, $t4, 0x1
    /* 83BBC 800FB14C AC4D0000 */  sw         $t5, 0x0($v0)
  .L800FB150:
    /* 83BC0 800FB150 8FBF001C */  lw         $ra, 0x1C($sp)
  .L800FB154:
    /* 83BC4 800FB154 8FB00018 */  lw         $s0, 0x18($sp)
    /* 83BC8 800FB158 27BD0060 */  addiu      $sp, $sp, 0x60
    /* 83BCC 800FB15C 03E00008 */  jr         $ra
    /* 83BD0 800FB160 00000000 */   nop
endlabel func_800FAC74
.size func_800FAC74, . - func_800FAC74
