.section .late_rodata
nonmatching jtbl_800D5B64

dlabel jtbl_800D5B64
    /* 7DDB4 800D5B64 800A384C */ .word .L800A384C
    /* 7DDB8 800D5B68 800A3864 */ .word .L800A3864
    /* 7DDBC 800D5B6C 800A389C */ .word .L800A389C
    /* 7DDC0 800D5B70 800A38D4 */ .word .L800A38D4
    /* 7DDC4 800D5B74 800A38F0 */ .word .L800A38F0
    /* 7DDC8 800D5B78 800A3928 */ .word .L800A3928
    /* 7DDCC 800D5B7C 800A3944 */ .word .L800A3944
    /* 7DDD0 800D5B80 800A397C */ .word .L800A397C
    /* 7DDD4 800D5B84 800A3998 */ .word .L800A3998
    /* 7DDD8 800D5B88 800A39D4 */ .word .L800A39D4
    /* 7DDDC 800D5B8C 800A3A1C */ .word .L800A3A1C
    /* 7DDE0 800D5B90 800A3AE0 */ .word .L800A3AE0
    /* 7DDE4 800D5B94 800A3818 */ .word .L800A3818
    /* 7DDE8 800D5B98 800A3B40 */ .word .L800A3B40
    /* 7DDEC 800D5B9C 800A3B4C */ .word .L800A3B4C
    /* 7DDF0 800D5BA0 800A3F5C */ .word .L800A3F5C
    /* 7DDF4 800D5BA4 800A3F5C */ .word .L800A3F5C
    /* 7DDF8 800D5BA8 800A3FB0 */ .word .L800A3FB0
    /* 7DDFC 800D5BAC 800A3FEC */ .word .L800A3FEC
    /* 7DE00 800D5BB0 800A3818 */ .word .L800A3818
    /* 7DE04 800D5BB4 800A3F74 */ .word .L800A3F74
    /* 7DE08 800D5BB8 800A40C4 */ .word .L800A40C4
    /* 7DE0C 800D5BBC 800A40AC */ .word .L800A40AC
    /* 7DE10 800D5BC0 800A40FC */ .word .L800A40FC
    /* 7DE14 800D5BC4 800A408C */ .word .L800A408C
    /* 7DE18 800D5BC8 800A40E4 */ .word .L800A40E4
    /* 7DE1C 800D5BCC 800A405C */ .word .L800A405C
    /* 7DE20 800D5BD0 800A4074 */ .word .L800A4074
    /* 7DE24 800D5BD4 800A411C */ .word .L800A411C
    /* 7DE28 800D5BD8 800A4134 */ .word .L800A4134
    /* 7DE2C 800D5BDC 800A414C */ .word .L800A414C
    /* 7DE30 800D5BE0 800A4164 */ .word .L800A4164
    /* 7DE34 800D5BE4 800A404C */ .word .L800A404C
    /* 7DE38 800D5BE8 800A3FA0 */ .word .L800A3FA0
enddlabel jtbl_800D5B64
.size jtbl_800D5B64, . - jtbl_800D5B64

nonmatching jtbl_800D5BEC

dlabel jtbl_800D5BEC
    /* 7DE3C 800D5BEC 800A3F10 */ .word .L800A3F10
    /* 7DE40 800D5BF0 800A3F48 */ .word .L800A3F48
    /* 7DE44 800D5BF4 800A3C90 */ .word .L800A3C90
    /* 7DE48 800D5BF8 800A3CA8 */ .word .L800A3CA8
    /* 7DE4C 800D5BFC 800A3D34 */ .word .L800A3D34
    /* 7DE50 800D5C00 800A3F48 */ .word .L800A3F48
    /* 7DE54 800D5C04 800A3B90 */ .word .L800A3B90
    /* 7DE58 800D5C08 800A3EC8 */ .word .L800A3EC8
enddlabel jtbl_800D5BEC
.size jtbl_800D5BEC, . - jtbl_800D5BEC

nonmatching jtbl_800D5C0C

dlabel jtbl_800D5C0C
    /* 7DE5C 800D5C0C 800A3D5C */ .word .L800A3D5C
    /* 7DE60 800D5C10 800A3D5C */ .word .L800A3D5C
    /* 7DE64 800D5C14 800A3D5C */ .word .L800A3D5C
    /* 7DE68 800D5C18 800A3D5C */ .word .L800A3D5C
    /* 7DE6C 800D5C1C 800A3D5C */ .word .L800A3D5C
    /* 7DE70 800D5C20 800A3DC8 */ .word .L800A3DC8
    /* 7DE74 800D5C24 00000000 */ .word 0x00000000
    /* 7DE78 800D5C28 00000000 */ .word 0x00000000
    /* 7DE7C 800D5C2C 00000000 */ .word 0x00000000
enddlabel jtbl_800D5C0C
.size jtbl_800D5C0C, . - jtbl_800D5C0C


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching game_tick, 0xA34

glabel game_tick
    /* 4B9CC 800A377C 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 4B9D0 800A3780 AFA40040 */  sw         $a0, 0x40($sp)
    /* 4B9D4 800A3784 AFBF003C */  sw         $ra, 0x3C($sp)
    /* 4B9D8 800A3788 3C04800D */  lui        $a0, %hi(D_800D7288)
    /* 4B9DC 800A378C AFBE0038 */  sw         $fp, 0x38($sp)
    /* 4B9E0 800A3790 AFB70034 */  sw         $s7, 0x34($sp)
    /* 4B9E4 800A3794 AFB60030 */  sw         $s6, 0x30($sp)
    /* 4B9E8 800A3798 AFB5002C */  sw         $s5, 0x2C($sp)
    /* 4B9EC 800A379C AFB40028 */  sw         $s4, 0x28($sp)
    /* 4B9F0 800A37A0 AFB30024 */  sw         $s3, 0x24($sp)
    /* 4B9F4 800A37A4 AFB20020 */  sw         $s2, 0x20($sp)
    /* 4B9F8 800A37A8 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 4B9FC 800A37AC AFB00018 */  sw         $s0, 0x18($sp)
    /* 4BA00 800A37B0 0C02F8C8 */  jal        func_800BE320
    /* 4BA04 800A37B4 24847288 */   addiu     $a0, $a0, %lo(D_800D7288)
    /* 4BA08 800A37B8 0C028AE7 */  jal        func_800A2B9C
    /* 4BA0C 800A37BC 00000000 */   nop
    /* 4BA10 800A37C0 0C029AC6 */  jal        func_800A6B18
    /* 4BA14 800A37C4 00000000 */   nop
    /* 4BA18 800A37C8 0C029AC8 */  jal        utilLoadOverlay
    /* 4BA1C 800A37CC 24040001 */   addiu     $a0, $zero, 0x1
    /* 4BA20 800A37D0 0C028B20 */  jal        func_800A2C80
    /* 4BA24 800A37D4 00000000 */   nop
    /* 4BA28 800A37D8 0C028C16 */  jal        func_800A3058
    /* 4BA2C 800A37DC 00000000 */   nop
    /* 4BA30 800A37E0 3C1E800D */  lui        $fp, %hi(D_800D6B98)
    /* 4BA34 800A37E4 3C16800D */  lui        $s6, %hi(saveCurrentWorld)
    /* 4BA38 800A37E8 3C13800D */  lui        $s3, %hi(D_800D6B68)
    /* 4BA3C 800A37EC 3C11800D */  lui        $s1, %hi(saveCurrentFileNum)
    /* 4BA40 800A37F0 3C10800C */  lui        $s0, %hi(gGameState)
    /* 4BA44 800A37F4 2610E4F0 */  addiu      $s0, $s0, %lo(gGameState)
    /* 4BA48 800A37F8 26316B88 */  addiu      $s1, $s1, %lo(saveCurrentFileNum)
    /* 4BA4C 800A37FC 26736B68 */  addiu      $s3, $s3, %lo(D_800D6B68)
    /* 4BA50 800A3800 26D66B90 */  addiu      $s6, $s6, %lo(saveCurrentWorld)
    /* 4BA54 800A3804 27DE6B98 */  addiu      $fp, $fp, %lo(D_800D6B98)
    /* 4BA58 800A3808 2417000C */  addiu      $s7, $zero, 0xC
    /* 4BA5C 800A380C 24150002 */  addiu      $s5, $zero, 0x2
    /* 4BA60 800A3810 2414000A */  addiu      $s4, $zero, 0xA
    /* 4BA64 800A3814 24120001 */  addiu      $s2, $zero, 0x1
  .L800A3818:
    /* 4BA68 800A3818 0C028B20 */  jal        func_800A2C80
    /* 4BA6C 800A381C 00000000 */   nop
    /* 4BA70 800A3820 8E0E0000 */  lw         $t6, 0x0($s0)
    /* 4BA74 800A3824 25CFFFFF */  addiu      $t7, $t6, -0x1
    /* 4BA78 800A3828 2DE10022 */  sltiu      $at, $t7, 0x22
    /* 4BA7C 800A382C 1020FFFA */  beqz       $at, .L800A3818
    /* 4BA80 800A3830 00000000 */   nop
    /* 4BA84 800A3834 000F7880 */  sll        $t7, $t7, 2
    /* 4BA88 800A3838 3C01800D */  lui        $at, %hi(jtbl_800D5B64)
    /* 4BA8C 800A383C 002F0821 */  addu       $at, $at, $t7
    /* 4BA90 800A3840 8C2F5B64 */  lw         $t7, %lo(jtbl_800D5B64)($at)
    /* 4BA94 800A3844 01E00008 */  jr         $t7
    /* 4BA98 800A3848 00000000 */   nop
  .L800A384C:
    /* 4BA9C 800A384C 0C029AC8 */  jal        utilLoadOverlay
    /* 4BAA0 800A3850 24040002 */   addiu     $a0, $zero, 0x2
    /* 4BAA4 800A3854 0C05473B */  jal        func_80151CEC_ovl4
    /* 4BAA8 800A3858 00002025 */   or        $a0, $zero, $zero
    /* 4BAAC 800A385C 1000FFEE */  b          .L800A3818
    /* 4BAB0 800A3860 AE150000 */   sw        $s5, 0x0($s0)
  .L800A3864:
    /* 4BAB4 800A3864 3C18800D */  lui        $t8, %hi(D_800D6B74)
    /* 4BAB8 800A3868 8F186B74 */  lw         $t8, %lo(D_800D6B74)($t8)
    /* 4BABC 800A386C 56580007 */  bnel       $s2, $t8, .L800A388C
    /* 4BAC0 800A3870 24190003 */   addiu     $t9, $zero, 0x3
    /* 4BAC4 800A3874 0C029AC8 */  jal        utilLoadOverlay
    /* 4BAC8 800A3878 24040004 */   addiu     $a0, $zero, 0x4
    /* 4BACC 800A387C 00002025 */  or         $a0, $zero, $zero
    /* 4BAD0 800A3880 0C055358 */  jal        func_80154D60_ovl6
    /* 4BAD4 800A3884 24050001 */   addiu     $a1, $zero, 0x1
    /* 4BAD8 800A3888 24190003 */  addiu      $t9, $zero, 0x3
  .L800A388C:
    /* 4BADC 800A388C AE190000 */  sw         $t9, 0x0($s0)
    /* 4BAE0 800A3890 3C01800D */  lui        $at, %hi(D_800D6B60)
    /* 4BAE4 800A3894 1000FFE0 */  b          .L800A3818
    /* 4BAE8 800A3898 AC396B60 */   sw        $t9, %lo(D_800D6B60)($at)
  .L800A389C:
    /* 4BAEC 800A389C 0C029AC8 */  jal        utilLoadOverlay
    /* 4BAF0 800A38A0 24040002 */   addiu     $a0, $zero, 0x2
    /* 4BAF4 800A38A4 0C05473B */  jal        func_80151CEC_ovl4
    /* 4BAF8 800A38A8 02402025 */   or        $a0, $s2, $zero
    /* 4BAFC 800A38AC 14550003 */  bne        $v0, $s5, .L800A38BC
    /* 4BB00 800A38B0 24090004 */   addiu     $t1, $zero, 0x4
    /* 4BB04 800A38B4 1000FFD8 */  b          .L800A3818
    /* 4BB08 800A38B8 AE090000 */   sw        $t1, 0x0($s0)
  .L800A38BC:
    /* 4BB0C 800A38BC 0C028C8A */  jal        func_800A3228
    /* 4BB10 800A38C0 00000000 */   nop
    /* 4BB14 800A38C4 8E0A0000 */  lw         $t2, 0x0($s0)
    /* 4BB18 800A38C8 AE140000 */  sw         $s4, 0x0($s0)
    /* 4BB1C 800A38CC 1000FFD2 */  b          .L800A3818
    /* 4BB20 800A38D0 AE6A0000 */   sw        $t2, 0x0($s3)
  .L800A38D4:
    /* 4BB24 800A38D4 0C028C54 */  jal        func_800A3150
    /* 4BB28 800A38D8 24040005 */   addiu     $a0, $zero, 0x5
    /* 4BB2C 800A38DC 240B0005 */  addiu      $t3, $zero, 0x5
    /* 4BB30 800A38E0 AE0B0000 */  sw         $t3, 0x0($s0)
    /* 4BB34 800A38E4 3C01800D */  lui        $at, %hi(D_800D6B60)
    /* 4BB38 800A38E8 1000FFCB */  b          .L800A3818
    /* 4BB3C 800A38EC AC2B6B60 */   sw        $t3, %lo(D_800D6B60)($at)
  .L800A38F0:
    /* 4BB40 800A38F0 0C029AC8 */  jal        utilLoadOverlay
    /* 4BB44 800A38F4 24040002 */   addiu     $a0, $zero, 0x2
    /* 4BB48 800A38F8 0C05473B */  jal        func_80151CEC_ovl4
    /* 4BB4C 800A38FC 02402025 */   or        $a0, $s2, $zero
    /* 4BB50 800A3900 14550003 */  bne        $v0, $s5, .L800A3910
    /* 4BB54 800A3904 240D0006 */   addiu     $t5, $zero, 0x6
    /* 4BB58 800A3908 1000FFC3 */  b          .L800A3818
    /* 4BB5C 800A390C AE0D0000 */   sw        $t5, 0x0($s0)
  .L800A3910:
    /* 4BB60 800A3910 0C028C8A */  jal        func_800A3228
    /* 4BB64 800A3914 00000000 */   nop
    /* 4BB68 800A3918 8E0E0000 */  lw         $t6, 0x0($s0)
    /* 4BB6C 800A391C AE140000 */  sw         $s4, 0x0($s0)
    /* 4BB70 800A3920 1000FFBD */  b          .L800A3818
    /* 4BB74 800A3924 AE6E0000 */   sw        $t6, 0x0($s3)
  .L800A3928:
    /* 4BB78 800A3928 0C028C54 */  jal        func_800A3150
    /* 4BB7C 800A392C 24040006 */   addiu     $a0, $zero, 0x6
    /* 4BB80 800A3930 240F0007 */  addiu      $t7, $zero, 0x7
    /* 4BB84 800A3934 AE0F0000 */  sw         $t7, 0x0($s0)
    /* 4BB88 800A3938 3C01800D */  lui        $at, %hi(D_800D6B60)
    /* 4BB8C 800A393C 1000FFB6 */  b          .L800A3818
    /* 4BB90 800A3940 AC2F6B60 */   sw        $t7, %lo(D_800D6B60)($at)
  .L800A3944:
    /* 4BB94 800A3944 0C029AC8 */  jal        utilLoadOverlay
    /* 4BB98 800A3948 24040002 */   addiu     $a0, $zero, 0x2
    /* 4BB9C 800A394C 0C05473B */  jal        func_80151CEC_ovl4
    /* 4BBA0 800A3950 02402025 */   or        $a0, $s2, $zero
    /* 4BBA4 800A3954 14550003 */  bne        $v0, $s5, .L800A3964
    /* 4BBA8 800A3958 24190008 */   addiu     $t9, $zero, 0x8
    /* 4BBAC 800A395C 1000FFAE */  b          .L800A3818
    /* 4BBB0 800A3960 AE190000 */   sw        $t9, 0x0($s0)
  .L800A3964:
    /* 4BBB4 800A3964 0C028C8A */  jal        func_800A3228
    /* 4BBB8 800A3968 00000000 */   nop
    /* 4BBBC 800A396C 8E080000 */  lw         $t0, 0x0($s0)
    /* 4BBC0 800A3970 AE140000 */  sw         $s4, 0x0($s0)
    /* 4BBC4 800A3974 1000FFA8 */  b          .L800A3818
    /* 4BBC8 800A3978 AE680000 */   sw        $t0, 0x0($s3)
  .L800A397C:
    /* 4BBCC 800A397C 0C028C54 */  jal        func_800A3150
    /* 4BBD0 800A3980 24040003 */   addiu     $a0, $zero, 0x3
    /* 4BBD4 800A3984 24090009 */  addiu      $t1, $zero, 0x9
    /* 4BBD8 800A3988 AE090000 */  sw         $t1, 0x0($s0)
    /* 4BBDC 800A398C 3C01800D */  lui        $at, %hi(D_800D6B60)
    /* 4BBE0 800A3990 1000FFA1 */  b          .L800A3818
    /* 4BBE4 800A3994 AC296B60 */   sw        $t1, %lo(D_800D6B60)($at)
  .L800A3998:
    /* 4BBE8 800A3998 0C029AC8 */  jal        utilLoadOverlay
    /* 4BBEC 800A399C 24040002 */   addiu     $a0, $zero, 0x2
    /* 4BBF0 800A39A0 0C05473B */  jal        func_80151CEC_ovl4
    /* 4BBF4 800A39A4 02402025 */   or        $a0, $s2, $zero
    /* 4BBF8 800A39A8 14550004 */  bne        $v0, $s5, .L800A39BC
    /* 4BBFC 800A39AC 3C01800D */   lui       $at, %hi(D_800D6B74)
    /* 4BC00 800A39B0 AC326B74 */  sw         $s2, %lo(D_800D6B74)($at)
    /* 4BC04 800A39B4 1000FF98 */  b          .L800A3818
    /* 4BC08 800A39B8 AE150000 */   sw        $s5, 0x0($s0)
  .L800A39BC:
    /* 4BC0C 800A39BC 0C028C8A */  jal        func_800A3228
    /* 4BC10 800A39C0 00000000 */   nop
    /* 4BC14 800A39C4 8E0B0000 */  lw         $t3, 0x0($s0)
    /* 4BC18 800A39C8 AE140000 */  sw         $s4, 0x0($s0)
    /* 4BC1C 800A39CC 1000FF92 */  b          .L800A3818
    /* 4BC20 800A39D0 AE6B0000 */   sw        $t3, 0x0($s3)
  .L800A39D4:
    /* 4BC24 800A39D4 0C028C4A */  jal        load_menu_overlays
    /* 4BC28 800A39D8 00000000 */   nop
    /* 4BC2C 800A39DC 0C028B39 */  jal        func_800A2CE4
    /* 4BC30 800A39E0 00000000 */   nop
    /* 4BC34 800A39E4 0C02E1F8 */  jal        func_800B87E0
    /* 4BC38 800A39E8 00000000 */   nop
    /* 4BC3C 800A39EC 0C056012 */  jal        func_80158048_ovl4
    /* 4BC40 800A39F0 00000000 */   nop
    /* 4BC44 800A39F4 0C02E2B5 */  jal        func_800B8AD4
    /* 4BC48 800A39F8 8E240000 */   lw        $a0, 0x0($s1)
    /* 4BC4C 800A39FC 8E0C0000 */  lw         $t4, 0x0($s0)
    /* 4BC50 800A3A00 2401000B */  addiu      $at, $zero, 0xB
    /* 4BC54 800A3A04 1581FF84 */  bne        $t4, $at, .L800A3818
    /* 4BC58 800A3A08 00000000 */   nop
    /* 4BC5C 800A3A0C 0C028D02 */  jal        func_800A3408
    /* 4BC60 800A3A10 00000000 */   nop
    /* 4BC64 800A3A14 1000FF80 */  b          .L800A3818
    /* 4BC68 800A3A18 00000000 */   nop
  .L800A3A1C:
    /* 4BC6C 800A3A1C 0C02E7D4 */  jal        saveCheckCutsceneWatched
    /* 4BC70 800A3A20 02402025 */   or        $a0, $s2, $zero
    /* 4BC74 800A3A24 1440000B */  bnez       $v0, .L800A3A54
    /* 4BC78 800A3A28 00000000 */   nop
    /* 4BC7C 800A3A2C 0C029AC8 */  jal        utilLoadOverlay
    /* 4BC80 800A3A30 24040004 */   addiu     $a0, $zero, 0x4
    /* 4BC84 800A3A34 02402025 */  or         $a0, $s2, $zero
    /* 4BC88 800A3A38 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4BC8C 800A3A3C 8E250000 */   lw        $a1, 0x0($s1)
    /* 4BC90 800A3A40 0C02E714 */  jal        func_800B9C50
    /* 4BC94 800A3A44 8E240000 */   lw        $a0, 0x0($s1)
    /* 4BC98 800A3A48 24040001 */  addiu      $a0, $zero, 0x1
    /* 4BC9C 800A3A4C 0C055358 */  jal        func_80154D60_ovl6
    /* 4BCA0 800A3A50 24050002 */   addiu     $a1, $zero, 0x2
  .L800A3A54:
    /* 4BCA4 800A3A54 0C028C4A */  jal        load_menu_overlays
    /* 4BCA8 800A3A58 00000000 */   nop
    /* 4BCAC 800A3A5C 0C028B57 */  jal        func_800A2D5C
    /* 4BCB0 800A3A60 00000000 */   nop
    /* 4BCB4 800A3A64 0C056695 */  jal        func_80159A54_ovl4
    /* 4BCB8 800A3A68 00000000 */   nop
    /* 4BCBC 800A3A6C 3C0D800D */  lui        $t5, %hi(D_800D6B78)
    /* 4BCC0 800A3A70 8DAD6B78 */  lw         $t5, %lo(D_800D6B78)($t5)
    /* 4BCC4 800A3A74 3C19800D */  lui        $t9, %hi(D_800D6B9C)
    /* 4BCC8 800A3A78 24090001 */  addiu      $t1, $zero, 0x1
    /* 4BCCC 800A3A7C 51A00006 */  beql       $t5, $zero, .L800A3A98
    /* 4BCD0 800A3A80 8FCF0000 */   lw        $t7, 0x0($fp)
    /* 4BCD4 800A3A84 8E0E0000 */  lw         $t6, 0x0($s0)
    /* 4BCD8 800A3A88 AE140000 */  sw         $s4, 0x0($s0)
    /* 4BCDC 800A3A8C 1000FF62 */  b          .L800A3818
    /* 4BCE0 800A3A90 AE6E0000 */   sw        $t6, 0x0($s3)
    /* 4BCE4 800A3A94 8FCF0000 */  lw         $t7, 0x0($fp)
  .L800A3A98:
    /* 4BCE8 800A3A98 3C01800C */  lui        $at, %hi(D_800BE500)
    /* 4BCEC 800A3A9C 3C18800C */  lui        $t8, %hi(D_800BE500)
    /* 4BCF0 800A3AA0 AC2FE500 */  sw         $t7, %lo(D_800BE500)($at)
    /* 4BCF4 800A3AA4 8F18E500 */  lw         $t8, %lo(D_800BE500)($t8)
    /* 4BCF8 800A3AA8 24010006 */  addiu      $at, $zero, 0x6
    /* 4BCFC 800A3AAC 57010009 */  bnel       $t8, $at, .L800A3AD4
    /* 4BD00 800A3AB0 AE170000 */   sw        $s7, 0x0($s0)
    /* 4BD04 800A3AB4 8F396B9C */  lw         $t9, %lo(D_800D6B9C)($t9)
    /* 4BD08 800A3AB8 3C01800C */  lui        $at, %hi(D_800BE504)
    /* 4BD0C 800A3ABC 0C028B5A */  jal        func_800A2D68
    /* 4BD10 800A3AC0 AC39E504 */   sw        $t9, %lo(D_800BE504)($at)
    /* 4BD14 800A3AC4 2408000F */  addiu      $t0, $zero, 0xF
    /* 4BD18 800A3AC8 1000FF53 */  b          .L800A3818
    /* 4BD1C 800A3ACC AE080000 */   sw        $t0, 0x0($s0)
    /* 4BD20 800A3AD0 AE170000 */  sw         $s7, 0x0($s0)
  .L800A3AD4:
    /* 4BD24 800A3AD4 3C01800D */  lui        $at, %hi(D_800D6B84)
    /* 4BD28 800A3AD8 1000FF4F */  b          .L800A3818
    /* 4BD2C 800A3ADC A0296B84 */   sb        $t1, %lo(D_800D6B84)($at)
  .L800A3AE0:
    /* 4BD30 800A3AE0 0C028C4A */  jal        load_menu_overlays
    /* 4BD34 800A3AE4 00000000 */   nop
    /* 4BD38 800A3AE8 0C028B5A */  jal        func_800A2D68
    /* 4BD3C 800A3AEC 00000000 */   nop
    /* 4BD40 800A3AF0 0C0554C7 */  jal        func_8015531C_ovl4
    /* 4BD44 800A3AF4 00000000 */   nop
    /* 4BD48 800A3AF8 3C0A800D */  lui        $t2, %hi(D_800D6B78)
    /* 4BD4C 800A3AFC 8D4A6B78 */  lw         $t2, %lo(D_800D6B78)($t2)
    /* 4BD50 800A3B00 3C02800C */  lui        $v0, %hi(D_800BE530)
    /* 4BD54 800A3B04 2442E530 */  addiu      $v0, $v0, %lo(D_800BE530)
    /* 4BD58 800A3B08 15400008 */  bnez       $t2, .L800A3B2C
    /* 4BD5C 800A3B0C 3C0B800D */   lui       $t3, %hi(D_800D6B9C)
    /* 4BD60 800A3B10 8D6B6B9C */  lw         $t3, %lo(D_800D6B9C)($t3)
    /* 4BD64 800A3B14 3C01800C */  lui        $at, %hi(D_800BE504)
    /* 4BD68 800A3B18 240D000F */  addiu      $t5, $zero, 0xF
    /* 4BD6C 800A3B1C AC4B0000 */  sw         $t3, 0x0($v0)
    /* 4BD70 800A3B20 AC2BE504 */  sw         $t3, %lo(D_800BE504)($at)
    /* 4BD74 800A3B24 10000003 */  b          .L800A3B34
    /* 4BD78 800A3B28 AE0D0000 */   sw        $t5, 0x0($s0)
  .L800A3B2C:
    /* 4BD7C 800A3B2C 240E000B */  addiu      $t6, $zero, 0xB
    /* 4BD80 800A3B30 AE0E0000 */  sw         $t6, 0x0($s0)
  .L800A3B34:
    /* 4BD84 800A3B34 3C01800D */  lui        $at, %hi(D_800D6F38)
    /* 4BD88 800A3B38 1000FF37 */  b          .L800A3818
    /* 4BD8C 800A3B3C AC206F38 */   sw        $zero, %lo(D_800D6F38)($at)
  .L800A3B40:
    /* 4BD90 800A3B40 240F000F */  addiu      $t7, $zero, 0xF
    /* 4BD94 800A3B44 1000FF34 */  b          .L800A3818
    /* 4BD98 800A3B48 AE0F0000 */   sw        $t7, 0x0($s0)
  .L800A3B4C:
    /* 4BD9C 800A3B4C 0C028C3A */  jal        func_800A30E8
    /* 4BDA0 800A3B50 00000000 */   nop
    /* 4BDA4 800A3B54 3C01800D */  lui        $at, %hi(D_800D6F3C)
    /* 4BDA8 800A3B58 0C028BA6 */  jal        func_800A2E98
    /* 4BDAC 800A3B5C AC206F3C */   sw        $zero, %lo(D_800D6F3C)($at)
    /* 4BDB0 800A3B60 0C03DAB5 */  jal        func_800F6AD4
    /* 4BDB4 800A3B64 00002025 */   or        $a0, $zero, $zero
    /* 4BDB8 800A3B68 3C18800C */  lui        $t8, %hi(D_800BE4F8)
    /* 4BDBC 800A3B6C 8F18E4F8 */  lw         $t8, %lo(D_800BE4F8)($t8)
    /* 4BDC0 800A3B70 2F010008 */  sltiu      $at, $t8, 0x8
    /* 4BDC4 800A3B74 102000F4 */  beqz       $at, .L800A3F48
    /* 4BDC8 800A3B78 0018C080 */   sll       $t8, $t8, 2
    /* 4BDCC 800A3B7C 3C01800D */  lui        $at, %hi(jtbl_800D5BEC)
    /* 4BDD0 800A3B80 00380821 */  addu       $at, $at, $t8
    /* 4BDD4 800A3B84 8C385BEC */  lw         $t8, %lo(jtbl_800D5BEC)($at)
    /* 4BDD8 800A3B88 03000008 */  jr         $t8
    /* 4BDDC 800A3B8C 00000000 */   nop
  .L800A3B90:
    /* 4BDE0 800A3B90 3C02800D */  lui        $v0, %hi(gKirbyLives)
    /* 4BDE4 800A3B94 24426E4C */  addiu      $v0, $v0, %lo(gKirbyLives)
    /* 4BDE8 800A3B98 8C480000 */  lw         $t0, 0x0($v0)
    /* 4BDEC 800A3B9C 24190011 */  addiu      $t9, $zero, 0x11
    /* 4BDF0 800A3BA0 AE190000 */  sw         $t9, 0x0($s0)
    /* 4BDF4 800A3BA4 2509FFFF */  addiu      $t1, $t0, -0x1
    /* 4BDF8 800A3BA8 19200035 */  blez       $t1, .L800A3C80
    /* 4BDFC 800A3BAC AC490000 */   sw        $t1, 0x0($v0)
    /* 4BE00 800A3BB0 0C03E158 */  jal        func_800F8560
    /* 4BE04 800A3BB4 00000000 */   nop
    /* 4BE08 800A3BB8 10550006 */  beq        $v0, $s5, .L800A3BD4
    /* 4BE0C 800A3BBC 3C0140C0 */   lui       $at, (0x40C00000 >> 16)
    /* 4BE10 800A3BC0 24010009 */  addiu      $at, $zero, 0x9
    /* 4BE14 800A3BC4 1041000D */  beq        $v0, $at, .L800A3BFC
    /* 4BE18 800A3BC8 3C03800C */   lui       $v1, %hi(D_800BE538)
    /* 4BE1C 800A3BCC 1000000C */  b          .L800A3C00
    /* 4BE20 800A3BD0 3C0140C0 */   lui       $at, (0x40C00000 >> 16)
  .L800A3BD4:
    /* 4BE24 800A3BD4 44812000 */  mtc1       $at, $f4
    /* 4BE28 800A3BD8 3C01800D */  lui        $at, %hi(gKirbyHp)
    /* 4BE2C 800A3BDC E4246E50 */  swc1       $f4, %lo(gKirbyHp)($at)
    /* 4BE30 800A3BE0 3C01800D */  lui        $at, %hi(D_800D6E54)
    /* 4BE34 800A3BE4 0C029D36 */  jal        func_800A74D8
    /* 4BE38 800A3BE8 AC206E54 */   sw        $zero, %lo(D_800D6E54)($at)
    /* 4BE3C 800A3BEC AE170000 */  sw         $s7, 0x0($s0)
    /* 4BE40 800A3BF0 3C01800D */  lui        $at, %hi(D_800D6B84)
    /* 4BE44 800A3BF4 10000022 */  b          .L800A3C80
    /* 4BE48 800A3BF8 A0206B84 */   sb        $zero, %lo(D_800D6B84)($at)
  .L800A3BFC:
    /* 4BE4C 800A3BFC 3C0140C0 */  lui        $at, (0x40C00000 >> 16)
  .L800A3C00:
    /* 4BE50 800A3C00 44813000 */  mtc1       $at, $f6
    /* 4BE54 800A3C04 3C01800D */  lui        $at, %hi(gKirbyHp)
    /* 4BE58 800A3C08 3C0B800C */  lui        $t3, %hi(D_800BE518)
    /* 4BE5C 800A3C0C E4266E50 */  swc1       $f6, %lo(gKirbyHp)($at)
    /* 4BE60 800A3C10 8D6BE518 */  lw         $t3, %lo(D_800BE518)($t3)
    /* 4BE64 800A3C14 3C01800D */  lui        $at, %hi(D_800D6E54)
    /* 4BE68 800A3C18 3C0C800C */  lui        $t4, %hi(D_800BE51C)
    /* 4BE6C 800A3C1C 8D8CE51C */  lw         $t4, %lo(D_800BE51C)($t4)
    /* 4BE70 800A3C20 AC206E54 */  sw         $zero, %lo(D_800D6E54)($at)
    /* 4BE74 800A3C24 3C02800C */  lui        $v0, %hi(D_800BE534)
    /* 4BE78 800A3C28 3C01800C */  lui        $at, %hi(D_800BE4FC)
    /* 4BE7C 800A3C2C 2442E534 */  addiu      $v0, $v0, %lo(D_800BE534)
    /* 4BE80 800A3C30 AC2BE4FC */  sw         $t3, %lo(D_800BE4FC)($at)
    /* 4BE84 800A3C34 3C0E800C */  lui        $t6, %hi(D_800BE520)
    /* 4BE88 800A3C38 AC4C0000 */  sw         $t4, 0x0($v0)
    /* 4BE8C 800A3C3C 8DCEE520 */  lw         $t6, %lo(D_800BE520)($t6)
    /* 4BE90 800A3C40 3C01800C */  lui        $at, %hi(D_800BE508)
    /* 4BE94 800A3C44 AC2CE508 */  sw         $t4, %lo(D_800BE508)($at)
    /* 4BE98 800A3C48 2463E538 */  addiu      $v1, $v1, %lo(D_800BE538)
    /* 4BE9C 800A3C4C 3C01800C */  lui        $at, %hi(D_800BE50C)
    /* 4BEA0 800A3C50 AC6E0000 */  sw         $t6, 0x0($v1)
    /* 4BEA4 800A3C54 AC2EE50C */  sw         $t6, %lo(D_800BE50C)($at)
    /* 4BEA8 800A3C58 3C01800C */  lui        $at, %hi(D_800BE524)
    /* 4BEAC 800A3C5C C428E524 */  lwc1       $f8, %lo(D_800BE524)($at)
    /* 4BEB0 800A3C60 3C04800C */  lui        $a0, %hi(D_800BE53C)
    /* 4BEB4 800A3C64 2484E53C */  addiu      $a0, $a0, %lo(D_800BE53C)
    /* 4BEB8 800A3C68 E4880000 */  swc1       $f8, 0x0($a0)
    /* 4BEBC 800A3C6C C48A0000 */  lwc1       $f10, 0x0($a0)
    /* 4BEC0 800A3C70 3C01800C */  lui        $at, %hi(D_800BE510)
    /* 4BEC4 800A3C74 2418000F */  addiu      $t8, $zero, 0xF
    /* 4BEC8 800A3C78 E42AE510 */  swc1       $f10, %lo(D_800BE510)($at)
    /* 4BECC 800A3C7C AE180000 */  sw         $t8, 0x0($s0)
  .L800A3C80:
    /* 4BED0 800A3C80 0C029D36 */  jal        func_800A74D8
    /* 4BED4 800A3C84 00000000 */   nop
    /* 4BED8 800A3C88 100000B0 */  b          .L800A3F4C
    /* 4BEDC 800A3C8C 00000000 */   nop
  .L800A3C90:
    /* 4BEE0 800A3C90 0C008322 */  jal        auFunc80020C88
    /* 4BEE4 800A3C94 00000000 */   nop
    /* 4BEE8 800A3C98 0C028C8C */  jal        func_800A3230
    /* 4BEEC 800A3C9C 00000000 */   nop
    /* 4BEF0 800A3CA0 100000AA */  b          .L800A3F4C
    /* 4BEF4 800A3CA4 00000000 */   nop
  .L800A3CA8:
    /* 4BEF8 800A3CA8 3C03800D */  lui        $v1, %hi(D_800D6B9C)
    /* 4BEFC 800A3CAC 8C636B9C */  lw         $v1, %lo(D_800D6B9C)($v1)
    /* 4BF00 800A3CB0 3C02800D */  lui        $v0, %hi(saveCurrentLevel)
    /* 4BF04 800A3CB4 8C426B94 */  lw         $v0, %lo(saveCurrentLevel)($v0)
    /* 4BF08 800A3CB8 24630001 */  addiu      $v1, $v1, 0x1
    /* 4BF0C 800A3CBC 3C01800D */  lui        $at, %hi(D_800D6B9C)
    /* 4BF10 800A3CC0 1443000D */  bne        $v0, $v1, .L800A3CF8
    /* 4BF14 800A3CC4 244A0001 */   addiu     $t2, $v0, 0x1
    /* 4BF18 800A3CC8 8FC80000 */  lw         $t0, 0x0($fp)
    /* 4BF1C 800A3CCC 8ED90000 */  lw         $t9, 0x0($s6)
    /* 4BF20 800A3CD0 25090001 */  addiu      $t1, $t0, 0x1
    /* 4BF24 800A3CD4 17290008 */  bne        $t9, $t1, .L800A3CF8
    /* 4BF28 800A3CD8 00000000 */   nop
    /* 4BF2C 800A3CDC AC236B9C */  sw         $v1, %lo(D_800D6B9C)($at)
    /* 4BF30 800A3CE0 3C01800D */  lui        $at, %hi(saveCurrentLevel)
    /* 4BF34 800A3CE4 AC2A6B94 */  sw         $t2, %lo(saveCurrentLevel)($at)
    /* 4BF38 800A3CE8 0C02E714 */  jal        func_800B9C50
    /* 4BF3C 800A3CEC 8E240000 */   lw        $a0, 0x0($s1)
    /* 4BF40 800A3CF0 3C01800D */  lui        $at, %hi(D_800D6B80)
    /* 4BF44 800A3CF4 AC326B80 */  sw         $s2, %lo(D_800D6B80)($at)
  .L800A3CF8:
    /* 4BF48 800A3CF8 0C029D36 */  jal        func_800A74D8
    /* 4BF4C 800A3CFC 00000000 */   nop
    /* 4BF50 800A3D00 0C03E158 */  jal        func_800F8560
    /* 4BF54 800A3D04 00000000 */   nop
    /* 4BF58 800A3D08 24010009 */  addiu      $at, $zero, 0x9
    /* 4BF5C 800A3D0C 10410005 */  beq        $v0, $at, .L800A3D24
    /* 4BF60 800A3D10 240B000B */   addiu     $t3, $zero, 0xB
    /* 4BF64 800A3D14 AE170000 */  sw         $s7, 0x0($s0)
    /* 4BF68 800A3D18 3C01800D */  lui        $at, %hi(D_800D6B84)
    /* 4BF6C 800A3D1C 1000008B */  b          .L800A3F4C
    /* 4BF70 800A3D20 A0206B84 */   sb        $zero, %lo(D_800D6B84)($at)
  .L800A3D24:
    /* 4BF74 800A3D24 AE0B0000 */  sw         $t3, 0x0($s0)
    /* 4BF78 800A3D28 3C01800D */  lui        $at, %hi(D_800D6B84)
    /* 4BF7C 800A3D2C 10000087 */  b          .L800A3F4C
    /* 4BF80 800A3D30 A0206B84 */   sb        $zero, %lo(D_800D6B84)($at)
  .L800A3D34:
    /* 4BF84 800A3D34 3C0C800C */  lui        $t4, %hi(D_800BE500)
    /* 4BF88 800A3D38 8D8CE500 */  lw         $t4, %lo(D_800BE500)($t4)
    /* 4BF8C 800A3D3C 2D810006 */  sltiu      $at, $t4, 0x6
    /* 4BF90 800A3D40 10200082 */  beqz       $at, .L800A3F4C
    /* 4BF94 800A3D44 000C6080 */   sll       $t4, $t4, 2
    /* 4BF98 800A3D48 3C01800D */  lui        $at, %hi(jtbl_800D5C0C)
    /* 4BF9C 800A3D4C 002C0821 */  addu       $at, $at, $t4
    /* 4BFA0 800A3D50 8C2C5C0C */  lw         $t4, %lo(jtbl_800D5C0C)($at)
    /* 4BFA4 800A3D54 01800008 */  jr         $t4
    /* 4BFA8 800A3D58 00000000 */   nop
  .L800A3D5C:
    /* 4BFAC 800A3D5C 8FCD0000 */  lw         $t5, 0x0($fp)
    /* 4BFB0 800A3D60 8EC20000 */  lw         $v0, 0x0($s6)
    /* 4BFB4 800A3D64 25AE0001 */  addiu      $t6, $t5, 0x1
    /* 4BFB8 800A3D68 144E000A */  bne        $v0, $t6, .L800A3D94
    /* 4BFBC 800A3D6C 28410007 */   slti      $at, $v0, 0x7
    /* 4BFC0 800A3D70 10200008 */  beqz       $at, .L800A3D94
    /* 4BFC4 800A3D74 244F0001 */   addiu     $t7, $v0, 0x1
    /* 4BFC8 800A3D78 AECF0000 */  sw         $t7, 0x0($s6)
    /* 4BFCC 800A3D7C 3C01800D */  lui        $at, %hi(saveCurrentLevel)
    /* 4BFD0 800A3D80 AC326B94 */  sw         $s2, %lo(saveCurrentLevel)($at)
    /* 4BFD4 800A3D84 3C01800D */  lui        $at, %hi(D_800D6B7C)
    /* 4BFD8 800A3D88 AC326B7C */  sw         $s2, %lo(D_800D6B7C)($at)
    /* 4BFDC 800A3D8C 0C02E714 */  jal        func_800B9C50
    /* 4BFE0 800A3D90 8E240000 */   lw        $a0, 0x0($s1)
  .L800A3D94:
    /* 4BFE4 800A3D94 0C029D36 */  jal        func_800A74D8
    /* 4BFE8 800A3D98 00000000 */   nop
    /* 4BFEC 800A3D9C 0C028CDB */  jal        func_800A336C
    /* 4BFF0 800A3DA0 00000000 */   nop
    /* 4BFF4 800A3DA4 3C18800D */  lui        $t8, %hi(D_800D6B7C)
    /* 4BFF8 800A3DA8 8F186B7C */  lw         $t8, %lo(D_800D6B7C)($t8)
    /* 4BFFC 800A3DAC 2408000B */  addiu      $t0, $zero, 0xB
    /* 4C000 800A3DB0 13000003 */  beqz       $t8, .L800A3DC0
    /* 4C004 800A3DB4 00000000 */   nop
    /* 4C008 800A3DB8 10000064 */  b          .L800A3F4C
    /* 4C00C 800A3DBC AE080000 */   sw        $t0, 0x0($s0)
  .L800A3DC0:
    /* 4C010 800A3DC0 10000062 */  b          .L800A3F4C
    /* 4C014 800A3DC4 AE170000 */   sw        $s7, 0x0($s0)
  .L800A3DC8:
    /* 4C018 800A3DC8 0C029D36 */  jal        func_800A74D8
    /* 4C01C 800A3DCC 00000000 */   nop
    /* 4C020 800A3DD0 0C029AD9 */  jal        utilTamperCheck
    /* 4C024 800A3DD4 00000000 */   nop
    /* 4C028 800A3DD8 14400004 */  bnez       $v0, .L800A3DEC
    /* 4C02C 800A3DDC 24050005 */   addiu     $a1, $zero, 0x5
    /* 4C030 800A3DE0 2419000B */  addiu      $t9, $zero, 0xB
    /* 4C034 800A3DE4 10000059 */  b          .L800A3F4C
    /* 4C038 800A3DE8 AE190000 */   sw        $t9, 0x0($s0)
  .L800A3DEC:
    /* 4C03C 800A3DEC 8FC90000 */  lw         $t1, 0x0($fp)
    /* 4C040 800A3DF0 8EC20000 */  lw         $v0, 0x0($s6)
    /* 4C044 800A3DF4 252A0001 */  addiu      $t2, $t1, 0x1
    /* 4C048 800A3DF8 144A0008 */  bne        $v0, $t2, .L800A3E1C
    /* 4C04C 800A3DFC 28410007 */   slti      $at, $v0, 0x7
    /* 4C050 800A3E00 10200006 */  beqz       $at, .L800A3E1C
    /* 4C054 800A3E04 244B0001 */   addiu     $t3, $v0, 0x1
    /* 4C058 800A3E08 AECB0000 */  sw         $t3, 0x0($s6)
    /* 4C05C 800A3E0C 3C01800D */  lui        $at, %hi(saveCurrentLevel)
    /* 4C060 800A3E10 AC326B94 */  sw         $s2, %lo(saveCurrentLevel)($at)
    /* 4C064 800A3E14 0C02E758 */  jal        func_800B9D60
    /* 4C068 800A3E18 8E240000 */   lw        $a0, 0x0($s1)
  .L800A3E1C:
    /* 4C06C 800A3E1C 0C02E714 */  jal        func_800B9C50
    /* 4C070 800A3E20 8E240000 */   lw        $a0, 0x0($s1)
    /* 4C074 800A3E24 240C0012 */  addiu      $t4, $zero, 0x12
    /* 4C078 800A3E28 AE0C0000 */  sw         $t4, 0x0($s0)
    /* 4C07C 800A3E2C 3C0D800D */  lui        $t5, %hi(savePercentComplete)
    /* 4C080 800A3E30 8DAD6BA8 */  lw         $t5, %lo(savePercentComplete)($t5)
    /* 4C084 800A3E34 24010064 */  addiu      $at, $zero, 0x64
    /* 4C088 800A3E38 2404000D */  addiu      $a0, $zero, 0xD
    /* 4C08C 800A3E3C 15A10043 */  bne        $t5, $at, .L800A3F4C
    /* 4C090 800A3E40 00000000 */   nop
    /* 4C094 800A3E44 0C02E7D4 */  jal        saveCheckCutsceneWatched
    /* 4C098 800A3E48 AE170000 */   sw        $s7, 0x0($s0)
    /* 4C09C 800A3E4C 1440003F */  bnez       $v0, .L800A3F4C
    /* 4C0A0 800A3E50 3C03800C */   lui       $v1, %hi(D_800BE508)
    /* 4C0A4 800A3E54 240E0006 */  addiu      $t6, $zero, 0x6
    /* 4C0A8 800A3E58 3C01800C */  lui        $at, %hi(D_800BE500)
    /* 4C0AC 800A3E5C AC2EE500 */  sw         $t6, %lo(D_800BE500)($at)
    /* 4C0B0 800A3E60 3C02800C */  lui        $v0, %hi(D_800BE504)
    /* 4C0B4 800A3E64 2442E504 */  addiu      $v0, $v0, %lo(D_800BE504)
    /* 4C0B8 800A3E68 2463E508 */  addiu      $v1, $v1, %lo(D_800BE508)
    /* 4C0BC 800A3E6C 240F0006 */  addiu      $t7, $zero, 0x6
    /* 4C0C0 800A3E70 AFCF0000 */  sw         $t7, 0x0($fp)
    /* 4C0C4 800A3E74 AC600000 */  sw         $zero, 0x0($v1)
    /* 4C0C8 800A3E78 AC400000 */  sw         $zero, 0x0($v0)
    /* 4C0CC 800A3E7C 3C01800D */  lui        $at, %hi(D_800D6B9C)
    /* 4C0D0 800A3E80 AC206B9C */  sw         $zero, %lo(D_800D6B9C)($at)
    /* 4C0D4 800A3E84 0C029AC8 */  jal        utilLoadOverlay
    /* 4C0D8 800A3E88 24040004 */   addiu     $a0, $zero, 0x4
    /* 4C0DC 800A3E8C 2404000D */  addiu      $a0, $zero, 0xD
    /* 4C0E0 800A3E90 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C0E4 800A3E94 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C0E8 800A3E98 0C02E714 */  jal        func_800B9C50
    /* 4C0EC 800A3E9C 8E240000 */   lw        $a0, 0x0($s1)
    /* 4C0F0 800A3EA0 2404000D */  addiu      $a0, $zero, 0xD
    /* 4C0F4 800A3EA4 0C055358 */  jal        func_80154D60_ovl6
    /* 4C0F8 800A3EA8 24050002 */   addiu     $a1, $zero, 0x2
    /* 4C0FC 800A3EAC 0C028B5A */  jal        func_800A2D68
    /* 4C100 800A3EB0 00000000 */   nop
    /* 4C104 800A3EB4 0C028BA6 */  jal        func_800A2E98
    /* 4C108 800A3EB8 00000000 */   nop
    /* 4C10C 800A3EBC 2419000F */  addiu      $t9, $zero, 0xF
    /* 4C110 800A3EC0 10000022 */  b          .L800A3F4C
    /* 4C114 800A3EC4 AE190000 */   sw        $t9, 0x0($s0)
  .L800A3EC8:
    /* 4C118 800A3EC8 8FC90000 */  lw         $t1, 0x0($fp)
    /* 4C11C 800A3ECC 8EC20000 */  lw         $v0, 0x0($s6)
    /* 4C120 800A3ED0 240B0008 */  addiu      $t3, $zero, 0x8
    /* 4C124 800A3ED4 252A0001 */  addiu      $t2, $t1, 0x1
    /* 4C128 800A3ED8 144A0008 */  bne        $v0, $t2, .L800A3EFC
    /* 4C12C 800A3EDC 28410008 */   slti      $at, $v0, 0x8
    /* 4C130 800A3EE0 10200006 */  beqz       $at, .L800A3EFC
    /* 4C134 800A3EE4 24050006 */   addiu     $a1, $zero, 0x6
    /* 4C138 800A3EE8 AECB0000 */  sw         $t3, 0x0($s6)
    /* 4C13C 800A3EEC 3C01800D */  lui        $at, %hi(saveCurrentLevel)
    /* 4C140 800A3EF0 AC326B94 */  sw         $s2, %lo(saveCurrentLevel)($at)
    /* 4C144 800A3EF4 0C02E758 */  jal        func_800B9D60
    /* 4C148 800A3EF8 8E240000 */   lw        $a0, 0x0($s1)
  .L800A3EFC:
    /* 4C14C 800A3EFC 0C029D36 */  jal        func_800A74D8
    /* 4C150 800A3F00 00000000 */   nop
    /* 4C154 800A3F04 240C0013 */  addiu      $t4, $zero, 0x13
    /* 4C158 800A3F08 10000010 */  b          .L800A3F4C
    /* 4C15C 800A3F0C AE0C0000 */   sw        $t4, 0x0($s0)
  .L800A3F10:
    /* 4C160 800A3F10 0C029D36 */  jal        func_800A74D8
    /* 4C164 800A3F14 00000000 */   nop
    /* 4C168 800A3F18 3C0D800C */  lui        $t5, %hi(D_800BE500)
    /* 4C16C 800A3F1C 8DADE500 */  lw         $t5, %lo(D_800BE500)($t5)
    /* 4C170 800A3F20 24010006 */  addiu      $at, $zero, 0x6
    /* 4C174 800A3F24 240E000B */  addiu      $t6, $zero, 0xB
    /* 4C178 800A3F28 51A10004 */  beql       $t5, $at, .L800A3F3C
    /* 4C17C 800A3F2C AE0E0000 */   sw        $t6, 0x0($s0)
    /* 4C180 800A3F30 10000002 */  b          .L800A3F3C
    /* 4C184 800A3F34 AE170000 */   sw        $s7, 0x0($s0)
    /* 4C188 800A3F38 AE0E0000 */  sw         $t6, 0x0($s0)
  .L800A3F3C:
    /* 4C18C 800A3F3C 3C01800D */  lui        $at, %hi(D_800D6B84)
    /* 4C190 800A3F40 10000002 */  b          .L800A3F4C
    /* 4C194 800A3F44 A0206B84 */   sb        $zero, %lo(D_800D6B84)($at)
  .L800A3F48:
    /* 4C198 800A3F48 AE120000 */  sw         $s2, 0x0($s0)
  .L800A3F4C:
    /* 4C19C 800A3F4C 0C02E714 */  jal        func_800B9C50
    /* 4C1A0 800A3F50 8E240000 */   lw        $a0, 0x0($s1)
    /* 4C1A4 800A3F54 1000FE30 */  b          .L800A3818
    /* 4C1A8 800A3F58 00000000 */   nop
  .L800A3F5C:
    /* 4C1AC 800A3F5C 0C028C4A */  jal        load_menu_overlays
    /* 4C1B0 800A3F60 00000000 */   nop
    /* 4C1B4 800A3F64 0C0567BF */  jal        func_80159EFC_ovl4
    /* 4C1B8 800A3F68 00000000 */   nop
    /* 4C1BC 800A3F6C 1000FE2A */  b          .L800A3818
    /* 4C1C0 800A3F70 AE120000 */   sw        $s2, 0x0($s0)
  .L800A3F74:
    /* 4C1C4 800A3F74 0C029AC8 */  jal        utilLoadOverlay
    /* 4C1C8 800A3F78 24040004 */   addiu     $a0, $zero, 0x4
    /* 4C1CC 800A3F7C 3C04800D */  lui        $a0, %hi(D_800D71E8)
    /* 4C1D0 800A3F80 8C8471E8 */  lw         $a0, %lo(D_800D71E8)($a0)
    /* 4C1D4 800A3F84 0C055358 */  jal        func_80154D60_ovl6
    /* 4C1D8 800A3F88 24050015 */   addiu     $a1, $zero, 0x15
    /* 4C1DC 800A3F8C 8E0F0000 */  lw         $t7, 0x0($s0)
    /* 4C1E0 800A3F90 24180017 */  addiu      $t8, $zero, 0x17
    /* 4C1E4 800A3F94 AE180000 */  sw         $t8, 0x0($s0)
    /* 4C1E8 800A3F98 1000FE1F */  b          .L800A3818
    /* 4C1EC 800A3F9C AE6F0000 */   sw        $t7, 0x0($s3)
  .L800A3FA0:
    /* 4C1F0 800A3FA0 0C028DB0 */  jal        func_800A36C0
    /* 4C1F4 800A3FA4 00000000 */   nop
    /* 4C1F8 800A3FA8 1000FE1B */  b          .L800A3818
    /* 4C1FC 800A3FAC 00000000 */   nop
  .L800A3FB0:
    /* 4C200 800A3FB0 0C029AC8 */  jal        utilLoadOverlay
    /* 4C204 800A3FB4 24040004 */   addiu     $a0, $zero, 0x4
    /* 4C208 800A3FB8 24040011 */  addiu      $a0, $zero, 0x11
    /* 4C20C 800A3FBC 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C210 800A3FC0 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C214 800A3FC4 24040013 */  addiu      $a0, $zero, 0x13
    /* 4C218 800A3FC8 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C21C 800A3FCC 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C220 800A3FD0 0C02E714 */  jal        func_800B9C50
    /* 4C224 800A3FD4 8E240000 */   lw        $a0, 0x0($s1)
    /* 4C228 800A3FD8 2404000E */  addiu      $a0, $zero, 0xE
    /* 4C22C 800A3FDC 0C055358 */  jal        func_80154D60_ovl6
    /* 4C230 800A3FE0 24050002 */   addiu     $a1, $zero, 0x2
    /* 4C234 800A3FE4 1000FE0C */  b          .L800A3818
    /* 4C238 800A3FE8 AE120000 */   sw        $s2, 0x0($s0)
  .L800A3FEC:
    /* 4C23C 800A3FEC 0C029AC8 */  jal        utilLoadOverlay
    /* 4C240 800A3FF0 24040004 */   addiu     $a0, $zero, 0x4
    /* 4C244 800A3FF4 2404000D */  addiu      $a0, $zero, 0xD
    /* 4C248 800A3FF8 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C24C 800A3FFC 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C250 800A4000 24040011 */  addiu      $a0, $zero, 0x11
    /* 4C254 800A4004 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C258 800A4008 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C25C 800A400C 24040012 */  addiu      $a0, $zero, 0x12
    /* 4C260 800A4010 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C264 800A4014 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C268 800A4018 24040013 */  addiu      $a0, $zero, 0x13
    /* 4C26C 800A401C 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C270 800A4020 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C274 800A4024 24040010 */  addiu      $a0, $zero, 0x10
    /* 4C278 800A4028 0C02E7E4 */  jal        saveSetCutsceneWatched
    /* 4C27C 800A402C 8E250000 */   lw        $a1, 0x0($s1)
    /* 4C280 800A4030 0C02E714 */  jal        func_800B9C50
    /* 4C284 800A4034 8E240000 */   lw        $a0, 0x0($s1)
    /* 4C288 800A4038 2404000F */  addiu      $a0, $zero, 0xF
    /* 4C28C 800A403C 0C055358 */  jal        func_80154D60_ovl6
    /* 4C290 800A4040 2405000A */   addiu     $a1, $zero, 0xA
    /* 4C294 800A4044 1000FDF4 */  b          .L800A3818
    /* 4C298 800A4048 AE120000 */   sw        $s2, 0x0($s0)
  .L800A404C:
    /* 4C29C 800A404C 0C028D32 */  jal        func_800A34C8
    /* 4C2A0 800A4050 00000000 */   nop
    /* 4C2A4 800A4054 1000FDF0 */  b          .L800A3818
    /* 4C2A8 800A4058 00000000 */   nop
  .L800A405C:
    /* 4C2AC 800A405C 0C028C4A */  jal        load_menu_overlays
    /* 4C2B0 800A4060 00000000 */   nop
    /* 4C2B4 800A4064 0C05FD65 */  jal        func_8017F594_ovl5
    /* 4C2B8 800A4068 00000000 */   nop
    /* 4C2BC 800A406C 1000FDEA */  b          .L800A3818
    /* 4C2C0 800A4070 00000000 */   nop
  .L800A4074:
    /* 4C2C4 800A4074 0C028C4A */  jal        load_menu_overlays
    /* 4C2C8 800A4078 00000000 */   nop
    /* 4C2CC 800A407C 0C05F30F */  jal        func_8017CC3C_ovl5
    /* 4C2D0 800A4080 00000000 */   nop
    /* 4C2D4 800A4084 1000FDE4 */  b          .L800A3818
    /* 4C2D8 800A4088 00000000 */   nop
  .L800A408C:
    /* 4C2DC 800A408C 0C028C4A */  jal        load_menu_overlays
    /* 4C2E0 800A4090 00000000 */   nop
    /* 4C2E4 800A4094 0C0608AB */  jal        func_801822AC_ovl5
    /* 4C2E8 800A4098 00000000 */   nop
    /* 4C2EC 800A409C 8E080000 */  lw         $t0, 0x0($s0)
    /* 4C2F0 800A40A0 AE140000 */  sw         $s4, 0x0($s0)
    /* 4C2F4 800A40A4 1000FDDC */  b          .L800A3818
    /* 4C2F8 800A40A8 AE680000 */   sw        $t0, 0x0($s3)
  .L800A40AC:
    /* 4C2FC 800A40AC 0C028C4A */  jal        load_menu_overlays
    /* 4C300 800A40B0 00000000 */   nop
    /* 4C304 800A40B4 0C0600AA */  jal        func_801802A8_ovl5
    /* 4C308 800A40B8 00000000 */   nop
    /* 4C30C 800A40BC 1000FDD6 */  b          .L800A3818
    /* 4C310 800A40C0 00000000 */   nop
  .L800A40C4:
    /* 4C314 800A40C4 0C028C4A */  jal        load_menu_overlays
    /* 4C318 800A40C8 00000000 */   nop
    /* 4C31C 800A40CC 0C05FB29 */  jal        func_8017ECA4_ovl5
    /* 4C320 800A40D0 00000000 */   nop
    /* 4C324 800A40D4 8E190000 */  lw         $t9, 0x0($s0)
    /* 4C328 800A40D8 AE140000 */  sw         $s4, 0x0($s0)
    /* 4C32C 800A40DC 1000FDCE */  b          .L800A3818
    /* 4C330 800A40E0 AE790000 */   sw        $t9, 0x0($s3)
  .L800A40E4:
    /* 4C334 800A40E4 0C028C4A */  jal        load_menu_overlays
    /* 4C338 800A40E8 00000000 */   nop
    /* 4C33C 800A40EC 0C060BFA */  jal        func_80182FE8_ovl5
    /* 4C340 800A40F0 00000000 */   nop
    /* 4C344 800A40F4 1000FDC8 */  b          .L800A3818
    /* 4C348 800A40F8 00000000 */   nop
  .L800A40FC:
    /* 4C34C 800A40FC 0C028C4A */  jal        load_menu_overlays
    /* 4C350 800A4100 00000000 */   nop
    /* 4C354 800A4104 0C0617BB */  jal        func_80185EEC_ovl5
    /* 4C358 800A4108 00000000 */   nop
    /* 4C35C 800A410C 8E090000 */  lw         $t1, 0x0($s0)
    /* 4C360 800A4110 AE140000 */  sw         $s4, 0x0($s0)
    /* 4C364 800A4114 1000FDC0 */  b          .L800A3818
    /* 4C368 800A4118 AE690000 */   sw        $t1, 0x0($s3)
  .L800A411C:
    /* 4C36C 800A411C 0C028C4A */  jal        load_menu_overlays
    /* 4C370 800A4120 00000000 */   nop
    /* 4C374 800A4124 0C05DE8C */  jal        func_80177A30_ovl5
    /* 4C378 800A4128 00000000 */   nop
    /* 4C37C 800A412C 1000FDBA */  b          .L800A3818
    /* 4C380 800A4130 00000000 */   nop
  .L800A4134:
    /* 4C384 800A4134 0C028C4A */  jal        load_menu_overlays
    /* 4C388 800A4138 00000000 */   nop
    /* 4C38C 800A413C 0C05BEAC */  jal        func_8016FAB0_ovl5
    /* 4C390 800A4140 00000000 */   nop
    /* 4C394 800A4144 1000FDB4 */  b          .L800A3818
    /* 4C398 800A4148 00000000 */   nop
  .L800A414C:
    /* 4C39C 800A414C 0C028C4A */  jal        load_menu_overlays
    /* 4C3A0 800A4150 00000000 */   nop
    /* 4C3A4 800A4154 0C0594DC */  jal        func_80165370_ovl5
    /* 4C3A8 800A4158 00000000 */   nop
    /* 4C3AC 800A415C 1000FDAE */  b          .L800A3818
    /* 4C3B0 800A4160 00000000 */   nop
  .L800A4164:
    /* 4C3B4 800A4164 0C028C4A */  jal        load_menu_overlays
    /* 4C3B8 800A4168 00000000 */   nop
    /* 4C3BC 800A416C 0C05E752 */  jal        func_80179D48_ovl5
    /* 4C3C0 800A4170 00000000 */   nop
    /* 4C3C4 800A4174 1000FDA8 */  b          .L800A3818
    /* 4C3C8 800A4178 00000000 */   nop
    /* 4C3CC 800A417C 00000000 */  nop
    /* 4C3D0 800A4180 8FBF003C */  lw         $ra, 0x3C($sp)
    /* 4C3D4 800A4184 8FB00018 */  lw         $s0, 0x18($sp)
    /* 4C3D8 800A4188 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 4C3DC 800A418C 8FB20020 */  lw         $s2, 0x20($sp)
    /* 4C3E0 800A4190 8FB30024 */  lw         $s3, 0x24($sp)
    /* 4C3E4 800A4194 8FB40028 */  lw         $s4, 0x28($sp)
    /* 4C3E8 800A4198 8FB5002C */  lw         $s5, 0x2C($sp)
    /* 4C3EC 800A419C 8FB60030 */  lw         $s6, 0x30($sp)
    /* 4C3F0 800A41A0 8FB70034 */  lw         $s7, 0x34($sp)
    /* 4C3F4 800A41A4 8FBE0038 */  lw         $fp, 0x38($sp)
    /* 4C3F8 800A41A8 03E00008 */  jr         $ra
    /* 4C3FC 800A41AC 27BD0040 */   addiu     $sp, $sp, 0x40
endlabel game_tick
.size game_tick, . - game_tick
