.section .late_rodata
nonmatching jtbl_800D5C70

dlabel jtbl_800D5C70
    /* 7DEC0 800D5C70 800A6CC8 */ .word .L800A6CC8
    /* 7DEC4 800D5C74 800A6DA4 */ .word .L800A6DA4
    /* 7DEC8 800D5C78 800A6D2C */ .word .L800A6D2C
    /* 7DECC 800D5C7C 800A6DA4 */ .word .L800A6DA4
    /* 7DED0 800D5C80 800A6CC8 */ .word .L800A6CC8
    /* 7DED4 800D5C84 800A6DA4 */ .word .L800A6DA4
    /* 7DED8 800D5C88 800A6D2C */ .word .L800A6D2C
    /* 7DEDC 800D5C8C 800A6DA4 */ .word .L800A6DA4
    /* 7DEE0 800D5C90 800A6CC8 */ .word .L800A6CC8
    /* 7DEE4 800D5C94 800A6DA4 */ .word .L800A6DA4
    /* 7DEE8 800D5C98 800A6D2C */ .word .L800A6D2C
    /* 7DEEC 800D5C9C 800A6DA4 */ .word .L800A6DA4
    /* 7DEF0 800D5CA0 800A6CC8 */ .word .L800A6CC8
    /* 7DEF4 800D5CA4 800A6DA4 */ .word .L800A6DA4
    /* 7DEF8 800D5CA8 800A6D2C */ .word .L800A6D2C
enddlabel jtbl_800D5C70
.size jtbl_800D5C70, . - jtbl_800D5C70


.section .text
/* Generated by spimdisasm 1.42.4 */

nonmatching func_800A6BC0, 0x2A4

glabel func_800A6BC0
    /* 4EE10 800A6BC0 27BDFF58 */  addiu      $sp, $sp, -0xA8
    /* 4EE14 800A6BC4 3C01800D */  lui        $at, %hi(D_800D7B68)
    /* 4EE18 800A6BC8 AC207B68 */  sw         $zero, %lo(D_800D7B68)($at)
    /* 4EE1C 800A6BCC F7BE0068 */  sdc1       $f30, 0x68($sp)
    /* 4EE20 800A6BD0 AFA400A8 */  sw         $a0, 0xA8($sp)
    /* 4EE24 800A6BD4 3C01439B */  lui        $at, (0x439B0000 >> 16)
    /* 4EE28 800A6BD8 308400FF */  andi       $a0, $a0, 0xFF
    /* 4EE2C 800A6BDC 4481F000 */  mtc1       $at, $f30
    /* 4EE30 800A6BE0 AFBE0090 */  sw         $fp, 0x90($sp)
    /* 4EE34 800A6BE4 AFB60088 */  sw         $s6, 0x88($sp)
    /* 4EE38 800A6BE8 F7BC0060 */  sdc1       $f28, 0x60($sp)
    /* 4EE3C 800A6BEC 00047080 */  sll        $t6, $a0, 2
    /* 4EE40 800A6BF0 3C02800C */  lui        $v0, %hi(D_800BF918)
    /* 4EE44 800A6BF4 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* 4EE48 800A6BF8 AFB7008C */  sw         $s7, 0x8C($sp)
    /* 4EE4C 800A6BFC AFB50084 */  sw         $s5, 0x84($sp)
    /* 4EE50 800A6C00 AFB3007C */  sw         $s3, 0x7C($sp)
    /* 4EE54 800A6C04 AFB20078 */  sw         $s2, 0x78($sp)
    /* 4EE58 800A6C08 004E1021 */  addu       $v0, $v0, $t6
    /* 4EE5C 800A6C0C 3C168001 */  lui        $s6, %hi(ohUpdateStub)
    /* 4EE60 800A6C10 3C1E800D */  lui        $fp, %hi(D_800D79D8)
    /* 4EE64 800A6C14 4481E000 */  mtc1       $at, $f28
    /* 4EE68 800A6C18 AFBF0094 */  sw         $ra, 0x94($sp)
    /* 4EE6C 800A6C1C AFB40080 */  sw         $s4, 0x80($sp)
    /* 4EE70 800A6C20 AFB10074 */  sw         $s1, 0x74($sp)
    /* 4EE74 800A6C24 AFB00070 */  sw         $s0, 0x70($sp)
    /* 4EE78 800A6C28 F7BA0058 */  sdc1       $f26, 0x58($sp)
    /* 4EE7C 800A6C2C F7B80050 */  sdc1       $f24, 0x50($sp)
    /* 4EE80 800A6C30 F7B60048 */  sdc1       $f22, 0x48($sp)
    /* 4EE84 800A6C34 F7B40040 */  sdc1       $f20, 0x40($sp)
    /* 4EE88 800A6C38 8C52F918 */  lw         $s2, %lo(D_800BF918)($v0)
    /* 4EE8C 800A6C3C 27DE79D8 */  addiu      $fp, $fp, %lo(D_800D79D8)
    /* 4EE90 800A6C40 26D6B6B4 */  addiu      $s6, $s6, %lo(ohUpdateStub)
    /* 4EE94 800A6C44 8FB3009C */  lw         $s3, 0x9C($sp)
    /* 4EE98 800A6C48 8FB500A0 */  lw         $s5, 0xA0($sp)
    /* 4EE9C 800A6C4C 3C178000 */  lui        $s7, (0x80000000 >> 16)
  .L800A6C50:
    /* 4EEA0 800A6C50 8E510000 */  lw         $s1, 0x0($s2)
    /* 4EEA4 800A6C54 2401FFFF */  addiu      $at, $zero, -0x1
    /* 4EEA8 800A6C58 1221006F */  beq        $s1, $at, .L800A6E18
    /* 4EEAC 800A6C5C 262FFFF6 */   addiu     $t7, $s1, -0xA
    /* 4EEB0 800A6C60 C654000C */  lwc1       $f20, 0xC($s2)
    /* 4EEB4 800A6C64 C6580014 */  lwc1       $f24, 0x14($s2)
    /* 4EEB8 800A6C68 8E420004 */  lw         $v0, 0x4($s2)
    /* 4EEBC 800A6C6C C6560010 */  lwc1       $f22, 0x10($s2)
    /* 4EEC0 800A6C70 4614C03C */  c.lt.s     $f24, $f20
    /* 4EEC4 800A6C74 C65A0018 */  lwc1       $f26, 0x18($s2)
    /* 4EEC8 800A6C78 3C014366 */  lui        $at, (0x43660000 >> 16)
    /* 4EECC 800A6C7C 45020004 */  bc1fl      .L800A6C90
    /* 4EED0 800A6C80 4616D03C */   c.lt.s    $f26, $f22
    /* 4EED4 800A6C84 4600E506 */  mov.s      $f20, $f28
    /* 4EED8 800A6C88 4600F606 */  mov.s      $f24, $f30
    /* 4EEDC 800A6C8C 4616D03C */  c.lt.s     $f26, $f22
  .L800A6C90:
    /* 4EEE0 800A6C90 00000000 */  nop
    /* 4EEE4 800A6C94 45020004 */  bc1fl      .L800A6CA8
    /* 4EEE8 800A6C98 2DE1000F */   sltiu     $at, $t7, 0xF
    /* 4EEEC 800A6C9C 4481D000 */  mtc1       $at, $f26
    /* 4EEF0 800A6CA0 4600E586 */  mov.s      $f22, $f28
    /* 4EEF4 800A6CA4 2DE1000F */  sltiu      $at, $t7, 0xF
  .L800A6CA8:
    /* 4EEF8 800A6CA8 1020003E */  beqz       $at, .L800A6DA4
    /* 4EEFC 800A6CAC 0220A025 */   or        $s4, $s1, $zero
    /* 4EF00 800A6CB0 000F7880 */  sll        $t7, $t7, 2
    /* 4EF04 800A6CB4 3C01800D */  lui        $at, %hi(jtbl_800D5C70)
    /* 4EF08 800A6CB8 002F0821 */  addu       $at, $at, $t7
    /* 4EF0C 800A6CBC 8C2F5C70 */  lw         $t7, %lo(jtbl_800D5C70)($at)
    /* 4EF10 800A6CC0 01E00008 */  jr         $t7
    /* 4EF14 800A6CC4 00000000 */   nop
  .L800A6CC8:
    /* 4EF18 800A6CC8 3C18800B */  lui        $t8, %hi(func_800ADD14)
    /* 4EF1C 800A6CCC 2718DD14 */  addiu      $t8, $t8, %lo(func_800ADD14)
    /* 4EF20 800A6CD0 2419FFFF */  addiu      $t9, $zero, -0x1
    /* 4EF24 800A6CD4 24080001 */  addiu      $t0, $zero, 0x1
    /* 4EF28 800A6CD8 24090001 */  addiu      $t1, $zero, 0x1
    /* 4EF2C 800A6CDC AFA9002C */  sw         $t1, 0x2C($sp)
    /* 4EF30 800A6CE0 AFA80020 */  sw         $t0, 0x20($sp)
    /* 4EF34 800A6CE4 AFB9001C */  sw         $t9, 0x1C($sp)
    /* 4EF38 800A6CE8 AFB80010 */  sw         $t8, 0x10($sp)
    /* 4EF3C 800A6CEC 02202025 */  or         $a0, $s1, $zero
    /* 4EF40 800A6CF0 02C02825 */  or         $a1, $s6, $zero
    /* 4EF44 800A6CF4 24060019 */  addiu      $a2, $zero, 0x19
    /* 4EF48 800A6CF8 02E03825 */  or         $a3, $s7, $zero
    /* 4EF4C 800A6CFC AFB10014 */  sw         $s1, 0x14($sp)
    /* 4EF50 800A6D00 AFA20018 */  sw         $v0, 0x18($sp)
    /* 4EF54 800A6D04 AFA00024 */  sw         $zero, 0x24($sp)
    /* 4EF58 800A6D08 AFA00028 */  sw         $zero, 0x28($sp)
    /* 4EF5C 800A6D0C 0C002F4F */  jal        ohCreateCamera
    /* 4EF60 800A6D10 AFA00030 */   sw        $zero, 0x30($sp)
    /* 4EF64 800A6D14 14400003 */  bnez       $v0, .L800A6D24
    /* 4EF68 800A6D18 0040A825 */   or        $s5, $v0, $zero
    /* 4EF6C 800A6D1C 1000003F */  b          .L800A6E1C
    /* 4EF70 800A6D20 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800A6D24:
    /* 4EF74 800A6D24 1000001F */  b          .L800A6DA4
    /* 4EF78 800A6D28 8C53003C */   lw        $s3, 0x3C($v0)
  .L800A6D2C:
    /* 4EF7C 800A6D2C 3C0A8002 */  lui        $t2, %hi(func_80018170)
    /* 4EF80 800A6D30 254A8170 */  addiu      $t2, $t2, %lo(func_80018170)
    /* 4EF84 800A6D34 240BFFFF */  addiu      $t3, $zero, -0x1
    /* 4EF88 800A6D38 240C0001 */  addiu      $t4, $zero, 0x1
    /* 4EF8C 800A6D3C 240D0001 */  addiu      $t5, $zero, 0x1
    /* 4EF90 800A6D40 AFAD002C */  sw         $t5, 0x2C($sp)
    /* 4EF94 800A6D44 AFAC0020 */  sw         $t4, 0x20($sp)
    /* 4EF98 800A6D48 AFAB001C */  sw         $t3, 0x1C($sp)
    /* 4EF9C 800A6D4C AFAA0010 */  sw         $t2, 0x10($sp)
    /* 4EFA0 800A6D50 02202025 */  or         $a0, $s1, $zero
    /* 4EFA4 800A6D54 02C02825 */  or         $a1, $s6, $zero
    /* 4EFA8 800A6D58 24060019 */  addiu      $a2, $zero, 0x19
    /* 4EFAC 800A6D5C 02E03825 */  or         $a3, $s7, $zero
    /* 4EFB0 800A6D60 AFB10014 */  sw         $s1, 0x14($sp)
    /* 4EFB4 800A6D64 AFA20018 */  sw         $v0, 0x18($sp)
    /* 4EFB8 800A6D68 AFA00024 */  sw         $zero, 0x24($sp)
    /* 4EFBC 800A6D6C AFA00028 */  sw         $zero, 0x28($sp)
    /* 4EFC0 800A6D70 0C002F4F */  jal        ohCreateCamera
    /* 4EFC4 800A6D74 AFA00030 */   sw        $zero, 0x30($sp)
    /* 4EFC8 800A6D78 14400003 */  bnez       $v0, .L800A6D88
    /* 4EFCC 800A6D7C 0040A825 */   or        $s5, $v0, $zero
    /* 4EFD0 800A6D80 10000026 */  b          .L800A6E1C
    /* 4EFD4 800A6D84 2402FFFF */   addiu     $v0, $zero, -0x1
  .L800A6D88:
    /* 4EFD8 800A6D88 4614C101 */  sub.s      $f4, $f24, $f20
    /* 4EFDC 800A6D8C 8C53003C */  lw         $s3, 0x3C($v0)
    /* 4EFE0 800A6D90 240E0004 */  addiu      $t6, $zero, 0x4
    /* 4EFE4 800A6D94 4616D181 */  sub.s      $f6, $f26, $f22
    /* 4EFE8 800A6D98 AE6E0080 */  sw         $t6, 0x80($s3)
    /* 4EFEC 800A6D9C 46062203 */  div.s      $f8, $f4, $f6
    /* 4EFF0 800A6DA0 E6680024 */  swc1       $f8, 0x24($s3)
  .L800A6DA4:
    /* 4EFF4 800A6DA4 2630FFF6 */  addiu      $s0, $s1, -0xA
    /* 4EFF8 800A6DA8 00108042 */  srl        $s0, $s0, 1
    /* 4EFFC 800A6DAC 00108080 */  sll        $s0, $s0, 2
    /* 4F000 800A6DB0 3C01800D */  lui        $at, %hi(D_800D79B0)
    /* 4F004 800A6DB4 00300821 */  addu       $at, $at, $s0
    /* 4F008 800A6DB8 AC3579B0 */  sw         $s5, %lo(D_800D79B0)($at)
    /* 4F00C 800A6DBC 03D07821 */  addu       $t7, $fp, $s0
    /* 4F010 800A6DC0 ADF30000 */  sw         $s3, 0x0($t7)
    /* 4F014 800A6DC4 4405A000 */  mfc1       $a1, $f20
    /* 4F018 800A6DC8 4406B000 */  mfc1       $a2, $f22
    /* 4F01C 800A6DCC 4407C000 */  mfc1       $a3, $f24
    /* 4F020 800A6DD0 E7BA0010 */  swc1       $f26, 0x10($sp)
    /* 4F024 800A6DD4 0C001F00 */  jal        func_80007C00
    /* 4F028 800A6DD8 26640008 */   addiu     $a0, $s3, 0x8
    /* 4F02C 800A6DDC 3C18800C */  lui        $t8, %hi(D_800BF8F0)
    /* 4F030 800A6DE0 0310C021 */  addu       $t8, $t8, $s0
    /* 4F034 800A6DE4 8F18F8F0 */  lw         $t8, %lo(D_800BF8F0)($t8)
    /* 4F038 800A6DE8 24010010 */  addiu      $at, $zero, 0x10
    /* 4F03C 800A6DEC 16810003 */  bne        $s4, $at, .L800A6DFC
    /* 4F040 800A6DF0 AF150000 */   sw        $s5, 0x0($t8)
    /* 4F044 800A6DF4 0C026E9A */  jal        func_8009BA68
    /* 4F048 800A6DF8 8FC4000C */   lw        $a0, 0xC($fp)
  .L800A6DFC:
    /* 4F04C 800A6DFC 8E420008 */  lw         $v0, 0x8($s2)
    /* 4F050 800A6E00 10400003 */  beqz       $v0, .L800A6E10
    /* 4F054 800A6E04 00000000 */   nop
    /* 4F058 800A6E08 0040F809 */  jalr       $v0
    /* 4F05C 800A6E0C 00000000 */   nop
  .L800A6E10:
    /* 4F060 800A6E10 1000FF8F */  b          .L800A6C50
    /* 4F064 800A6E14 2652001C */   addiu     $s2, $s2, 0x1C
  .L800A6E18:
    /* 4F068 800A6E18 00001025 */  or         $v0, $zero, $zero
  .L800A6E1C:
    /* 4F06C 800A6E1C 8FBF0094 */  lw         $ra, 0x94($sp)
    /* 4F070 800A6E20 D7B40040 */  ldc1       $f20, 0x40($sp)
    /* 4F074 800A6E24 D7B60048 */  ldc1       $f22, 0x48($sp)
    /* 4F078 800A6E28 D7B80050 */  ldc1       $f24, 0x50($sp)
    /* 4F07C 800A6E2C D7BA0058 */  ldc1       $f26, 0x58($sp)
    /* 4F080 800A6E30 D7BC0060 */  ldc1       $f28, 0x60($sp)
    /* 4F084 800A6E34 D7BE0068 */  ldc1       $f30, 0x68($sp)
    /* 4F088 800A6E38 8FB00070 */  lw         $s0, 0x70($sp)
    /* 4F08C 800A6E3C 8FB10074 */  lw         $s1, 0x74($sp)
    /* 4F090 800A6E40 8FB20078 */  lw         $s2, 0x78($sp)
    /* 4F094 800A6E44 8FB3007C */  lw         $s3, 0x7C($sp)
    /* 4F098 800A6E48 8FB40080 */  lw         $s4, 0x80($sp)
    /* 4F09C 800A6E4C 8FB50084 */  lw         $s5, 0x84($sp)
    /* 4F0A0 800A6E50 8FB60088 */  lw         $s6, 0x88($sp)
    /* 4F0A4 800A6E54 8FB7008C */  lw         $s7, 0x8C($sp)
    /* 4F0A8 800A6E58 8FBE0090 */  lw         $fp, 0x90($sp)
    /* 4F0AC 800A6E5C 03E00008 */  jr         $ra
    /* 4F0B0 800A6E60 27BD00A8 */   addiu     $sp, $sp, 0xA8
endlabel func_800A6BC0
.size func_800A6BC0, . - func_800A6BC0
