name: Kirby 64 Pull Request CI

on:
  push:
    branches: [ master, splat ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Download Qemu Irix
      run: wget https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
    - name: Install Qemu Irix
      run: sudo dpkg -i qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y binutils-mips-linux-gnu gcc git gcc-mips-linux-gnu
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Prepare Kirby 64 for building
      run: make setup CROSS=mips-linux-gnu- CI_CD=1
    - name: Build Kirby 64
      run: make -j$(nproc) VERBOSE=0 CROSS=mips-linux-gnu-
