.include "macro.inc"

.section .bss, "wa"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_801F0120_ovl16, 0x4

dlabel D_801F0120_ovl16
    /* 801F0120 */ .space 0x04

nonmatching D_801F0124_ovl16, 0x4

dlabel D_801F0124_ovl16
    /* 801F0124 */ .space 0x04

nonmatching D_801F0128_ovl16, 0x18

dlabel D_801F0128_ovl16
    /* 801F0128 */ .space 0x18

nonmatching D_801F0140_ovl16, 0x4

dlabel D_801F0140_ovl16
    /* 801F0140 */ .space 0x04

nonmatching D_801F0144_ovl16, 0x4

dlabel D_801F0144_ovl16
    /* 801F0144 */ .space 0x04

nonmatching D_801F0148_ovl16, 0x18

dlabel D_801F0148_ovl16
    /* 801F0148 */ .space 0x18

nonmatching D_801F0160_ovl16, 0x28

dlabel D_801F0160_ovl16
    /* 801F0160 */ .space 0x28

nonmatching D_801F0188_ovl16, 0x28

dlabel D_801F0188_ovl16
    /* 801F0188 */ .space 0x28

nonmatching D_801F01B0_ovl16, 0x20

dlabel D_801F01B0_ovl16
    /* 801F01B0 */ .space 0x20

nonmatching D_801F01D0_ovl16, 0x8

dlabel D_801F01D0_ovl16
    /* 801F01D0 */ .space 0x08

nonmatching D_801F01D8_ovl16, 0x20

dlabel D_801F01D8_ovl16
    /* 801F01D8 */ .space 0x20

nonmatching D_801F01F8_ovl16, 0x8

dlabel D_801F01F8_ovl16
    /* 801F01F8 */ .space 0x08

nonmatching D_801F0200_ovl16, 0x20

dlabel D_801F0200_ovl16
    /* 801F0200 */ .space 0x20

nonmatching D_801F0220_ovl16, 0x10

dlabel D_801F0220_ovl16
    /* 801F0220 */ .space 0x10
